<?xml version="1.0" encoding="utf-8" ?>
<xs:schema  targetNamespace="http://www.analog.com" 
			elementFormDefault="qualified" 
			xmlns:adins="http://www.analog.com"
			xmlns:xs="http://www.w3.org/2001/XMLSchema"
			>
	<xs:include id="ADSP" schemaLocation="ADSP.xsd" />
	<xs:element name="cces-core-xml">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string" />
				<xs:element name="version">
					<xs:complexType>
						<xs:sequence />
						<xs:attribute name="file-version" type="xs:string" />
					</xs:complexType>
				</xs:element>
				<xs:element name="register-core-definitions">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="register" type="adins:registerType" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>