/*----------------------------------------------------------------------
 * Ch 11 Input (INPUT_TDM)
 * Node ID:    C1_IN_11
 * Chip:       1
 * Channels:   1
 * SPI Page:   -1
 * SPI Addr:   -1
 *
 * AUTO-GENERATED by dsp_codegen.py — do not edit directly.
 * Implement DSP logic in the marked section below.
 *----------------------------------------------------------------------*/

/* INPUT_TDM: Read from SPORT1 TDM slot 2 */
/* DMA fills rx_buf[] automatically — just reference the slot offset */

.section/dm seg_dmda;
.var _rx_slot_C1_IN_11;     /* pointer to DMA rx buffer slot */

.section/pm seg_pmco;
.global _C1_IN_11_process;
_C1_IN_11_process:
    /* Audio sample available in _rx_slot_C1_IN_11 after DMA complete */
    /* Copy to channel processing buffer */
    r0 = dm(_rx_slot_C1_IN_11);
    dm(_buf_C1_IN_11) = r0;
    rts;
_C1_IN_11_process.end:
