/*----------------------------------------------------------------------
 * Ch 24 Send (INTERCHIP_SEND)
 * Node ID:    C1_SEND_24
 * Chip:       1
 * Channels:   1
 * SPI Page:   -1
 * SPI Addr:   -1
 * RampProfile: (none)
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/

/* INTERCHIP_SEND: Write to inter-chip SPORT7 TDM slot 23 */

.section/dm seg_dmda;
.extern _buf_C1_COMP_24;
.global _tx_slot_C1_SEND_24;
.var _tx_slot_C1_SEND_24;

.section/pm seg_pmco;
.global _C1_SEND_24_process;
_C1_SEND_24_process:
    r0 = dm(_buf_C1_COMP_24);
    dm(_tx_slot_C1_SEND_24) = r0;
    rts;
_C1_SEND_24_process.end:
