/*----------------------------------------------------------------------
 * Ch 5 Send (INTERCHIP_SEND)
 * Node ID:    C1_SEND_05
 * Chip:       1
 * Channels:   1
 * SPI Page:   -1
 * SPI Addr:   -1
 *
 * AUTO-GENERATED by dsp_codegen.py — do not edit directly.
 * Implement DSP logic in the marked section below.
 *----------------------------------------------------------------------*/

/* INTERCHIP_SEND: Write to inter-chip SPORT7 TDM slot 4 */

.section/dm seg_dmda;
.var _tx_slot_C1_SEND_05;     /* pointer to DMA tx buffer slot */

.section/pm seg_pmco;
.global _C1_SEND_05_process;
_C1_SEND_05_process:
    /* Copy processed sample to inter-chip TDM tx buffer */
    r0 = dm(_buf_C1_COMP_05);
    dm(_tx_slot_C1_SEND_05) = r0;
    rts;
_C1_SEND_05_process.end:
