/*----------------------------------------------------------------------
 * Ch 23 Send (INTERCHIP_SEND)
 * Node ID:    C1_SEND_23
 * Chip:       1
 * Channels:   1
 * SPI Page:   -1
 * SPI Addr:   -1
 * RampProfile: (none)
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/

/* INTERCHIP_SEND: Write to inter-chip SPORT7 TDM slot 22 */

.section/dm seg_dmda;
.extern _buf_C1_COMP_23;
.global _tx_slot_C1_SEND_23;
.var _tx_slot_C1_SEND_23;

.section/pm seg_pmco;
.global _C1_SEND_23_process;
_C1_SEND_23_process:
    r0 = dm(_buf_C1_COMP_23);
    dm(_tx_slot_C1_SEND_23) = r0;
    rts;
_C1_SEND_23_process.end:
