/* mask_gates.asm — CHAN_MASK / AUX_MASK application for CHIP1 */
/* AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly. */
/*
 *
 * Three things, all run once from _product_config_commit:
 *
 *   1. LATCH. `_chan_mask` / `_aux_mask` are the words the host writes
 *      over SPI at any time; `_chan_mask_live` / `_aux_mask_live` are
 *      what this file reads. Only a CONFIG_COMMIT moves one to the
 *      other, which is what makes "the mask is applied at
 *      product-config time" true rather than aspirational, and what
 *      keeps a half-written mask out of a block in flight.
 *
 *   2. RESOLVE THE GATES. `_mask_on[k]` is one word per GATE GROUP of
 *      the process chain -- a strip, an aux, or a pair of strips -- and
 *      the chain's gate is three instructions: load it, test it, jump.
 *      The alternative is a 32-bit immediate and an AND at every one of
 *      the chain's sixty-odd gates, and chip 1 has no program memory to
 *      spend on that: the first cut of this fix overflowed sec_swco by
 *      622 words in the block-16 paired build.
 *
 *   3. SILENCE WHAT THE SKIP LEAVES BEHIND. A skipped node does not
 *      write its output, so anything downstream reading a BUFFER rather
 *      than calling the node would carry the last value the node ever
 *      produced. Three such buffers exist and all are zeroed here for
 *      every masked index:
 *
 *        chip 1  _buf_C1_BUS_AUX_nn         (the gather points at it)
 *                _tx_slot_C1_BUS_AUX_nn_SEND
 *                _xpc[bus][strip]           (the crosspoint column)
 *        chip 2  _tx_out_slot_C2_AUX_OUT_nn
 *
 *      The crosspoint column is the one that matters for strips: the
 *      bus-major fabric MACs `_xpc[bus][s] * _rtg_src[s]` for every s in
 *      a bus's live range whether or not strip s ran this block, so a
 *      strip that stops running with a live coefficient would freeze a
 *      DC term into its buses. Zeroing the column also NARROWS
 *      `_xp_lo`/`_xp_hi` (hence the `_xp_dirty` set after it), which is
 *      why masking strips 25-32 costs the fabric less as well as
 *      summing less.
 *
 * At a FIRST commit parts 2 and 3 have nothing to undo -- the columns
 * are still the zeros rtg_fabric.asm initialises them to and no node has
 * run. They exist for the SECOND commit, which the bench recipe does on
 * every boot and which a host may do again at any time.
 *
 */
#include "dsp_block.h"

/* DSP4_CHAN_MASK=0 IS THE BYTE-FOR-BYTE CONTROL. The whole file is
 * inside this guard, and so are the live words and the commit-time
 * call in product_config.asm, so a control build is the pre-fix
 * image -- the same md5, not merely the same behaviour. That is what
 * makes every cycle figure recorded before 2026-09-09 reproducible
 * on this tree. */
#if DSP4_CHAN_MASK

.section/dm seg_dmda;

/* One word per gate group of the process chain, in the order the
 * chain numbers them. NON-ZERO = run. Initialised LIVE, so a part
 * between reset and the host's first commit -- and chip 2 on the
 * profile bench, which is configured but need not be -- runs the
 * whole graph. */
.global _mask_on;
.var _mask_on[61] = 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1;
/* ...and what each group is a function of: the mask word (0 =
 * channel, 1 = aux) and the bits of it that keep the group
 * alive. A PAIR OF STRIPS CARRIES BOTH BITS and runs if EITHER
 * is live -- the paired kernels are one instruction stream over
 * two strips and there is no runtime way to half-issue them.
 * The masked half of a live pair contributes nothing anyway:
 * its ROUTING node has a gate group of its own and its
 * crosspoint column is zeroed below. */
.var _mask_grp_word[61] =
    0,    /* strip 1+2 */
    0,    /* strip 1 */
    0,    /* strip 2 */
    0,    /* strip 3+4 */
    0,    /* strip 3 */
    0,    /* strip 4 */
    0,    /* strip 5+6 */
    0,    /* strip 5 */
    0,    /* strip 6 */
    0,    /* strip 7+8 */
    0,    /* strip 7 */
    0,    /* strip 8 */
    0,    /* strip 9+10 */
    0,    /* strip 9 */
    0,    /* strip 10 */
    0,    /* strip 11+12 */
    0,    /* strip 11 */
    0,    /* strip 12 */
    0,    /* strip 13+14 */
    0,    /* strip 13 */
    0,    /* strip 14 */
    0,    /* strip 15+16 */
    0,    /* strip 15 */
    0,    /* strip 16 */
    0,    /* strip 17+18 */
    0,    /* strip 17 */
    0,    /* strip 18 */
    0,    /* strip 19+20 */
    0,    /* strip 19 */
    0,    /* strip 20 */
    0,    /* strip 21+22 */
    0,    /* strip 21 */
    0,    /* strip 22 */
    0,    /* strip 23+24 */
    0,    /* strip 23 */
    0,    /* strip 24 */
    0,    /* strip 25+26 */
    0,    /* strip 25 */
    0,    /* strip 26 */
    0,    /* strip 27+28 */
    0,    /* strip 27 */
    0,    /* strip 28 */
    0,    /* strip 29+30 */
    0,    /* strip 29 */
    0,    /* strip 30 */
    0,    /* strip 31+32 */
    0,    /* strip 31 */
    0,    /* strip 32 */
    0,    /* strip 1+2+3+4+5+6+7+8+9+10+11+12+13+14+15+16+17+18+19+20+21+22+23+24+25+26+27+28+29+30+31+32 */
    1,    /* aux  1 */
    1,    /* aux  2 */
    1,    /* aux  3 */
    1,    /* aux  4 */
    1,    /* aux  5 */
    1,    /* aux  6 */
    1,    /* aux  7 */
    1,    /* aux  8 */
    1,    /* aux  9 */
    1,    /* aux  10 */
    1,    /* aux  11 */
    1;    /* aux  12 */
.var _mask_grp_bits[61] =
    0x00000003,
    0x00000001,
    0x00000002,
    0x0000000C,
    0x00000004,
    0x00000008,
    0x00000030,
    0x00000010,
    0x00000020,
    0x000000C0,
    0x00000040,
    0x00000080,
    0x00000300,
    0x00000100,
    0x00000200,
    0x00000C00,
    0x00000400,
    0x00000800,
    0x00003000,
    0x00001000,
    0x00002000,
    0x0000C000,
    0x00004000,
    0x00008000,
    0x00030000,
    0x00010000,
    0x00020000,
    0x000C0000,
    0x00040000,
    0x00080000,
    0x00300000,
    0x00100000,
    0x00200000,
    0x00C00000,
    0x00400000,
    0x00800000,
    0x03000000,
    0x01000000,
    0x02000000,
    0x0C000000,
    0x04000000,
    0x08000000,
    0x30000000,
    0x10000000,
    0x20000000,
    0xC0000000,
    0x40000000,
    0x80000000,
    0xFFFFFFFF,
    0x00000001,
    0x00000002,
    0x00000004,
    0x00000008,
    0x00000010,
    0x00000020,
    0x00000040,
    0x00000080,
    0x00000100,
    0x00000200,
    0x00000400,
    0x00000800;

/* Every buffer a masked aux would otherwise leave stale, and
 * the aux bit that keeps it live. */
.extern _buf_C1_BUS_AUX_01;
.extern _tx_slot_C1_BUS_AUX_01_SEND;
.extern _buf_C1_BUS_AUX_02;
.extern _tx_slot_C1_BUS_AUX_02_SEND;
.extern _buf_C1_BUS_AUX_03;
.extern _tx_slot_C1_BUS_AUX_03_SEND;
.extern _buf_C1_BUS_AUX_04;
.extern _tx_slot_C1_BUS_AUX_04_SEND;
.extern _buf_C1_BUS_AUX_05;
.extern _tx_slot_C1_BUS_AUX_05_SEND;
.extern _buf_C1_BUS_AUX_06;
.extern _tx_slot_C1_BUS_AUX_06_SEND;
.extern _buf_C1_BUS_AUX_07;
.extern _tx_slot_C1_BUS_AUX_07_SEND;
.extern _buf_C1_BUS_AUX_08;
.extern _tx_slot_C1_BUS_AUX_08_SEND;
.extern _buf_C1_BUS_AUX_09;
.extern _tx_slot_C1_BUS_AUX_09_SEND;
.extern _buf_C1_BUS_AUX_10;
.extern _tx_slot_C1_BUS_AUX_10_SEND;
.extern _buf_C1_BUS_AUX_11;
.extern _tx_slot_C1_BUS_AUX_11_SEND;
.extern _buf_C1_BUS_AUX_12;
.extern _tx_slot_C1_BUS_AUX_12_SEND;
.var _mask_zero_ptrs[24] =
    _buf_C1_BUS_AUX_01,
    _tx_slot_C1_BUS_AUX_01_SEND,
    _buf_C1_BUS_AUX_02,
    _tx_slot_C1_BUS_AUX_02_SEND,
    _buf_C1_BUS_AUX_03,
    _tx_slot_C1_BUS_AUX_03_SEND,
    _buf_C1_BUS_AUX_04,
    _tx_slot_C1_BUS_AUX_04_SEND,
    _buf_C1_BUS_AUX_05,
    _tx_slot_C1_BUS_AUX_05_SEND,
    _buf_C1_BUS_AUX_06,
    _tx_slot_C1_BUS_AUX_06_SEND,
    _buf_C1_BUS_AUX_07,
    _tx_slot_C1_BUS_AUX_07_SEND,
    _buf_C1_BUS_AUX_08,
    _tx_slot_C1_BUS_AUX_08_SEND,
    _buf_C1_BUS_AUX_09,
    _tx_slot_C1_BUS_AUX_09_SEND,
    _buf_C1_BUS_AUX_10,
    _tx_slot_C1_BUS_AUX_10_SEND,
    _buf_C1_BUS_AUX_11,
    _tx_slot_C1_BUS_AUX_11_SEND,
    _buf_C1_BUS_AUX_12,
    _tx_slot_C1_BUS_AUX_12_SEND;
.var _mask_zero_bits[24] =
    0x00000001,   /* aux 1 */
    0x00000001,   /* aux 1 */
    0x00000002,   /* aux 2 */
    0x00000002,   /* aux 2 */
    0x00000004,   /* aux 3 */
    0x00000004,   /* aux 3 */
    0x00000008,   /* aux 4 */
    0x00000008,   /* aux 4 */
    0x00000010,   /* aux 5 */
    0x00000010,   /* aux 5 */
    0x00000020,   /* aux 6 */
    0x00000020,   /* aux 6 */
    0x00000040,   /* aux 7 */
    0x00000040,   /* aux 7 */
    0x00000080,   /* aux 8 */
    0x00000080,   /* aux 8 */
    0x00000100,   /* aux 9 */
    0x00000100,   /* aux 9 */
    0x00000200,   /* aux 10 */
    0x00000200,   /* aux 10 */
    0x00000400,   /* aux 11 */
    0x00000400,   /* aux 11 */
    0x00000800,   /* aux 12 */
    0x00000800;   /* aux 12 */

.section/pm seg_pmco;

.extern _chan_mask;
.extern _aux_mask;
.extern _chan_mask_live;
.extern _aux_mask_live;
#if DSP4_BLOCK_KERNELS && DSP4_RTG_FABRIC
.extern _xpc;
.extern _xp_dirty;
#endif

/* _mask_apply — latch, resolve, silence. Called from
 * _product_config_commit; runs once, so it is written for size and
 * not for speed. Clobbers r0-r8, i0-i2, l0-l2, m0. */
.global _mask_apply;
_mask_apply:
    r0 = dm(_chan_mask);
    dm(_chan_mask_live) = r0;
    r1 = dm(_aux_mask);
    dm(_aux_mask_live) = r1;
    l0 = 0;
    l1 = 0;
    l2 = 0;
    r2 = 0;                       /* the zero written into buffers */
    /* resolve every gate group */
    i0 = _mask_grp_word;
    i1 = _mask_grp_bits;
    i2 = _mask_on;
    lcntr = 61, do .mg_c1_grp until lce;
        r4 = dm(i0, 1);       /* 0 = chan, 1 = aux    */
        r5 = dm(i1, 1);       /* the group's bits     */
        r6 = r0;              /* assume the chan word */
        r4 = pass r4;
        if ne r6 = r1;        /* ...no, the aux word  */
        r6 = r6 and r5;
    .mg_c1_grp:
        dm(i2, 1) = r6;       /* non-zero = run       */
    /* every buffer a masked aux would otherwise leave stale */
    i0 = _mask_zero_ptrs;
    i1 = _mask_zero_bits;
    lcntr = 24, do .mg_c1_az until lce;
        r4 = dm(i0, 1);       /* the buffer           */
        r5 = dm(i1, 1);       /* its aux's bit        */
        r5 = r1 and r5;
        if ne jump (pc, .mg_c1_az_next);
        i2 = r4;
#if DSP4_BLOCK_KERNELS
        lcntr = DSP4_BLOCK_SIZE, do .mg_c1_az_in until lce;
        .mg_c1_az_in:
            dm(i2, 1) = r2;
#else
        dm(i2, 0) = r2;
#endif
    .mg_c1_az_next:
        nop;
    .mg_c1_az:
        nop;
#if DSP4_BLOCK_KERNELS && DSP4_RTG_FABRIC
    /* a masked strip's crosspoint column, 25 buses at stride 32 */
    m0 = 32;
    r7 = 1;                   /* strip 1's bit        */
    r8 = _xpc;                /* &_xpc[0][strip]      */
    lcntr = 32, do .mg_c1_str until lce;
        r5 = r0 and r7;
        if ne jump (pc, .mg_c1_str_next);
        i0 = r8;
        lcntr = 25, do .mg_c1_str_in until lce;
        .mg_c1_str_in:
            dm(i0, m0) = r2;
    .mg_c1_str_next:
        r7 = lshift r7 by 1;
        r8 = r8 + 1;
    .mg_c1_str:
        nop;
    /* the live ranges are now wrong in the narrowing direction */
    r0 = 1;
    dm(_xp_dirty) = r0;
#endif
    rts;
_mask_apply.end:

#endif /* DSP4_CHAN_MASK */
