#!/usr/bin/env python3
"""Validate imported matrix contract files for compatibility and addressing sanity.

Checks:
- every expanded product's MxAdd values are contiguous starting at 1
- every expanded product's _Cell names parse in expanded form
- every expanded product's cell-family set is contained by an allowlist

THE ALLOWLIST IS THE D32 SET AND THAT IS DELIBERATE. D32 is the largest
matrix-based product in the range, so every smaller product's families are
a subset of it by construction -- checked here rather than assumed, and a
family that appears on a small product and not on D32 is exactly the
no-fallback case this file exists for. (D24's `MainCtr*` and `MainOut3Mode`
are the one exception on record: a centre-cluster D32 does not carry, and
they are named below rather than silently tolerated.)

Use --update-allowlist to refresh the allowlist from current D32 _matrix.csv.
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
# The products sync-defs.sh expands, smallest first. Keep in step with
# PRODUCTS in sync-defs.sh: a product expanded and not validated here is a
# matrix nothing checks.
PRODUCTS = ("D12", "D16", "D24", "D32")
MATRIX = {p: ROOT / "MW" / p / "MX" / "_matrix.csv" for p in PRODUCTS}
D32_MATRIX = MATRIX["D32"]
ALLOWLIST = ROOT / "matrix-families-allowlist.txt"

# Families D24 defines and D32 does not: the centre cluster and the third
# main output's mode word. Named, not tolerated by a wildcard -- adopting a
# family is intentional (the no-fallback policy), and this list is the
# adoption record for the ones that cannot come from the D32 set.
NON_D32_FAMILIES = {
    "D24": {f"MainCtr{suffix}" for suffix in (
        "CompAtt", "CompDetSrc", "CompEqPos", "CompFilterHpf",
        "CompFilterLpf", "CompFilterOn", "CompFilterQ", "CompKey",
        "CompKnee", "CompLimMode", "CompMake", "CompOn", "CompPar",
        "CompRat", "CompRel", "CompThr", "CompType", "CrossoverFreq",
        "CrossoverSlope", "Dca", "DcaOn", "Delay", "EqFreq", "EqGain",
        "EqHpf", "EqOn", "EqQ", "EqShelf", "Level", "LimiterAtt",
        "LimiterOn", "LimiterRel", "LimiterRng", "LimiterThr", "Mtr",
        "Mute", "Name", "PeqGain")} | {"MainOut3Mode"},
}

CELL_RE = re.compile(r"^([A-Za-z]+)(\d{3})([A-Za-z0-9]+)(\d{3})$")


def parse_rows(path: Path) -> list[dict[str, str]]:
    if not path.is_file():
        raise FileNotFoundError(f"Missing matrix file: {path}")
    with path.open(newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        raise ValueError(f"No data rows in {path}")
    return rows


def family(cell: str) -> str:
    m = CELL_RE.match(cell)
    if not m:
        raise ValueError(f"Unparseable expanded _Cell: {cell}")
    return f"{m.group(1)}{m.group(3)}"


def check_mxadd(path: Path) -> tuple[int, int]:
    rows = parse_rows(path)
    expected = 1
    for i, r in enumerate(rows, start=2):
        raw = (r.get("MxAdd") or "").strip()
        if not raw:
            raise ValueError(f"{path}:{i} missing MxAdd")
        try:
            val = int(raw)
        except ValueError as exc:
            raise ValueError(f"{path}:{i} invalid MxAdd={raw!r}") from exc
        if val != expected:
            raise ValueError(
                f"{path}:{i} expected MxAdd={expected} but found {val}"
            )
        expected += 1
    return len(rows), expected - 1


def extract_families(path: Path) -> set[str]:
    out: set[str] = set()
    rows = parse_rows(path)
    for i, r in enumerate(rows, start=2):
        cell = (r.get("_Cell") or "").strip()
        if not cell:
            raise ValueError(f"{path}:{i} missing _Cell")
        out.add(family(cell))
    return out


def read_allowlist(path: Path) -> set[str]:
    if not path.is_file():
        raise FileNotFoundError(f"Missing allowlist: {path}")
    items: set[str] = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        items.add(line)
    if not items:
        raise ValueError(f"Allowlist is empty: {path}")
    return items


def write_allowlist(path: Path, items: set[str]) -> None:
    lines = [
        "# Allowed D32 matrix families for DSP contract compatibility",
        "# Generated by validate-matrix-contract.py --update-allowlist",
        "",
    ]
    lines.extend(sorted(items))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--update-allowlist",
        action="store_true",
        help="Refresh matrix-families-allowlist.txt from current D32 _matrix.csv",
    )
    args = ap.parse_args()

    d32_families = extract_families(D32_MATRIX)

    if args.update_allowlist:
        write_allowlist(ALLOWLIST, d32_families)
        print(f"Updated allowlist: {ALLOWLIST}")
        print(f"D32 family count: {len(d32_families)}")
        return 0

    allowed = read_allowlist(ALLOWLIST)
    rc = 0
    for p in PRODUCTS:
        rows, last = check_mxadd(MATRIX[p])
        fams = extract_families(MATRIX[p])
        unexpected = sorted(fams - allowed - NON_D32_FAMILIES.get(p, set()))
        print(f"{p} MxAdd contiguous: 1..{last} ({rows} rows); "
              f"{len(fams)} families")
        if unexpected:
            print(f"ERROR: Unexpected {p} matrix families detected:",
                  file=sys.stderr)
            for name in unexpected[:50]:
                print(f"  - {name}", file=sys.stderr)
            if len(unexpected) > 50:
                print(f"  ... and {len(unexpected) - 50} more", file=sys.stderr)
            rc = 1

    print(f"Allowlist: {len(allowed)} families (the D32 set)")
    if rc:
        print(
            "Review matrix/definition changes before allowing them, then run --update-allowlist intentionally.",
            file=sys.stderr,
        )
        return rc

    print("Compatibility check passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
