#!/usr/bin/env python3
"""Validate imported matrix contract files for compatibility and addressing sanity.

Checks:
- D24/D32 MxAdd values are contiguous starting at 1
- D24/D32 _Cell names parse in expanded form
- D32 cell-family set is contained by an allowlist

Use --update-allowlist to refresh the allowlist from current D32 _matrix.csv.
"""

from __future__ import annotations

import argparse
import csv
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
D24_MATRIX = ROOT / "MW" / "D24" / "MX" / "_matrix.csv"
D32_MATRIX = ROOT / "MW" / "D32" / "MX" / "_matrix.csv"
ALLOWLIST = ROOT / "matrix-families-allowlist.txt"

CELL_RE = re.compile(r"^([A-Za-z]+)(\d{3})([A-Za-z0-9]+)(\d{3})$")


def parse_rows(path: Path) -> list[dict[str, str]]:
    if not path.is_file():
        raise FileNotFoundError(f"Missing matrix file: {path}")
    with path.open(newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    if not rows:
        raise ValueError(f"No data rows in {path}")
    return rows


def family(cell: str) -> str:
    m = CELL_RE.match(cell)
    if not m:
        raise ValueError(f"Unparseable expanded _Cell: {cell}")
    return f"{m.group(1)}{m.group(3)}"


def check_mxadd(path: Path) -> tuple[int, int]:
    rows = parse_rows(path)
    expected = 1
    for i, r in enumerate(rows, start=2):
        raw = (r.get("MxAdd") or "").strip()
        if not raw:
            raise ValueError(f"{path}:{i} missing MxAdd")
        try:
            val = int(raw)
        except ValueError as exc:
            raise ValueError(f"{path}:{i} invalid MxAdd={raw!r}") from exc
        if val != expected:
            raise ValueError(
                f"{path}:{i} expected MxAdd={expected} but found {val}"
            )
        expected += 1
    return len(rows), expected - 1


def extract_families(path: Path) -> set[str]:
    out: set[str] = set()
    rows = parse_rows(path)
    for i, r in enumerate(rows, start=2):
        cell = (r.get("_Cell") or "").strip()
        if not cell:
            raise ValueError(f"{path}:{i} missing _Cell")
        out.add(family(cell))
    return out


def read_allowlist(path: Path) -> set[str]:
    if not path.is_file():
        raise FileNotFoundError(f"Missing allowlist: {path}")
    items: set[str] = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        items.add(line)
    if not items:
        raise ValueError(f"Allowlist is empty: {path}")
    return items


def write_allowlist(path: Path, items: set[str]) -> None:
    lines = [
        "# Allowed D32 matrix families for DSP contract compatibility",
        "# Generated by validate-matrix-contract.py --update-allowlist",
        "",
    ]
    lines.extend(sorted(items))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--update-allowlist",
        action="store_true",
        help="Refresh matrix-families-allowlist.txt from current D32 _matrix.csv",
    )
    args = ap.parse_args()

    d24_rows, d24_last = check_mxadd(D24_MATRIX)
    d32_rows, d32_last = check_mxadd(D32_MATRIX)
    d32_families = extract_families(D32_MATRIX)

    if args.update_allowlist:
        write_allowlist(ALLOWLIST, d32_families)
        print(f"Updated allowlist: {ALLOWLIST}")
        print(f"D32 family count: {len(d32_families)}")
        return 0

    allowed = read_allowlist(ALLOWLIST)
    unexpected = sorted(d32_families - allowed)

    print(f"D24 MxAdd contiguous: 1..{d24_last} ({d24_rows} rows)")
    print(f"D32 MxAdd contiguous: 1..{d32_last} ({d32_rows} rows)")
    print(f"D32 families: {len(d32_families)} (allowlist: {len(allowed)})")

    if unexpected:
        print("ERROR: Unexpected D32 matrix families detected:", file=sys.stderr)
        for name in unexpected[:50]:
            print(f"  - {name}", file=sys.stderr)
        if len(unexpected) > 50:
            print(f"  ... and {len(unexpected) - 50} more", file=sys.stderr)
        print(
            "Review matrix/definition changes before allowing them, then run --update-allowlist intentionally.",
            file=sys.stderr,
        )
        return 1

    print("Compatibility check passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
