#!/usr/bin/env python3
"""gen_patch_paths.py -- the D24 audio patch list, generated (S121).

ONE list of signal paths for the analog station. Every entry is one D24 OUTPUT
reaching one D24 INPUT, named the way the panel names them, with the route that
makes it live, the stimulus, and what the reading has to be. The operator's
view of the same list is a sequence of PATCHES: one lead, moved once.

    gen_patch_paths.py [--out MW/D24/DSP/s121] [--check]

It writes three files and prints a summary:

    patch-paths.csv    one row per PATH (a measurement). The `patch` column
                       groups them: consecutive rows sharing a patch id are
                       sub-tests of ONE physical connection and the operator is
                       prompted once (runner-interface.md, `connect`).
    patch-routes.csv   one row per ROUTE id: the cells, by NAME, that make that
                       output live and everything else silent.
    patch-plan.md      the human table -- patches per lead, per cable type,
                       and the coverage proof.

WHERE THE FACTS COME FROM, and what is NOT invented here:

  * defs/products/d24/d24-io.csv -- the rear panel inventory: which socket is
    an XLR and which is a TRS jack, and that the "Aux Out A 1-2 ... 7-8" TRS
    jacks are a PAIRED JACK ALTERNATIVE to the Aux Out A1..A8 XLRs (the same
    eight aux buses reach both).
  * defs/products/d24/dsp.csv -- every cell this file names is checked to
    exist. A route that names a cell the product does not declare is a hard
    error, never a silent drop (the no-fallback rule).
  * tools/pi/d24_inputs.py -- MIC n is on strip n, which is what MeasChan and
    the Chan<nnn> cells are indexed by.
  * tools/dsp/dsp_codegen.py TEST_MEAS_LANE_CODES -- MeasChan 51/53/55 are the
    codec return lanes: the mini-jack tip, the talkback XLR and the mini-jack
    ring. Nothing else can measure those three inputs at all.
  * s121/harness-ref/d24-harness-ports.csv -- the harness revision's port
    table: panel name, direction, catalog row, and how each TRS jack is wired
    (MONITOR tip->hot with ring+sleeve->cold; the stereo jacks tip->L,
    ring->R, common sleeve). The catalog rows come from here so the station
    and the harness stamp the same rows.

THE STEREO RULE (PW 2026-09-26). Every stereo TRS jack, input or output, is
ONE patch through ONE standard lead, and the channels are separated by DRIVING
them separately, not by splitting the lead:

  * a stereo TRS OUTPUT through K2 (tip->pin 2, ring->pin 3) presents L-R at
    the XLR input, so the patch is three sub-tests -- L alone (normal), R alone
    (inverted), both in phase (a null). The null is what proves L and R match
    and are not crossed; the polarity of the L-alone reading is what proves tip
    and ring are not swapped.
  * a stereo TRS INPUT through K3 is driven from ONE balanced XLR output, whose
    pin 2 becomes L and pin 3 becomes R, so ONE stimulus reads both lanes at
    once -- L normal, R inverted, equal level. An inverted LEFT is a channel
    swap, scored as a swap and not as two failures.

POLARITY IS RELATIVE AND THE LIST SAYS SO. `polarity` is NOT an absolute sign:
a 1 kHz tone through this unit's loop arrives with the whole path's latency
rotated into its phase (units.csv records 91.40 samples on MW-D24-2, which is
1.9 cycles at 1 kHz). What the runner measures is the phase of the coherent
fit against TEST_OSC's own reference -- `_meas_a`/`_meas_b`, the signed
in-phase and quadrature amplitudes the measurement node already computes every
window -- and what the list asks for is that phase RELATIVE to a reference
reading taken on the SAME input lane earlier in the same pass. `ref` marks the
rows that ESTABLISH a reference; `normal` and `inverted` are judged against it.
Rows whose lane never carries a balanced reference (the codec lanes) carry
`info`, and say so, until a good unit sets them.
"""
import argparse
import csv
import math
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
sys.path.insert(0, os.path.join(ROOT, 'tools', 'pi'))

DEFS_DSP = os.path.join(ROOT, 'defs', 'products', 'd24', 'dsp.csv')
DEFS_INPUTS = os.path.join(ROOT, 'defs', 'products', 'd24', 'inputs.csv')
DEFS_GAIN_LAW = os.path.join(ROOT, 'defs', 'common', 'tables',
                             'mic-gain-law.csv')
# HUB ADDENDUM 2 to S130 (PW, "fix the table"): the gain steps' expected
# values come from the 64-code MEDIAN table, not mic-gain-law.csv's 61-row
# target_db fit (worst residual 0.51 dB -- addendum 5). Reads the landed defs
# copy once the hub advances the pin (S131, not this repo's call tonight);
# until then the identical content -- both generated by
# MW/D24/DSP/s55/tools/s55_ingest.py from the same survey -- is staged here.
DEFS_GAIN_CODES = os.path.join(ROOT, 'defs', 'common', 'tables',
                               'mic-gain-codes.csv')
PROPOSED_GAIN_CODES = os.path.join(ROOT, 'proposals', 'defs', 'common',
                                   'tables', 'mic-gain-codes.csv')
DEFS_IO = os.path.join(ROOT, 'defs', 'products', 'd24', 'd24-io.csv')
OUT_DEFAULT = os.path.join(ROOT, 'MW', 'D24', 'DSP', 's121')
PORTS = os.path.join(OUT_DEFAULT, 'harness-ref', 'd24-harness-ports.csv')

# ---------------------------------------------------------------------------
# The leads. One of each, standard and off the shelf (PW 2026-09-26).
# ---------------------------------------------------------------------------
# `wiring` is what the operator's lead must actually be, and it is the reason
# each block reads the way it does. K2 and K4 are the same wiring with opposite
# XLR gender, because one goes INTO a panel input and the other ONTO a panel
# output; there is no adapter in the kit.
LEADS = {
    'K1': dict(name='XLR-F to XLR-M',
               wiring='straight balanced: pin 1-1, 2-2, 3-3',
               use='a D24 XLR output into a D24 XLR input'),
    'K2': dict(name='6.35 mm TRS to XLR-M',
               wiring='tip -> pin 2, ring -> pin 3, sleeve -> pin 1',
               use='a D24 TRS output jack into a D24 XLR input'),
    'K3': dict(name='XLR-F to 3.5 mm TRS',
               wiring='pin 2 -> tip, pin 3 -> ring, pin 1 -> sleeve',
               use='a D24 XLR output into the stereo mini-jack input'),
    'K4': dict(name='XLR-F to 6.35 mm TRS',
               wiring='pin 2 -> tip, pin 3 -> ring, pin 1 -> sleeve',
               use="a D24 XLR output into a combo jack's TRS line centre"),
    'K5': dict(name='150 ohm XLR-M terminator',
               wiring='150 ohm across pins 2-3, pin 1 to the shell',
               use='the input noise (EIN) reading, one input at a time'),
}

# The order the blocks are walked. It is the order that costs the operator the
# least: the lead type changes exactly four times, and inside K5 and K4 the
# hand is already on the input row it was on for K1.
BLOCK_ORDER = ('K1', 'K5', 'K2', 'K4', 'K3')

# ---------------------------------------------------------------------------
# The donor strip: where the oscillator goes in
# ---------------------------------------------------------------------------
# TEST_OSC REPLACES a strip's input block (dsp_codegen.py `_test_osc_inject`:
# "The stimulus REPLACES the strip's input rather than adding to it"), so the
# strip carrying the oscillator cannot also be measured. D24 declares Chan
# cells for strips 1..24 ONLY -- there is no strip 25 to hide the donor on --
# so the donor is one of the twenty-four and the list moves it out of the way
# when its own input is the one under test.
DONOR_DEFAULT = 24
DONOR_ALT = 1


def donor_for(strip):
    """The strip the oscillator is injected into while `strip` is measured."""
    return DONOR_ALT if strip == DONOR_DEFAULT else DONOR_DEFAULT


# ---------------------------------------------------------------------------
# Levels and windows -- PROVISIONAL, and each one says what it is derived from
# ---------------------------------------------------------------------------
# NOTHING HERE IS A SPEC LIMIT. These are the windows a factory reading has to
# land in for the path to be called proven, and every one of them is either
# (a) a topological ratio that follows from how the lead is wired, or (b) a
# placeholder marked so, waiting on a good unit or a PW ruling. The runner
# reads them from patch-paths.csv; it never carries a number of its own.
#
# THE BALANCED REFERENCE is not predicted at all: the first K1 patch on each
# input lane MEASURES the loop gain and every later reading on that lane is
# judged against it. That is what makes the list survive a change of drive
# level, a gain-law revision or a different unit.
#
# SINGLE-ENDED = BALANCED - 6.02 dB is the ratio, and it is a ratio, not a
# guess: a balanced XLR output drives pin 2 and pin 3 in anti-phase, so the
# differential the input sees is twice one leg; a TRS jack's tip drives one leg
# and the input's other leg sits at the sleeve. It holds only if the
# single-ended driver swings the same voltage as one leg of the balanced one,
# which is an OUTPUT-STAGE fact this repo does not record -- see the report's
# open items. The window is wide enough (+-3 dB) to pass either convention and
# narrow enough to catch a dead or halved path; PW tightens it from a good
# unit.
SINGLE_ENDED_DB = -6.02
LEVEL_TOL_DB = 3.0
# The null: L-R with L and R driven identically. What is left is the L/R match
# of the output stage plus the lead. -30 dB below the single-ended reading is
# a placeholder that a crossed or absent channel cannot reach; a good unit sets
# the real figure.
NULL_MAX_DB = -30.0
# The two sub-tests of a stereo output must match each other far more tightly
# than either matches the absolute window: they share everything but the
# channel.
STEREO_MATCH_TOL_DB = 1.5
# Tone present: how far above the lane's own idle floor the reading must rise
# before the runner will call it a tone at all, and how far below the measured
# lane every OTHER input must stay. 40 dB is the harness revision's figure for
# the same check (runner-interface.md, "Detecting a wrong connection").
TONE_MIN_OVER_FLOOR_DB = 40.0
ISOLATION_MIN_DB = 40.0

# The stimulus. 1 kHz because that is where the wrong-connection check is
# specified and where a switch pair isolates worst; -12 dBFS because S89e's
# loop window was taken there and it leaves headroom at every gain code the
# station uses.
TONE_HZ = 1000.0
TONE_DBFS = -12.0

# THE GAIN STEPS ARE DRIVEN 18 dB QUIETER, AND IT IS THE DIFFERENCE BETWEEN A
# TEST AND A PLACEBO (S125). The station judges a gain step off the
# measurement node's level, and that reading SATURATES above about -24 dBFS.
# Measured on MW-D24-2 2026-09-26, commanding the test oscillator down in 6 dB
# steps and reading the node and the strip meter together:
#
#   commanded   node RMS   node coherent   strip meter
#      -6.0      -18.65        -15.63         -6.00     <- 9.6 dB compressed
#     -12.0      -20.14        -17.13        -12.00     <- 5.1 dB compressed
#     -18.0      -21.64        -18.63        -18.00     <- 0.6 dB compressed
#     -24.0      -27.01        -24.00        -24.00        exact
#     -30.0      -33.01        -30.00        -30.00        exact
#      ...                                                 exact to -96.0
#
# The meter is exact everywhere; the node's level is exact only below about
# -24 dBFS. At the -12 dBFS the steps used to be driven at, a step SHORT by
# the smallest element the station has to catch -- 6.552 dB -- read only
# 1.649 dB low, inside the 3 dB tolerance, and PASSED. At -30 dBFS the same
# short element reads 6.554 dB low, error +0.002 dB, spread 0.021 over five
# reps. Every element from 6.552 to 12.845 dB reads to within 0.011 dB there.
#
# -30 and not -24: six decibels below the knee, and the tone is still 84 dB
# over this unit's measured converter floor (-114 dBFS), where the station
# only asks for 40. The lowest drive this produces is -78.05 dBFS for code 32
# and the oscillator and the node are both exact 1:1 down to -96 dBFS
# (measured, same run).
#
# THIS APPLIES TO THE GAIN STEPS ONLY. Every other level reading the station
# takes is still driven at TONE_DBFS through the same compressed instrument --
# see the S125 report; re-levelling the whole ruled stimulus is PW's call.
GAIN_TONE_DBFS = -30.0


# ---------------------------------------------------------------------------
# Reading the sources
# ---------------------------------------------------------------------------
def read_csv(path, comment='#'):
    with open(path, newline='') as fh:
        return list(csv.DictReader(l for l in fh if not l.startswith(comment)))


def load_cells():
    """Every cell name the product declares, so a route can be checked."""
    names = set()
    with open(DEFS_DSP, newline='') as fh:
        for row in csv.reader(fh):
            if row and row[0] and not row[0].startswith('#'):
                names.add(row[0])
    if len(names) < 1000:
        raise SystemExit('dsp.csv gave only %d cell names: wrong file?' % len(names))
    return names


def load_send_pos():
    """Which byte of the 25-byte 595 image belongs to which panel input.

    `send_pos`, off `defs/products/d24/inputs.csv`, ZERO-BASED, and it is the
    index into the array of bytes that goes out of the shift register -- the
    thing `s55_chain.py` and `d24_chain.py` take.

    NOT `chain_index`, WHICH IS A DIFFERENT COLUMN OF THE SAME TABLE AND WAS
    WHAT THIS READ UNTIL S125. `chain_index` is the preamp's position along
    the physical daisy chain; `send_pos` is its byte in the transmitted image,
    and the two orders are not the same -- MIC 5 is chain position 9 and tx
    byte 15. Reading the wrong one put EVERY gain step on the wrong preamp:
    measured on MW-D24-2 2026-09-26, walking one position at a time at gain 63
    and watching which lane's own noise rose 33 dB, all fourteen gain-step
    inputs in the generated list addressed a byte that does not drive their
    lane -- six of them drove another input's preamp and eight addressed the
    bytes of the mics this unit has no front end for, so they moved nothing at
    all. `send_pos + 1` matched the measurement on 16 of 16 populated inputs
    and `chain_index` on 0 of 16.
    """
    out = {}
    for r in read_csv(DEFS_INPUTS, comment='#'):
        m = re.match(r'^MIC\s+(\d+)$', r['panel'].strip())
        if m:
            out[int(m.group(1))] = int(r['send_pos'])
    if len(out) != len(STRIPS):
        raise SystemExit('inputs.csv gave %d mic send positions, expected %d'
                         % (len(out), len(STRIPS)))
    if sorted(out.values()) != list(range(len(STRIPS))):
        raise SystemExit('inputs.csv send_pos is not a 0..%d permutation: %s'
                         % (len(STRIPS) - 1, sorted(out.values())))
    return out


def load_gain_codes():
    """All 64 hardware codes' measured step (HUB ADDENDUM 2 to S130, PW "fix
    the table"): no fit. Supersedes the old six-element fit through
    mic-gain-law.csv's 61-row target_db table, which left codes 8/16/32/63 a
    0.51 dB worst-case residual (S129 addendum 5) -- mic-gain-codes.csv
    carries all 64 codes directly, so every step is measured.

    Returns {code: dB}, 0..63, every code present."""
    path = DEFS_GAIN_CODES if os.path.exists(DEFS_GAIN_CODES) else PROPOSED_GAIN_CODES
    seen = {}
    for r in read_csv(path, comment='#'):
        seen[int(r['code'])] = float(r['step_db'])
    if len(seen) != 64:
        raise SystemExit('%s has %d codes, expected 64' % (path, len(seen)))
    return seen


def gain_db(code, seen):
    """The expected hardware gain of one code. Always measured -- `seen` is
    `load_gain_codes()`'s table, and it carries every code 0..63."""
    return seen[code], 'measured'


def load_ports():
    """The harness revision's port table, keyed by panel name."""
    rows = read_csv(PORTS)
    out = {}
    for r in rows:
        out[r['port']] = r
    return out


# ---------------------------------------------------------------------------
# The output map: which D24 socket each DSP output actually reaches
# ---------------------------------------------------------------------------
# NOT invented here. docs/d24-dac-lane-xlr-candidate-20260913.md walked the
# Analog PCBA netlist DAC lane by DAC lane, and tools/dsp/gen_dsp_csv.py's
# AUX_DAC / MAIN_OUT_DAC tables are what the firmware actually emits. The two
# agree, and together they say something this station has to act on:
#
#   THE OUTPUT MAP MOVED WITH THE S143/S144 GRAPH (factory-test-v3, S151).
#   Everything below was true of the pre-S143 pair and is no longer true of
#   the pair this list runs on. The three rear sockets that had no
#   host-reachable source have one now, and two of them are different
#   sockets from the ones the old list drove:
#
#   * MAIN R (J57, DAC_11) carries the RIGHT bus. Until S143 the chip-2
#     main chain was mono from the master fader onward -- C2_MAIN_FDR read
#     `_blk_C2_MIX_MAIN_L` and nothing read `_blk_C2_MIX_MAIN_R` (S142-1) --
#     so C2_MAIN_OEQ_01 and C2_MAIN_OEQ_02 read the SAME block and both MAIN
#     XLRs carried LEFT. `main:R` pans the donor hard right, which empties
#     the only bus either XLR could carry, so the mainR patch asked the R
#     socket for a signal the image could not put there and MAIN R read
#     silence on a healthy board. S143 gives C2_MAIN_OEQ_02 its own
#     C2_MAIN_XOVER_R, so the route is right now and was not before.
#   * C/LF (J55, DAC_14) is C2_OUT3_OUT, fed through C2_OUT3_SEL from the
#     CENTRE strip (C2_CTR_FDR <- C2_RECV_SUB <- C1_BUS_SUB, every channel's
#     `Chan*CtrOn` send) or from the Woof strip, whichever `Main Out3Mode`
#     selects. Until S144 the lane was C2_AUX_OUT_12 -- aux bus 12, and
#     CFG_AUX_MASK on a D24 is 0x000000FF, so the bus was masked off in
#     firmware and no cell could ever open it. It is a patch now.
#   * MONITOR L / MONITOR R (J53/J54, DAC_15/16) carry the MONITOR BUS.
#     Until S144 they were C2_MAIN_OUT_03/04, the main crossover's centre
#     and high-pass legs, which is why the old list drove them through
#     `xover:ctr` / `xover:sub` and tested the second one at 100 Hz. They
#     are C2_MON_OUT_L / C2_MON_OUT_R now: the main bus taken at
#     C2_MON_PICK (sel=2, post master fader) through C2_MON's own L and R
#     levels. So they are an ordinary stereo pair, driven by the donor's
#     PAN exactly as the MAIN XLRs are, and both are tested at 1 kHz.
#   * PHONES L / PHONES R (J10, DAC_09/10) are C2_PHN_OUT_L/R, the same
#     pick-off through `Mon PhonesLevel`. They are REACHABLE now and are
#     still not driven here: a phones patch is a stereo TRS with a null
#     sub-test and a level cell nothing has ever measured, which is its own
#     piece of work (S151 note).
#
#   THE CROSSOVER IS OUT, AND IT IS OUT BY DEFAULT.  `Main CrossoverOn`
#   (addr 1438) boots 0 and `_xover_coeffs_next_*` boots the compiled
#   identity, so both MAIN XLRs are full-range with no write at all. The
#   old list wrote `MainL CrossoverFreq/Slope` to set the two monitor legs
#   wide and shallow; those two cells no longer exist (the family is
#   `Main CrossoverFreq/Slope` now) and nothing this station measures reads
#   a crossover leg any more, so the station writes no crossover cell.
# Sockets this list does NOT drive, and why -- said by name, so a socket
# never falls off the list silently. Nothing on a D24 is UNREACHABLE by the
# firmware any more (S144 gave DAC_09/10/14 sources); what is left is one
# pair this list has not been written for yet.
UNREACHABLE = {
    'PHONES L': ('reachable since S144 (DAC_09 = C2_PHN_OUT_L, off the '
                 'monitor pick-off through `Mon PhonesLevel`) but no patch '
                 'is written for it yet: a phones patch is a stereo TRS with '
                 'its own null sub-test and a level cell nothing has '
                 'measured -- S151 note, owed'),
    'PHONES R': ('reachable since S144 (DAC_10 = C2_PHN_OUT_R, off the '
                 'monitor pick-off through `Mon PhonesLevel`) but no patch '
                 'is written for it yet: a phones patch is a stereo TRS with '
                 'its own null sub-test and a level cell nothing has '
                 'measured -- S151 note, owed'),
}


def socket_sort(names):
    """MIC 2 before MIC 13. A plain sort puts them the other way round, which
    is fine for a machine and wrong on a page a person reads."""
    def key(s):
        m = re.match(r'^(.*?)(\d+)$', s.strip())
        return (m.group(1), int(m.group(2))) if m else (s, 0)
    return sorted(names, key=key)


def fmt(v):
    """A cell value the way s89_set.py spells it: floats as f<x>, ints bare."""
    return ('f%g' % v) if isinstance(v, float) else str(int(v))


def cells_close_assigns(strips, auxes):
    """Every strip's route to every bus this station can drive, shut.

    The oscillator REPLACES the donor strip's input, so the other strips carry
    only their own converter lanes -- which are the inputs under test, with a
    patch lead in them. Without this, a lead into MIC 5 puts MIC 5 on the main
    bus and the next MAIN patch measures the lead instead of the DSP.
    """
    out = []
    for s in strips:
        out.append('Chan%03dMainOn001=0' % s)
        out.append('Chan%03dCtrOn001=0' % s)
        for a in auxes:
            out.append('Chan%03dAuxOn%03d=0' % (s, a))
    return out


def cells_strip_transparent(d):
    """One strip, made a wire.

    EVERY strip under test needs this, not just the donor, and the reason is
    where the instrument stands: MeasChan taps a strip POST-FADER. A muted or
    faded strip therefore reads as an exact zero however healthy its converter
    lane is -- which is indistinguishable from a dead input. Measured on
    MW-D24-2 on 2026-09-26: twenty-three lanes read about -116 dBFS and MIC 20
    read -336, because the acoustic-loop test's own teardown leaves
    Chan020Mute001 at 1 and nothing had ever put it back.

    The processing goes with it, for S54-2's reason: a strip left at the
    configuration defaults has its gate and compressor ON, so a reading taken
    through one is not a reading of the path.
    """
    return ['Chan%03dPol001=0' % d,
            'Chan%03dEqOn001=0' % d,
            'Chan%03dEqHpf001=0' % d,
            'Chan%03dGateOn001=0' % d,
            'Chan%03dCompOn001=0' % d,
            'Chan%03dTubeOn001=0' % d,
            'Chan%03dDelay001=0' % d,
            'Chan%03dLevel001=f1.0' % d,
            'Chan%03dMute001=0' % d,
            'Chan%03dPan001=f0.5' % d,
            'Chan%03dGain001=f1.0' % d]


def cells_all_strips_transparent(strips):
    out = []
    for s in strips:
        out += cells_strip_transparent(s)
    return out


def cells_bus_masters(auxes):
    """Every bus master open at unity, so a reading is the PATH and not a fader."""
    out = []
    for a in auxes:
        out += ['Aux%03dLevel001=f1.0' % a, 'Aux%03dMute001=0' % a,
                'Aux%03dEqOn001=0' % a, 'Aux%03dLimiterOn001=0' % a,
                'Aux%03dAntiFbOn001=0' % a, 'Aux%03dDelay001=0' % a]
    # THE MONITOR BUS IS A MEASURED PATH NOW, NOT A HAZARD (S122, S144).
    #
    # It used to be both. Until S122 the monitor bus fed the codec's
    # talkback-speaker pair, the speaker amplifier runs from the digital
    # board's 5 V and is live whenever the unit is up, and `defs` declares
    # C2_MON at unity -- so every boot left the panel speaker wide open and
    # this station, which drives the MAIN bus at full level for ten of its
    # patches, had to shut the monitor legs to stop a 1 kHz tone playing out
    # of the panel for the length of the pass.
    #
    # S122 took the speaker off the monitor bus: C2_HPT_01 is C2_SPKR_OUT's
    # only source and the monitor bus reaches no speaker at all. S144 then
    # gave the monitor bus the two rear MONITOR jacks. So shutting these two
    # legs no longer protects anything and now silences two sockets under
    # test -- they are opened at unity, like every other bus master here.
    out += ['Mon001Level001=f1.0', 'Mon001Level002=f1.0', 'Mon001Delay001=0']
    # The monitor pick-off, asserted rather than assumed: 2 = post master
    # fader (C2_MON_PICK sources are C2_MIX_MAIN_L, C2_MAIN_DLY, C2_MAIN_FDR
    # and sel boots 2), which is the tap the MONITOR rows are written for.
    out += ['Mon001PickOff001=2']
    out += ['Main001Level001=f1.0', 'Main001Mute001=0', 'Main001Delay001=0',
            'MainL001Level001=f1.0', 'MainL001Mute001=0',
            'MainR001Level001=f1.0', 'MainR001Mute001=0']
    # THE THIRD MAIN OUTPUT (S144). `Main Out3Mode` picks which strip the
    # one C/LF XLR carries -- 0 = Centre, 1 = Woof -- and the station tests
    # the CENTRE, because the Centre strip is what `Chan*CtrOn` reaches and
    # the Woof strip is fed from the main L/R sum through a low-pass that a
    # 1 kHz tone is meant not to survive. Its own processing goes off for
    # S54-2's reason: a reading taken through a limiter is not a reading of
    # the path. There is no `MainCtr Mute` and no `MainSub Mute` cell in this
    # generation; the mute on this path is `Main Out3Mute`.
    out += ['Main001Out3Mode001=0', 'Main001Out3Mute001=0',
            'Main001Out3Delay001=0',
            'MainCtr001Level001=f1.0', 'MainCtr001EqOn001=0',
            'MainCtr001LimiterOn001=0', 'MainCtr001AntiFbOn001=0',
            'MainSub001Level001=f1.0']
    return out


def route_cells(donor, drive, auxes):
    """The cells that change per patch: which bus the donor strip feeds.

    `drive` is the list's own word for the output under test -- 'aux:1',
    'aux:1+2', 'main:L', 'main:R', 'ctr' or 'none'. Every other assign on the
    donor is written 0 in the same breath, so a route is always asserted whole
    and never left half-set from the patch before.

    'main:L' / 'main:R' drive BOTH stereo pairs the main bus reaches -- the
    MAIN XLRs (C2_MAIN_OUT_01/02) and the rear MONITOR jacks
    (C2_MON_OUT_L/R) -- because both pairs take their two legs from the same
    two buses and the donor's PAN is what separates them. That is only true
    of the S143 graph: before it, C2_MAIN_FDR read the LEFT mix and nothing
    read the right, so 'main:R' emptied every main socket at once.

    'ctr' is the third main output. It is NOT a pan position: `Chan*CtrOn`
    is its own assign into C1_BUS_SUB (the Centre/sub channel bus, PW ruling
    R5), so a centre send is full level and the pan is left at the middle.
    The old list spelled it 'xover:ctr' / 'xover:sub' because DAC_15/16 were
    the main crossover's two legs; they are the monitor bus now (S144).
    """
    off = {'main': 0, 'ctr': 0}
    off_aux = dict((a, 0) for a in auxes)
    pan = 0.5
    kind, _, arg = drive.partition(':')
    if kind == 'aux':
        for a in (int(x) for x in arg.split('+')):
            off_aux[a] = 1
    elif kind == 'main':
        off['main'] = 1
        pan = 0.0 if arg == 'L' else 1.0
    elif kind == 'ctr':
        off['ctr'] = 1
    elif kind != 'none':
        raise SystemExit('unknown drive %r' % drive)
    out = ['Chan%03dMainOn001=%d' % (donor, off['main']),
           'Chan%03dCtrOn001=%d' % (donor, off['ctr']),
           'Chan%03dPan001=%s' % (donor, fmt(pan))]
    for a in auxes:
        out.append('Chan%03dAuxOn%03d=%d' % (donor, a, off_aux[a]))
        if off_aux[a]:
            out.append('Chan%03dAuxSend%03d=f1.0' % (donor, a))
            out.append('Chan%03dAuxPick%03d=3' % (donor, a))   # post-fader
    return out


# ---------------------------------------------------------------------------
# The list
# ---------------------------------------------------------------------------
AUXES = tuple(range(1, 9))
STRIPS = tuple(range(1, 25))
# The codec return lanes. MeasChan 1..32 are strips and 33..50 are buses, so
# these three inputs cannot be measured any other way at all
# (dsp_codegen.py TEST_MEAS_LANE_CODES, proven on the part in S70/S73).
LANE_TALKBACK = 53
LANE_MJ_L = 51
LANE_MJ_R = 55

# The output the list parks a lead on when the patch is about the INPUT. AUX 1
# is chosen because it is the first path the station proves (patch 1), so by
# the time anything is parked on it, it has already passed.
PARK_OUT = 'AUX 1'
PARK_DRIVE = 'aux:1'
# The input the list parks a lead in when the patch is about the OUTPUT. MIC 1
# for the same reason, and because it is not the donor strip.
PARK_IN = 'MIC 1'
PARK_IN_STRIP = 1

# The eight aux XLRs and the three main XLRs, in the order the K1 block
# proves them. Every one is a socket in its own right and gets a patch of its
# own before AUX 1 is parked for the rest of the block. C/LF is one of them
# since S144 gave it a source (S151); its panel name is the one the rear
# panel and the harness port table use, "C/LF" -- "Center/LF Out" in the
# catalog, row 35, loop partner MIC 11.
XLR_OUTS = [('AUX %d' % a, 'aux:%d' % a) for a in AUXES] + [
    ('MAIN L', 'main:L'), ('MAIN R', 'main:R'), ('C/LF', 'ctr')]

# ---------------------------------------------------------------------------
# THE PARKED KIT (PW 2026-09-27, ruling c; review §2.3)
# ---------------------------------------------------------------------------
# "All five kit items go on during START, under machine time. Parked ends are
# per review §2.3: XLR lead on the 1st XLR output, XLR->jack on the 2nd XLR
# output, jack->XLR on the 2nd XLR input (not the reference input), XLR->mini-
# jack on the 3rd XLR output, and the 150 ohm plug on the bench. The generator
# orders every block around the parked ends."
#
# WHAT PARKING CAN AND CANNOT BUY, MEASURED RATHER THAN ASSUMED (S126-1).
# Every socket a lead can usefully be parked on is a socket some walk has to
# visit: each of the ten XLR outputs gets a patch of its own in the output
# walk, and each of the twenty-four XLR inputs gets seven gain steps and a
# noise reading in the input walk. So a parked end cannot simply stay put --
# the walk that proves its socket has to have it off. What the generator CAN
# do, and does here, is order each walk so that the socket carrying a parked
# lead is the LAST one that walk visits, which makes the collision exactly one
# folded sentence ("take the jack-to-XLR lead off AUX 2 first") at the moment
# the hand is already at that socket, and puts the lead in the operator's hand
# immediately before the block that needs it. There is no separate change
# screen and no card, which is what the ruling asked for; the hand-move
# arithmetic is in the S126 report and it is not the review's 24-40 s.
#
# `end` is which END of the lead is parked:
#   out    an XLR-F (or the XLR lead's output end) hangs on a D24 XLR OUTPUT
#   in     an XLR-M sits in a D24 XLR INPUT
#   bench  it is not on the unit at all
PARK_OUT_END_LEADS = ('K1', 'K4', 'K3')
KIT_PARK = {
    # lead: (which end, the nominal socket, the drive that socket carries)
    'K1': ('out', 'AUX 1', 'aux:1'),
    'K4': ('out', 'AUX 2', 'aux:2'),
    'K3': ('out', 'AUX 3', 'aux:3'),
    'K2': ('in', None, None),        # the second working input, bound below
    'K5': ('bench', None, None),
}
# The order the output walk visits its ten sockets in: everything that has
# nothing parked on it first, then the parked ones, last, in kit order. Built,
# not typed, so excluding AUX 2 moves the parking rather than breaking it.
def output_walk_order(parked):
    clean = [x for x in XLR_OUTS if x[0] not in parked]
    late = [x for x in XLR_OUTS if x[0] in parked]
    return clean + late

# The stereo TRS output jacks: one patch, three sub-tests. `l`/`r` are the two
# aux buses the jack's tip and ring carry -- the SAME buses the Aux Out A XLRs
# carry, tapped in parallel off the same output stage (findings.md: the TRS
# jack is "J9.19/20 in parallel" with the XLR), which is why a jack can fail
# while its XLR passes and both are worth a patch.
STEREO_TRS_OUTS = [('AUX A %d-%d' % (a, a + 1), a, a + 1) for a in (1, 3, 5, 7)]

# The two mono TRS output jacks. They are the MONITOR bus's two legs since
# S144 -- C2_MON_OUT_L/R off C2_MON_PICK -- so they are a stereo pair driven
# by the donor's pan, both in the passband, and neither of them is a
# crossover leg any more.
MONO_TRS_OUTS = [('MONITOR L', 'main:L', TONE_HZ,
                  'the MONITOR bus LEFT leg (C2_MON), post master fader: the '
                  'donor is panned hard left, so a reading here that follows '
                  'MAIN L is the monitor path and not a crossover leg'),
                 ('MONITOR R', 'main:R', TONE_HZ,
                  'the MONITOR bus RIGHT leg (C2_MON_R). Hard right: this is '
                  'the other half of the same pair, and it only exists at all '
                  'because S143 gave chip 2 a right bus')]

COLUMNS = ('path', 'patch', 'lead', 'block', 'out', 'in', 'sub', 'drive',
           'lane', 'donor', 'route', 'freq_hz', 'level_dbfs', 'expect',
           'level_ref', 'polarity', 'rows', 'prompt', 'note', 'park',
           'gain_code', 'send_pos', 'unpark')

# ---------------------------------------------------------------------------
# THE ORDER (PW 2026-09-26)
# ---------------------------------------------------------------------------
# "Test all XLR outputs first, in a line, as they flow on the mixer. If there
# is no detection, move the input to the next one until a working loop is
# established; then check all XLR outs in a row first, then all XLR ins in a
# row second -- faster, and it saves cross-patching to find combinations that
# may or may not work."
#
# So every patch has ONE END PARKED and the other end moving, and the parked
# end is a socket that has already been proved. That is what makes a fail mean
# something: a patch with a known-good input and a moving output fails BECAUSE
# OF THE OUTPUT, with nothing to hunt.
#
# The parked end is not decided here. It cannot be: which input is good is a
# fact about the unit in front of the operator, and this list is generated
# before anybody plugs anything in. So the `park` column says WHICH END is
# parked and the runner binds it at run time to the socket the first step
# found:
#
#   find   the first patch of all. The output end sits on the first XLR
#          output; the input end WALKS until the tone arrives, and the input
#          it stops on becomes the reference for everything after it.
#   in     the input end is parked on the reference input; the output moves.
#   out    the output end is parked on the reference output; the input moves.
#   ''     neither: the patch names both ends itself.
#
# The cost of this order, stated plainly, is about ten extra hand moves: the
# old list proved an output and an input with the same patch, and this one
# does not. What it buys is that no fail ever needs a second patch to
# interpret.
PARK_FIND, PARK_IN_END, PARK_OUT_END = 'find', 'in', 'out'

# ---------------------------------------------------------------------------
# THE SEVEN GAIN STEPS (PW 2026-09-26)
# ---------------------------------------------------------------------------
# "The real test should test all 6 gain resistors off, and each resistor
# enabled individually -- total 7 steps." The lead is already in the socket,
# so this costs no hand move at all: it is machine time spent behind a screen
# that already says "Checking...".
#
# WHAT EACH STEP SHOULD READ IS NOT TYPED HERE. defs' own mic gain law
# (`defs/common/tables/mic-gain-law.csv`, measured on MW-D24-2's analog board
# on 2026-09-16) gives `hw_gain_db` for 25 of the 64 codes -- and three of the
# six single-element codes are NOT among them, because the law only keeps the
# code it would actually pick for each target dB. So the six ELEMENT gains are
# fitted to that same table and the three missing steps come out of the fit.
#
# The fit is one line of physics and no free hardware constants: the preamp is
# an instrumentation amplifier whose gain is 1 + 2Rf/Rg with Rg the PARALLEL
# combination of whichever elements are switched in, so
#
#     G(code) = 1 + sum(k_i for each element i in the code)
#
# with six unknowns k_i = 2Rf/R_i. Twenty-four measured codes determine them
# by least squares, and the residual is reported so nobody has to take the fit
# on trust. A step whose expected value came out of the fit says so in the
# `source` column, and the window in patch-limits.csv is wide enough to cover
# the fit's own error several times over.
GAIN_STEPS = (0, 1, 2, 4, 8, 16, 32)

# ---------------------------------------------------------------------------
# THE INPUT ORDER (PW 2026-09-27, ruling g: STOPWATCH FIRST)
# ---------------------------------------------------------------------------
# Both orders are generated, behind one switch, and the default is the one the
# bench runs today until PW's stopwatch says otherwise:
#
#   three-walks  the XLR lead walks every input with its seven gain steps and
#                then the talkback; the 150 ohm plug walks every input; the
#                XLR-to-jack lead walks every combo jack. Three traverses of
#                the input row, one lead each.
#   one-stop     one stop per input: at each input the XLR lead's seven gain
#                steps, then the plug, then the jack lead, then on to the next
#                input. One traverse, three leads juggled at every socket.
#
# The estimate that made this PW's call rather than the generator's: 24 traverse
# moves become in-place swaps, worth 29 / 48 s IF a swap is about 60 % of a
# traverse -- and juggling three ends at one socket could erase it. Nobody has
# timed either, so nobody knows. `s126-stopwatch-card.md` is the card that
# settles it.
INPUT_ORDERS = ('three-walks', 'one-stop')
# The noise reading rides the input walk now (PW 2026-09-26), at the gain the
# 2026-09-16 survey used: every element in, which is the code the old separate
# noise block wrote.
EIN_GAIN_CODE = 63


# ---------------------------------------------------------------------------
# Exclusions: a shorter list, still generated
# ---------------------------------------------------------------------------
# WHY THE GENERATOR AND NOT A FILTER AFTERWARDS (S123 item 5). A unit with
# eight dead inputs and no mini-jacks fitted still has to be patch-tested, and
# on 2026-09-26 that meant a hand-written script that cut rows out of the full
# list and patched three of them up by hand. A cut list is not the same thing
# as a shorter list: taking MIC 2 out takes AUX 2's ONLY test with it, and
# taking MIC 1 out takes the input every TRS output is read on. Both of those
# have to be re-homed, and re-homing is exactly the kind of thing that is
# right once and wrong the second time somebody does it by hand. So the
# exclusions go in here, where the block that knows what each patch is FOR can
# do it, and the short list is generated from the same source as the full one.
#
# WHAT IS RE-HOMED, and it is only ever onto a PARKED input:
#   * an output whose only patch used an excluded input moves to the first
#     working input that was only carrying the parked output anyway;
#   * the TRS-output block, which reads everything on one input, moves to the
#     first working input.
# Nothing is re-homed onto an input that has a test of its own, because that
# would silently drop the output that test was proving.
def parse_excludes(specs):
    """`MIC1-4,MIC13-16` or `MIC 1-4, MIC 13` -> {'MIC 1', ... }.

    A range is a socket name with two numbers in it. Anything without a
    number is taken whole, so TALKBACK excludes the talkback XLR.
    """
    out = set()
    for spec in specs or ():
        for item in re.split(r'[,\s]*,[,\s]*|\s{2,}', spec.strip()):
            item = item.strip()
            if not item:
                continue
            m = re.match(r'^([A-Za-z][A-Za-z\- ]*?)\s*(\d+)\s*-\s*(\d+)$', item)
            if m:
                pre = m.group(1).strip().upper()
                for n in range(int(m.group(2)), int(m.group(3)) + 1):
                    out.add('%s %d' % (pre, n))
                continue
            m = re.match(r'^([A-Za-z][A-Za-z\- ]*?)\s*(\d+)$', item)
            if m:
                out.add('%s %d' % (m.group(1).strip().upper(), int(m.group(2))))
            else:
                out.add(item.upper())
    return out


# The leads, by the words a person uses for them rather than by kit code, so
# `--exclude-lead mini-jack` works without anybody looking up K3.
LEAD_ALIASES = {
    'K1': 'K1', 'XLR': 'K1',
    'K2': 'K2', 'JACK-TO-XLR': 'K2',
    'K3': 'K3', 'MINI-JACK': 'K3', 'MINIJACK': 'K3', 'XLR-TO-MINI-JACK': 'K3',
    'K4': 'K4', 'XLR-TO-JACK': 'K4', 'LINE': 'K4',
    'K5': 'K5', 'TERMINATOR': 'K5', '150-OHM': 'K5', '150OHM': 'K5',
}


def parse_lead_excludes(specs):
    out = set()
    for spec in specs or ():
        for item in re.split(r'[,\s]+', spec.strip()):
            if not item:
                continue
            key = item.strip().upper()
            if key not in LEAD_ALIASES:
                raise SystemExit(
                    '%r is not a lead. Use one of: %s'
                    % (item, ', '.join(sorted(set(LEAD_ALIASES)))))
            out.add(LEAD_ALIASES[key])
    return out


class Builder:
    def __init__(self, ports, cells, excl_inputs=(), excl_leads=(),
                 park_kit=True, input_order='three-walks'):
        if input_order not in INPUT_ORDERS:
            raise SystemExit('--input-order must be one of %s'
                             % ', '.join(INPUT_ORDERS))
        self.park_kit = bool(park_kit)
        self.input_order = input_order
        self.ports, self.cells = ports, cells
        self.send_at = load_send_pos()
        self.gain_seen = load_gain_codes()
        self.paths, self.routes, self.missing = [], {}, []
        self.n = 0
        self.patch = 0
        self.notrun = []
        self.excl_in = set(excl_inputs)
        self.excl_lead = set(excl_leads)
        self.rehomed = []            # (what moved, where to, why)
        self.dropped = 0             # patches the exclusions removed

    # -- exclusions ---------------------------------------------------------
    def out_in(self, name):
        """`MIC 5 line` and `MIC 5` are the same socket to an exclusion: a
        combo jack that is dead is dead through both of its holes."""
        base = (name or '').replace(' line', '').strip().upper()
        return base in self.excl_in

    def out_lead(self, lead):
        return lead in self.excl_lead

    def strips(self):
        return tuple(n for n in STRIPS if not self.out_in('MIC %d' % n))

    def park_in(self):
        """The input the TRS-output block reads on: MIC 1, or the first
        working input if MIC 1 is excluded."""
        if not self.out_in(PARK_IN):
            return PARK_IN, PARK_IN_STRIP
        left = self.strips()
        if not left:
            raise SystemExit('every input is excluded: there is no list left')
        return 'MIC %d' % left[0], left[0]

    # -- the parked kit (ruling c) ------------------------------------------
    def kit(self):
        """Each lead, which end of it is parked, and on which socket.

        Resolved against the exclusions, never typed twice: an excluded AUX 2
        moves the XLR-to-jack lead's parked end to the next working output, and
        an excluded MIC 1 moves the reference input, which moves the input the
        jack-to-XLR lead parks in. With `--no-park-kit` every lead falls back
        to the socket the list used before the ruling, which is what makes the
        before/after timing runs comparable.
        """
        if getattr(self, '_kit', None) is not None:
            return self._kit
        ref_in, _ref_strip = self.park_in()
        outs = [o for o in XLR_OUTS if not self.out_in(o[0])]
        if not outs:
            raise SystemExit('every XLR output is excluded: there is no list left')
        kit = {}
        if self.park_kit:
            # The first three working XLR outputs, in panel order: the XLR
            # lead, then the XLR-to-jack lead, then the XLR-to-mini-jack lead.
            for lead, o in zip(PARK_OUT_END_LEADS, outs):
                kit[lead] = dict(end='out', socket=o[0], drive=o[1], lane=None)
            for lead in PARK_OUT_END_LEADS[len(outs):]:
                kit[lead] = dict(end='out', socket=outs[-1][0],
                                 drive=outs[-1][1], lane=None)
            name, strip = self.park_in2()
            kit['K2'] = dict(end='in', socket=name, drive=None, lane=strip)
        else:
            for lead in PARK_OUT_END_LEADS:
                kit[lead] = dict(end='out', socket=outs[0][0], drive=outs[0][1],
                                 lane=None)
            name, strip = self.park_in()
            kit['K2'] = dict(end='in', socket=name, drive=None, lane=strip)
        kit['K5'] = dict(end='bench', socket=None, drive=None, lane=None)
        self._kit = kit
        return kit

    def parked_outputs(self):
        """The output sockets that carry a parked lead, and which lead."""
        k = self.kit()
        return dict((k[l]['socket'], l) for l in PARK_OUT_END_LEADS
                    if k[l]['end'] == 'out' and k[l]['socket'])

    def input_walk_strips(self):
        """The inputs, in the order the walk visits them.

        The input the jack-to-XLR lead parks in comes LAST (ruling c): the walk
        has to have that lead out of the socket to read the input's own seven
        gain steps, so the collision is put where it costs one folded sentence
        and hands the operator the lead the TRS block needs next.
        """
        left = list(self.strips())
        if not self.park_kit:
            return left
        _name, strip = self.kit()['K2']['lane'], None
        strip = self.kit()['K2']['lane']
        if strip in left and len(left) > 1:
            left = [n for n in left if n != strip] + [strip]
        return left

    def park_in2(self):
        """The input the jack-to-XLR lead parks in: the first working input
        that is NOT the reference input (PW: "not the reference input"), and
        not the donor strip, whose input block the oscillator replaces."""
        ref, ref_strip = self.park_in()
        for n in self.strips():
            if n != ref_strip and n != DONOR_DEFAULT:
                return 'MIC %d' % n, n
        # One working input and it is the reference: there is nowhere else, so
        # the lead parks where it used to and the collision is the walk's own.
        return ref, ref_strip

    def rows_for(self, *names):
        out = []
        for nm in names:
            p = self.ports.get(nm)
            if p and p.get('catalog_row'):
                out.append(p['catalog_row'])
        return ' '.join(sorted(set(out), key=int))

    def route(self, donor, drive):
        """The route id, and BOTH donors for it.

        The runner binds a parked end at run time -- it cannot know before the
        operator plugs anything in which input is good -- and the donor
        depends on the input being measured (the oscillator cannot be injected
        into the strip under test). So every drive this list uses gets a route
        for both donors, and a rebound patch can never name one that is not
        there.
        """
        rid = '%s@%d' % (drive.replace(':', '').replace('+', 'p'), donor)
        for d in (DONOR_DEFAULT, DONOR_ALT):
            alt = '%s@%d' % (drive.replace(':', '').replace('+', 'p'), d)
            if alt not in self.routes:
                self.routes[alt] = route_cells(d, drive, AUXES)
        return rid

    def add(self, **kw):
        if 'in_' in kw:                      # `in` is a keyword; the column is not
            kw['in'] = kw.pop('in_')
        self.n += 1
        kw.setdefault('sub', '')
        kw.setdefault('note', '')
        kw.setdefault('park', '')
        kw.setdefault('gain_code', '')
        kw.setdefault('unpark', '')
        kw.setdefault('send_pos', '')
        kw.setdefault('prompt', '')
        kw.setdefault('freq_hz', TONE_HZ)
        kw.setdefault('level_dbfs', TONE_DBFS)
        row = dict((c, '') for c in COLUMNS)
        row.update(kw)
        row['path'] = self.n
        row['patch'] = 'P%d' % self.patch
        row['route'] = self.route(int(kw['donor']), kw['drive'])
        self.paths.append(row)

    def new_patch(self):
        self.patch += 1
        return 'P%d' % self.patch

    # -- the blocks ---------------------------------------------------------
    def block_k1_outputs(self):
        """Every XLR output in a row, into one input (PW 2026-09-26).

        The FIRST patch is the one that finds the loop: its output end is the
        first XLR output and its input end walks until the tone arrives. The
        input it stops on is the reference for the whole pass, and every
        patch after this one in this block is that same input with the output
        end moving -- so a fail here is the OUTPUT and nothing else.
        """
        ref_in, ref_strip = self.park_in()
        parked = self.parked_outputs()
        # THE PARKED SOCKETS ARE VISITED LAST (ruling c). The XLR lead's own
        # parked socket is the first patch of all, because that patch is what
        # the lead is already plugged into; the other two carry leads this
        # walk has to have off, so they come at the end of the walk, where the
        # unpark hands the operator the lead the next block needs.
        mine = self.kit()['K1']['socket']
        late = dict((k, v) for k, v in parked.items() if k != mine)
        order = output_walk_order(late)
        for i, (out, drive) in enumerate(order):
            self.new_patch()
            self.add(lead='K1', block='the outputs', out=out, in_=ref_in,
                     drive=drive, lane=ref_strip, donor=donor_for(ref_strip),
                     expect='tone', level_ref='ref', polarity='ref',
                     rows=self.rows_for(out, ref_in),
                     prompt='Patch %s to %s' % (out, ref_in),
                     park=(PARK_FIND if i == 0 else PARK_IN_END),
                     unpark=late.get(out, ''),
                     note=('the first patch of the pass: the input end walks '
                           'until the tone arrives, and the input it stops on '
                           'is the reference for every patch after it'
                           if i == 0 else
                           'at the end of the walk on purpose: the %s has '
                           'been parked on this socket since START and has to '
                           'come off for this patch, so the walk pays that '
                           'once, last, with the hand already there'
                           % LEADS[late[out]]['name'] if out in late else ''))

    def block_k1_inputs(self):
        """Every XLR input in a row, from one output (PW 2026-09-26).

        The output end is parked on the output the loop was found with, so a
        fail here is the INPUT and nothing else. Inputs the first step already
        walked past are recorded there and are not walked again.

        EACH INPUT IS TWO OPERATOR STEPS AND NINE READINGS. The lead goes in
        and the tester takes SEVEN gain steps without the hand moving again
        (all six gain-leg elements off, then each one alone); then the lead
        comes out, the 150 ohm plug goes in, and the input's own noise is read
        at full gain. PW's amendment of 2026-09-26 made it that way round --
        sequential, one socket at a time -- rather than the plug following one
        socket behind, so nothing has to be proved about crosstalk between a
        driven input and the one next to it.
        """
        for strip in self.input_walk_strips():
            inp = 'MIC %d' % strip
            pos = self.send_at[strip]
            self.new_patch()
            unpark = ('K2' if (self.park_kit
                               and strip == self.kit()['K2']['lane']) else '')
            k1out, k1drive = self.kit()['K1']['socket'], self.kit()['K1']['drive']
            for step in GAIN_STEPS:
                db, _src = gain_db(step, self.gain_seen)
                self.add(lead='K1', block='the inputs', out=k1out, in_=inp,
                         drive=k1drive, lane=strip, donor=donor_for(strip),
                         unpark=(unpark if step == 0 else ''),
                         expect='tone',
                         level_ref=('ref' if step == 0 else 'gain'),
                         polarity=('ref' if step == 0 else '-'),
                         sub='g%d' % step, gain_code=step, send_pos=pos,
                         level_dbfs=round(GAIN_TONE_DBFS - db, 2),
                         rows=self.rows_for(k1out, inp),
                         prompt='Patch %s to %s' % (k1out, inp),
                         park=PARK_OUT_END,
                         note=('the tone reference for this input, every gain '
                               'element off' if step == 0 else
                               'gain element %d alone; the drive is dropped by '
                               'the step\'s own expected gain so the converter '
                               'reads about the same level every step'
                               % (step.bit_length())))
            if not self.out_lead('K5'):
                self.new_patch()
                self.add(lead='K5', block='the inputs', out='', in_=inp,
                         drive='none', lane=strip, donor=donor_for(strip),
                         expect='noise', level_ref='ein', polarity='-',
                         level_dbfs='', freq_hz='', gain_code=EIN_GAIN_CODE,
                         send_pos=pos, rows=self.rows_for(inp),
                         prompt='Fit the 150 ohm terminator in %s' % inp,
                         note='the input noise, at the gain the 2026-09-16 '
                              'survey used; the window is limits.csv '
                              't4b_ein_max_dbu')
            # ONE STOP PER INPUT (ruling g): the jack lead's own patch for this
            # input rides here instead of in a walk of its own. Same patch,
            # same reading, same row -- only the order changes.
            if self.input_order == 'one-stop' and not self.out_lead('K4'):
                self.add_k4_patch(strip, block='the inputs')
        if self.out_in('TALKBACK'):
            return
        self.new_patch()
        k1out, k1drive = self.kit()['K1']['socket'], self.kit()['K1']['drive']
        self.add(lead='K1', block='the inputs', out=k1out,
                 in_='TALKBACK', drive=k1drive, lane=LANE_TALKBACK,
                 donor=DONOR_DEFAULT, expect='tone', level_ref='info',
                 polarity='info', rows=self.rows_for(k1out, 'TALKBACK'),
                 prompt='Patch %s to TALKBACK' % k1out,
                 park=PARK_OUT_END,
                 note='the talkback XLR is on the AK4619 codec, not the mic '
                      'preamps: a different gain law and about 23 dB more noise '
                      '(S70), so its level is reported and not judged until PW '
                      'rules a window')

    def block_k4(self):
        """The line paths: the same combo jacks, entered through the TRS centre.

        HOW THE LINE PATH IS SELECTED IS NOT IN THIS REPO. Chan<n>InputSel001
        is declared `mcu` -- "MCU hardware control" -- so it is not a DSP write
        this runner can make, and nothing in defs, the DSP graph or the 595
        image says what else selects it. On a combo jack the TRS centre is
        normally switched mechanically by the plug, in which case there is
        nothing to set and this block just works. The list therefore sets NO
        selection cell, measures the path, and reports the level rather than
        judging it -- the tone-present verdict is the factory question either
        way. See the report's open items.

        AND THE SOCKET IS JUDGED, NOT ASSUMED (S129, PW's finding). A tester
        with the XLR lead in hand can put it in the SAME socket's XLR and every
        one of these patches passes, which is what happened on 2026-09-27: MIC
        7, 9, 10 and 11 were patched XLR and passed, MIC 12 and 17..22 were
        patched jack and all seven came back inverted. Those eleven readings in
        one pass are the discriminator, and the netlist says why it is sound --
        see `add_k4_patch`'s note. So the expectation is `inverted`, and a
        `normal` reading on a line row is reported as the lead being in the
        wrong socket rather than as a polarity fault.

        THE ERRATUM, ONE CHANNEL TRACED (mx26 `docs/d24-netlist-global.csv`):
        MIC 12's jack TIP is `analog:J41.T` -> net `MIC_9-12_21-24_MIC_IN_12_L1`
        -> `R1715` -> net `..._M1`, and `..._M1` is also `analog:J41.3`, XLR
        pin 3 -- the preamp's COLD leg. The RING is `analog:J41.R` -> `..._L0`
        -> `R1714` -> `..._M0` = `analog:J41.2`, XLR pin 2, the HOT leg. Every
        combo socket from MIC 3 to MIC 24 is wired the same way round through
        its own pair of resistors (MIC 1-2 are XLR-only and have no jack), so
        a standard TRS lead -- tip to pin 2, which is how K4 is wired --
        presents the signal on the cold leg and the channel reads inverted.
        The mod is the same two parts on every channel whichever way the
        connector symbol's T/R pins are labelled: cross the two resistors'
        inner ends so the tip reaches M0 and the ring reaches M1.
        """
        if self.input_order == 'one-stop':
            return                        # every K4 patch rode the input walk
        for strip in self.input_walk_strips():
            self.add_k4_patch(strip, block='the line inputs')

    def add_k4_patch(self, strip, block):
        """One combo jack's line path. Its output end is the XLR-to-jack
        lead's own parked socket (ruling c), which the output walk proved."""
        k = self.kit()['K4']
        out, drive = k['socket'], k['drive']
        self.new_patch()
        self.add(lead='K4', block=block, out=out,
                 in_='MIC %d line' % strip, drive=drive, lane=strip,
                 donor=donor_for(strip), expect='tone', level_ref='info',
                 polarity='inverted', rows='',
                 prompt='Patch %s to LIN %d' % (out, strip),
                 park=PARK_OUT_END,
                 note='the jack centre reads INVERTED against this socket\'s '
                      'own XLR reference: the board wires the jack TIP to the '
                      'preamp cold leg on MIC 3..24 (S129 erratum, red mod '
                      'owed -- see block_k4). That reading is also what tells '
                      'the jack from the XLR, so an XLR lead is refused here. '
                      'Level reported, tone presence and socket judged')

    def block_k2(self):
        """The TRS output jacks, read through the input the jack-to-XLR lead
        is parked in (ruling c) -- the second working input, not the reference
        one, and one the input walk has just proved with its own gain steps."""
        k = self.kit()['K2']
        park_in, park_strip = k['socket'], k['lane']
        if park_in != PARK_IN:
            self.rehomed.append(('the TRS outputs', park_in,
                                 'the jack-to-XLR lead is parked there'
                                 if self.park_kit else
                                 '%s is excluded' % PARK_IN))
        for name, drive, hz, why in MONO_TRS_OUTS:
            self.new_patch()
            self.add(lead='K2', block='the TRS outputs', out=name, in_=park_in,
                     drive=drive, lane=park_strip, donor=DONOR_DEFAULT,
                     freq_hz=hz, expect='tone', level_ref='info',
                     polarity='normal', rows=self.rows_for(name, park_in),
                     prompt='Patch %s to %s' % (name, park_in), note=why,
                     park=PARK_IN_END)
        for jack, la, ra in STEREO_TRS_OUTS:
            self.new_patch()
            base = dict(lead='K2', block='the TRS outputs', out=jack,
                        in_=park_in, lane=park_strip, donor=DONOR_DEFAULT,
                        rows=self.rows_for('%s L' % jack, park_in),
                        prompt='Patch %s to %s' % (jack, park_in),
                        park=PARK_IN_END)
            self.add(sub='L', drive='aux:%d' % la, expect='tone',
                     level_ref='single', polarity='normal',
                     note='tip alone: one leg of aux %d into a balanced input' % la,
                     **base)
            self.add(sub='R', drive='aux:%d' % ra, expect='tone',
                     level_ref='single', polarity='inverted',
                     note='ring alone: the input reads tip minus ring, so a '
                          'healthy ring reads inverted against the tip',
                     **base)
            self.add(sub='null', drive='aux:%d+%d' % (la, ra), expect='null',
                     level_ref='null', polarity='-',
                     note='both in phase: what is left is the L/R match. A '
                          'crossed or absent channel cannot null',
                     **base)

    def block_k3(self):
        """The stereo mini-jacks: one balanced drive, both lanes at once.

        BOTH JACKS LAND ON THE SAME CODEC LANE. The AK4619 has one stereo aux
        input and it is ADC1 L/R -- MeasChan 51 and 55 -- while the Analog PCBA
        carries two identical TIP/RING/GND/MJ_SW connectors (J2 and J3) for the
        two panel jacks. So the station proves each jack's own copper, one at a
        time, and CANNOT tell which jack a signal arrived through: the prompt
        says to leave the other one empty, and a tone with both plugged would
        be ambiguous rather than wrong.
        """
        for n in (1, 2):
            lane_l, lane_r = LANE_MJ_L, LANE_MJ_R
            other = 2 if n == 1 else 1
            jack = 'MINI-JACK %d' % n
            if self.out_in(jack):
                continue
            self.new_patch()
            k3 = self.kit()['K3']
            base = dict(lead='K3', block='the mini-jack inputs',
                        out=k3['socket'], in_=jack, drive=k3['drive'],
                        donor=DONOR_DEFAULT,
                        rows=self.rows_for('%s L' % jack),
                        prompt='Patch %s to %s, with MINI-JACK %d empty'
                               % (k3['socket'], jack, other),
                        park=PARK_OUT_END)
            # level_ref='info', not 'single': the mini-jack class has no ruled
            # level window (test-catalog PL-5, "class limit unruled") and no
            # balanced XLR reference of its own to read a single-ended leg
            # against -- both lanes are ADC1 direct. S130 (item 4): grade
            # INFORMATIONAL (tone presence + level reported) until PW rules
            # the class, same pattern as K4's line rows before their window.
            self.add(sub='L', lane=lane_l, expect='tone', level_ref='info',
                     polarity='info',
                     note='pin 2 reaches the tip, so the left lane carries the '
                          'drive as it stands', **base)
            self.add(sub='R', lane=lane_r, expect='tone', level_ref='info',
                     polarity='info',
                     note='pin 3 reaches the ring, so the right lane carries '
                          'the drive inverted. An inverted LEFT is a channel '
                          'swap, not two failures', **base)

    def block_unreachable(self):
        for name, why in sorted(UNREACHABLE.items()):
            p = self.ports.get(name, {})
            self.notrun.append(dict(port=name, row=p.get('catalog_row', ''),
                                    reason=why))

    def build(self):
        # THE ORDER IS PW'S, AND IT IS THE POINT: find a loop, then every
        # output in a row against it, then every input in a row against a
        # known-good output. Each block moves ONE end.
        # THE TRS BLOCK FOLLOWS THE INPUT WALK (S126, ruling c). The jack-to-XLR
        # lead is parked in the second working input and that input is the LAST
        # one the walk visits, so putting its own block next is what turns the
        # collision into a handover: the lead comes out of the socket for the
        # input's gain steps and goes straight back into it for the block that
        # reads on it. The line block, which used to sit here, moves after it.
        blocks = [('K1', self.block_k1_outputs), ('K1', self.block_k1_inputs),
                  ('K2', self.block_k2), ('K4', self.block_k4),
                  ('K3', self.block_k3)]
        for lead, fn in blocks:
            if self.out_lead(lead):
                self.notrun.append(dict(
                    port='every path that needs %s' % LEADS[lead]['name'],
                    row='',
                    reason='that lead was excluded from this list'))
                continue
            fn()
        for name in sorted(self.excl_in):
            self.notrun.append(dict(
                port=name, row=self.ports.get(name, {}).get('catalog_row', ''),
                reason='excluded from this list'))
        self.block_unreachable()
        self.check()
        return self

    def check(self):
        """Every cell the routes name must be declared by the product."""
        for rid, cl in sorted(self.routes.items()):
            for spec in cl:
                nm = spec.split('=')[0]
                if nm not in self.cells:
                    self.missing.append('%s: %s' % (rid, nm))
        for spec in (cells_close_assigns(STRIPS, AUXES)
                     + cells_all_strips_transparent(STRIPS)
                     + cells_bus_masters(AUXES)):
            nm = spec.split('=')[0]
            if nm not in self.cells:
                self.missing.append('standing: %s' % nm)
        if self.missing:
            raise SystemExit('cells named but not declared by the product:\n  '
                             + '\n  '.join(sorted(set(self.missing))))


# ---------------------------------------------------------------------------
# Writing it out
# ---------------------------------------------------------------------------
HEAD_PATHS = """\
# patch-paths.csv -- GENERATED by tools/accept/gen_patch_paths.py (S121). Do not edit.
# ONE row per measurement. Rows sharing a `patch` id are sub-tests of ONE physical
# connection and the operator is prompted once for the lot.
#   lead        which of the five kit leads this patch uses (see patch-plan.md)
#   out / in    D24 PANEL names. J numbers belong in records, never in a prompt
#   drive       which bus the oscillator is routed to: the `route` column's cells do it
#   lane        MeasChan: 1..24 a strip, 51/53/55 the codec return lanes
#   donor       the strip the oscillator replaces (never the lane under test)
#   expect      tone = a tone must be there; null = it must cancel; noise = no tone at all
#   level_ref   ref = this reading SETS the lane's balanced reference
#               single = about %.2f dB under that reference (one leg of a balanced pair)
#               null   = at or below %.0f dB relative to the same jack's single-ended reading
#               ein    = the input noise window, limits.csv t4b_ein_max_dbu
#               info   = measured and reported, not judged (no window ruled yet)
#   polarity    ref = sets the lane's reference phase; normal/inverted = against it;
#               info = reported only; - = not applicable
#   park        which end of the lead is PARKED on a socket already proved, and so
#               which end the runner binds at run time: find = the first patch of
#               all, whose input end walks until the tone arrives; in = the input
#               end is the reference input; out = the output end is the reference
#               output; empty = the patch names both ends itself
#   unpark      a kit lead is parked on THIS patch's socket and has to come off
#               before the lead in hand goes in (S126, ruling c). One folded
#               sentence on the same screen; never a card of its own
""" % (SINGLE_ENDED_DB, NULL_MAX_DB)

HEAD_ROUTES = """\
# patch-routes.csv -- GENERATED by tools/accept/gen_patch_paths.py (S121). Do not edit.
# The cells, BY NAME, that assert one route. Written whole every time, so a route is
# never half-set from the patch before. Values: f<x> is an IEEE-754 float word.
"""


HEAD_KIT = """\
# patch-kit.csv -- GENERATED by tools/accept/gen_patch_paths.py (S126). Do not edit.
# THE PARKED KIT (PW 2026-09-27, ruling c). One row per kit item, in the order the
# operator is walked through it on the D24's own screen at START. `end` is which end
# of the lead is parked and `socket` is the PANEL name it goes on. The operator's
# words are not here: d24_live.py owns those (see KIT_COLUMNS below).
"""

# NO INSTRUCTION COLUMN, ON PURPOSE. The words an operator reads live in
# d24_live.py and nowhere else -- the kit codes and the wiring descriptions in
# this file are records ("XLR-F to XLR-M"), not something anybody says out
# loud, and a generated sentence here would be a second vocabulary for
# `--check-md` to have to police. This file carries the FACTS: which lead,
# which end, which panel socket. `d24_live.park_kit_page` turns each row into
# the one big line.
KIT_COLUMNS = ('lead', 'name', 'wiring', 'end', 'socket', 'drive', 'lane')

# The order the operator is walked through the kit at START: the three ends that
# hang on XLR OUTPUTS first, in panel order, because that is one reach along one
# row of sockets; then the one that goes into an input; then the plug, which
# goes on the bench and not on the unit at all.
KIT_ORDER = ('K1', 'K4', 'K3', 'K2', 'K5')


def write_kit(out, b):
    path = os.path.join(out, 'patch-kit.csv')
    k = b.kit()
    with open(path, 'w', newline='') as fh:
        fh.write(HEAD_KIT)
        w = csv.DictWriter(fh, KIT_COLUMNS, extrasaction='ignore')
        w.writeheader()
        for lead in KIT_ORDER:
            d = k.get(lead)
            if d is None or b.out_lead(lead):
                continue
            w.writerow(dict(lead=lead, name=LEADS[lead]['name'],
                            wiring=LEADS[lead]['wiring'], end=d['end'],
                            socket=d['socket'] or '', drive=d['drive'] or '',
                            lane=d['lane'] if d['lane'] else ''))
    return path


def write_paths(out, b):
    path = os.path.join(out, 'patch-paths.csv')
    with open(path, 'w', newline='') as fh:
        fh.write(HEAD_PATHS)
        w = csv.DictWriter(fh, COLUMNS, extrasaction='ignore')
        w.writeheader()
        for r in b.paths:
            w.writerow(r)
    return path


def write_routes(out, b):
    path = os.path.join(out, 'patch-routes.csv')
    with open(path, 'w', newline='') as fh:
        fh.write(HEAD_ROUTES)
        w = csv.writer(fh)
        w.writerow(('route', 'cells'))
        w.writerow(('_standing_close', ';'.join(cells_close_assigns(STRIPS, AUXES))))
        w.writerow(('_standing_strips',
                    ';'.join(cells_all_strips_transparent(STRIPS))))
        w.writerow(('_standing_masters', ';'.join(cells_bus_masters(AUXES))))
        for rid in sorted(b.routes):
            w.writerow((rid, ';'.join(b.routes[rid])))
    return path


HEAD_GAIN = """\
# patch-gain-steps.csv -- GENERATED by tools/accept/gen_patch_paths.py (S121). Do not edit.
# The seven mic-preamp gain steps: every gain-leg element off, then each one alone.
# `expected_db` is the step's hardware gain, MEASURED (HUB ADDENDUM 2 to S130,
# PW "fix the table"): defs/common/tables/mic-gain-codes.csv carries all %d
# hardware codes directly (the MEDIAN over channels of a 2026-09-16 survey), so
# every one of these seven steps is `source=measured` and none is a fit through
# the six element gains -- that fit (mic-gain-law.csv's 61-row target_db table
# carries only %d codes) is what left a 0.51 dB worst-case residual on codes
# 8/16/32/63 (S129 addendum 5), twice PW's +/-0.25 dB window.
# `drive_dbfs` is what the oscillator is set to for this step, so the converter sees
# about the same level at every gain and nothing clips. That level is
# GAIN_TONE_DBFS = %.1f dBFS and NOT the station's own -12: the measurement node's
# level reading saturates above about -24 dBFS, and at -12 a step short by the
# smallest element (6.552 dB) read only 1.649 dB low and passed. See the generator.
"""


def write_gain_steps(out, b):
    path = os.path.join(out, 'patch-gain-steps.csv')
    law_codes = len(set(int(r['code']) for r in read_csv(DEFS_GAIN_LAW, comment='#')))
    with open(path, 'w', newline='') as fh:
        fh.write(HEAD_GAIN % (len(b.gain_seen), law_codes, GAIN_TONE_DBFS))
        w = csv.writer(fh)
        w.writerow(('step', 'code', 'byte', 'expected_db', 'source',
                    'drive_dbfs'))
        for i, code in enumerate(GAIN_STEPS):
            db, src = gain_db(code, b.gain_seen)
            w.writerow((i, code, '0x%02X' % ((code & 63) << 2), '%.3f' % db,
                        src, '%.2f' % (GAIN_TONE_DBFS - db)))
        db, src = gain_db(EIN_GAIN_CODE, b.gain_seen)
        w.writerow(('ein', EIN_GAIN_CODE, '0x%02X' % ((EIN_GAIN_CODE & 63) << 2),
                    '%.3f' % db, src, ''))
    return path


def write_plan(out, b):
    path = os.path.join(out, 'patch-plan.md')
    by_lead, patches = {}, {}
    for r in b.paths:
        by_lead.setdefault(r['lead'], set()).add(r['patch'])
        patches.setdefault(r['patch'], []).append(r)
    leads_used = [k for k in BLOCK_ORDER if by_lead.get(k)]
    L = ['<!-- GENERATED by tools/accept/gen_patch_paths.py (S121). Do not edit. -->',
         '# The D24 audio patch plan', '',
         '%d patches, %d measurements, %d lead changes.'
         % (b.patch, b.n, max(0, len(leads_used) - 1)), '']
    if b.excl_in or b.excl_lead:
        L += ['## This is a SHORT list', '',
              'It is generated from the same source as the full one, with '
              'sockets left out on purpose. Nothing here was edited by hand.',
              '',
              '* left out: %s'
              % ', '.join(socket_sort(b.excl_in)
                          + sorted('every path that needs the %s'
                                   % LEADS[k]['name'] for k in b.excl_lead)),
              '* patches the exclusions removed: %d' % b.dropped]
        for out, inp, why in b.rehomed:
            L.append('* %s now reads on %s (%s)' % (out, inp, why))
        L += ['',
              'Leaving an input out never quietly stops proving an OUTPUT: '
              'every output is tested against the reference input, whichever '
              'input that turns out to be, so the outputs are covered whatever '
              'is left out of the input row.', '']
    L += ['## The kit', '',
         '| lead | what it is | how it is wired | patches |',
         '|---|---|---|---|']
    for k in leads_used:
        d = LEADS[k]
        L.append('| %s | %s | %s | %d |'
                 % (k, d['name'], d['wiring'], len(by_lead.get(k, ()))))
    L += ['',
          'One of each. The order above is the order the station walks, so the '
          'operator changes lead type %d times in a whole pass and never goes '
          'back to a lead already put down.' % max(0, len(leads_used) - 1), '',
          '## The blocks', '',
          '| # | lead | block | patches | measurements | the end that stays put |',
          '|---|---|---|---|---|---|']
    seen = []
    for r in b.paths:
        key = (r['lead'], r['block'])
        if key not in seen:
            seen.append(key)
    for i, (lead, block) in enumerate(seen, start=1):
        mine = [r for r in b.paths if r['lead'] == lead and r['block'] == block]
        pp = sorted({r['patch'] for r in mine})
        outs = {r['out'] for r in mine}
        ins = {r['in'] for r in mine}
        outs.discard('')
        if not outs:
            parked = 'nothing: the terminator moves on its own'
        elif len(outs) == 1 and len(ins) > 1:
            parked = 'the output end, on %s' % list(outs)[0]
        elif len(ins) == 1 and len(outs) > 1:
            parked = 'the input end, in %s' % list(ins)[0]
        elif len(outs) == 1 and len(ins) == 1:
            parked = 'both ends'
        else:
            nout = len(outs)
            park = sorted(((sum(1 for r in mine if r['out'] == o), o)
                           for o in outs), reverse=True)[0]
            parked = ('the input end walks all %d; the output end moves once '
                      'per output for the first %d and then stays on %s for '
                      'the remaining %d' % (len(pp), nout, park[1],
                                            len(pp) - nout))
        L.append('| %d | %s | %s | %d | %d | %s |'
                 % (i, lead, block, len(pp), len(mine), parked))
    L += ['', '## Coverage', '',
          'Every D24 analog socket, and what proves it.', '',
          '| socket | catalog row | proved by |', '|---|---|---|']
    for name, p in sorted(b.ports.items(), key=lambda kv: int(kv[1]['catalog_row'] or 0)):
        hits = [r['patch'] for r in b.paths
                if r['out'] == name or r['in'] == name
                or r['in'].startswith(name + ' ')
                or (r['out'] and name.startswith(r['out'] + ' '))
                or (r['in'] and name.startswith(r['in'] + ' '))]
        if hits:
            L.append('| %s | %s | %s |' % (name, p['catalog_row'],
                                           ', '.join(sorted(set(hits),
                                                            key=lambda s: int(s[1:])))))
    L += ['', '### Not run, and why', '',
          'These are not failures and not omissions. The socket exists; no cell '
          'this product declares can put a signal on it.', '',
          '| socket | catalog row | why |', '|---|---|---|']
    for n in b.notrun:
        L.append('| %s | %s | %s |' % (n['port'], n['row'], n['reason']))
    L.append('')
    with open(path, 'w') as fh:
        fh.write('\n'.join(L))
    return path


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument('--out', default=OUT_DEFAULT)
    ap.add_argument('--check', action='store_true',
                    help='build and validate, write nothing')
    ap.add_argument('--exclude', action='append', metavar='SOCKETS',
                    help='inputs to leave out, e.g. MIC1-4,MIC13-16 . '
                         'Repeatable. Outputs that lose their only test are '
                         're-homed onto a working input')
    ap.add_argument('--exclude-lead', action='append', metavar='LEAD',
                    help='leads to leave out, by name (mini-jack, line, '
                         'terminator, xlr, jack-to-xlr) or by kit code')
    ap.add_argument('--input-order', default='three-walks', choices=INPUT_ORDERS,
                    help='three-walks (the default, and what the bench runs '
                         'today): the XLR lead walks every input, then the '
                         '150 ohm plug, then the jack lead. one-stop: every '
                         'lead at one input before moving on. PW 2026-09-27 '
                         'ruled STOPWATCH FIRST -- see s126-stopwatch-card.md')
    ap.add_argument('--no-park-kit', dest='park_kit', action='store_false',
                    help='every block homes on the first XLR output and the '
                         'reference input, as the list did before the parked '
                         'kit (ruling c). For a before/after timing run')
    a = ap.parse_args(argv)
    excl_in = parse_excludes(a.exclude)
    excl_lead = parse_lead_excludes(a.exclude_lead)
    b = Builder(load_ports(), load_cells(), excl_in, excl_lead,
                park_kit=a.park_kit, input_order=a.input_order).build()
    if a.check:
        print('OK: %d patches, %d paths, %d routes, %d sockets not run'
              % (b.patch, b.n, len(b.routes), len(b.notrun)))
        return 0
    os.makedirs(a.out, exist_ok=True)
    written = [write_paths(a.out, b), write_routes(a.out, b),
               write_gain_steps(a.out, b), write_kit(a.out, b),
               write_plan(a.out, b)]
    # The windows are a SOURCE file, hand-tuned by PW, and the station reads
    # them out of the list directory it was pointed at. A short list written
    # somewhere else would otherwise be a directory the station cannot run
    # from, or -- worse -- one somebody fills in with a second copy that
    # drifts. It is copied here, on every generation, from the one original.
    src_lim = os.path.join(OUT_DEFAULT, 'patch-limits.csv')
    dst_lim = os.path.join(a.out, 'patch-limits.csv')
    if os.path.abspath(src_lim) != os.path.abspath(dst_lim):
        with open(src_lim) as fh:
            text = fh.read()
        with open(dst_lim, 'w') as fh:
            fh.write(text)
        written.append(dst_lim)
    for p in written:
        print('wrote %s' % os.path.relpath(p, ROOT))
    print('%d patches, %d measurements, %d sockets not run'
          % (b.patch, b.n, len(b.notrun)))
    print('gain steps: all %d hardware codes measured (mic-gain-codes.csv), no fit'
          % len(b.gain_seen))
    if excl_in or excl_lead:
        print('excluded: %s' % ', '.join(sorted(excl_in) +
                                         sorted(LEADS[k]['name']
                                                for k in excl_lead)))
        for out, inp, why in b.rehomed:
            print('re-homed: %s now reads on %s (%s)' % (out, inp, why))
    return 0


if __name__ == '__main__':
    sys.exit(main())
