/* block_io.asm — DMA↔node scatter/gather for CHIP2 */
/* AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly. */
/* Lane-major DMA layout per MW/D32/DSP/dsp4-plumbing.md. */
#include "dsp_block.h"

.section/dm seg_dmda;

/* IC RX node tables (37 packed mix-fabric slots over 3 lanes) */
.extern _rx_ic_slot_C2_RECV_MAIN_L;
.extern _rx_ic_slot_C2_RECV_MAIN_R;
.extern _rx_ic_slot_C2_RECV_SUB;
.extern _rx_ic_slot_C2_RECV_GRP_01;
.extern _rx_ic_slot_C2_RECV_GRP_02;
.extern _rx_ic_slot_C2_RECV_GRP_03;
.extern _rx_ic_slot_C2_RECV_GRP_04;
.extern _rx_ic_slot_C2_RECV_AUX_01;
.extern _rx_ic_slot_C2_RECV_AUX_02;
.extern _rx_ic_slot_C2_RECV_AUX_03;
.extern _rx_ic_slot_C2_RECV_AUX_04;
.extern _rx_ic_slot_C2_RECV_AUX_05;
.extern _rx_ic_slot_C2_RECV_AUX_06;
.extern _rx_ic_slot_C2_RECV_AUX_07;
.extern _rx_ic_slot_C2_RECV_AUX_08;
.extern _rx_ic_slot_C2_RECV_AUX_09;
.extern _rx_ic_slot_C2_RECV_AUX_10;
.extern _rx_ic_slot_C2_RECV_AUX_11;
.extern _rx_ic_slot_C2_RECV_AUX_12;
.extern _rx_ic_slot_C2_RECV_FX_01;
.extern _rx_ic_slot_C2_RECV_FX_02;
.extern _rx_ic_slot_C2_RECV_FX_03;
.extern _rx_ic_slot_C2_RECV_FX_04;
.extern _rx_ic_slot_C2_RECV_FX_05;
.extern _rx_ic_slot_C2_RECV_FX_06;
.extern _rx_ic_slot_C2_XR_CODEC_AUX_L;
.extern _rx_ic_slot_C2_XR_CODEC_AUX_R;
.extern _rx_ic_slot_C2_XR_PI_L;
.extern _rx_ic_slot_C2_XR_PI_R;
.extern _rx_ic_slot_C2_XR_SNAKE_01;
.extern _rx_ic_slot_C2_XR_SNAKE_02;
.extern _rx_ic_slot_C2_XR_SNAKE_03;
.extern _rx_ic_slot_C2_XR_SNAKE_04;
.extern _rx_ic_slot_C2_XR_SNAKE_05;
.extern _rx_ic_slot_C2_XR_SNAKE_06;
.extern _rx_ic_slot_C2_XR_SNAKE_07;
.extern _rx_ic_slot_C2_XR_SNAKE_08;
#if DSP4_BLOCK_KERNELS
.global _c2_ic_rx_off;
.global _c2_ic_rx_stride;
#endif
.var _c2_ic_rx_off[37] =
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    128,
    129,
    130,
    131,
    132,
    133,
    134,
    135,
    136,
    137,
    138,
    139,
    140,
    141,
    142,
    143,
    256,
    257,
    258,
    259,
    260;
.var _c2_ic_rx_stride[37] =
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    16,
    5,
    5,
    5,
    5,
    5;
.var _c2_ic_rx_ptrs[37] =
    _rx_ic_slot_C2_RECV_MAIN_L,
    _rx_ic_slot_C2_RECV_MAIN_R,
    _rx_ic_slot_C2_RECV_SUB,
    _rx_ic_slot_C2_RECV_GRP_01,
    _rx_ic_slot_C2_RECV_GRP_02,
    _rx_ic_slot_C2_RECV_GRP_03,
    _rx_ic_slot_C2_RECV_GRP_04,
    _rx_ic_slot_C2_RECV_AUX_01,
    _rx_ic_slot_C2_RECV_AUX_02,
    _rx_ic_slot_C2_RECV_AUX_03,
    _rx_ic_slot_C2_RECV_AUX_04,
    _rx_ic_slot_C2_RECV_AUX_05,
    _rx_ic_slot_C2_RECV_AUX_06,
    _rx_ic_slot_C2_RECV_AUX_07,
    _rx_ic_slot_C2_RECV_AUX_08,
    _rx_ic_slot_C2_RECV_AUX_09,
    _rx_ic_slot_C2_RECV_AUX_10,
    _rx_ic_slot_C2_RECV_AUX_11,
    _rx_ic_slot_C2_RECV_AUX_12,
    _rx_ic_slot_C2_RECV_FX_01,
    _rx_ic_slot_C2_RECV_FX_02,
    _rx_ic_slot_C2_RECV_FX_03,
    _rx_ic_slot_C2_RECV_FX_04,
    _rx_ic_slot_C2_RECV_FX_05,
    _rx_ic_slot_C2_RECV_FX_06,
    _rx_ic_slot_C2_XR_CODEC_AUX_L,
    _rx_ic_slot_C2_XR_CODEC_AUX_R,
    _rx_ic_slot_C2_XR_PI_L,
    _rx_ic_slot_C2_XR_PI_R,
    _rx_ic_slot_C2_XR_SNAKE_01,
    _rx_ic_slot_C2_XR_SNAKE_02,
    _rx_ic_slot_C2_XR_SNAKE_03,
    _rx_ic_slot_C2_XR_SNAKE_04,
    _rx_ic_slot_C2_XR_SNAKE_05,
    _rx_ic_slot_C2_XR_SNAKE_06,
    _rx_ic_slot_C2_XR_SNAKE_07,
    _rx_ic_slot_C2_XR_SNAKE_08;

/* TX node tables (20 outputs over 5 full-window lanes of 8) */
.extern _tx_out_slot_C2_AUX_OUT_01;
.extern _tx_out_slot_C2_AUX_OUT_02;
.extern _tx_out_slot_C2_AUX_OUT_03;
.extern _tx_out_slot_C2_AUX_OUT_04;
.extern _tx_out_slot_C2_AUX_OUT_05;
.extern _tx_out_slot_C2_AUX_OUT_06;
.extern _tx_out_slot_C2_AUX_OUT_07;
.extern _tx_out_slot_C2_AUX_OUT_08;
.extern _tx_out_slot_C2_AUX_OUT_09;
.extern _tx_out_slot_C2_AUX_OUT_10;
.extern _tx_out_slot_C2_AUX_OUT_11;
.extern _tx_out_slot_C2_AUX_OUT_12;
.extern _tx_out_slot_C2_MAIN_OUT_01;
.extern _tx_out_slot_C2_MAIN_OUT_02;
.extern _tx_out_slot_C2_MAIN_OUT_03;
.extern _tx_out_slot_C2_MAIN_OUT_04;
.extern _tx_out_slot_C2_MON_OUT;
.extern _tx_out_slot_C2_CODEC_AUX_OUT;
.extern _tx_out_slot_C2_MAIN_ST_OUT;
.extern _tx_out_slot_C2_SUB_OUT;
#if DSP4_BLOCK_KERNELS
.global _c2_tx_off;
.global _c2_tx_stride;
#endif
.var _c2_tx_off[20] =
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    64,
    65,
    66,
    67,
    68,
    69,
    70,
    71,
    128,
    130,
    192,
    256;
.var _c2_tx_stride[20] =
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8;
.var _c2_tx_ptrs[20] =
    _tx_out_slot_C2_AUX_OUT_01,
    _tx_out_slot_C2_AUX_OUT_02,
    _tx_out_slot_C2_AUX_OUT_03,
    _tx_out_slot_C2_AUX_OUT_04,
    _tx_out_slot_C2_AUX_OUT_05,
    _tx_out_slot_C2_AUX_OUT_06,
    _tx_out_slot_C2_AUX_OUT_07,
    _tx_out_slot_C2_AUX_OUT_08,
    _tx_out_slot_C2_AUX_OUT_09,
    _tx_out_slot_C2_AUX_OUT_10,
    _tx_out_slot_C2_AUX_OUT_11,
    _tx_out_slot_C2_AUX_OUT_12,
    _tx_out_slot_C2_MAIN_OUT_01,
    _tx_out_slot_C2_MAIN_OUT_02,
    _tx_out_slot_C2_MAIN_OUT_03,
    _tx_out_slot_C2_MAIN_OUT_04,
    _tx_out_slot_C2_MON_OUT,
    _tx_out_slot_C2_CODEC_AUX_OUT,
    _tx_out_slot_C2_MAIN_ST_OUT,
    _tx_out_slot_C2_SUB_OUT;

/* DMA ping-pong buffers live in generated lane_config.c —
 * see the chip-1 note. */
.extern _ic_rx_active_buf;
.extern _tx_active_buf;
.extern _meter_peaks;

.section/pm seg_pmco;

/* Scatter 37 inter-chip recvs (lane-major packed) */
.global _scatter_chip2;
_scatter_chip2:
    /* r0 = sample index (0..7) */
    r6 = dm(_ic_rx_active_buf);
    i1 = _c2_ic_rx_off;
    i2 = _c2_ic_rx_stride;
    i3 = _c2_ic_rx_ptrs;
    r7 = 37;
    lcntr = r7; do .scatter_chip2_lp until lce;
        r3 = dm(i1, 1);       /* off */
        r4 = dm(i2, 1);       /* stride */
        r2 = r0 * r4 (SSI);   /* sample*stride */
        r3 = r3 + r2;
        r3 = r6 + r3;         /* DMA word address */
        r5 = dm(i3, 1);       /* node slot var ptr */
        #if DSP4_BLOCK_KERNELS
        r5 = r5 + r0;         /* slot[sample] */
        #endif
        i4 = r3;
        r2 = dm(i4, 0);   /* read DMA */
        i4 = r5;
        dm(i4, 0) = r2;   /* write slot var */
    .scatter_chip2_lp:
        nop;
    rts;
_scatter_chip2.end:

/* Gather 20 outputs (lane-major full-window) */
.global _gather_chip2;
_gather_chip2:
    /* r0 = sample index (0..7) */
    r6 = dm(_tx_active_buf);
    i1 = _c2_tx_off;
    i2 = _c2_tx_stride;
    i3 = _c2_tx_ptrs;
    r7 = 20;
    lcntr = r7; do .gather_chip2_lp until lce;
        r3 = dm(i1, 1);       /* off */
        r4 = dm(i2, 1);       /* stride */
        r2 = r0 * r4 (SSI);   /* sample*stride */
        r3 = r3 + r2;
        r3 = r6 + r3;         /* DMA word address */
        r5 = dm(i3, 1);       /* node slot var ptr */
        #if DSP4_BLOCK_KERNELS
        r5 = r5 + r0;         /* slot[sample] */
        #endif
        i4 = r5;
        r2 = dm(i4, 0);   /* read slot var */
        /* Q4.28 -> Q1.31 with saturation */
        r8 = ashift r2 by 3;
        r9 = ashift r8 by -3;
        comp(r9, r2);
        if eq jump (pc, .gather_chip2_ok);
        r8 = 0x7FFFFFFF;
        r9 = ashift r2 by -31;
        r8 = r8 xor r9;
    .gather_chip2_ok:
        r2 = r8;
        i4 = r3;
        dm(i4, 0) = r2;   /* write DMA */
    .gather_chip2_lp:
        nop;
    rts;
_gather_chip2.end:

/* Peak-hold meter scan over TX outputs (once per block) */
.global _meter_scan_chip2;
_meter_scan_chip2:
    i0 = _c2_tx_ptrs;
    i1 = _meter_peaks;
    m0 = 0;
    m1 = 1;
    r5 = 20;
    lcntr = r5; do .meter_scan_chip2_lp until lce;
        r2 = dm(i0, 1);
        i2 = r2;
        r3 = dm(i2, 0);   /* Q4.28 sample */
        r3 = abs r3;
        r4 = -28;
        f3 = float r3 by r4;  /* peaks stay FLOAT (readback contract) */
        f4 = dm(i1, m0);
        comp(f3, f4);
        if gt f4 = f3;
        dm(i1, m1) = f4;
    .meter_scan_chip2_lp:
        nop;
    rts;
_meter_scan_chip2.end:
