/* CHIP2 — SIMD strip-pair dynamics drivers */
/* AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly. */
#include "dsp_block.h"
#include "blk_pool.h"

#if DSP4_PAIRED_GRAPH

.section/dm seg_dmda;
.var _dynpair_saved_idx;

.section/pm seg_pmco;
.extern _sample_idx;
.extern _dsim_n;
.extern _gate_pair_blk;
.extern _comp_pair_blk;
.extern _cmp_gn;

#if DSP4_GATE_LINTHR
#error "DSP4_SIMD_DYN pairs the GATE in the log2 domain; DSP4_GATE_LINTHR converts the threshold to linear once per block and the two are different arithmetic. Build with DSP4_GATE_LINTHR=0."
#endif
#if !DSP4_BLOCK_KERNELS
#error "DSP4_SIMD_GRAPH is a per-BLOCK pairing: build with DSP4_BLOCK_KERNELS=1."
#endif

#endif /* DSP4_PAIRED_GRAPH */
