/* lane_config.c — generated lane tables + DMA buffers for CHIP2 */
/* AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly. */
/* Entries of 4: sport, cs_mask, words_per_sample, region_off. */

const int c2_ic_lanes_count = 3;
const int c2_ic_lanes_dir = 0;    /* 0 = RX (half A), 1 = TX (half B) */
const int c2_ic_lanes_mcpde = 1;
const int c2_ic_lanes_wsize = 15;
const int c2_ic_lanes[12] = {
    0, 0xFFFF, 16, 0,
    1, 0xFFFF, 16, 128,
    2, 0x001F, 5, 256
};

const int c2_ic_region_words = 296;
#pragma align 32
unsigned int c2_ic_buf_ping[2 * 296];  /* [0..296) ping, [296..2*296) pong */

const int c2_tx_lanes_count = 5;
const int c2_tx_lanes_dir = 1;    /* 0 = RX (half A), 1 = TX (half B) */
const int c2_tx_lanes_mcpde = 0;
const int c2_tx_lanes_wsize = 7;
const int c2_tx_lanes[20] = {
    0, 0x00FF, 8, 0,
    1, 0x00FF, 8, 64,
    2, 0x000F, 8, 128,
    3, 0x0003, 8, 192,
    4, 0x0001, 8, 256
};

const int c2_tx_region_words = 320;
#pragma align 32
unsigned int c2_tx_buf_ping[2 * 320];  /* [0..320) ping, [320..2*320) pong */
