/* lane_config.c — generated lane tables + DMA buffers for CHIP2 */
/* AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly. */
/* Entries of 4: sport, cs_mask, words_per_sample, region_off. */
/* <region>_mfd[] is the per-lane frame-sync-to-data delay */
/* (SPORT_MCTL.MFD) -- see MFD_CONVERTER/MFD_CPLD in the   */
/* generator. It is per LANE, not per region, because the  */
/* pin-strapped AKM converters and the LOGIC CPLD frame    */
/* differently and only one of them can be reprogrammed.   */

#include "dsp_block.h"

/* GENERATION-TIME BLOCK SIZE GUARD (review finding D12).
 * The lane region_off values below (count * BLOCK) and the
 * region_words / DMA ping-pong buffer extents (lane total * BLOCK)
 * are baked here at GENERATION time from BLOCK=16. What walks
 * them resolves DSP4_BLOCK_SIZE at BUILD time. This makes the two
 * disagreeing a build failure instead of an out-of-bounds write. */
#if DSP4_BLOCK_SIZE != 16
#error "STALE GENERATED FILE: baked for DSP4_BLOCK_SIZE=16, built against a different one. Regenerate: python3 tools/dsp/dsp_codegen.py <dsp.csv> <src> --force"
#endif

#if DSP4_CUE
const int c2_ic_lanes_count = 3;
const int c2_ic_lanes_dir = 0;    /* 0 = RX (half A), 1 = TX (half B) */
const int c2_ic_lanes_mcpde = 1;
const int c2_ic_lanes_wsize = 15;
const int c2_ic_lanes_mfd[3] = { 1, 1, 1 };
const int c2_ic_lanes[12] = {
    0, 0xFFFF, 16, 0,   /* MFD 1 */
    1, 0xFFFF, 16, 256,   /* MFD 1 */
    2, 0x07FF, 11, 512   /* MFD 1 */
};

const int c2_ic_region_words = 688;
#pragma align 32
unsigned int c2_ic_buf_ping[2 * 688];  /* [0..688) ping, [688..2*688) pong */

#else
const int c2_ic_lanes_count = 3;
const int c2_ic_lanes_dir = 0;    /* 0 = RX (half A), 1 = TX (half B) */
const int c2_ic_lanes_mcpde = 1;
const int c2_ic_lanes_wsize = 15;
const int c2_ic_lanes_mfd[3] = { 1, 1, 1 };
const int c2_ic_lanes[12] = {
    0, 0xFFFF, 16, 0,   /* MFD 1 */
    1, 0xFFFF, 16, 256,   /* MFD 1 */
    2, 0x01FF, 9, 512   /* MFD 1 */
};

const int c2_ic_region_words = 656;
#pragma align 32
unsigned int c2_ic_buf_ping[2 * 656];  /* [0..656) ping, [656..2*656) pong */

#endif

const int c2_tx_lanes_count = 5;
const int c2_tx_lanes_dir = 1;    /* 0 = RX (half A), 1 = TX (half B) */
const int c2_tx_lanes_mcpde = 0;
const int c2_tx_lanes_wsize = 7;
const int c2_tx_lanes_mfd[5] = { 2, 2, 2, 1, 2 };
const int c2_tx_lanes[20] = {
    0, 0x00FF, 8, 0,   /* MFD 2 */
    1, 0x00FF, 8, 128,   /* MFD 2 */
    2, 0x000D, 8, 256,   /* MFD 2 */
    3, 0x0003, 8, 384,   /* MFD 1 */
    4, 0x001F, 8, 512   /* MFD 2 */
};

const int c2_tx_region_words = 640;
#pragma align 32
unsigned int c2_tx_buf_ping[2 * 640];  /* [0..640) ping, [640..2*640) pong */
