/*======================================================================
 * pool_table.asm — chip 2 memory-pool line registration (S75).
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *
 * 0 pool lines on this chip. The index is the line's position in the
 * external history store hist[slot][line][BLOCK]; see src/lib/mem_pool.asm
 * for the layout and why it is indexed by block rather than by line.
 *
 * line  buffer                             L2 head   full spec
 *   (none)
 *
 * HEAD vs MAX. The head is the L2 ring the line keeps whatever backend is
 * in force -- with no RAM it is the WHOLE line and reads clamp into it,
 * which is the tiering that ships today. With the RAM the head becomes the
 * recent window and everything older comes from the external store, so the
 * clamp lifts and every line reaches its full spec.
 *======================================================================*/

#include "dsp_block.h"

#if DSP4_EXTRAM



.section/dm seg_dmda;

.global _pool_head_base;
.var _pool_head_base[1] = {
    0
};

.global _pool_head_len;
.var _pool_head_len[1] = { 0 };

.global _pool_max_len;
.var _pool_max_len[1] = { 0 };

#endif /* DSP4_EXTRAM */
