/*----------------------------------------------------------------------
 * Ch 13 Gain (GAIN)
 * Node ID:    C1_GAIN_13
 * Chip:       1
 * Channels:   1
 * SPI Page:   1
 * SPI Addr:   1728
 * RampProfile: GainFast
 *
 * AUTO-GENERATED by dsp_codegen.py (D32) — do not edit directly.
 *----------------------------------------------------------------------*/

/* RampProfile: GainFast | Mode: Slew | Up: 3ms (4f) Down: 8ms (12f) | Curve: Exp | Scope: Scalar */

/* GAIN: Per-channel gain / trim */
/* SPI page=1 addr=1728 */

.section/dm seg_dmda;
.extern _buf_C1_IN_13;
.global _gain_coeff_C1_GAIN_13;
.var _gain_coeff_C1_GAIN_13 = 1.0;
.global _gain_target_C1_GAIN_13;
.var _gain_target_C1_GAIN_13 = 1.0;   /* ramp target */
.global _gain_step_C1_GAIN_13;
.var _gain_step_C1_GAIN_13 = 0.0;      /* per-frame ramp increment */
.global _gain_frames_C1_GAIN_13;
.var _gain_frames_C1_GAIN_13 = 0;       /* remaining ramp frames */
.global _mute_C1_GAIN_13;
.var _mute_C1_GAIN_13 = 0;
.global _polarity_C1_GAIN_13;
.var _polarity_C1_GAIN_13 = 0;
.global _tap_post_trim_C1_GAIN_13;
.var _tap_post_trim_C1_GAIN_13;         /* post trim / pre-EQ tap */
.global _buf_C1_GAIN_13;
.var _buf_C1_GAIN_13;

.section/pm seg_pmco;
.global _C1_GAIN_13_process;
_C1_GAIN_13_process:
    /* --- Slew ramp update (per frame) --- */
    r4 = dm(_gain_frames_C1_GAIN_13);
    r15 = 1;
    r4 = r4 - r15;
    if le jump (pc, .no_ramp_C1_GAIN_13);
    dm(_gain_frames_C1_GAIN_13) = r4;
    f1 = dm(_gain_coeff_C1_GAIN_13);
    f2 = dm(_gain_step_C1_GAIN_13);
    f1 = f1 + f2;                /* linear interpolation step */
    dm(_gain_coeff_C1_GAIN_13) = f1;
    jump (pc, .apply_C1_GAIN_13);
.no_ramp_C1_GAIN_13:
    f1 = dm(_gain_target_C1_GAIN_13);
    dm(_gain_coeff_C1_GAIN_13) = f1;  /* snap to target */
.apply_C1_GAIN_13:

    r0 = dm(_buf_C1_IN_13);
    f0 = f0 * f1;

    /* Polarity */
    r3 = dm(_polarity_C1_GAIN_13);
    r4 = 0;
    comp(r3, r4);
    if ne f0 = -f0;

    /* Mute */
    r2 = dm(_mute_C1_GAIN_13);
    comp(r2, r4);
    if ne r0 = r4;      /* if muted, clear f0 (r4 = 0 = 0.0f IEEE 754) */

    dm(_tap_post_trim_C1_GAIN_13) = r0;
    dm(_buf_C1_GAIN_13) = r0;
    rts;
_C1_GAIN_13_process.end:
