/*----------------------------------------------------------------------
 * Ch 2 Input (INPUT_TDM)
 * Node ID:    C1_IN_02
 * Chip:       1
 * Channels:   1
 * SPI Page:   -1
 * SPI Addr:   -1
 * RampProfile: (none)
 *
 * AUTO-GENERATED by dsp_codegen.py (D32) — do not edit directly.
 *----------------------------------------------------------------------*/

/* RampProfile: Instant (default — no ramp) */

/* INPUT_TDM: Read from SPORT0 TDM slot 1 */

.section/dm seg_dmda;
.global _rx_slot_C1_IN_02;
.var _rx_slot_C1_IN_02;
.global _buf_C1_IN_02;
.var _buf_C1_IN_02;

.section/pm seg_pmco;
.global _C1_IN_02_process;
_C1_IN_02_process:
    r0 = dm(_rx_slot_C1_IN_02);
    dm(_buf_C1_IN_02) = r0;
    rts;
_C1_IN_02_process.end:
