/*----------------------------------------------------------------------
 * Ch 4 Input (INPUT_TDM)
 * Node ID:    C1_IN_04
 * Chip:       1
 * Channels:   1
 * SPI Page:   -1
 * SPI Addr:   -1
 * RampProfile: (none)
 *
 * AUTO-GENERATED by dsp_codegen.py (D32) — do not edit directly.
 *----------------------------------------------------------------------*/

/* RampProfile: Instant (default — no ramp) */

/* INPUT_TDM: Read from SPORT0 TDM slot 3 */

.section/dm seg_dmda;
.global _rx_slot_C1_IN_04;
.var _rx_slot_C1_IN_04;
.global _buf_C1_IN_04;
.var _buf_C1_IN_04;

.section/pm seg_pmco;
.global _C1_IN_04_process;
_C1_IN_04_process:
    r0 = dm(_rx_slot_C1_IN_04);
    dm(_buf_C1_IN_04) = r0;
    rts;
_C1_IN_04_process.end:
