/*======================================================================
 * num_selftest.asm — is the ASSEMBLY the same arithmetic as fixed_ref,
 * AT the wide-accumulator and blend boundaries and on BOTH sides of them?
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *
 * Two arms, for the two touchpoints the 2026-08-28 review found could
 * WRAP rather than saturate:
 *
 *   MIX   review finding D1 (SEVERE). The bus accumulators. Zero a
 *         [lo, hi, ex] triple, MAC N contributions into it with the
 *         REAL _acc64_mac, read it out with the REAL _acc64_rns28.
 *         No copied arithmetic: these are the routines the graph runs.
 *   BLEND review finding D3. The dual-instance crossfade. The probe
 *         body is emitted from _xfade_blend_core() in dsp_codegen.py --
 *         the SAME expression that emits it into all 32 EQ, all 32
 *         FILT and both crossover nodes -- so the instructions proved
 *         here are the instructions those nodes execute.
 *
 * THE VECTORS STRADDLE THE BOUNDARIES ON PURPOSE, and the host reads
 * the results back and compares them against fixed_ref.mix_sum and
 * fixed_ref.xfade_blend. They are the same vectors golden_harness.py
 * uses, so "asm == model" and "model is right" are checked on identical
 * numbers.
 *
 * NEGATIVE CONTROL, IN THE SAME INSTRUMENT: DSP4_NUM_NEGCTL=1 swaps the
 * fixed routines for _nst_mac_old / _nst_rns_old / _nst_blend_old, which
 * are the PRE-FIX arithmetic -- the 64-bit accumulator that discards
 * MR2F and the 32-bit new-old difference. The host requires those to
 * FAIL exactly the vectors that cross a boundary and to PASS every
 * vector that does not. A test that cannot fail proves nothing, and
 * this bench has produced two of those already.
 *
 * TIMING ARM: the same two MAC forms over the same work, against the
 * 1 kHz diag tick. That is the per-MAC cost of the third word, MEASURED.
 *
 * Debug only: DSP4_NUM_SELFTEST. Never in a shipping image.
 *====================================================================*/

#include "dsp_block.h"
#include "diag.h"

#if DSP4_NUM_SELFTEST

.section/dm seg_dmda;

/* ---- MIX vectors: 15 of them ------------------------------------
 * Each is (n1, x1, g1, n2, x2, g2): n1 contributions of x1*g1 followed
 * by n2 of x2*g2 (n2 = 0 for the single-part vectors). Unity x unity is
 * exactly 2^56 in Q8.56, so a count of 128 lands the sum EXACTLY on the
 * old 64-bit +/-128.0 boundary and 127/129 sit one contribution either
 * side of it.
 */
.global _nst_mix_v;
.var _nst_mix_v[90] =
    0x00000001, 0x7FFFFFFF, 0x10000000, 0x00000000, 0x00000000, 0x00000000,   /* one x unity */
    0x00000001, 0x7FFFFFFF, 0x80000000, 0x00000000, 0x00000000, 0x00000000,   /* one x -8.0 */
    0x00000020, 0x7FFFFFFF, 0x08000000, 0x00000000, 0x00000000, 0x00000000,   /* 32 x 0.5 = 16.0 */
    0x00000001, 0x7FFFFFFF, 0x7FFFFFFF, 0x00000000, 0x00000000, 0x00000000,   /* one x 7.999 = 64.0 */
    0x00000002, 0x7FFFFFFF, 0x7FFFFFFF, 0x00000000, 0x00000000, 0x00000000,   /* two x 64.0 = 127.99, just UNDER */
    0x0000007F, 0x10000000, 0x10000000, 0x00000000, 0x00000000, 0x00000000,   /* 127 x 1.0 = 127.0, UNDER by one */
    0x00000080, 0x10000000, 0x10000000, 0x00000000, 0x00000000, 0x00000000,   /* 128 x 1.0 = 128.0, exactly AT */
    0x00000081, 0x10000000, 0x10000000, 0x00000000, 0x00000000, 0x00000000,   /* 129 x 1.0 = 129.0, ACROSS by one */
    0x00000080, 0xF0000000, 0x10000000, 0x00000000, 0x00000000, 0x00000000,   /* 128 x -1.0 = -128.0, AT, negative */
    0x00000081, 0xF0000000, 0x10000000, 0x00000000, 0x00000000, 0x00000000,   /* 129 x -1.0, ACROSS, negative */
    0x00000003, 0x7FFFFFFF, 0x7FFFFFFF, 0x00000000, 0x00000000, 0x00000000,   /* three x 64.0, ACROSS */
    0x00000003, 0x80000000, 0x7FFFFFFF, 0x00000000, 0x00000000, 0x00000000,   /* three x -64.0, ACROSS negative */
    0x00000020, 0x7FFFFFFF, 0x10000000, 0x00000000, 0x00000000, 0x00000000,   /* 32 coherent at full scale */
    0x00000020, 0x7FFFFFFF, 0x7FFFFFFF, 0x00000000, 0x00000000, 0x00000000,   /* 32 x 64.0, 16x over */
    0x00000003, 0x7FFFFFFF, 0x7FFFFFFF, 0x00000003, 0x80000000, 0x7FFFFFFF    /* +3 then -3 x 64.0, excursion cancels */;
.global _nst_mix_n;     .var _nst_mix_n = 15;
.global _nst_mix_r;     .var _nst_mix_r[15];

/* ---- BLEND vectors: 42 of them, (new, old, alpha_f32) ---------- */
.global _nst_bl_v;
.var _nst_bl_v[126] =
    0x10000000, 0xF0000000, 0x00000000,   /* +1.0/-1.0 a=0.0000 */
    0x7FFFFFFF, 0x00000000, 0x00000000,   /* +FS/0 a=0.0000 */
    0x00000000, 0x80000000, 0x00000000,   /* 0/-FS a=0.0000 */
    0x7FFFFFFF, 0x80000000, 0x00000000,   /* +FS/-FS a=0.0000 */
    0x80000000, 0x7FFFFFFF, 0x00000000,   /* -FS/+FS a=0.0000 */
    0x7FFFFFFF, 0x80000001, 0x00000000,   /* +FS/-FS+1 a=0.0000 */
    0x10000000, 0xF0000000, 0x3AE38E39,   /* +1.0/-1.0 a=0.0017 */
    0x7FFFFFFF, 0x00000000, 0x3AE38E39,   /* +FS/0 a=0.0017 */
    0x00000000, 0x80000000, 0x3AE38E39,   /* 0/-FS a=0.0017 */
    0x7FFFFFFF, 0x80000000, 0x3AE38E39,   /* +FS/-FS a=0.0017 */
    0x80000000, 0x7FFFFFFF, 0x3AE38E39,   /* -FS/+FS a=0.0017 */
    0x7FFFFFFF, 0x80000001, 0x3AE38E39,   /* +FS/-FS+1 a=0.0017 */
    0x10000000, 0xF0000000, 0x3E800000,   /* +1.0/-1.0 a=0.2500 */
    0x7FFFFFFF, 0x00000000, 0x3E800000,   /* +FS/0 a=0.2500 */
    0x00000000, 0x80000000, 0x3E800000,   /* 0/-FS a=0.2500 */
    0x7FFFFFFF, 0x80000000, 0x3E800000,   /* +FS/-FS a=0.2500 */
    0x80000000, 0x7FFFFFFF, 0x3E800000,   /* -FS/+FS a=0.2500 */
    0x7FFFFFFF, 0x80000001, 0x3E800000,   /* +FS/-FS+1 a=0.2500 */
    0x10000000, 0xF0000000, 0x3F000000,   /* +1.0/-1.0 a=0.5000 */
    0x7FFFFFFF, 0x00000000, 0x3F000000,   /* +FS/0 a=0.5000 */
    0x00000000, 0x80000000, 0x3F000000,   /* 0/-FS a=0.5000 */
    0x7FFFFFFF, 0x80000000, 0x3F000000,   /* +FS/-FS a=0.5000 */
    0x80000000, 0x7FFFFFFF, 0x3F000000,   /* -FS/+FS a=0.5000 */
    0x7FFFFFFF, 0x80000001, 0x3F000000,   /* +FS/-FS+1 a=0.5000 */
    0x10000000, 0xF0000000, 0x3F400000,   /* +1.0/-1.0 a=0.7500 */
    0x7FFFFFFF, 0x00000000, 0x3F400000,   /* +FS/0 a=0.7500 */
    0x00000000, 0x80000000, 0x3F400000,   /* 0/-FS a=0.7500 */
    0x7FFFFFFF, 0x80000000, 0x3F400000,   /* +FS/-FS a=0.7500 */
    0x80000000, 0x7FFFFFFF, 0x3F400000,   /* -FS/+FS a=0.7500 */
    0x7FFFFFFF, 0x80000001, 0x3F400000,   /* +FS/-FS+1 a=0.7500 */
    0x10000000, 0xF0000000, 0x3F7F1C72,   /* +1.0/-1.0 a=0.9965 */
    0x7FFFFFFF, 0x00000000, 0x3F7F1C72,   /* +FS/0 a=0.9965 */
    0x00000000, 0x80000000, 0x3F7F1C72,   /* 0/-FS a=0.9965 */
    0x7FFFFFFF, 0x80000000, 0x3F7F1C72,   /* +FS/-FS a=0.9965 */
    0x80000000, 0x7FFFFFFF, 0x3F7F1C72,   /* -FS/+FS a=0.9965 */
    0x7FFFFFFF, 0x80000001, 0x3F7F1C72,   /* +FS/-FS+1 a=0.9965 */
    0x10000000, 0xF0000000, 0x3F7F8E39,   /* +1.0/-1.0 a=0.9983 */
    0x7FFFFFFF, 0x00000000, 0x3F7F8E39,   /* +FS/0 a=0.9983 */
    0x00000000, 0x80000000, 0x3F7F8E39,   /* 0/-FS a=0.9983 */
    0x7FFFFFFF, 0x80000000, 0x3F7F8E39,   /* +FS/-FS a=0.9983 */
    0x80000000, 0x7FFFFFFF, 0x3F7F8E39,   /* -FS/+FS a=0.9983 */
    0x7FFFFFFF, 0x80000001, 0x3F7F8E39    /* +FS/-FS+1 a=0.9983 */;
.global _nst_bl_n;      .var _nst_bl_n = 42;
.global _nst_bl_r;      .var _nst_bl_r[42];

/* the blend core reads its alpha from here (pfx=nst, nid=PROBE) */
.global _nst_xfade_alpha_PROBE;
.var _nst_xfade_alpha_PROBE = 0.0;

/* one accumulator triple for the MIX arm */
.global _nst_acc;       .var _nst_acc[3];

/* ---- results / timing ------------------------------------------- */
.global _nst_done;      .var _nst_done = 0;
.global _nst_negctl;    .var _nst_negctl = DSP4_NUM_NEGCTL;
/* TIMING. Six (ticks, tcount) PAIRS -- ticks alone quantises to 1 ms,
 * which at 200k iterations is 2.46 cycles/MAC and cannot see a two- or
 * three-instruction change. TCOUNT counts core clocks down and reloads
 * from DIAG_TPERIOD, so
 *     cycles = (ticks_end - ticks_start) * DIAG_TPERIOD
 *              + (tcount_start - tcount_end)
 * which is the form main.asm already uses for its per-block cost. */
.global _nst_tick;      .var _nst_tick[20] =
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0;
/* BLOCK arms present? The block-kernel MAC only exists in a
 * DSP4_BLOCK_KERNELS build, and that is the operating point the
 * capacity work runs at, so it gets its own pair of arms there. */
.global _nst_have_blk;  .var _nst_have_blk = DSP4_BLOCK_KERNELS;
.global _nst_blk_n;     .var _nst_blk_n = DSP4_BLOCK_SIZE;
/* BLOCK arms need a BLOCK-long source and a BLOCK-triple accumulator */
.global _nst_blk_src;   .var _nst_blk_src[DSP4_BLOCK_SIZE];
.global _nst_blk_acc;   .var _nst_blk_acc[3*DSP4_BLOCK_SIZE];
.global _nst_tper;      .var _nst_tper = DIAG_TPERIOD;
.global _nst_iters;     .var _nst_iters = 200000;

.section/pm seg_pmco;
.extern _acc64_mac;
.extern _acc64_rns28;
.extern _diag_ticks;
#if DSP4_BLOCK_KERNELS
.extern _acc64_mac_blk;
#endif

/*----------------------------------------------------------------------
 * _xfade_blend_probe — the SHIPPED blend body, callable.
 * In:  r0 = new, r14 = old, _nst_xfade_alpha_PROBE = alpha (float)
 * Out: r0 = blended sample
 *----------------------------------------------------------------------*/
.global _xfade_blend_probe;
_xfade_blend_probe:
            f4 = dm(_nst_xfade_alpha_PROBE);
            r5 = 0x4F000000;               /* 2^31 as float */
            f5 = r5;
            f4 = f4 * f5;
            r4 = fix f4;                   /* alpha_q31; `fix` saturates */
            /* alpha*(new - old) as TWO MACs into the 80-bit MRF, so the
             * difference is NEVER formed in a 32-bit register (review
             * finding D3). `new` and `old` are independently saturated
             * Q4.28 outputs, so new-old spans +/-(2^32-1) and the old
             * `r5 = r0 - r14` wrapped when the two instances straddled
             * full scale mid-swap -- up to a block of full-scale-wrong
             * samples, a click. Same instruction count, and identical
             * arithmetic everywhere the subtract did not wrap.
             * Model: fixed_ref.xfade_blend. The final add cannot
             * overflow -- the result is a convex combination of two
             * int32s, bounded by them; the bound is in numeric-spec.md.
             *
             * EMITTED FROM ONE PLACE: _xfade_blend_core() in
             * dsp_codegen.py. Every EQ/GEQ/AFB/FILT/CROSSOVER node and
             * the in-part self-test (lib/num_selftest.asm) get these
             * exact instructions from this one expression, so the
             * sequence the self-test proves bit-exact against the model
             * is the sequence the nodes run. */
            mrf = r0 * r4 (ssi);           /* + new*alpha */
            mrf = mrf - r14 * r4 (ssi);    /* - old*alpha */
            r5 = 0x40000000;               /* 2^30 rounding half */
            r12 = 1;
            mrf = mrf + r5 * r12 (ssi);
            r5 = mr0f;
            r12 = mr1f;
            r5 = lshift r5 by -31;
            r12 = lshift r12 by 1;
            r5 = r5 or r12;
            r0 = r14 + r5;                 /* blended output */
    rts;
_xfade_blend_probe.end:

/*----------------------------------------------------------------------
 * _nst_blend_old — the PRE-FIX blend: the difference in 32 bits.
 * Same registers. Only the two MACs differ.
 *----------------------------------------------------------------------*/
.global _nst_blend_old;
_nst_blend_old:
    f4 = dm(_nst_xfade_alpha_PROBE);
    r5 = 0x4F000000;
    f5 = r5;
    f4 = f4 * f5;
    r4 = fix f4;
    r5 = r0 - r14;                 /* new - old, IN 32 BITS: wraps */
    mrf = r5 * r4 (ssi);
    r5 = 0x40000000;
    r12 = 1;
    mrf = mrf + r5 * r12 (ssi);
    r5 = mr0f;
    r12 = mr1f;
    r5 = lshift r5 by -31;
    r12 = lshift r12 by 1;
    r5 = r5 or r12;
    r0 = r14 + r5;
    rts;
_nst_blend_old.end:

/*----------------------------------------------------------------------
 * _nst_mac_old / _nst_rns_old — the PRE-FIX bus accumulator: two words,
 * MR2F discarded on store and manufactured from the sign of hi on load.
 * Byte-for-byte what lib/mac64_fx.asm held before 2026-08-29.
 *----------------------------------------------------------------------*/
.global _nst_mac_old;
_nst_mac_old:
    r2 = dm(i2, 1);
    r3 = dm(i2, 0);
    mr0f = r2;
    mr1f = r3;
    r2 = ashift r3 by -31;
    mr2f = r2;
    mrf = mrf + r0 * r1 (ssi);
    r2 = mr1f;
    dm(i2, -1) = r2;
    r2 = mr0f;
    dm(i2, 0) = r2;
    rts;
_nst_mac_old.end:

#if DSP4_BLOCK_KERNELS
/*----------------------------------------------------------------------
 * _nst_mac_blk_old — the PRE-FIX per-BLOCK accumulate: BLOCK [lo, hi]
 * pairs, MR2F discarded. Byte-for-byte what the generator emitted as
 * _acc64_mac_blk before 2026-08-29. Timing arm only.
 *----------------------------------------------------------------------*/
.global _nst_mac_blk_old;
_nst_mac_blk_old:
    l0 = 0;
    l2 = 0;
    r5 = DSP4_BLOCK_SIZE;
    lcntr = r5, do .nmbo_lp until lce;
        r0 = dm(i0, 1);
        r2 = dm(i2, 1);            /* lo; i2 -> hi */
        r3 = dm(i2, 0);            /* hi           */
        mr0f = r2;
        mr1f = r3;
        r2 = ashift r3 by -31;
        mr2f = r2;
        mrf = mrf + r0 * r1 (ssi);
        r2 = mr1f;
        dm(i2, -1) = r2;           /* hi; i2 -> lo */
        r2 = mr0f;
    .nmbo_lp:
        dm(i2, 2) = r2;            /* lo; i2 -> next pair */
    rts;
_nst_mac_blk_old.end:
#endif

.global _nst_rns_old;
_nst_rns_old:
    r1 = dm(i2, 1);
    r2 = dm(i2, 0);
    mr0f = r1;
    mr1f = r2;
    r3 = ashift r2 by -31;
    mr2f = r3;
    r1 = 0x08000000;
    r3 = 1;
    mrf = mrf + r1 * r3 (ssi);
    r1 = mr0f;
    r2 = mr1f;
    r1 = lshift r1 by -28;
    r3 = lshift r2 by 4;
    r0 = r1 or r3;
    r1 = ashift r2 by -28;
    r3 = ashift r0 by -31;
    comp(r1, r3);
    if eq rts;
    r0 = 0x7FFFFFFF;
    r1 = ashift r2 by -31;
    r0 = r0 xor r1;
    rts;
_nst_rns_old.end:

/*----------------------------------------------------------------------
 * _num_selftest — run both arms once, then the timing arm.
 *----------------------------------------------------------------------*/
.global _num_selftest;
_num_selftest:
    l0 = 0; l1 = 0; l2 = 0; l3 = 0; l4 = 0; l5 = 0;

    /* ================= MIX arm ================= */
    i4 = _nst_mix_v;
    i5 = _nst_mix_r;
    r14 = dm(_nst_mix_n);
    lcntr = r14, do .nst_mix_lp until lce;
        /* zero the triple */
        r0 = 0;
        dm(_nst_acc) = r0;
        dm(_nst_acc + 1) = r0;
        dm(_nst_acc + 2) = r0;
        /* part 1 */
        r10 = dm(i4, 1);           /* n1 */
        r11 = dm(i4, 1);           /* x1 */
        r12 = dm(i4, 1);           /* g1 */
        r10 = pass r10;
        if eq jump (pc, .nst_p2);
        lcntr = r10, do .nst_a1 until lce;
            r0 = r11;
            r1 = r12;
            i2 = _nst_acc;
#if DSP4_NUM_NEGCTL
            call _nst_mac_old;
#else
            call _acc64_mac;
#endif
            nop;
        .nst_a1:
            nop;
    .nst_p2:
        /* part 2 */
        r10 = dm(i4, 1);           /* n2 */
        r11 = dm(i4, 1);           /* x2 */
        r12 = dm(i4, 1);           /* g2 */
        r10 = pass r10;
        if eq jump (pc, .nst_rd);
        lcntr = r10, do .nst_a2 until lce;
            r0 = r11;
            r1 = r12;
            i2 = _nst_acc;
#if DSP4_NUM_NEGCTL
            call _nst_mac_old;
#else
            call _acc64_mac;
#endif
            nop;
        .nst_a2:
            nop;
    .nst_rd:
        i2 = _nst_acc;
#if DSP4_NUM_NEGCTL
        call _nst_rns_old;
#else
        call _acc64_rns28;
#endif
        dm(i5, 1) = r0;
        nop;
    .nst_mix_lp:
        nop;

    /* ================= BLEND arm ================= */
    i4 = _nst_bl_v;
    i5 = _nst_bl_r;
    r14 = dm(_nst_bl_n);
    lcntr = r14, do .nst_bl_lp until lce;
        r10 = dm(i4, 1);           /* new */
        r11 = dm(i4, 1);           /* old */
        r12 = dm(i4, 1);           /* alpha, float bits */
        dm(_nst_xfade_alpha_PROBE) = r12;
        r0 = r10;
        r14 = r11;
#if DSP4_NUM_NEGCTL
        call _nst_blend_old;
#else
        call _xfade_blend_probe;
#endif
        dm(i5, 1) = r0;
        nop;
    .nst_bl_lp:
        nop;

    /* ================= TIMING arm =================
     * The SAME work through both MAC forms. Three arms:
     *   pair 0  null loop (the setup and loop overhead)
     *   pair 1  _acc64_mac   -- the three-word form the graph now runs
     *   pair 2  _nst_mac_old -- the pre-fix two-word form
     * Each pair is (ticks, tcount) at the start and again at the end,
     * six pairs in _nst_tick. The host computes
     *   cycles = (ticks_end - ticks_start) * DIAG_TPERIOD
     *            + (tcount_start - tcount_end)
     * which is main.asm's own per-block accounting form -- ticks alone
     * quantise to 1 ms, which at 200k iterations is 2.46 cycles/MAC and
     * cannot see a two-instruction change. */
    r2 = tcount;
    r0 = dm(_diag_ticks);
    dm(_nst_tick + 0) = r0;
    dm(_nst_tick + 1) = r2;
    r10 = dm(_nst_iters);
    lcntr = r10, do .nst_tn until lce;
        r0 = 0x40000000;
        r1 = 0x10000000;
        i2 = _nst_acc;
        nop;
        nop;
    .nst_tn:
        nop;
    r2 = tcount;
    r0 = dm(_diag_ticks);
    dm(_nst_tick + 2) = r0;
    dm(_nst_tick + 3) = r2;

    r2 = tcount;
    r0 = dm(_diag_ticks);
    dm(_nst_tick + 4) = r0;
    dm(_nst_tick + 5) = r2;
    r10 = dm(_nst_iters);
    lcntr = r10, do .nst_tnew until lce;
        r0 = 0x40000000;
        r1 = 0x10000000;
        i2 = _nst_acc;
        call _acc64_mac;
        nop;
    .nst_tnew:
        nop;
    r2 = tcount;
    r0 = dm(_diag_ticks);
    dm(_nst_tick + 6) = r0;
    dm(_nst_tick + 7) = r2;

    r2 = tcount;
    r0 = dm(_diag_ticks);
    dm(_nst_tick + 8) = r0;
    dm(_nst_tick + 9) = r2;
    r10 = dm(_nst_iters);
    lcntr = r10, do .nst_told until lce;
        r0 = 0x40000000;
        r1 = 0x10000000;
        i2 = _nst_acc;
        call _nst_mac_old;
        nop;
    .nst_told:
        nop;
    r2 = tcount;
    r0 = dm(_diag_ticks);
    dm(_nst_tick + 10) = r0;
    dm(_nst_tick + 11) = r2;

#if DSP4_BLOCK_KERNELS
    /* pair 3 = _acc64_mac_blk (3 word), pair 4 = the pre-fix 2-word
     * block form. Each call is BLOCK MACs, so the host divides by
     * iters * BLOCK. This is the form the block-8 operating point runs
     * and the one the capacity arithmetic is built on. */
    r2 = tcount;
    r0 = dm(_diag_ticks);
    dm(_nst_tick + 12) = r0;
    dm(_nst_tick + 13) = r2;
    r10 = dm(_nst_iters);
    lcntr = r10, do .nst_tbn until lce;
        r1 = 0x10000000;
        i0 = _nst_blk_src;
        i2 = _nst_blk_acc;
        call _acc64_mac_blk;
        nop;
    .nst_tbn:
        nop;
    r2 = tcount;
    r0 = dm(_diag_ticks);
    dm(_nst_tick + 14) = r0;
    dm(_nst_tick + 15) = r2;

    r2 = tcount;
    r0 = dm(_diag_ticks);
    dm(_nst_tick + 16) = r0;
    dm(_nst_tick + 17) = r2;
    r10 = dm(_nst_iters);
    lcntr = r10, do .nst_tbo until lce;
        r1 = 0x10000000;
        i0 = _nst_blk_src;
        i2 = _nst_blk_acc;
        call _nst_mac_blk_old;
        nop;
    .nst_tbo:
        nop;
    r2 = tcount;
    r0 = dm(_diag_ticks);
    dm(_nst_tick + 18) = r0;
    dm(_nst_tick + 19) = r2;
#endif

    r0 = 1;
    dm(_nst_done) = r0;
    rts;
_num_selftest.end:

#endif /* DSP4_NUM_SELFTEST */
