/*----------------------------------------------------------------------
 * Aux 12 Bus Send (INTERCHIP_SEND)
 * Node ID:    C1_BUS_AUX_12_SEND
 * Chip:       1
 * Channels:   1
 * SPI Page:   -1
 * SPI Addr:   -1
 * RampProfile: (none)
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/

/* INTERCHIP_SEND: Write to inter-chip SPORT7 TDM slot 18 */

.section/dm seg_dmda;
.extern _buf_C1_BUS_AUX_12;
.global _tx_slot_C1_BUS_AUX_12_SEND;
.var _tx_slot_C1_BUS_AUX_12_SEND;

.section/pm seg_pmco;
.global _C1_BUS_AUX_12_SEND_process;
_C1_BUS_AUX_12_SEND_process:
    r0 = dm(_buf_C1_BUS_AUX_12);
    dm(_tx_slot_C1_BUS_AUX_12_SEND) = r0;
    rts;
_C1_BUS_AUX_12_SEND_process.end:
