/*----------------------------------------------------------------------
 * Sub Bus (MIX_BUS)
 * Node ID:    C1_BUS_SUB
 * Chip:       1
 * Channels:   1
 * SPI Page:   1
 * SPI Addr:   4752
 * RampProfile: (none)
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/

/* MIX_BUS (FIXED, D5): bus_id=2 — exact 64-bit acc readout */

.section/dm seg_dmda;
.global _buf_C1_BUS_SUB;
.var _buf_C1_BUS_SUB;

.section/pm seg_pmco;
.extern _bus_acc_sub;
.extern _acc64_rns28;
.global _C1_BUS_SUB_process;
_C1_BUS_SUB_process:
    i2 = _bus_acc_sub;
    call _acc64_rns28;
    dm(_buf_C1_BUS_SUB) = r0;
    rts;
_C1_BUS_SUB_process.end:
