/*----------------------------------------------------------------------
 * Main L Bus (MIX_BUS)
 * Node ID:    C1_BUS_MAIN_L
 * Chip:       1
 * Channels:   1
 * SPI Page:   1
 * SPI Addr:   4748
 * RampProfile: (none)
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/

/* MIX_BUS (FIXED, D5): bus_id=0 — exact 64-bit acc readout */

#include "blk_pool.h"

.section/dm seg_dmda;
#if DSP4_BLOCK_KERNELS
.global _buf_C1_BUS_MAIN_L;
.var _buf_C1_BUS_MAIN_L[32];
#else
.global _buf_C1_BUS_MAIN_L;
.var _buf_C1_BUS_MAIN_L;
#endif

.section/pm seg_pmco;
.extern _bus_acc_main_l;
.extern _acc64_rns28;
.global _C1_BUS_MAIN_L_process;
_C1_BUS_MAIN_L_process:
#if DSP4_BLOCK_KERNELS
    /* One call per BLOCK instead of 32. The accumulator is
     * already per-sample (64 words = 32 x 2), so this walks it
     * and rounds each sample in turn. _acc64_rns28 advances i2
     * by one, so it takes one more modify to step a pair. */
    l2 = 0;
    l3 = 0;
    i2 = _bus_acc_main_l;
    i3 = _buf_C1_BUS_MAIN_L;
    m0 = 1;
    lcntr = 32, do .mbk_C1_BUS_MAIN_L until lce;
        call _acc64_rns28;
        modify(i2, m0);
    .mbk_C1_BUS_MAIN_L: dm(i3, 1) = r0;
    rts;
#else
    i2 = _bus_acc_main_l;
    call _acc64_rns28;
    dm(_buf_C1_BUS_MAIN_L) = r0;
    rts;
#endif
_C1_BUS_MAIN_L_process.end:
