/*----------------------------------------------------------------------
 * Grp 1 Bus Send (INTERCHIP_SEND)
 * Node ID:    C1_BUS_GRP_01_SEND
 * Chip:       1
 * Channels:   1
 * SPI Page:   -1
 * SPI Addr:   -1
 * RampProfile: (none)
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/

/* INTERCHIP_SEND: mix-fabric line 0 slot 3 (global slot 3, signal BUS_GRP_01) */

#include "blk_pool.h"

.section/dm seg_dmda;
.extern _buf_C1_BUS_GRP_01;
#if DSP4_BLOCK_KERNELS
.global _tx_slot_C1_BUS_GRP_01_SEND;
.var _tx_slot_C1_BUS_GRP_01_SEND[32];
#else
.global _tx_slot_C1_BUS_GRP_01_SEND;
.var _tx_slot_C1_BUS_GRP_01_SEND;
#endif

.section/pm seg_pmco;
.global _C1_BUS_GRP_01_SEND_process;
_C1_BUS_GRP_01_SEND_process:
#if DSP4_BLOCK_KERNELS
    l2 = 0;
    l3 = 0;
    i2 = _buf_C1_BUS_GRP_01;
    i3 = _tx_slot_C1_BUS_GRP_01_SEND;
    lcntr = 32, do .isk_C1_BUS_GRP_01_SEND until lce;
        r0 = dm(i2, 1);
    .isk_C1_BUS_GRP_01_SEND: dm(i3, 1) = r0;
    rts;
#else
    r0 = dm(_buf_C1_BUS_GRP_01);
    dm(_tx_slot_C1_BUS_GRP_01_SEND) = r0;
    rts;
#endif
_C1_BUS_GRP_01_SEND_process.end:
