/*----------------------------------------------------------------------
 * FX 4 Bus (MIX_BUS)
 * Node ID:    C1_BUS_FX_04
 * Chip:       1
 * Channels:   1
 * SPI Page:   1
 * SPI Addr:   4792
 * RampProfile: (none)
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/

/* MIX_BUS (FIXED, D5): bus_id=22 — exact 64-bit acc readout */

.section/dm seg_dmda;
.global _buf_C1_BUS_FX_04;
.var _buf_C1_BUS_FX_04;

.section/pm seg_pmco;
.extern _bus_acc_fx_04;
.extern _acc64_rns28;
.global _C1_BUS_FX_04_process;
_C1_BUS_FX_04_process:
    i2 = _bus_acc_fx_04;
    call _acc64_rns28;
    dm(_buf_C1_BUS_FX_04) = r0;
    rts;
_C1_BUS_FX_04_process.end:
