/*----------------------------------------------------------------------
 * FX 5 Bus (MIX_BUS)
 * Node ID:    C1_BUS_FX_05
 * Chip:       1
 * Channels:   1
 * SPI Page:   1
 * SPI Addr:   4794
 * RampProfile: (none)
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/

/* MIX_BUS (FIXED, D5): bus_id=23 — exact 64-bit acc readout */

.section/dm seg_dmda;
.global _buf_C1_BUS_FX_05;
.var _buf_C1_BUS_FX_05;

.section/pm seg_pmco;
.extern _bus_acc_fx_05;
.extern _acc64_rns28;
.global _C1_BUS_FX_05_process;
_C1_BUS_FX_05_process:
    i2 = _bus_acc_fx_05;
    call _acc64_rns28;
    dm(_buf_C1_BUS_FX_05) = r0;
    rts;
_C1_BUS_FX_05_process.end:
