/*----------------------------------------------------------------------
 * Main R Bus Send (INTERCHIP_SEND)
 * Node ID:    C1_BUS_MAIN_R_SEND
 * Chip:       1
 * Channels:   1
 * SPI Page:   -1
 * SPI Addr:   -1
 * RampProfile: (none)
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/

/* INTERCHIP_SEND: mix-fabric line 0 slot 1 (global slot 1, signal BUS_MAIN_R) */

.section/dm seg_dmda;
.extern _buf_C1_BUS_MAIN_R;
.global _tx_slot_C1_BUS_MAIN_R_SEND;
.var _tx_slot_C1_BUS_MAIN_R_SEND;

.section/pm seg_pmco;
.global _C1_BUS_MAIN_R_SEND_process;
_C1_BUS_MAIN_R_SEND_process:
    r0 = dm(_buf_C1_BUS_MAIN_R);
    dm(_tx_slot_C1_BUS_MAIN_R_SEND) = r0;
    rts;
_C1_BUS_MAIN_R_SEND_process.end:
