/*----------------------------------------------------------------------
 * Grp 2 Bus Send (INTERCHIP_SEND)
 * Node ID:    C1_BUS_GRP_02_SEND
 * Chip:       1
 * Channels:   1
 * SPI Page:   -1
 * SPI Addr:   -1
 * RampProfile: (none)
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/

/* INTERCHIP_SEND: mix-fabric line 0 slot 4 (global slot 4, signal BUS_GRP_02) */

.section/dm seg_dmda;
.extern _buf_C1_BUS_GRP_02;
.global _tx_slot_C1_BUS_GRP_02_SEND;
.var _tx_slot_C1_BUS_GRP_02_SEND;

.section/pm seg_pmco;
.global _C1_BUS_GRP_02_SEND_process;
_C1_BUS_GRP_02_SEND_process:
    r0 = dm(_buf_C1_BUS_GRP_02);
    dm(_tx_slot_C1_BUS_GRP_02_SEND) = r0;
    rts;
_C1_BUS_GRP_02_SEND_process.end:
