/*----------------------------------------------------------------------
 * Aux 2 Bus (MIX_BUS)
 * Node ID:    C1_BUS_AUX_02
 * Chip:       1
 * Channels:   1
 * SPI Page:   1
 * SPI Addr:   4764
 * RampProfile: (none)
 *
 * AUTO-GENERATED by dsp_codegen.py (D32) — do not edit directly.
 *----------------------------------------------------------------------*/

/* MIX_BUS: Summing bus (bus_id=8) — scatter passthrough */
/* Chip 1: reads pre-accumulated value from _bus_acc_aux_02 */

.section/dm seg_dmda;
.global _buf_C1_BUS_AUX_02;
.var _buf_C1_BUS_AUX_02;

.section/pm seg_pmco;
.extern _bus_acc_aux_02;
.global _C1_BUS_AUX_02_process;
_C1_BUS_AUX_02_process:
    f0 = dm(_bus_acc_aux_02);
    dm(_buf_C1_BUS_AUX_02) = f0;
    rts;
_C1_BUS_AUX_02_process.end:
