/*----------------------------------------------------------------------
 * Ch 24 Comp (COMPRESSOR)
 * Node ID:    C1_COMP_24
 * Chip:       1
 * Channels:   1
 * SPI Page:   1
 * SPI Addr:   3368
 * RampProfile: DynSafe
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/

/* RampProfile: DynSafe | Mode: LinearFrames | Up: 6ms (9f) Down: 20ms (30f) | Curve: Exp | Scope: Scalar */

/* COMPRESSOR (FIXED Q4.28, D5) */
/* SPI page=1 addr=3368 */

.section/dm seg_dmda;
.extern _buf_C1_GATE_24;
.global _comp_on_C1_COMP_24;
.var _comp_on_C1_COMP_24 = 1;
.global _comp_threshold_C1_COMP_24;
.var _comp_threshold_C1_COMP_24 = -20.0;
.global _comp_ratio_C1_COMP_24;
.var _comp_ratio_C1_COMP_24 = 4.0;
.global _comp_attack_C1_COMP_24;
.var _comp_attack_C1_COMP_24 = 0.01;
.global _comp_release_C1_COMP_24;
.var _comp_release_C1_COMP_24 = 0.001;
.global _comp_makeup_C1_COMP_24;
.var _comp_makeup_C1_COMP_24 = 1.0;
.global _comp_makeup_target_C1_COMP_24;
.var _comp_makeup_target_C1_COMP_24 = 1.0;
.global _comp_makeup_step_C1_COMP_24;
.var _comp_makeup_step_C1_COMP_24 = 0.0;
.global _comp_makeup_frames_C1_COMP_24;
.var _comp_makeup_frames_C1_COMP_24 = 0;
.global _comp_knee_C1_COMP_24;
.var _comp_knee_C1_COMP_24;
.global _comp_parallel_C1_COMP_24;
.var _comp_parallel_C1_COMP_24 = 0.0;
.global _comp_type_C1_COMP_24;
.var _comp_type_C1_COMP_24 = 0;
.global _comp_key_src_C1_COMP_24;
.var _comp_key_src_C1_COMP_24 = 0;
.global _comp_det_src_C1_COMP_24;
.var _comp_det_src_C1_COMP_24 = 0;
.global _comp_eq_pos_C1_COMP_24;
.var _comp_eq_pos_C1_COMP_24 = 0;
.global _comp_lim_mode_C1_COMP_24;
.var _comp_lim_mode_C1_COMP_24 = 0;
.global _comp_filter_on_C1_COMP_24;
.var _comp_filter_on_C1_COMP_24 = 0;
.global _comp_filter_coeffs_C1_COMP_24;
.var _comp_filter_coeffs_C1_COMP_24[10];
.global _comp_filter_state_C1_COMP_24;
.var _comp_filter_state_C1_COMP_24[4];
.global _comp_envelope_C1_COMP_24;
.var _comp_envelope_C1_COMP_24 = 0;        /* Q4.28 */
.global _comp_gain_C1_COMP_24;
.var _comp_gain_C1_COMP_24 = 0x10000000;   /* Q4.28 (display) */
.global _comp_attq_C1_COMP_24;
.var _comp_attq_C1_COMP_24 = 0;
.global _comp_relq_C1_COMP_24;
.var _comp_relq_C1_COMP_24 = 0;
.global _comp_mkq_C1_COMP_24;
.var _comp_mkq_C1_COMP_24 = 0x10000000;
.global _comp_parq_C1_COMP_24;
.var _comp_parq_C1_COMP_24 = 0;            /* Q0.31 */
.global _comp_cgp_C1_COMP_24;
.var _comp_cgp_C1_COMP_24[4];              /* thr, slope, halfk, k2 */
.global _buf_C1_COMP_24;
.var _buf_C1_COMP_24;

.section/pm seg_pmco;
.extern _sample_idx;
.extern _envq_fx;
.extern _compgain_fx;
.extern _mrf_rns28;
.global _C1_COMP_24_process;
_C1_COMP_24_process:
    r0 = dm(_buf_C1_GATE_24);
    r2 = dm(_comp_on_C1_COMP_24);
    r3 = 0;
    comp(r2, r3);
    if eq jump (pc, .comp_bypass_C1_COMP_24);
    r13 = r0;                     /* dry (r13-r15 lib-safe) */

    /* --- block rate: makeup ramp + param conversion --- */
    r4 = dm(_sample_idx);
    r1 = 0;
    comp(r4, r1);
    if ne jump (pc, .comp_go_C1_COMP_24);
    r4 = dm(_comp_makeup_frames_C1_COMP_24);
    comp(r4, r1);
    if le jump (pc, .no_mramp_C1_COMP_24);
    r4 = r4 - 1;
    dm(_comp_makeup_frames_C1_COMP_24) = r4;
    f1 = dm(_comp_makeup_C1_COMP_24);
    f2 = dm(_comp_makeup_step_C1_COMP_24);
    f1 = f1 + f2;
    dm(_comp_makeup_C1_COMP_24) = f1;
    jump (pc, .comp_cvt_C1_COMP_24);
.no_mramp_C1_COMP_24:
    f1 = dm(_comp_makeup_target_C1_COMP_24);
    dm(_comp_makeup_C1_COMP_24) = f1;
.comp_cvt_C1_COMP_24:
    r2 = 0x4D800000;
    f2 = r2;
    f1 = f1 * f2;
    r1 = fix f1;
    dm(_comp_mkq_C1_COMP_24) = r1;
    f1 = dm(_comp_parallel_C1_COMP_24);
    r2 = 0x4F000000;
    f2 = r2;
    f1 = f1 * f2;
    r1 = fix f1;
    dm(_comp_parq_C1_COMP_24) = r1;
    r2 = 0x4F000000;              /* 2^31 float */
    f2 = r2;
    f1 = dm(_comp_attack_C1_COMP_24);
    f1 = f1 * f2;
    r1 = fix f1;
    dm(_comp_attq_C1_COMP_24) = r1;
    f1 = dm(_comp_release_C1_COMP_24);
    f1 = f1 * f2;
    r1 = fix f1;
    dm(_comp_relq_C1_COMP_24) = r1;
    r2 = 0x4AAA152D;            /* dB -> Q6.25 log2 */
    f2 = r2;
    f1 = dm(_comp_threshold_C1_COMP_24);
    f1 = f1 * f2;
    r1 = fix f1;
    dm(_comp_cgp_C1_COMP_24) = r1;    /* thr */
    /* slope = 1 - 1/ratio */
    f6 = dm(_comp_ratio_C1_COMP_24);
    f7 = recips f6;
    f8 = f6 * f7;
    r10 = 0x40000000;
    f8 = f10 - f8;
    f7 = f7 * f8;
    f8 = f6 * f7;
    f8 = f10 - f8;
    f6 = f7 * f8;
    r2 = 0x3F800000;
    f5 = r2;
    f5 = f5 - f6;                 /* slope float */
    r2 = 0x4F000000;
    f2 = r2;
    f1 = f5 * f2;
    r1 = fix f1;
    dm(_comp_cgp_C1_COMP_24 + 1) = r1;
    /* knee: halfk = knee_db/2 in Q6.25 log2; k2 = slope*K/(2*knee) Q6.25 */
    f4 = dm(_comp_knee_C1_COMP_24);
    r2 = 0x3DCCCCCD;              /* 0.1 dB min for soft path */
    f3 = r2;
    comp(f4, f3);
    if gt jump (pc, .comp_soft_C1_COMP_24);
    r1 = 0;
    dm(_comp_cgp_C1_COMP_24 + 2) = r1;
    dm(_comp_cgp_C1_COMP_24 + 3) = r1;
    jump (pc, .comp_kdone_C1_COMP_24);
.comp_soft_C1_COMP_24:
    r2 = 0x4AAA152D;
    f2 = r2;
    f1 = f4 * f2;
    r2 = 0x3F000000;              /* 0.5 */
    f3 = r2;
    f1 = f1 * f3;
    r1 = fix f1;
    dm(_comp_cgp_C1_COMP_24 + 2) = r1;  /* halfk */
    f7 = recips f4;
    f8 = f4 * f7;
    r10 = 0x40000000;
    f8 = f10 - f8;
    f7 = f7 * f8;
    f8 = f4 * f7;
    f8 = f10 - f8;
    f6 = f7 * f8;
    r2 = 0x4040A8C1;             /* K/2 */
    f3 = r2;
    f6 = f6 * f3;                 /* K/(2*knee_db) */
    f6 = f6 * f5;                 /* * slope */
    r2 = 0x4C000000;              /* 2^25 float */
    f2 = r2;
    f1 = f6 * f2;
    r1 = fix f1;
    dm(_comp_cgp_C1_COMP_24 + 3) = r1;  /* k2 */
.comp_kdone_C1_COMP_24:
.comp_go_C1_COMP_24:

    /* --- envelope (fixed) --- */
    r0 = abs r13;
    r1 = dm(_comp_envelope_C1_COMP_24);
    r2 = dm(_comp_attq_C1_COMP_24);
    r3 = dm(_comp_relq_C1_COMP_24);
    call _envq_fx;
    dm(_comp_envelope_C1_COMP_24) = r0;

    /* --- gain computer (log2 domain) --- */
    i0 = _comp_cgp_C1_COMP_24;
    call _compgain_fx;            /* r0 = gain Q4.28 */
    dm(_comp_gain_C1_COMP_24) = r0;

    /* wet = dry * gain * makeup */
    r1 = r0;
    r0 = r13;
    mrf = r0 * r1 (ssi);
    call _mrf_rns28;
    r1 = dm(_comp_mkq_C1_COMP_24);
    mrf = r0 * r1 (ssi);
    call _mrf_rns28;

    /* parallel: out = dry + par*(wet - dry) — matches the float
     * node exactly (par==0 -> dry, its default behaviour) */
    r5 = r0 - r13;
    r4 = dm(_comp_parq_C1_COMP_24);
    mrf = r5 * r4 (ssi);
    r1 = 0x40000000;
    r12 = 1;
    mrf = mrf + r1 * r12 (ssi);
    r1 = mr0f;
    r12 = mr1f;
    r1 = lshift r1 by -31;
    r12 = lshift r12 by 1;
    r1 = r1 or r12;
    r0 = r13 + r1;
    dm(_buf_C1_COMP_24) = r0;
    rts;
.comp_bypass_C1_COMP_24:
    dm(_buf_C1_COMP_24) = r0;
    rts;
_C1_COMP_24_process.end:
