/*----------------------------------------------------------------------
 * Ch 6 Fader (FADER_PAN)
 * Node ID:    C1_FDR_06
 * Chip:       1
 * Channels:   1
 * SPI Page:   1
 * SPI Addr:   800
 * RampProfile: GainFast
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/

        /* RampProfile: GainFast | Mode: Slew | Up: 3ms (4f) Down: 8ms (12f) | Curve: Exp | Scope: Scalar */

        /* FADER_PAN (FIXED Q4.28, D5) — float control, fixed sample path */
        /* SPI page=1 addr=800 */

        .section/dm seg_dmda;
.extern _buf_C1_DLY_06;
        .global _fdr_level_C1_FDR_06;
        .var _fdr_level_C1_FDR_06 = 1.0;
        .global _fdr_level_target_C1_FDR_06;
        .var _fdr_level_target_C1_FDR_06 = 1.0;
        .global _fdr_level_step_C1_FDR_06;
        .var _fdr_level_step_C1_FDR_06 = 0.0;
        .global _fdr_level_frames_C1_FDR_06;
        .var _fdr_level_frames_C1_FDR_06 = 0;
        .global _fdr_pan_C1_FDR_06;
        .var _fdr_pan_C1_FDR_06 = 0.5;
        .global _fdr_pan_target_C1_FDR_06;
        .var _fdr_pan_target_C1_FDR_06 = 0.5;
        .global _fdr_pan_step_C1_FDR_06;
        .var _fdr_pan_step_C1_FDR_06 = 0.0;
        .global _fdr_pan_frames_C1_FDR_06;
        .var _fdr_pan_frames_C1_FDR_06 = 0;
        .global _fdr_mute_C1_FDR_06;
        .var _fdr_mute_C1_FDR_06 = 0;
        .global _fdr_dca_gain_C1_FDR_06;
        .var _fdr_dca_gain_C1_FDR_06 = 1.0;
        .global _fdr_gq_C1_FDR_06;
        .var _fdr_gq_C1_FDR_06 = 0x10000000;          /* Q4.28 level*dca */
        .global _tap_post_fader_C1_FDR_06;
        .var _tap_post_fader_C1_FDR_06;
        .global _buf_C1_FDR_06;
        .var _buf_C1_FDR_06;
        .global _fdr_lq_C1_FDR_06;
        .var _fdr_lq_C1_FDR_06 = 0;
        .global _fdr_rq_C1_FDR_06;
        .var _fdr_rq_C1_FDR_06 = 0;
        .global _buf_L_C1_FDR_06;
        .var _buf_L_C1_FDR_06;
        .global _buf_R_C1_FDR_06;
        .var _buf_R_C1_FDR_06;

        .section/pm seg_pmco;
        .extern _sample_idx;
        .extern _mrf_rns28;
        .global _C1_FDR_06_process;
        _C1_FDR_06_process:
            /* block-rate: float ramps + shadow conversion */
            r4 = dm(_sample_idx);
            r1 = 0;
            comp(r4, r1);
            if ne jump (pc, .apply_C1_FDR_06);

            /* level ramp */
            r4 = dm(_fdr_level_frames_C1_FDR_06);
            r1 = 0;
            comp(r4, r1);
            if le jump (pc, .lsnap_C1_FDR_06);
            /* Consume a BLOCK's worth of frames and apply a BLOCK's
             * worth of step. spi_handler scales every profile frame count
             * by 32 (BLOCK_SIZE), which is right for the ramps that
             * decrement once per SAMPLE. This one decrements once per
             * BLOCK, so taking 1 per block ran it 32x long: measured
             * 2026-08-23, a GainSafe down-ramp took 960 ms against the
             * 30 ms its own cell table specifies, and a GainFast fader
             * move took 85 ms instead of 3 ms. 32.0f is exact in binary,
             * so scaling the step loses nothing. */
            r5 = 32;
            r4 = r4 - r5;
            dm(_fdr_level_frames_C1_FDR_06) = r4;
            f1 = dm(_fdr_level_C1_FDR_06);
            f2 = dm(_fdr_level_step_C1_FDR_06);
            r5 = 0x42000000;                  /* 32.0f */
            f5 = r5;
            f2 = f2 * f5;
            f1 = f1 + f2;
            dm(_fdr_level_C1_FDR_06) = f1;
            jump (pc, .pramp_C1_FDR_06);
        .lsnap_C1_FDR_06:
            f1 = dm(_fdr_level_target_C1_FDR_06);
            dm(_fdr_level_C1_FDR_06) = f1;
        .pramp_C1_FDR_06:
            /* pan ramp */
            r4 = dm(_fdr_pan_frames_C1_FDR_06);
            r1 = 0;
            comp(r4, r1);
            if le jump (pc, .psnap_C1_FDR_06);
            /* Consume a BLOCK's worth of frames and apply a BLOCK's
             * worth of step. spi_handler scales every profile frame count
             * by 32 (BLOCK_SIZE), which is right for the ramps that
             * decrement once per SAMPLE. This one decrements once per
             * BLOCK, so taking 1 per block ran it 32x long: measured
             * 2026-08-23, a GainSafe down-ramp took 960 ms against the
             * 30 ms its own cell table specifies, and a GainFast fader
             * move took 85 ms instead of 3 ms. 32.0f is exact in binary,
             * so scaling the step loses nothing. */
            r5 = 32;
            r4 = r4 - r5;
            dm(_fdr_pan_frames_C1_FDR_06) = r4;
            f1 = dm(_fdr_pan_C1_FDR_06);
            f2 = dm(_fdr_pan_step_C1_FDR_06);
            r5 = 0x42000000;                  /* 32.0f */
            f5 = r5;
            f2 = f2 * f5;
            f1 = f1 + f2;
            dm(_fdr_pan_C1_FDR_06) = f1;
            jump (pc, .cvt_C1_FDR_06);
        .psnap_C1_FDR_06:
            f1 = dm(_fdr_pan_target_C1_FDR_06);
            dm(_fdr_pan_C1_FDR_06) = f1;
        .cvt_C1_FDR_06:
            /* composite = level * dca; Q4.28 shadow(s) */
            f1 = dm(_fdr_level_C1_FDR_06);
            f2 = dm(_fdr_dca_gain_C1_FDR_06);
            f1 = f1 * f2;
            r2 = 0x4D800000;
            f2 = r2;
            f3 = f1 * f2;
            r2 = fix f3;
            dm(_fdr_gq_C1_FDR_06) = r2;
/* L/R pan gains (linear pan law, matches float node).
 *
 * PAN GAIN ONLY -- do NOT fold `comp` in here. The sample path
 * below multiplies the ALREADY-POST-FADER mono by these, so
 * including comp applied the fader twice and the bus feed came
 * out as x * level^2 * (1-pan). It is invisible at unity, which
 * is how it shipped: bench 2026-08-23 measured the main bus
 * 6.02 dB low at level 0.5 and 12.04 dB low at level 0.25, and
 * exact at level 1.0. The float node this was ported from does
 * `f1 = f14 * f7` with f7 = 1 - pan and no comp -- the squaring
 * was introduced by the fixed-point port, not inherited. */
r2 = 0x3F800000;
f2 = r2;
f5 = dm(_fdr_pan_C1_FDR_06);
f6 = f2 - f5;                     /* L gain = 1 - pan */
r2 = 0x4D800000;
f7 = r2;
f6 = f6 * f7;
r2 = fix f6;
dm(_fdr_lq_C1_FDR_06) = r2;
f5 = f5 * f7;
r2 = fix f5;
dm(_fdr_rq_C1_FDR_06) = r2;

        .apply_C1_FDR_06:
            r0 = dm(_buf_C1_DLY_06);
            r1 = dm(_fdr_gq_C1_FDR_06);
            mrf = r0 * r1 (ssi);
            call _mrf_rns28;

            r2 = dm(_fdr_mute_C1_FDR_06);
            r4 = 0;
            comp(r2, r4);
            if ne r0 = r4;

            dm(_tap_post_fader_C1_FDR_06) = r0;
            dm(_buf_C1_FDR_06) = r0;
r14 = r0;                         /* mono in (lib preserves) */
r1 = dm(_fdr_lq_C1_FDR_06);
mrf = r14 * r1 (ssi);
call _mrf_rns28;
dm(_buf_L_C1_FDR_06) = r0;
r1 = dm(_fdr_rq_C1_FDR_06);
mrf = r14 * r1 (ssi);
call _mrf_rns28;
dm(_buf_R_C1_FDR_06) = r0;
r0 = r14;
            rts;
        _C1_FDR_06_process.end:
