/*----------------------------------------------------------------------
 * Ch 11 HPF+LPF (HPF_LPF)
 * Node ID:    C1_FILT_11
 * Chip:       1
 * Channels:   1
 * SPI Page:   1
 * SPI Addr:   1444
 * RampProfile: EqSafe
 *
 * AUTO-GENERATED by dsp_codegen.py (D32) — do not edit directly.
 *----------------------------------------------------------------------*/

/* RampProfile: EqSafe | Mode: LinearFrames | Up: 12ms (18f) Down: 12ms (18f) | Curve: Linear | Scope: CoeffSetAtomic */

/* HPF_LPF: High-pass + Low-pass filter — dual-instance crossfade */
/* HPF: 80.0 Hz, slope 18 dB/oct */
/* LPF: 20000.0 Hz */
/* SPI page=1 addr=1444 */
/*
 * Each instance runs HPF→LPF in series (2 biquads total).
 * Crossfade architecture identical to EQ_BIQUAD: dormant instance
 * loaded on swap_pending, 576-sample linear blend.
 *
 * When EITHER hpf_swap_pending or lpf_swap_pending fires:
 *   1. Copy active instance's HPF+LPF coeffs to dormant (baseline)
 *   2. Overwrite the pending filter(s) with _next values
 *   3. Zero dormant state, start crossfade
 * This ensures the dormant instance always has a complete, consistent
 * coefficient set even if only one filter was updated.
 */

.section/dm seg_dmda;
.extern _buf_C1_GAIN_11;

/* ---- Instance A ---- */
.global _filt_hpf_A_C1_FILT_11;
.var _filt_hpf_A_C1_FILT_11[5] = 1.0, 0.0, 0.0, 0.0, 0.0;
.global _filt_lpf_A_C1_FILT_11;
.var _filt_lpf_A_C1_FILT_11[5] = 1.0, 0.0, 0.0, 0.0, 0.0;
.global _filt_state_A_C1_FILT_11;
.var _filt_state_A_C1_FILT_11[4];             /* HPF w1,w2 + LPF w1,w2 */

/* ---- Instance B ---- */
.global _filt_hpf_B_C1_FILT_11;
.var _filt_hpf_B_C1_FILT_11[5] = 1.0, 0.0, 0.0, 0.0, 0.0;
.global _filt_lpf_B_C1_FILT_11;
.var _filt_lpf_B_C1_FILT_11[5] = 1.0, 0.0, 0.0, 0.0, 0.0;
.global _filt_state_B_C1_FILT_11;
.var _filt_state_B_C1_FILT_11[4];

/* ---- SPI staging buffers ---- */
.global _hpf_coeffs_next_C1_FILT_11;
.var _hpf_coeffs_next_C1_FILT_11[5] = 1.0, 0.0, 0.0, 0.0, 0.0;
.global _hpf_swap_pending_C1_FILT_11;
.var _hpf_swap_pending_C1_FILT_11 = 0;
.global _lpf_coeffs_next_C1_FILT_11;
.var _lpf_coeffs_next_C1_FILT_11[5] = 1.0, 0.0, 0.0, 0.0, 0.0;
.global _lpf_swap_pending_C1_FILT_11;
.var _lpf_swap_pending_C1_FILT_11 = 0;

/* ---- Crossfade control ---- */
.global _filt_active_C1_FILT_11;
.var _filt_active_C1_FILT_11 = 0;             /* 0=A, 1=B */
.global _filt_xfade_alpha_C1_FILT_11;
.var _filt_xfade_alpha_C1_FILT_11 = 0.0;
.global _filt_xfade_step_C1_FILT_11;
.var _filt_xfade_step_C1_FILT_11 = 0.0;       /* 0 = idle */

.global _buf_C1_FILT_11;
.var _buf_C1_FILT_11;

.section/pm seg_pmco;
.extern _biquad_mono;
.global _C1_FILT_11_process;
_C1_FILT_11_process:

    /* ── Check swap pending (either filter) ── */
    r4 = dm(_hpf_swap_pending_C1_FILT_11);
    r4 = pass r4;
    if ne jump .filt_do_xfade_C1_FILT_11;
    r4 = dm(_lpf_swap_pending_C1_FILT_11);
    r4 = pass r4;
    if ne jump .filt_do_xfade_C1_FILT_11;
    jump .filt_mode_check_C1_FILT_11;
.filt_do_xfade_C1_FILT_11:
    call _filt_start_xfade_C1_FILT_11;

.filt_mode_check_C1_FILT_11:
    r4 = dm(_filt_xfade_step_C1_FILT_11);
    r4 = pass r4;
    if ne jump .filt_xfade_C1_FILT_11;

    /* ═══ STEADY STATE ══════════════════════════════════════ */
    r0 = dm(_buf_C1_GAIN_11);
    r4 = dm(_filt_active_C1_FILT_11);
    r4 = pass r4;
    if ne jump .filt_ss_B_C1_FILT_11;
    /* Instance A */
    i0 = _filt_hpf_A_C1_FILT_11;   i1 = _filt_state_A_C1_FILT_11;
    call _biquad_mono;                   /* HPF */
    i0 = _filt_lpf_A_C1_FILT_11;             /* i1 already at LPF state */
    call _biquad_mono;                   /* LPF */
    dm(_buf_C1_FILT_11) = r0;
    rts;
.filt_ss_B_C1_FILT_11:
    i0 = _filt_hpf_B_C1_FILT_11;   i1 = _filt_state_B_C1_FILT_11;
    call _biquad_mono;
    i0 = _filt_lpf_B_C1_FILT_11;
    call _biquad_mono;
    dm(_buf_C1_FILT_11) = r0;
    rts;

    /* ═══ CROSSFADE ═════════════════════════════════════════ */
.filt_xfade_C1_FILT_11:
    r0 = dm(_buf_C1_GAIN_11);
    f15 = f0;                            /* save input */

    /* ── Active (old) instance: HPF → LPF ── */
    r4 = dm(_filt_active_C1_FILT_11);
    r4 = pass r4;
    if ne jump .filt_xf_actB_C1_FILT_11;
    i0 = _filt_hpf_A_C1_FILT_11;   i1 = _filt_state_A_C1_FILT_11;
    call _biquad_mono;
    i0 = _filt_lpf_A_C1_FILT_11;
    call _biquad_mono;
    jump .filt_xf_act_done_C1_FILT_11;
.filt_xf_actB_C1_FILT_11:
    i0 = _filt_hpf_B_C1_FILT_11;   i1 = _filt_state_B_C1_FILT_11;
    call _biquad_mono;
    i0 = _filt_lpf_B_C1_FILT_11;
    call _biquad_mono;
.filt_xf_act_done_C1_FILT_11:
    f13 = f0;                            /* old output */

    /* ── Inactive (new) instance: HPF → LPF ── */
    f0 = f15;                            /* reload input */
    r4 = dm(_filt_active_C1_FILT_11);
    r4 = pass r4;
    if eq jump .filt_xf_inB_C1_FILT_11;
    i0 = _filt_hpf_A_C1_FILT_11;   i1 = _filt_state_A_C1_FILT_11;
    call _biquad_mono;
    i0 = _filt_lpf_A_C1_FILT_11;
    call _biquad_mono;
    jump .filt_xf_in_done_C1_FILT_11;
.filt_xf_inB_C1_FILT_11:
    i0 = _filt_hpf_B_C1_FILT_11;   i1 = _filt_state_B_C1_FILT_11;
    call _biquad_mono;
    i0 = _filt_lpf_B_C1_FILT_11;
    call _biquad_mono;
.filt_xf_in_done_C1_FILT_11:
    /* f0 = new output */

    /* ── Blend + advance ── */
    f14 = dm(_filt_xfade_alpha_C1_FILT_11);
    r15 = 0x3F800000;  /* 1.0 IEEE 754 */
    f15 = f15 - f14;
    f13 = f13 * f15;                    /* old × (1−α) */
    f0 = f0 * f14;                      /* new × α */
    f0 = f0 + f13;

    f14 = dm(_filt_xfade_alpha_C1_FILT_11);
    f15 = dm(_filt_xfade_step_C1_FILT_11);
    f14 = f14 + f15;
    dm(_filt_xfade_alpha_C1_FILT_11) = f14;
    r15 = 0x3F800000;  /* 1.0 IEEE 754 */
    comp(f14, f15);
    if ge call _filt_xfade_done_C1_FILT_11;

    dm(_buf_C1_FILT_11) = f0;
    rts;

/* ── Start crossfade ── */
_filt_start_xfade_C1_FILT_11:
    /* Determine dormant instance */
    r4 = dm(_filt_active_C1_FILT_11);
    r4 = pass r4;
    if ne jump .filt_sxf_toA_C1_FILT_11;

    /* Active=A → dormant=B:
     * 1. Copy active HPF/LPF coeffs to B (baseline)
     * 2. Overwrite with any pending _next values
     * 3. Zero state B */
    /* Copy A's HPF → B's HPF */
    i0 = _filt_hpf_A_C1_FILT_11;  i1 = _filt_hpf_B_C1_FILT_11;
    r4 = 5;
    lcntr = r4; do .fc1_C1_FILT_11 until lce;
        r0 = dm(i0, 1); dm(i1, 1) = r0;
    .fc1_C1_FILT_11:
    /* Copy A's LPF → B's LPF */
    i0 = _filt_lpf_A_C1_FILT_11;  i1 = _filt_lpf_B_C1_FILT_11;
    r4 = 5;
    lcntr = r4; do .fc2_C1_FILT_11 until lce;
        r0 = dm(i0, 1); dm(i1, 1) = r0;
    .fc2_C1_FILT_11:
    /* Overwrite pending HPF? */
    r4 = dm(_hpf_swap_pending_C1_FILT_11);
    r4 = pass r4;
    if eq jump .filt_sxf_nohpfB_C1_FILT_11;
    i0 = _hpf_coeffs_next_C1_FILT_11;  i1 = _filt_hpf_B_C1_FILT_11;
    r4 = 5;
    lcntr = r4; do .fc3_C1_FILT_11 until lce;
        r0 = dm(i0, 1); dm(i1, 1) = r0;
    .fc3_C1_FILT_11:
.filt_sxf_nohpfB_C1_FILT_11:
    /* Overwrite pending LPF? */
    r4 = dm(_lpf_swap_pending_C1_FILT_11);
    r4 = pass r4;
    if eq jump .filt_sxf_nolpfB_C1_FILT_11;
    i0 = _lpf_coeffs_next_C1_FILT_11;  i1 = _filt_lpf_B_C1_FILT_11;
    r4 = 5;
    lcntr = r4; do .fc4_C1_FILT_11 until lce;
        r0 = dm(i0, 1); dm(i1, 1) = r0;
    .fc4_C1_FILT_11:
.filt_sxf_nolpfB_C1_FILT_11:
    /* Zero state B */
    i1 = _filt_state_B_C1_FILT_11;
    r0 = 0;
    r4 = 4;
    lcntr = r4; do .fz1_C1_FILT_11 until lce;
        dm(i1, 1) = r0;
    .fz1_C1_FILT_11:
    nop;
    jump .filt_sxf_go_C1_FILT_11;

.filt_sxf_toA_C1_FILT_11:
    /* Active=B → dormant=A: same pattern, copy B→A, overlay _next */
    i0 = _filt_hpf_B_C1_FILT_11;  i1 = _filt_hpf_A_C1_FILT_11;
    r4 = 5;
    lcntr = r4; do .fc5_C1_FILT_11 until lce;
        r0 = dm(i0, 1); dm(i1, 1) = r0;
    .fc5_C1_FILT_11:
    i0 = _filt_lpf_B_C1_FILT_11;  i1 = _filt_lpf_A_C1_FILT_11;
    r4 = 5;
    lcntr = r4; do .fc6_C1_FILT_11 until lce;
        r0 = dm(i0, 1); dm(i1, 1) = r0;
    .fc6_C1_FILT_11:
    r4 = dm(_hpf_swap_pending_C1_FILT_11);
    r4 = pass r4;
    if eq jump .filt_sxf_nohpfA_C1_FILT_11;
    i0 = _hpf_coeffs_next_C1_FILT_11;  i1 = _filt_hpf_A_C1_FILT_11;
    r4 = 5;
    lcntr = r4; do .fc7_C1_FILT_11 until lce;
        r0 = dm(i0, 1); dm(i1, 1) = r0;
    .fc7_C1_FILT_11:
.filt_sxf_nohpfA_C1_FILT_11:
    r4 = dm(_lpf_swap_pending_C1_FILT_11);
    r4 = pass r4;
    if eq jump .filt_sxf_nolpfA_C1_FILT_11;
    i0 = _lpf_coeffs_next_C1_FILT_11;  i1 = _filt_lpf_A_C1_FILT_11;
    r4 = 5;
    lcntr = r4; do .fc8_C1_FILT_11 until lce;
        r0 = dm(i0, 1); dm(i1, 1) = r0;
    .fc8_C1_FILT_11:
.filt_sxf_nolpfA_C1_FILT_11:
    i1 = _filt_state_A_C1_FILT_11;
    r0 = 0;
    r4 = 4;
    lcntr = r4; do .fz2_C1_FILT_11 until lce;
        dm(i1, 1) = r0;
    .fz2_C1_FILT_11:

.filt_sxf_go_C1_FILT_11:
    /* Clear both pending flags */
    r0 = 0;
    dm(_hpf_swap_pending_C1_FILT_11) = r0;
    dm(_lpf_swap_pending_C1_FILT_11) = r0;
    /* Start crossfade */
    dm(_filt_xfade_alpha_C1_FILT_11) = r0;
    f0 = 0.001736111111111111;
    dm(_filt_xfade_step_C1_FILT_11) = f0;
    rts;
_filt_start_xfade_C1_FILT_11.end:

/* ── Crossfade complete ── */
_filt_xfade_done_C1_FILT_11:
    r4 = dm(_filt_active_C1_FILT_11);
    r5 = 1;
    r4 = r4 xor r5;
    dm(_filt_active_C1_FILT_11) = r4;
    r4 = 0;
    dm(_filt_xfade_alpha_C1_FILT_11) = r4;
    dm(_filt_xfade_step_C1_FILT_11) = r4;
    rts;
_filt_xfade_done_C1_FILT_11.end:

_C1_FILT_11_process.end:
