/*----------------------------------------------------------------------
 * Ch 8 Gain (GAIN)
 * Node ID:    C1_GAIN_08
 * Chip:       1
 * Channels:   1
 * SPI Page:   1
 * SPI Addr:   1008
 * RampProfile: GainFast
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/

/* RampProfile: GainFast | Mode: Slew | Up: 3ms (4f) Down: 8ms (12f) | Curve: Exp | Scope: Scalar */

/* GAIN (FIXED Q4.28, D5) — float control, fixed sample path */
/* SPI page=1 addr=1008 */

.section/dm seg_dmda;
.extern _buf_C1_IN_08;
.global _gain_coeff_C1_GAIN_08;
.var _gain_coeff_C1_GAIN_08 = 1.0;            /* FLOAT (ramped) */
.global _gain_target_C1_GAIN_08;
.var _gain_target_C1_GAIN_08 = 1.0;
.global _gain_step_C1_GAIN_08;
.var _gain_step_C1_GAIN_08 = 0.0;
.global _gain_frames_C1_GAIN_08;
.var _gain_frames_C1_GAIN_08 = 0;
.global _gain_q_C1_GAIN_08;
.var _gain_q_C1_GAIN_08 = 0x10000000;          /* Q4.28 shadow */
.global _mute_C1_GAIN_08;
.var _mute_C1_GAIN_08 = 0;
.global _polarity_C1_GAIN_08;
.var _polarity_C1_GAIN_08 = 0;
.global _tap_post_trim_C1_GAIN_08;
.var _tap_post_trim_C1_GAIN_08;
.global _buf_C1_GAIN_08;
.var _buf_C1_GAIN_08;

.section/pm seg_pmco;
.extern _sample_idx;
.extern _mrf_rns28;
.global _C1_GAIN_08_process;
_C1_GAIN_08_process:
    /* block-rate: advance float ramp, refresh Q4.28 shadow */
    r4 = dm(_sample_idx);
    r1 = 0;
    comp(r4, r1);
    if ne jump (pc, .apply_C1_GAIN_08);

    r4 = dm(_gain_frames_C1_GAIN_08);
    r1 = 0;
    comp(r4, r1);
    if le jump (pc, .snap_C1_GAIN_08);
    r4 = r4 - 1;
    dm(_gain_frames_C1_GAIN_08) = r4;
    f1 = dm(_gain_coeff_C1_GAIN_08);
    f2 = dm(_gain_step_C1_GAIN_08);
    f1 = f1 + f2;
    dm(_gain_coeff_C1_GAIN_08) = f1;
    jump (pc, .cvt_C1_GAIN_08);
.snap_C1_GAIN_08:
    f1 = dm(_gain_target_C1_GAIN_08);
    dm(_gain_coeff_C1_GAIN_08) = f1;
.cvt_C1_GAIN_08:
    r2 = 0x4D800000;                      /* 2^28 as float */
    f2 = r2;
    f1 = f1 * f2;
    r1 = fix f1;
    dm(_gain_q_C1_GAIN_08) = r1;

.apply_C1_GAIN_08:
    r0 = dm(_buf_C1_IN_08);
    r1 = dm(_gain_q_C1_GAIN_08);
    mrf = r0 * r1 (ssi);
    call _mrf_rns28;                      /* r0 = sat(rns(x*g,28)) */

    r3 = dm(_polarity_C1_GAIN_08);
    r4 = 0;
    comp(r3, r4);
    if ne r0 = -r0;

    r2 = dm(_mute_C1_GAIN_08);
    comp(r2, r4);
    if ne r0 = r4;

    dm(_tap_post_trim_C1_GAIN_08) = r0;
    dm(_buf_C1_GAIN_08) = r0;
    rts;
_C1_GAIN_08_process.end:
