/*----------------------------------------------------------------------
 * Ch 2 Gain (GAIN)
 * Node ID:    C1_GAIN_02
 * Chip:       1
 * Channels:   1
 * SPI Page:   1
 * SPI Addr:   144
 * RampProfile: GainFast
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/

/* RampProfile: GainFast | Mode: Slew | Up: 3ms (4f) Down: 8ms (12f) | Curve: Exp | Scope: Scalar */

/* GAIN: Per-channel gain / trim
 *
 * Slew ramp: updated once per block (when _sample_idx == 0).
 * Per-sample: apply current coefficient, polarity, mute.
 * Mute clears output to 0.0 (r4=0 = 0x00000000 = 0.0f IEEE 754).
 */
/* SPI page=1 addr=144 */

.section/dm seg_dmda;
.extern _buf_C1_IN_02;
.global _gain_coeff_C1_GAIN_02;
.var _gain_coeff_C1_GAIN_02 = 1.0;
.global _gain_target_C1_GAIN_02;
.var _gain_target_C1_GAIN_02 = 1.0;   /* ramp target */
.global _gain_step_C1_GAIN_02;
.var _gain_step_C1_GAIN_02 = 0.0;      /* per-frame ramp step */
.global _gain_frames_C1_GAIN_02;
.var _gain_frames_C1_GAIN_02 = 0;       /* remaining ramp frames */
.global _mute_C1_GAIN_02;
.var _mute_C1_GAIN_02 = 0;
.global _polarity_C1_GAIN_02;
.var _polarity_C1_GAIN_02 = 0;
.global _tap_post_trim_C1_GAIN_02;
.var _tap_post_trim_C1_GAIN_02;         /* post-trim / pre-EQ tap */
.global _buf_C1_GAIN_02;
.var _buf_C1_GAIN_02;

.section/pm seg_pmco;
.extern _sample_idx;
.global _C1_GAIN_02_process;
_C1_GAIN_02_process:
    /* --- Slew ramp: advance once per block, at sample 0 only --- */
    r4 = dm(_sample_idx);
    r1 = 0;
    comp(r4, r1);
    if ne jump (pc, .apply_C1_GAIN_02);

    r4 = dm(_gain_frames_C1_GAIN_02);
    r1 = 0;
    comp(r4, r1);
    if le jump (pc, .snap_C1_GAIN_02);
    /* Ramp in progress: step coefficient, decrement counter */
    r4 = r4 - 1;
    dm(_gain_frames_C1_GAIN_02) = r4;
    f1 = dm(_gain_coeff_C1_GAIN_02);
    f2 = dm(_gain_step_C1_GAIN_02);
    f1 = f1 + f2;
    dm(_gain_coeff_C1_GAIN_02) = f1;
    jump (pc, .apply_C1_GAIN_02);
.snap_C1_GAIN_02:
    /* Ramp complete or instant: snap to target */
    f1 = dm(_gain_target_C1_GAIN_02);
    dm(_gain_coeff_C1_GAIN_02) = f1;

.apply_C1_GAIN_02:
    r0 = dm(_buf_C1_IN_02);
    f1 = dm(_gain_coeff_C1_GAIN_02);
    f0 = f0 * f1;                          /* apply gain */

    /* Polarity inversion */
    r3 = dm(_polarity_C1_GAIN_02);
    r4 = 0;
    comp(r3, r4);
    if ne f0 = -f0;

    /* Mute: force output to 0.0 */
    r2 = dm(_mute_C1_GAIN_02);
    comp(r2, r4);
    if ne r0 = r4;    /* r4 = 0 = 0x00000000 = 0.0f */

    dm(_tap_post_trim_C1_GAIN_02) = r0;
    dm(_buf_C1_GAIN_02) = r0;
    rts;
_C1_GAIN_02_process.end:
