/*----------------------------------------------------------------------
 * Ch 7 Input (INPUT_TDM)
 * Node ID:    C1_IN_07
 * Chip:       1
 * Channels:   1
 * SPI Page:   -1
 * SPI Addr:   -1
 * RampProfile: (none)
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/

/* RampProfile: Instant (default — no ramp) */

/* INPUT_TDM: Read from SPORT0 TDM slot 6 */

.section/dm seg_dmda;
.global _rx_slot_C1_IN_07;
.var _rx_slot_C1_IN_07;
.global _buf_C1_IN_07;
.var _buf_C1_IN_07;

.section/pm seg_pmco;
.global _C1_IN_07_process;
_C1_IN_07_process:
    r0 = dm(_rx_slot_C1_IN_07);
    dm(_buf_C1_IN_07) = r0;
    rts;
_C1_IN_07_process.end:
