/*----------------------------------------------------------------------
 * Ch 10 Meter (METER)
 * Node ID:    C1_MTR_10
 * Chip:       1
 * Channels:   1
 * SPI Page:   1
 * SPI Addr:   4644
 * RampProfile: (none)
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/
#include "dsp_block.h"

        /* METER: level read-back (DSP writes, host polls) */
        /* SPI page=1 addr=4644 */

        #include "blk_pool.h"

        .section/dm seg_dmda;
        /* ORDER IS LOAD-BEARING: _mtr_fold takes the address of
         * _mtr_peak_C1_MTR_10 and reaches the rest by offset. The three float
         * words keep their names and their SPI dispatch entries. */
        .global _mtr_peak_C1_MTR_10;
        .var _mtr_peak_C1_MTR_10 = 0.0;      /* +0 linear peak, host contract */
        .global _mtr_rms_C1_MTR_10;
        .var _mtr_rms_C1_MTR_10 = 0.0;       /* +1 linear TRUE rms            */
        .global _mtr_gr_C1_MTR_10;
        .var _mtr_gr_C1_MTR_10 = 0.0;        /* +2 gain reduction -- see below */
        .global _mtr_st_C1_MTR_10;
        .var _mtr_st_C1_MTR_10[4];           /* +3 pk_lo pk_hi ms_lo ms_hi     */
        /* The block accumulators. FIVE words, not four: the sum of Q8.24
         * squares is Q16.48 and a block of them overruns 64 bits, so mr2f
         * is state and not a sign extension. Filled by C1_GAIN_10 under block
         * kernels and by this node's own per-sample body otherwise. */
        .global _mtr_acc_C1_MTR_10;
        .var _mtr_acc_C1_MTR_10[5];          /* mx mn ssq_lo ssq_hi ssq_ex     */

        .section/pm seg_pmco;
        .extern _mtr_fold;
        .extern _mtr_load_fold;
        .extern _sample_idx;
        .extern _mtr_wide_C1_GAIN_10;
        .global _C1_MTR_10_process;
        _C1_MTR_10_process:
        #if DSP4_MTR_OFF
            /* measurement only: what the meter costs, by removing it */
            rts;
        #elif DSP4_BLOCK_KERNELS
/* WIDE WORD, 'acc' shape. C1_GAIN_10 accumulated this block's peak,
 * trough and exact sum of squares from the MS word of its own
 * product register, inside its own loop, and left them here.
 * There is no per-sample work in this node at all and nothing
 * rounded was stored anywhere on the way.
 *
 * The load and the fold are ONE SHARED ROUTINE
 * (lib/meter_fx.asm::_mtr_load_fold): eleven instructions in
 * each of 32 meter nodes is 2,112 bytes, and chip 1 has under
 * two thousand left. */
r0 = _mtr_peak_C1_MTR_10;
r1 = _mtr_acc_C1_MTR_10;
call _mtr_load_fold;
rts;

        #else
            /* Per SAMPLE. The block accumulators live in DM because there
             * is no loop to hold them in registers, and the fold fires on
             * the last sample of the block -- so both paths run the SAME
             * arithmetic and the same reference covers both.
             *
             * Source: _mtr_wide_C1_GAIN_10, the Q8.24 word C1_GAIN_10 publishes from its
             * product register before it rounds or saturates. */
            r0 = dm(_mtr_wide_C1_GAIN_10);
            r4 = dm(_sample_idx);
            r1 = 0;
            comp(r4, r1);
            if ne jump (pc, .mtacc_C1_MTR_10);
            /* first sample of the block: seed rather than accumulate */
            dm(_mtr_acc_C1_MTR_10 + 0) = r0;
            dm(_mtr_acc_C1_MTR_10 + 1) = r0;
            mrf = 0;
            mrf = mrf + r0 * r0 (ssi);
            r2 = mr0f;
            dm(_mtr_acc_C1_MTR_10 + 2) = r2;
            r2 = mr1f;
            dm(_mtr_acc_C1_MTR_10 + 3) = r2;
            r2 = mr2f;
            dm(_mtr_acc_C1_MTR_10 + 4) = r2;
            rts;
        .mtacc_C1_MTR_10:
            r2 = dm(_mtr_acc_C1_MTR_10 + 0);
            r2 = max(r2, r0);
            dm(_mtr_acc_C1_MTR_10 + 0) = r2;
            r2 = dm(_mtr_acc_C1_MTR_10 + 1);
            r2 = min(r2, r0);
            dm(_mtr_acc_C1_MTR_10 + 1) = r2;
            r2 = dm(_mtr_acc_C1_MTR_10 + 2);
            mr0f = r2;
            r3 = dm(_mtr_acc_C1_MTR_10 + 3);
            mr1f = r3;
            r2 = dm(_mtr_acc_C1_MTR_10 + 4);
            mr2f = r2;
            mrf = mrf + r0 * r0 (ssi);
            r2 = mr0f;
            dm(_mtr_acc_C1_MTR_10 + 2) = r2;
            r2 = mr1f;
            dm(_mtr_acc_C1_MTR_10 + 3) = r2;
            r2 = mr2f;
            dm(_mtr_acc_C1_MTR_10 + 4) = r2;
            r1 = DSP4_BLOCK_SIZE - 1;
            comp(r4, r1);
            if ne rts;
            r8 = dm(_mtr_acc_C1_MTR_10 + 0);
            r9 = dm(_mtr_acc_C1_MTR_10 + 1);
            r0 = _mtr_peak_C1_MTR_10;
            call _mtr_fold;
            rts;
        #endif
        _C1_MTR_10_process.end:

        /* _mtr_gr_C1_MTR_10 IS STILL NOT WRITTEN, and that is recorded defect
         * 4. It is not a numerics bug: the meter's `taps` parameter names
         * gate_gr and comp_gr but dsp.csv carries no ids for them, so
         * there is nothing to read without inventing a naming convention
         * between MTR_nn and GATE_nn. That belongs in the mx26 contract,
         * not here. The word stays declared and zero. */
