/*----------------------------------------------------------------------
 * Test Measurement (TEST_MEAS)
 * Node ID:    C1_TEST_MEAS
 * Chip:       1
 * Channels:   1
 * SPI Page:   1
 * SPI Addr:   4967
 * RampProfile: InstantCtl
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/
#include "dsp_block.h"
#include "lib/dyn_lut.h"

/* RampProfile: InstantCtl | Mode: Instant | Up: 0ms (0f) Down: 0ms (0f) | Curve: Linear | Scope: Scalar */

/* TEST_MEAS -- self-test RMS / THD+N / noise / crosstalk (S49) */
/* SPI page=1 addr=4967 */

#include "dsp_block.h"

.section/dm seg_dmda;
/* The other ten contract words, declared unconditionally for the
 * same reason the oscillator's six are: the SPI dispatch table
 * names them. The four Result words are READ-ONLY to the host --
 * this node writes them and the host polls. */
.global _meas_chan_C1_TEST_MEAS;
.var _meas_chan_C1_TEST_MEAS   = 0;   /* 1..32, 0 = off */
.global _meas_rms_C1_TEST_MEAS;
.var _meas_rms_C1_TEST_MEAS    = 0.0;   /* ro: total RMS,        dBFS */
.global _meas_thd_C1_TEST_MEAS;
.var _meas_thd_C1_TEST_MEAS    = 0.0;   /* ro: THD+N vs total,   dB   */
.global _meas_noise_C1_TEST_MEAS;
.var _meas_noise_C1_TEST_MEAS  = 0.0;   /* ro: noise+distortion, dBFS */
.global _meas_xsrc_C1_TEST_MEAS;
.var _meas_xsrc_C1_TEST_MEAS   = 0;
.global _meas_xdst_C1_TEST_MEAS;
.var _meas_xdst_C1_TEST_MEAS   = 0;
.global _meas_xtalk_C1_TEST_MEAS;
.var _meas_xtalk_C1_TEST_MEAS  = 0.0;   /* ro: dst vs src,       dB   */
/* THE WINDOW SERIAL, and the one word that makes a host poll safe:
 * a reader that sees the same serial twice is looking at the same
 * window's results twice, and a reader that reads it either side of
 * the four results knows whether what it got was torn. The sweep in
 * TEST_OSC steps on it, and a caller waits for it to advance TWICE
 * after a change -- see the residual note in the section header. */
.global _meas_seq_C1_TEST_MEAS;
.var _meas_seq_C1_TEST_MEAS    = 0;
/* Reserved: the eighth word of the block. Named so the dispatch
 * table has a symbol for it rather than a hole. */
.global _meas_rsvd_C1_TEST_MEAS;
.var _meas_rsvd_C1_TEST_MEAS   = 0;
/* THE CAPTURE ARM (S56). Two words, dispatched without cells until
 * the contract lands CaptureArm / CaptureReady (proposals/
 * CONTRACT-PROPOSAL-S56.md). The host writes CaptureReady = 0, then
 * CaptureArm = N samples; at the next block boundary the tap starts
 * copying MeasChan's post-fader block, whole blocks, contiguous, into
 * _meas_cap_buf_, and when N (or the buffer) is full it publishes the
 * count in CaptureReady and clears CaptureArm. The host then reads
 * the buffer by peek. Declared unconditionally for the same reason
 * as the words above: the dispatch table names them. */
.global _meas_cap_arm_C1_TEST_MEAS;
.var _meas_cap_arm_C1_TEST_MEAS   = 0;   /* rw: samples wanted, 0 = idle */
.global _meas_cap_ready_C1_TEST_MEAS;
.var _meas_cap_ready_C1_TEST_MEAS = 0;   /* ro: samples captured, 0 = none/busy */

#if DSP4_TEST_NODES && DSP4_BLOCK_KERNELS
.global _meas_blk_C1_TEST_MEAS;
.var _meas_blk_C1_TEST_MEAS    = 0;     /* blocks accumulated this window */
.global _meas_axx_C1_TEST_MEAS;
.var _meas_axx_C1_TEST_MEAS    = 0.0;   /* sum x*x  on MeasChan  */
.global _meas_axs_C1_TEST_MEAS;
.var _meas_axs_C1_TEST_MEAS    = 0.0;   /* sum x*s               */
.global _meas_axc_C1_TEST_MEAS;
.var _meas_axc_C1_TEST_MEAS    = 0.0;   /* sum x*c               */
.global _meas_aee_C1_TEST_MEAS;
.var _meas_aee_C1_TEST_MEAS    = 0.0;   /* sum e*e, e = x-a*s-b*c */
.global _meas_ass_C1_TEST_MEAS;
.var _meas_ass_C1_TEST_MEAS    = 0.0;   /* sum s*s  (reference)  */
.global _meas_acc_C1_TEST_MEAS;
.var _meas_acc_C1_TEST_MEAS    = 0.0;   /* sum c*c  (reference)  */
.global _meas_asc_C1_TEST_MEAS;
.var _meas_asc_C1_TEST_MEAS    = 0.0;   /* sum s*c  (reference)  */
.global _meas_asx_C1_TEST_MEAS;
.var _meas_asx_C1_TEST_MEAS    = 0.0;   /* sum x*x  on XtalkSrc  */
.global _meas_adx_C1_TEST_MEAS;
.var _meas_adx_C1_TEST_MEAS    = 0.0;   /* sum x*x  on XtalkDst  */
/* THE PREVIOUS WINDOW'S FIT. Zero until a window has closed, which
 * is exactly why the first window after any change reads ThdResult
 * 0.00 dB. */
.global _meas_a_C1_TEST_MEAS;
.var _meas_a_C1_TEST_MEAS      = 0.0;
.global _meas_b_C1_TEST_MEAS;
.var _meas_b_C1_TEST_MEAS      = 0.0;
.global _meas_cap_idx_C1_TEST_MEAS;
.var _meas_cap_idx_C1_TEST_MEAS  = 0;     /* samples copied this run */
.extern _osc_blk_sc_C1_TEST_OSC;

.section/dm seg_delay;
.global _meas_cap_buf_C1_TEST_MEAS;
.var _meas_cap_buf_C1_TEST_MEAS[DSP4_TEST_CAP_MAX];
#endif

.section/pm seg_pmco;

#if DSP4_TEST_NODES && DSP4_BLOCK_KERNELS
/* ------------------------------------------------------------------
 * _test_meas_tap -- the per-strip measurement hook.
 *
 * The chain calls this immediately after each strip's FADER_PAN
 * kernel -- the post-fader block, the last point in a chip-1 strip
 * that is still one channel -- with r0 = the strip's 1-based number
 * and r1 = the pool slot it has just been left in. The slot is
 * SHARED and the next strip overwrites it, which is why the tap has
 * to be here and not at the end of the chain: the same constraint
 * the meters carry, and for the same reason.
 *
 * Three comparisons and out for a strip nobody named. The Q4.28
 * sample becomes float through FLOAT ... BY -28, one instruction.
 *
 * THE BLOCK SUBTOTALS ARE ACCUMULATED IN REGISTERS AND ADDED TO THE
 * WINDOW ONCE, which is not a cycle optimisation: summing sixteen
 * terms of order 1 into a running total of order 2000 loses about
 * an ulp of 2000 each time, and doing it in two levels takes the
 * accumulated rounding from 4e-6 to 1e-6 of the total -- twelve dB
 * of THD+N floor for no extra instructions. */
.global _test_meas_tap;
    /* THREE INDEPENDENT TESTS, NOT A FIRST-MATCH DISPATCH, and that
     * is a correction: the first shape of this routine jumped to
     * the first accumulator whose cell named the strip, so a strip
     * named as BOTH MeasChan and XtalkSrc fed only the measurement
     * and `sum x*x on XtalkSrc` stayed at zero. XtalkResult then
     * published 10*log10(Sdd/floor) -- a large POSITIVE number,
     * +220.03 dB, measured on the part 2026-09-15 -- or, with the
     * roles reversed, -317 dB. Neither is a crosstalk figure and
     * both look like one. The cells are independent selectors and
     * the routine now treats them that way; naming one strip in
     * two of them is a NORMAL arrangement (measure the source while
     * watching a neighbour) and not a misuse.
     *
     * r4 holds the strip and r5 the slot across all three, because
     * the accumulation loops clobber r0-r3. */
_test_meas_tap:
    r4 = r0;
    r5 = r1;
    r2 = dm(_meas_xsrc_C1_TEST_MEAS);
    comp(r4, r2);
    if ne jump (pc, .tmt_no_xsrc_C1_TEST_MEAS);
    i4 = r5;
    l4 = 0;
    r3 = -28;
    r6 = 0x00000000;   /* 0.0 */
    lcntr = DSP4_BLOCK_SIZE, do .tmt_xsrc_lp_C1_TEST_MEAS until lce;
        r0 = dm(i4, 1);
        f0 = float r0 by r3;
        f1 = f0 * f0;
.tmt_xsrc_lp_C1_TEST_MEAS:
        f6 = f6 + f1;
    f2 = dm(_meas_asx_C1_TEST_MEAS);
    f2 = f2 + f6;
    dm(_meas_asx_C1_TEST_MEAS) = f2;
.tmt_no_xsrc_C1_TEST_MEAS:
    r2 = dm(_meas_xdst_C1_TEST_MEAS);
    comp(r4, r2);
    if ne jump (pc, .tmt_no_xdst_C1_TEST_MEAS);
    i4 = r5;
    l4 = 0;
    r3 = -28;
    r6 = 0x00000000;   /* 0.0 */
    lcntr = DSP4_BLOCK_SIZE, do .tmt_xdst_lp_C1_TEST_MEAS until lce;
        r0 = dm(i4, 1);
        f0 = float r0 by r3;
        f1 = f0 * f0;
.tmt_xdst_lp_C1_TEST_MEAS:
        f6 = f6 + f1;
    f2 = dm(_meas_adx_C1_TEST_MEAS);
    f2 = f2 + f6;
    dm(_meas_adx_C1_TEST_MEAS) = f2;
.tmt_no_xdst_C1_TEST_MEAS:
    r2 = dm(_meas_chan_C1_TEST_MEAS);
    comp(r4, r2);
    if ne rts;

    /* ---- THE CAPTURE ARM (S56). Idle it is one load and a branch,
     * and only on the ONE strip MeasChan names. Armed it is a
     * block-length store loop. No other chip, no interrupt, no
     * change to what the block does: the samples are the pool slot
     * the measurement below reads, copied before it reads them. */
    r2 = dm(_meas_cap_arm_C1_TEST_MEAS);
    r2 = pass r2;
    if eq jump (pc, .tmt_nocap_C1_TEST_MEAS);
    r6 = dm(_meas_cap_idx_C1_TEST_MEAS);
    r6 = pass r6;
    if ne jump (pc, .tmt_cap_go_C1_TEST_MEAS);
    dm(_meas_cap_ready_C1_TEST_MEAS) = r6;   /* a new run: Ready = 0 */
.tmt_cap_go_C1_TEST_MEAS:
    i4 = r5;
    l4 = 0;
    r7 = _meas_cap_buf_C1_TEST_MEAS;
    r7 = r7 + r6;
    i5 = r7;
    l5 = 0;
    lcntr = DSP4_BLOCK_SIZE, do .tmt_cap_lp_C1_TEST_MEAS until lce;
        r0 = dm(i4, 1);
.tmt_cap_lp_C1_TEST_MEAS:
        dm(i5, 1) = r0;
    r7 = DSP4_BLOCK_SIZE;
    r6 = r6 + r7;
    /* Done at N, and done at the buffer whatever N says. The buffer
     * is a whole number of blocks, so a copy never starts past it. */
    comp(r6, r2);
    if ge jump (pc, .tmt_cap_done_C1_TEST_MEAS);
    r7 = DSP4_TEST_CAP_MAX;
    comp(r6, r7);
    if ge jump (pc, .tmt_cap_done_C1_TEST_MEAS);
    dm(_meas_cap_idx_C1_TEST_MEAS) = r6;
    jump (pc, .tmt_nocap_C1_TEST_MEAS);
.tmt_cap_done_C1_TEST_MEAS:
    dm(_meas_cap_ready_C1_TEST_MEAS) = r6;
    r6 = 0;
    dm(_meas_cap_idx_C1_TEST_MEAS) = r6;
    dm(_meas_cap_arm_C1_TEST_MEAS) = r6;
.tmt_nocap_C1_TEST_MEAS:
    r1 = r5;
    i4 = r1;
    l4 = 0;
    i5 = _osc_blk_sc_C1_TEST_OSC;
    l5 = 0;
    r3 = -28;
    f8 = dm(_meas_a_C1_TEST_MEAS);   /* the PREVIOUS window's fit */
    f9 = dm(_meas_b_C1_TEST_MEAS);
    r4 = 0x00000000;   /* 0.0   sum x*x  this block */
    r5 = 0x00000000;   /* 0.0   sum x*s */
    r6 = 0x00000000;   /* 0.0   sum x*c */
    r7 = 0x00000000;   /* 0.0   sum e*e */
    lcntr = DSP4_BLOCK_SIZE, do .tmt_meas_lp_C1_TEST_MEAS until lce;
        r0 = dm(i4, 1);
        f0 = float r0 by r3;        /* x, Q4.28 -> float */
        f1 = dm(i5, 1);             /* s[n] */
        f2 = dm(i5, 1);             /* c[n] */
        f10 = f0 * f0;
        f4 = f4 + f10;
        f10 = f0 * f1;
        f5 = f5 + f10;
        f10 = f0 * f2;
        f6 = f6 + f10;
        f10 = f8 * f1;              /* a*s */
        f11 = f9 * f2;              /* b*c */
        f10 = f10 + f11;
        f10 = f0 - f10;             /* e   */
        f10 = f10 * f10;
.tmt_meas_lp_C1_TEST_MEAS:
        f7 = f7 + f10;
    f0 = dm(_meas_axx_C1_TEST_MEAS);
    f0 = f0 + f4;
    dm(_meas_axx_C1_TEST_MEAS) = f0;
    f0 = dm(_meas_axs_C1_TEST_MEAS);
    f0 = f0 + f5;
    dm(_meas_axs_C1_TEST_MEAS) = f0;
    f0 = dm(_meas_axc_C1_TEST_MEAS);
    f0 = f0 + f6;
    dm(_meas_axc_C1_TEST_MEAS) = f0;
    f0 = dm(_meas_aee_C1_TEST_MEAS);
    f0 = f0 + f7;
    dm(_meas_aee_C1_TEST_MEAS) = f0;
    rts;
_test_meas_tap.end:
#endif

.global _C1_TEST_MEAS_process;
_C1_TEST_MEAS_process:
#if DSP4_TEST_NODES && DSP4_BLOCK_KERNELS
    /* Idle unless the host has named a channel somewhere. Three
     * loads, two ORs and a branch: this runs on every block of every
     * image carrying the flag, whether or not anything is armed. */
    r0 = dm(_meas_chan_C1_TEST_MEAS);
    r1 = dm(_meas_xsrc_C1_TEST_MEAS);
    r0 = r0 or r1;
    r1 = dm(_meas_xdst_C1_TEST_MEAS);
    r0 = r0 or r1;
    r0 = pass r0;
    if eq rts;

    /* ---- the REFERENCE self-sums, over the same block the strips
     * were just given. The chain calls this node AFTER every strip
     * and BEFORE the oscillator regenerates, so _osc_blk_sc_ still
     * holds exactly the waveform that was injected on this pass.
     * That ordering is the whole reason the two test nodes sit where
     * they do in dsp.csv, and it is why the measurement needs no
     * delay compensation at all. */
    i4 = _osc_blk_sc_C1_TEST_OSC;
    l4 = 0;
    r4 = 0x00000000;   /* 0.0 */
    r5 = 0x00000000;   /* 0.0 */
    r6 = 0x00000000;   /* 0.0 */
    lcntr = DSP4_BLOCK_SIZE, do .tm_ref_lp_C1_TEST_MEAS until lce;
        f0 = dm(i4, 1);             /* s */
        f1 = dm(i4, 1);             /* c */
        f2 = f0 * f0;
        f4 = f4 + f2;
        f2 = f1 * f1;
        f5 = f5 + f2;
        f2 = f0 * f1;
.tm_ref_lp_C1_TEST_MEAS:
        f6 = f6 + f2;
    f0 = dm(_meas_ass_C1_TEST_MEAS);
    f0 = f0 + f4;
    dm(_meas_ass_C1_TEST_MEAS) = f0;
    f0 = dm(_meas_acc_C1_TEST_MEAS);
    f0 = f0 + f5;
    dm(_meas_acc_C1_TEST_MEAS) = f0;
    f0 = dm(_meas_asc_C1_TEST_MEAS);
    f0 = f0 + f6;
    dm(_meas_asc_C1_TEST_MEAS) = f0;

    r0 = dm(_meas_blk_C1_TEST_MEAS);
    r0 = r0 + 1;
    dm(_meas_blk_C1_TEST_MEAS) = r0;
    r1 = DSP4_TEST_WIN_BLOCKS;
    comp(r0, r1);
    if lt rts;

    /* ================== THE WINDOW CLOSES ======================= */
    /* Once every DSP4_TEST_WIN_BLOCKS blocks, so everything from
     * here down is written for clarity and not for cycles. */
    r0 = 0;
    dm(_meas_blk_C1_TEST_MEAS) = r0;

    f8  = dm(_meas_axx_C1_TEST_MEAS);
    f14 = dm(_meas_aee_C1_TEST_MEAS);

    /* ---- publish. Every result is a RATIO OF ENERGIES in dB, so
     * each is a difference of two log2s scaled by 10*log10(2). No
     * division is needed anywhere for the results and none is done;
     * the single reciprocal below belongs to the FIT. */
    /* Floor both arguments first. A residual that has gone very
     * slightly negative on rounding is a PERFECT fit, not an error,
     * and it lands on the floor exactly as it should. */
    r7 = 0x0DA24260;   /* the energy floor, about -300 dB */
    comp(f14, f7);
    if lt f14 = pass f7;
    comp(f8, f7);
    if lt f8 = pass f7;
    /* ---- log2(Sxx) -> f15 ---- */
    r4 = logb f8;   /* exponent, as an INTEGER: LOGB writes Rn */
    r5 = -r4;
    f0 = scalb f8 by r5;   /* mantissa, [1,2) */
    r1 = 0x3F800000;   /* 1.0 */
    f2 = f0 - f1;   /* m-1 */
    f3 = f0 + f1;   /* m+1 */
    f3 = recips f3;
    f5 = f0 + f1;
    f5 = f5 * f3;
    f5 = f1 - f5;
    f5 = f3 * f5;
    f3 = f3 + f5;   /* Newton on 1/(m+1) */
    f5 = f0 + f1;
    f5 = f5 * f3;
    f5 = f1 - f5;
    f5 = f3 * f5;
    f3 = f3 + f5;   /* Newton on 1/(m+1) */
    f0 = f2 * f3;   /* u */
    f1 = f0 * f0;   /* u^2 */
    r2 = 0x3DE38E39;   /* 1/9 */
    f2 = f2 * f1;
    r3 = 0x3E124925;   /* 1/7 */
    f2 = f2 + f3;
    f2 = f2 * f1;
    r3 = 0x3E4CCCCD;   /* 1/5 */
    f2 = f2 + f3;
    f2 = f2 * f1;
    r3 = 0x3EAAAAAB;   /* 1/3 */
    f2 = f2 + f3;
    f2 = f2 * f1;
    r3 = 0x3F800000;   /* 1.0 */
    f2 = f2 + f3;
    f0 = f0 * f2;
    r1 = 0x4038AA3B;   /* 2/ln2 */
    f0 = f0 * f1;   /* log2(m) */
    f5 = float r4;
    f15 = f0 + f5;   /* + the exponent */
    /* ---- log2(See) -> f13 ---- */
    r4 = logb f14;   /* exponent, as an INTEGER: LOGB writes Rn */
    r5 = -r4;
    f0 = scalb f14 by r5;   /* mantissa, [1,2) */
    r1 = 0x3F800000;   /* 1.0 */
    f2 = f0 - f1;   /* m-1 */
    f3 = f0 + f1;   /* m+1 */
    f3 = recips f3;
    f5 = f0 + f1;
    f5 = f5 * f3;
    f5 = f1 - f5;
    f5 = f3 * f5;
    f3 = f3 + f5;   /* Newton on 1/(m+1) */
    f5 = f0 + f1;
    f5 = f5 * f3;
    f5 = f1 - f5;
    f5 = f3 * f5;
    f3 = f3 + f5;   /* Newton on 1/(m+1) */
    f0 = f2 * f3;   /* u */
    f1 = f0 * f0;   /* u^2 */
    r2 = 0x3DE38E39;   /* 1/9 */
    f2 = f2 * f1;
    r3 = 0x3E124925;   /* 1/7 */
    f2 = f2 + f3;
    f2 = f2 * f1;
    r3 = 0x3E4CCCCD;   /* 1/5 */
    f2 = f2 + f3;
    f2 = f2 * f1;
    r3 = 0x3EAAAAAB;   /* 1/3 */
    f2 = f2 + f3;
    f2 = f2 * f1;
    r3 = 0x3F800000;   /* 1.0 */
    f2 = f2 + f3;
    f0 = f0 * f2;
    r1 = 0x4038AA3B;   /* 2/ln2 */
    f0 = f0 * f1;   /* log2(m) */
    f5 = float r4;
    f13 = f0 + f5;   /* + the exponent */
    r9 = 0x4040A8C1;   /* 10*log10(2) */
    r10 = 0x41400000;   /* log2(N), N = 4096 samples */
    /* RmsResult = 10log10(Sxx/N) */
    f0 = f15 - f10;
    f0 = f0 * f9;
    dm(_meas_rms_C1_TEST_MEAS) = f0;
    /* NoiseResult = 10log10(See/N) */
    f0 = f13 - f10;
    f0 = f0 * f9;
    dm(_meas_noise_C1_TEST_MEAS) = f0;
    /* ThdResult = 10log10(See/Sxx) */
    f0 = f13 - f15;
    f0 = f0 * f9;
    dm(_meas_thd_C1_TEST_MEAS) = f0;

    /* ---- crosstalk: XtalkDst against XtalkSrc, same machinery */
    f8  = dm(_meas_adx_C1_TEST_MEAS);
    f14 = dm(_meas_asx_C1_TEST_MEAS);
    r7 = 0x0DA24260;   /* the energy floor */
    comp(f8, f7);
    if lt f8 = pass f7;
    comp(f14, f7);
    if lt f14 = pass f7;
    /* ---- log2(Sdd) -> f15 ---- */
    r4 = logb f8;   /* exponent, as an INTEGER: LOGB writes Rn */
    r5 = -r4;
    f0 = scalb f8 by r5;   /* mantissa, [1,2) */
    r1 = 0x3F800000;   /* 1.0 */
    f2 = f0 - f1;   /* m-1 */
    f3 = f0 + f1;   /* m+1 */
    f3 = recips f3;
    f5 = f0 + f1;
    f5 = f5 * f3;
    f5 = f1 - f5;
    f5 = f3 * f5;
    f3 = f3 + f5;   /* Newton on 1/(m+1) */
    f5 = f0 + f1;
    f5 = f5 * f3;
    f5 = f1 - f5;
    f5 = f3 * f5;
    f3 = f3 + f5;   /* Newton on 1/(m+1) */
    f0 = f2 * f3;   /* u */
    f1 = f0 * f0;   /* u^2 */
    r2 = 0x3DE38E39;   /* 1/9 */
    f2 = f2 * f1;
    r3 = 0x3E124925;   /* 1/7 */
    f2 = f2 + f3;
    f2 = f2 * f1;
    r3 = 0x3E4CCCCD;   /* 1/5 */
    f2 = f2 + f3;
    f2 = f2 * f1;
    r3 = 0x3EAAAAAB;   /* 1/3 */
    f2 = f2 + f3;
    f2 = f2 * f1;
    r3 = 0x3F800000;   /* 1.0 */
    f2 = f2 + f3;
    f0 = f0 * f2;
    r1 = 0x4038AA3B;   /* 2/ln2 */
    f0 = f0 * f1;   /* log2(m) */
    f5 = float r4;
    f15 = f0 + f5;   /* + the exponent */
    /* ---- log2(Ssrc) -> f13 ---- */
    r4 = logb f14;   /* exponent, as an INTEGER: LOGB writes Rn */
    r5 = -r4;
    f0 = scalb f14 by r5;   /* mantissa, [1,2) */
    r1 = 0x3F800000;   /* 1.0 */
    f2 = f0 - f1;   /* m-1 */
    f3 = f0 + f1;   /* m+1 */
    f3 = recips f3;
    f5 = f0 + f1;
    f5 = f5 * f3;
    f5 = f1 - f5;
    f5 = f3 * f5;
    f3 = f3 + f5;   /* Newton on 1/(m+1) */
    f5 = f0 + f1;
    f5 = f5 * f3;
    f5 = f1 - f5;
    f5 = f3 * f5;
    f3 = f3 + f5;   /* Newton on 1/(m+1) */
    f0 = f2 * f3;   /* u */
    f1 = f0 * f0;   /* u^2 */
    r2 = 0x3DE38E39;   /* 1/9 */
    f2 = f2 * f1;
    r3 = 0x3E124925;   /* 1/7 */
    f2 = f2 + f3;
    f2 = f2 * f1;
    r3 = 0x3E4CCCCD;   /* 1/5 */
    f2 = f2 + f3;
    f2 = f2 * f1;
    r3 = 0x3EAAAAAB;   /* 1/3 */
    f2 = f2 + f3;
    f2 = f2 * f1;
    r3 = 0x3F800000;   /* 1.0 */
    f2 = f2 + f3;
    f0 = f0 * f2;
    r1 = 0x4038AA3B;   /* 2/ln2 */
    f0 = f0 * f1;   /* log2(m) */
    f5 = float r4;
    f13 = f0 + f5;   /* + the exponent */
    r9 = 0x4040A8C1;   /* 10*log10(2) */
    f0 = f15 - f13;
    f0 = f0 * f9;
    dm(_meas_xtalk_C1_TEST_MEAS) = f0;

    /* ---- THE FIT, for the NEXT window to subtract sample by
     * sample. Solve [Sss Ssc; Ssc Scc][a;b] = [Sxs;Sxc]. */
    f8  = dm(_meas_axs_C1_TEST_MEAS);
    f9  = dm(_meas_axc_C1_TEST_MEAS);
    f10 = dm(_meas_ass_C1_TEST_MEAS);
    f11 = dm(_meas_acc_C1_TEST_MEAS);
    f12 = dm(_meas_asc_C1_TEST_MEAS);
    f6 = f10 * f11;
    f7 = f12 * f12;
    f6 = f6 - f7;                   /* det */
    /* A SINGULAR 2x2 IS A DEFINITION AND NOT A GUARD: with the
     * oscillator off the reference is silent, nothing can be
     * identified as a sinusoid, and a = b = 0 makes e[n] = x[n]. So
     * NoiseResult == RmsResult == the channel's own noise floor and
     * ThdResult reads 0.00 dB, which is the honest answer. */
    r13 = 0x00000000;   /* 0.0 */
    r7 = 0x0DA24260;   /* the energy floor */
    comp(f6, f7);
    if le jump (pc, .tm_nofit_C1_TEST_MEAS);
    /* 1/det by RECIPS plus two Newton steps -- the shape
     * _fx_recip_asm() emits everywhere else in this file. */
    f2 = recips f6;
    r3 = 0x40000000;   /* 2.0 */
    f4 = f6 * f2;
    f4 = f3 - f4;
    f2 = f2 * f4;
    f4 = f6 * f2;
    f4 = f3 - f4;
    f2 = f2 * f4;
    /* a = (Sxs*Scc - Sxc*Ssc)/det ; b = (Sxc*Sss - Sxs*Ssc)/det */
    f0 = f8 * f11;
    f1 = f9 * f12;
    f0 = f0 - f1;
    f0 = f0 * f2;
    f1 = f9 * f10;
    f4 = f8 * f12;
    f1 = f1 - f4;
    f1 = f1 * f2;
    /* The same backstop the oscillator carries, and for the same
     * reason: a or b poisons EVERY later window through the
     * per-sample residual, so a value that is not a number, or is
     * absurdly large for a fit to a unit-amplitude reference, is
     * replaced by zero -- which makes the next window read
     * ThdResult 0.00 dB and say so, rather than NaN. */
    comp(f0, f0);
    if ne jump (pc, .tm_nofit_C1_TEST_MEAS);
    comp(f1, f1);
    if ne jump (pc, .tm_nofit_C1_TEST_MEAS);
    f4 = abs f0;
    r5 = 0x44800000;   /* 1024.0 */
    comp(f4, f5);
    if gt jump (pc, .tm_nofit_C1_TEST_MEAS);
    f4 = abs f1;
    comp(f4, f5);
    if gt jump (pc, .tm_nofit_C1_TEST_MEAS);
    dm(_meas_a_C1_TEST_MEAS) = f0;
    dm(_meas_b_C1_TEST_MEAS) = f1;
    jump (pc, .tm_zero_C1_TEST_MEAS);
.tm_nofit_C1_TEST_MEAS:
    dm(_meas_a_C1_TEST_MEAS) = f13;
    dm(_meas_b_C1_TEST_MEAS) = f13;

.tm_zero_C1_TEST_MEAS:
    /* ---- zero the accumulators, and publish the serial LAST so a
     * host that reads serial, results, serial can prove it saw one
     * window and not the seam between two. */
    r0 = 0x00000000;   /* 0.0 */
    dm(_meas_axx_C1_TEST_MEAS) = f0;
    dm(_meas_axs_C1_TEST_MEAS) = f0;
    dm(_meas_axc_C1_TEST_MEAS) = f0;
    dm(_meas_aee_C1_TEST_MEAS) = f0;
    dm(_meas_ass_C1_TEST_MEAS) = f0;
    dm(_meas_acc_C1_TEST_MEAS) = f0;
    dm(_meas_asc_C1_TEST_MEAS) = f0;
    dm(_meas_asx_C1_TEST_MEAS) = f0;
    dm(_meas_adx_C1_TEST_MEAS) = f0;
    r0 = dm(_meas_seq_C1_TEST_MEAS);
    r0 = r0 + 1;
    dm(_meas_seq_C1_TEST_MEAS) = r0;
#endif
    rts;
_C1_TEST_MEAS_process.end:
