/*----------------------------------------------------------------------
 * XFER_SNAKE_08 Send (INTERCHIP_SEND)
 * Node ID:    C1_XS_XFER_SNAKE_08
 * Chip:       1
 * Channels:   1
 * SPI Page:   -1
 * SPI Addr:   -1
 * RampProfile: (none)
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/
#include "dsp_block.h"

/* INTERCHIP_SEND: mix-fabric line 2 slot 4 (global slot 36, signal XFER_SNAKE_08) */

#include "blk_pool.h"

.section/dm seg_dmda;
.extern _buf_C1_XIN_SNK_08;
#if DSP4_BLOCK_KERNELS
.global _tx_slot_C1_XS_XFER_SNAKE_08;
.var _tx_slot_C1_XS_XFER_SNAKE_08[DSP4_BLOCK_SIZE];
#else
.global _tx_slot_C1_XS_XFER_SNAKE_08;
.var _tx_slot_C1_XS_XFER_SNAKE_08;
#endif

.section/pm seg_pmco;
.global _C1_XS_XFER_SNAKE_08_process;
_C1_XS_XFER_SNAKE_08_process:
#if DSP4_BLOCK_KERNELS
    l2 = 0;
    l3 = 0;
    i2 = _buf_C1_XIN_SNK_08;
    i3 = _tx_slot_C1_XS_XFER_SNAKE_08;
    lcntr = DSP4_BLOCK_SIZE, do .isk_C1_XS_XFER_SNAKE_08 until lce;
        r0 = dm(i2, 1);
    .isk_C1_XS_XFER_SNAKE_08: dm(i3, 1) = r0;
    rts;
#else
    r0 = dm(_buf_C1_XIN_SNK_08);
    dm(_tx_slot_C1_XS_XFER_SNAKE_08) = r0;
    rts;
#endif
_C1_XS_XFER_SNAKE_08_process.end:
