/*----------------------------------------------------------------------
 * XFER_SNAKE_07 Send (INTERCHIP_SEND)
 * Node ID:    C1_XS_XFER_SNAKE_07
 * Chip:       1
 * Channels:   1
 * SPI Page:   -1
 * SPI Addr:   -1
 * RampProfile: (none)
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/

/* INTERCHIP_SEND: mix-fabric line 2 slot 3 (global slot 35, signal XFER_SNAKE_07) */

#include "blk_pool.h"

.section/dm seg_dmda;
.extern _buf_C1_XIN_SNK_07;
#if DSP4_BLOCK_KERNELS
.global _tx_slot_C1_XS_XFER_SNAKE_07;
.var _tx_slot_C1_XS_XFER_SNAKE_07[32];
#else
.global _tx_slot_C1_XS_XFER_SNAKE_07;
.var _tx_slot_C1_XS_XFER_SNAKE_07;
#endif

.section/pm seg_pmco;
.global _C1_XS_XFER_SNAKE_07_process;
_C1_XS_XFER_SNAKE_07_process:
#if DSP4_BLOCK_KERNELS
    l2 = 0;
    l3 = 0;
    i2 = _buf_C1_XIN_SNK_07;
    i3 = _tx_slot_C1_XS_XFER_SNAKE_07;
    lcntr = 32, do .isk_C1_XS_XFER_SNAKE_07 until lce;
        r0 = dm(i2, 1);
    .isk_C1_XS_XFER_SNAKE_07: dm(i3, 1) = r0;
    rts;
#else
    r0 = dm(_buf_C1_XIN_SNK_07);
    dm(_tx_slot_C1_XS_XFER_SNAKE_07) = r0;
    rts;
#endif
_C1_XS_XFER_SNAKE_07_process.end:
