/*----------------------------------------------------------------------
 * XFER_SNAKE_05 Send (INTERCHIP_SEND)
 * Node ID:    C1_XS_XFER_SNAKE_05
 * Chip:       1
 * Channels:   1
 * SPI Page:   -1
 * SPI Addr:   -1
 * RampProfile: (none)
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/
#include "dsp_block.h"

/* INTERCHIP_SEND: mix-fabric line 2 slot 1 (global slot 33, signal XFER_SNAKE_05) */

#include "blk_pool.h"

.section/dm seg_dmda;
.extern _buf_C1_XIN_SNK_05;
#if DSP4_BLOCK_KERNELS
.global _tx_slot_C1_XS_XFER_SNAKE_05;
.var _tx_slot_C1_XS_XFER_SNAKE_05[DSP4_BLOCK_SIZE];
#else
.global _tx_slot_C1_XS_XFER_SNAKE_05;
.var _tx_slot_C1_XS_XFER_SNAKE_05;
#endif

.section/pm seg_pmco;
.global _C1_XS_XFER_SNAKE_05_process;
_C1_XS_XFER_SNAKE_05_process:
#if DSP4_BLOCK_KERNELS
    /* NOTHING TO DO (review finding D25). This body used to copy the
     * source bus block into _tx_slot_C1_XS_XFER_SNAKE_05 so that
     * _gather_chip1 had a named array to read. The gather walks a
     * pointer table, and gen_block_io now points that table straight
     * at _buf_C1_XIN_SNK_05, so the copy was moving a block to
     * hand the same block over. The slot array above is kept
     * declared -- it is the per-sample build's target and it costs a
     * block-kernel image nothing but DM it no longer touches.
     *
     * The node is NOT removed from the chain: DSP4_NODE_LIMIT counts
     * chain positions, and taking one out would silently renumber
     * every profile point ever recorded against this graph. */
    rts;
#else
    r0 = dm(_buf_C1_XIN_SNK_05);
    dm(_tx_slot_C1_XS_XFER_SNAKE_05) = r0;
    rts;
#endif
_C1_XS_XFER_SNAKE_05_process.end:
