/*======================================================================
 * bus_accumulators.asm — Shared bus accumulator variables for Chip 1
 *
 * Each channel ROUTING node accumulates (scatter) into these accumulators.
 * At frame start, _bus_clear_all zeros them all.
 * MIX_BUS nodes then read the final accumulated values.
 *
 * Bus topology (D32):
 *   Main L, Main R, Sub, Grp ×4, Aux ×12, FX Send ×6 = 25 buses
 *
 * AUTO-GENERATED by dsp_codegen.py (D32) — infrastructure.
 *======================================================================*/

.section/dm seg_dmda;

/* --- Individual bus accumulators --- */
.global _bus_acc_main_l;   .var _bus_acc_main_l = 0.0;
.global _bus_acc_main_r;   .var _bus_acc_main_r = 0.0;
.global _bus_acc_sub;      .var _bus_acc_sub = 0.0;

.global _bus_acc_grp_01;   .var _bus_acc_grp_01 = 0.0;
.global _bus_acc_grp_02;   .var _bus_acc_grp_02 = 0.0;
.global _bus_acc_grp_03;   .var _bus_acc_grp_03 = 0.0;
.global _bus_acc_grp_04;   .var _bus_acc_grp_04 = 0.0;

.global _bus_acc_aux_01;   .var _bus_acc_aux_01 = 0.0;
.global _bus_acc_aux_02;   .var _bus_acc_aux_02 = 0.0;
.global _bus_acc_aux_03;   .var _bus_acc_aux_03 = 0.0;
.global _bus_acc_aux_04;   .var _bus_acc_aux_04 = 0.0;
.global _bus_acc_aux_05;   .var _bus_acc_aux_05 = 0.0;
.global _bus_acc_aux_06;   .var _bus_acc_aux_06 = 0.0;
.global _bus_acc_aux_07;   .var _bus_acc_aux_07 = 0.0;
.global _bus_acc_aux_08;   .var _bus_acc_aux_08 = 0.0;
.global _bus_acc_aux_09;   .var _bus_acc_aux_09 = 0.0;
.global _bus_acc_aux_10;   .var _bus_acc_aux_10 = 0.0;
.global _bus_acc_aux_11;   .var _bus_acc_aux_11 = 0.0;
.global _bus_acc_aux_12;   .var _bus_acc_aux_12 = 0.0;

.global _bus_acc_fx_01;    .var _bus_acc_fx_01 = 0.0;
.global _bus_acc_fx_02;    .var _bus_acc_fx_02 = 0.0;
.global _bus_acc_fx_03;    .var _bus_acc_fx_03 = 0.0;
.global _bus_acc_fx_04;    .var _bus_acc_fx_04 = 0.0;
.global _bus_acc_fx_05;    .var _bus_acc_fx_05 = 0.0;
.global _bus_acc_fx_06;    .var _bus_acc_fx_06 = 0.0;

/* --- Pointer arrays for looped access from ROUTING nodes --- */
.global _bus_acc_grp_ptrs;
.var _bus_acc_grp_ptrs[4] = _bus_acc_grp_01, _bus_acc_grp_02, _bus_acc_grp_03, _bus_acc_grp_04;

.global _bus_acc_aux_ptrs;
.var _bus_acc_aux_ptrs[12] = _bus_acc_aux_01, _bus_acc_aux_02, _bus_acc_aux_03,
                             _bus_acc_aux_04, _bus_acc_aux_05, _bus_acc_aux_06,
                             _bus_acc_aux_07, _bus_acc_aux_08, _bus_acc_aux_09,
                             _bus_acc_aux_10, _bus_acc_aux_11, _bus_acc_aux_12;

.global _bus_acc_fx_ptrs;
.var _bus_acc_fx_ptrs[6] = _bus_acc_fx_01, _bus_acc_fx_02, _bus_acc_fx_03,
                           _bus_acc_fx_04, _bus_acc_fx_05, _bus_acc_fx_06;


/* --- Clear all accumulators (called at frame start before processing) --- */
.section/pm seg_pmco;
.global _bus_clear_all;
_bus_clear_all:
    f0 = 0.0;
    dm(_bus_acc_main_l) = f0;
    dm(_bus_acc_main_r) = f0;
    dm(_bus_acc_sub) = f0;
    dm(_bus_acc_grp_01) = f0;
    dm(_bus_acc_grp_02) = f0;
    dm(_bus_acc_grp_03) = f0;
    dm(_bus_acc_grp_04) = f0;
    dm(_bus_acc_aux_01) = f0;
    dm(_bus_acc_aux_02) = f0;
    dm(_bus_acc_aux_03) = f0;
    dm(_bus_acc_aux_04) = f0;
    dm(_bus_acc_aux_05) = f0;
    dm(_bus_acc_aux_06) = f0;
    dm(_bus_acc_aux_07) = f0;
    dm(_bus_acc_aux_08) = f0;
    dm(_bus_acc_aux_09) = f0;
    dm(_bus_acc_aux_10) = f0;
    dm(_bus_acc_aux_11) = f0;
    dm(_bus_acc_aux_12) = f0;
    dm(_bus_acc_fx_01) = f0;
    dm(_bus_acc_fx_02) = f0;
    dm(_bus_acc_fx_03) = f0;
    dm(_bus_acc_fx_04) = f0;
    dm(_bus_acc_fx_05) = f0;
    dm(_bus_acc_fx_06) = f0;
    rts;
_bus_clear_all.end:
