/* dsp_block.h — audio block size (samples per DMA block) */
/* AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly. */
/*
 * BLOCK SIZE IS A BUILD PARAMETER. Change it in dsp_codegen.py (BLOCK)
 * and regenerate; every loop count, slot array, DMA ring, ramp step and
 * verdict rate in the tree follows from these macros.
 *
 * 2026-08-28 (PW ruling): the working operating point is 8.
 * Predicted digital latency ~23 samples = 0.48 ms at 48 kHz, from the
 * 93-samples-at-BLOCK-32 pipeline measured on the part. Any figure in
 * the ledger or the options paper that predates this header is a
 * BLOCK-32 figure and is labelled as one.
 *
 * DSP4_BLOCK_SIZE   samples per block
 * DSP4_BLOCK_HALF   for the two-samples-per-iteration fused kernels
 * DSP4_BLOCK_SHIFT  log2(BLOCK): block-rate frames -> samples
 * DSP4_BLOCK_F32    BLOCK as an IEEE-754 single, for per-block ramp steps
 * DSP4_BLOCK_RATE   blocks per second at 48 kHz -- the verdict rate
 */
#ifndef DSP4_BLOCK_H
#define DSP4_BLOCK_H

#define DSP4_BLOCK_SIZE   8
#define DSP4_BLOCK_HALF   4
#define DSP4_BLOCK_SHIFT  3
#define DSP4_BLOCK_F32    0x41000000
#define DSP4_BLOCK_RATE   6000

/* METER coefficients. They live here because they are functions of the
 * BLOCK RATE, not of the meter: the time constants are fixed properties
 * (RMS window 300 ms, peak-hold decay
 * 1.333 s) and the per-block coefficient that
 * realises them moves when the block size moves. Getting this wrong is
 * exactly the third recorded meter defect -- a constant derived for 1500
 * blocks/s applied once per SAMPLE, which ran the decay 32x fast.
 * Q4.28, one - exp(-1 / (rate * tau)). Normative source:
 * tools/dsp/fixed_ref.py::meter_coeffs.
 *
 * DSP4_MTR_CVT_DIV rate-limits only the float CONVERSION for the host
 * (750 Hz); the measurement itself is
 * every sample of every block. */
#define DSP4_MTR_ALPHA_Q  149089
#define DSP4_MTR_BETA_Q   33561
#define DSP4_MTR_CVT_DIV  8

/* LEGACY float meter (src/lib/meter.asm), IEEE-754 single. The peak
 * array decays by this factor once per BLOCK, so it is the same
 * 1.333 s time constant expressed as a survivor:
 * exp(-1 / (rate * tau)) = 0.999874977 at 6000 blocks/s.
 * It used to be a hand constant, 0.99950, derived for 1500 blocks/s and
 * left unchanged when the operating point moved to BLOCK=8 -- so it
 * decayed in 0.333 s, FOUR TIMES FAST, in the shipping image (review
 * finding D6). It is the same recorded meter-defect class as
 * DSP4_MTR_BETA_Q above, in the one meter path the 08-28 rebuild did not
 * replace, and it is derived here for the same reason. */
#define DSP4_MTR_DECAY_F32 0x3F7FF7CE

/* PAIRED GRAPH. DSP4_SIMD_DYN says the paired dynamics KERNELS are in the
 * image; DSP4_SIMD_GRAPH says the graph is WIRED for them -- the odd pool,
 * the pair drivers and the pair-ordered chain. They are separate because
 * the self-test build wants the kernels and their scalar twins and nothing
 * else: with the drivers in as well, chip 1's PM overflows sec_swco. Every
 * piece of the wiring is guarded on this one macro. */
#ifndef DSP4_SIMD_GRAPH
#define DSP4_SIMD_GRAPH 1
#endif

/* GAIN's SIMD block kernel (2026-09-02). Independent of every macro above
 * it: what it pairs is two ADJACENT SAMPLES of one channel, not two
 * channels, so it needs neither the odd pool nor the pair-ordered chain
 * and it is on whether or not the graph is paired. DSP4_GAIN_SIMD=0 is the
 * byte-for-byte scalar control the cost is measured against. Inert unless
 * DSP4_BLOCK_KERNELS is on -- the per-sample path is untouched. */
#ifndef DSP4_GAIN_SIMD
#define DSP4_GAIN_SIMD 1
#endif
#ifndef DSP4_GAIN_SIMD_NEGCTL
#define DSP4_GAIN_SIMD_NEGCTL 0
#endif
#if DSP4_SIMD_DYN && DSP4_SIMD_GRAPH
#define DSP4_PAIRED_GRAPH 1
#else
#define DSP4_PAIRED_GRAPH 0
#endif

/* PAIRED BIQUADS IN THE GRAPH (2026-08-29). The same separation once more:
 * DSP4_SIMD_PROBE puts _bq_pair_blk and _bq_fx_cascade_simd in the image
 * for the self-test, DSP4_BQ_GRAPH wires the FILT and EQ classes of a
 * strip PAIR into one call the way the dynamics already are. The kernel
 * side has been measured at 1.43-1.54x since the paired-cascade hang was
 * root-caused; until this macro nothing in the GRAPH used it.
 *
 * DSP4_BQ_PAIRED is what the library and the drivers are guarded on, so a
 * probe build and a graph build reach the same code and there is one
 * copy of it. */
#ifndef DSP4_BQ_GRAPH
#define DSP4_BQ_GRAPH 1
#endif
#if DSP4_PAIRED_GRAPH && DSP4_BQ_GRAPH
#define DSP4_BQ_PAIRED_GRAPH 1
#else
#define DSP4_BQ_PAIRED_GRAPH 0
#endif
/* PAIRED BIQUAD CASCADES ON CHIP 2 (2026-09-02) -- NATIVE INTERLEAVE.
 * Chip 1's _bq_pair_blk gathers the two strips' coefficients and state
 * into an interleaved scratch on EVERY block, which costs 4.25 cycles per
 * band-sample whatever the stage count is and turns a 2x lever into 1.5x.
 * Chip 2 does not gather per block: the pair OWNS the interleaved arrays
 * and latches them, so the gather happens once when a pair engages and
 * the per-block path is the signal interleave alone.
 *
 * DSP4_C2_BQ_GRAPH=0 is the CONTROL: the same tree with chip 2's biquad
 * classes back in the chain as scalar nodes and the dynamics pairs
 * untouched, which is what the 240,681-cycle figure was measured on. */
#ifndef DSP4_C2_BQ_GRAPH
#define DSP4_C2_BQ_GRAPH 1
#endif
#if DSP4_PAIRED_GRAPH && DSP4_C2_BQ_GRAPH
#define DSP4_C2_BQ_PAIRED_GRAPH 1
#else
#define DSP4_C2_BQ_PAIRED_GRAPH 0
#endif

/* The SIMD cascade itself is shared: chip 1 reaches it through
 * _bq_pair_blk, chip 2 points straight at its own interleaved arrays. */
#if DSP4_BQ_PAIRED_GRAPH || DSP4_C2_BQ_PAIRED_GRAPH || DSP4_SIMD_PROBE
#define DSP4_BQ_PAIRED 1
#else
#define DSP4_BQ_PAIRED 0
#endif

/* ROUND ONCE PER CASCADE, NOT PER STAGE (PW ruling 2026-09-02, D5
 * amendment; landed 2026-09-03).
 *
 * The per-stage SATURATE is deleted from the fixed cascade kernels. The
 * per-stage ERROR FEEDBACK is NOT -- they are two separate deletions and
 * RIG C measured them as costing wildly different things: the saturate
 * is six instructions and, while nothing overflows, costs nothing
 * numerically at all, because a saturate that never fires is the
 * identity; the error feedback is ONE instruction and is worth 16 dB of
 * LF response on the +15 dB Q3.16 20 Hz shelf D5 was decided on.
 *
 * DSP4_BQ_ROUNDONCE=0 is the CONTROL and it is the per-stage-saturating
 * contract kernel byte for byte. bqeverify.sh needs both: built at 0 it
 * diffs the contract against the round-once arm and the divergences must
 * be exactly the ones fixed_ref predicts; built at 1 the two arms must
 * agree on every word of every vector.
 *
 * What this gives up is the overflow GUARANTEE, and only that. Headroom
 * sized per cascade on |h|_1 at parameter-load time is the guard that
 * keeps the cycles; see MW/D32/DSP/dsp4-roundonce-land-20260903.md. */
#ifndef DSP4_BQ_ROUNDONCE
#define DSP4_BQ_ROUNDONCE 1
#endif

/* THE PER-CASCADE HEADROOM GUARD (2026-09-03), which is what buys the
 * overflow guarantee back.
 *
 * H = ceil(log2(|h|_1 / 8)) bits, sized over the worst PARTIAL cascade
 * at PARAMETER-LOAD time (lib/bq_headroom.asm; model
 * tools/dsp/bq_h_load.py) and carried as the FIRST WORD of the cascade's
 * coefficient block. The kernels shift the cascade input down H on entry
 * and the output back up and saturate ONCE on exit; the recursion runs
 * at the scaled level where |h|_1 * x fits Q4.28 and only the word
 * handed on comes back up.
 *
 * H = 0 FOR 94% OF THE DEFS SPACE, and there both scaling passes are
 * jumped over whole -- the sample loop is byte for byte the unguarded
 * one. It is inseparable from round-once and is defined to follow it:
 * with the per-stage saturate in place there is nothing to guard, and
 * DSP4_BQ_ROUNDONCE=0 must stay the byte-for-byte contract control that
 * every bar is run against.
 *
 * DSP4_BQ_GUARD_FORCE > 0 overrides the sized H on EVERY cascade, which
 * is how the guard's worst-case cost is measured in the graph rather
 * than estimated from a rig. It is a measurement, not a mode. */
/* FLOAT ON SHARC -- DSP4_BQ_FLOAT, THE SHIPPING CASCADE (PW ruling
 * 2026-09-03: the SHARC DSP is 40-bit float). DEFAULTS ON.
 *
 * The four cascade kernels are software FLOAT DF-II-T instead of the
 * Q4.28 offset form, and the cascade's coefficient block carries FIVE
 * float32 words a stage in D5's OWN OFFSET ENCODING -- b0, n1 = b1+2*b0,
 * n2 = b2-b0, c1 = 2+a1, c2 = 1-a2 -- which the kernel reconstructs in
 * registers once per stage per block. `_bq_fx_convert_N` is a COPY: the
 * wire word IS the stored word, and the Q4.28 quantisation step is gone.
 * The signal buffers stay Q4.28: the conversion is ONE instruction per
 * sample on the way into a cascade (`Fn = FLOAT Rx BY -28`) and one on
 * the way out (`Rn = FIX Fx BY 28`, after the one CLIP, because the
 * inter-node bus is still Q4.28).
 *
 * THE OFFSET WIRE IS THE ACCURACY, NOT A DETAIL. Direct float32
 * coefficients cost 0.3715 dB on the DEFS worst set -- eight times the
 * 0.046 dB golden bar -- because a1 = -1.9948 has a 2.4e-7 ulp in
 * float32 against Q4.28's 3.7e-9, six bits on the number that places
 * the pole. On the offset wire the same arithmetic reads 0.0080 dB,
 * better than the fixed contract's 0.0265.
 *
 * IT NEEDS NONE OF THE GUARD MACHINERY: no per-stage saturate, no
 * 64-bit extract, no |h|_1 headroom guard and no load-time sizer,
 * because an 8-bit exponent absorbs the |h|_1 = 1313 (+62 dB) worst
 * case that costs the fixed path eight bits of mantissa (proved, not
 * asserted: peak 1285.0 against 3.4e38). DSP4_BQ_GUARD is therefore
 * FORCED OFF here (and DSP4_BQ_HDR with it) rather than merely
 * defaulting off.
 *
 * THE STATE IS 40-BIT. MODE1.RND32 is CLEARED, so the register file
 * carries the SHARC's extended-precision float -- eight more mantissa
 * bits -- through the whole recursion, and the block kernels hold w1/w2
 * in registers across all DSP4_BLOCK_SIZE samples, which is where a
 * high-Q low-frequency biquad's state error accumulates. It costs
 * nothing: one `bit clr` against one `bit set` in the same place.
 * DSP4_BQ_FLOAT32=1 is the CONTROL: RND32 set, so every result rounds at
 * the 32-bit boundary and the arm is IEEE single throughout -- RIG A2
 * exactly. The difference between the two is what the 40 bits buy
 * (33-48 dB of noise floor at zero cycle cost).
 *
 * DSP4_BQ_FLOAT=0 IS THE FIXED REFERENCE MODEL AND IT STAYS. The
 * round-once path and its guard are what a future FPGA fixed engine
 * follows; the fixed build must keep rebuilding its recorded W0
 * witnesses byte for byte, and that is the bar that proves it intact.
 * Do not delete them. */
#ifndef DSP4_BQ_FLOAT
#define DSP4_BQ_FLOAT 1
#endif
#ifndef DSP4_BQ_FLOAT32
#define DSP4_BQ_FLOAT32 0
#endif

#if DSP4_BQ_ROUNDONCE && !DSP4_BQ_FLOAT
#ifndef DSP4_BQ_GUARD
#define DSP4_BQ_GUARD 1
#endif
#else
#undef DSP4_BQ_GUARD
#define DSP4_BQ_GUARD 0
#endif
#ifndef DSP4_BQ_GUARD_FORCE
#define DSP4_BQ_GUARD_FORCE 0
#endif

/* Header words in front of a cascade's coefficients: 1 with the guard,
 * 0 without. The interleaved pair blocks carry two, one per strip. */
/* GAIN ON THE FLOAT PATH -- DSP4_GAIN_FLOAT, and it follows the cascade.
 *
 * `_gsimd_gain_blk` (lib/meter_fx.asm) is the block kernel every one of
 * the 32 metered GAIN nodes runs, and it is where all of the graph's
 * GAIN cycles are. Under this flag its AUDIO path becomes one float
 * multiply, one CLIP and one FIX in place of the 64-bit extract and the
 * branch-free saturate -- eighteen instructions per two samples become
 * eleven.
 *
 * THE METER STAYS FIXED, AND THAT IS NOT A COMPROMISE. The meter wants
 * the PRE-CLIP wide word and an EXACT sum of squares across the block:
 * `mrb = x*g (ssi)` gives it the full Q8.24 over-range the 32-bit store
 * cannot hold, and MRF accumulates 80 bits with no rounding and no
 * saturation, which is order-independent and is what makes the SIMD
 * split exact. Float would make both approximate to buy back two
 * instructions. So the wide MAC stays and only the audio word changes,
 * and the gain the audio uses is FLOATed from the same Q4.28 word the
 * meter's MAC uses -- polarity and mute already folded in -- so the two
 * cannot disagree about what gain was applied.
 *
 * The scalar body, the DSP4_GAIN_SIMD=0 body and the DSP4_MTR_OFF body
 * stay FIXED and are the byte-for-byte controls they always were.
 *
 * Defaults to DSP4_BQ_FLOAT, so DSP4_BQ_FLOAT=0 is still the whole fixed
 * reference model in one flag. */
#ifndef DSP4_GAIN_FLOAT
#define DSP4_GAIN_FLOAT DSP4_BQ_FLOAT
#endif

/* MODE1.RND32, bit 16: set = every float result rounds at the 32-bit
 * boundary (IEEE single), clear = the register file's 40-bit extended
 * format. This firmware has never written it, so the part boots in
 * 40-bit mode; every kernel that touches it saves and restores MODE1. */
#define DSP4_RND32_BIT 0x00010000

#define DSP4_BQ_HDR DSP4_BQ_GUARD

/* Samples of the load-time impulse run per main-loop pass. The sizing
 * is spent out of the idle spin between blocks and never out of block
 * work; this is what bounds how much of one pass it can take. */
#ifndef DSP4_BQHR_BUDGET
#define DSP4_BQHR_BUDGET 128
#endif

/* The round-once kernel against fixed_ref on the DEFS curve set, on the
 * part (lib/bqe_verify.asm). Debug only; never in a shipping image. */
#ifndef DSP4_BQE_VERIFY
#define DSP4_BQE_VERIFY 0
#endif

/* The headroom guard on the part: the sizer against its model, and the
 * sign inversions the guard exists to prevent, counted both ways in one
 * image (lib/bq_guard_test.asm, SHARC/bqguard.sh). Debug only. */
#ifndef DSP4_BQG_VERIFY
#define DSP4_BQG_VERIFY 0
#endif

#endif /* DSP4_BLOCK_H */
