/* ramp_engine.asm — Shared slew/ramp infrastructure for D32 DSP */
/* AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly. */

/* Frame period: 8 samples @ 48 kHz = 0.1667 ms */
/* Ramp modes: Instant (0 frames), Slew, LinearFrames, ExpFrames */
/* Ramp scope: Scalar (per-value ramp), CoeffSetAtomic (double-buffer swap) */

/*
 * SPI receive handler calls _ramp_set_target to initiate a ramp:
 *   Input:  r0 = pointer to coefficient
 *           r1 = new target value
 *           r2 = ramp mode (0=Instant, 1=Slew, 2=LinearFrames, 3=ExpFrames)
 *           r3 = frame count (0 for Instant)
 *           r4 = STRIDE from the value to its companion words
 *                (1 for a scalar; the array length for the routing
 *                 sends, whose target/step/frames are parallel
 *                 arrays -- see _spi_dispatch_cN_stride)
 *
 * For Instant: write target directly, frames=0
 * For Slew/LinearFrames:
 *   step = (target - current) / frames
 *   Store step + frame count; per-block ISR decrements and applies
 * For CoeffSetAtomic:
 *   Write to _next buffer; set swap_pending flag
 *   Process function checks flag at block start
 */

.section/pm seg_pmco;
.global _ramp_set_target;
_ramp_set_target:
    i4 = r0;               /* save coeff pointer in DAG I register */
    /* Stash the stride FIRST: the slew path loads the current value
     * into f4, and f4 IS r4, so the incoming stride would be gone. */
    r12 = r4;              /* stride */
    r5 = 0;
    comp(r2, r5);
    if eq jump (pc, .ramp_instant);

    /* Slew / LinearFrames: compute step = (target - current) / frames */
    f4 = dm(i4, 0);        /* current value */
    f5 = f1 - f4;           /* delta */
    f6 = float r3;          /* frame count as float */
    /* f5 = f5 / f6 via Newton-Raphson reciprocal (no float div in SHARC) */
    f7 = RECIPS f6;         /* seed: ~8-bit 1/f6 */
    f8 = f6 * f7;
    r10 = 0x40000000;       /* 2.0 in IEEE 754 */
    f8 = f10 - f8;
    f7 = f7 * f8;           /* ~16-bit 1/f6 */
    f8 = f6 * f7;
    f8 = f10 - f8;
    f7 = f7 * f8;           /* ~32-bit 1/f6 */
    f5 = f5 * f7;           /* step = delta / frames */
    /* Store target at [r0+s], step at [r0+2s], frames at [r0+3s].
     *
     * NOT dm(i4, 1) / dm(i4, 2) / dm(i4, 3). That form is POST-modify:
     * it writes the address currently in i4 and THEN adds the modifier,
     * so the old code wrote target over the LEVEL at [r0+0], step over
     * the TARGET at [r0+1], and only landed frames correctly by luck.
     *
     * The stride is NOT always 1. A scalar parameter emits
     * value/target/step/frames back to back, but the routing sends
     * emit four PARALLEL ARRAYS, so element i of a 12-wide AuxSend has
     * its companions 12/24/36 words away. Writing those at +1/+2/+3
     * corrupts the NEIGHBOURING crosspoint's level and leaves the send
     * with no ramp state at all -- which is why aux and fx sends could
     * never be set over SPI. The handler passes the right stride from
     * the generated _spi_dispatch_cN_stride table.
     *
     * Bench 2026-08-23: writing 1.0 to C2_PI_IN's level put 1/128 in
     * the target slot, converging to ~1/129 over repeats -- that value
     * is step = delta/frames, which is what identified the fault. The
     * block-rate code then copied the bogus target into level and the
     * audio path went silent, unrecoverable by any further write
     * because the copy happens every block.
     *
     * Explicit address arithmetic instead, so the intent is on the
     * page. */
    r11 = r0;
    r11 = r11 + r12;  i4 = r11;  dm(i4, 0) = f1;   /* target  [r0+s]  */
    r11 = r11 + r12;  i4 = r11;  dm(i4, 0) = f5;   /* step    [r0+2s] */
    r11 = r11 + r12;  i4 = r11;  dm(i4, 0) = r3;   /* frames  [r0+3s] */
    rts;

.ramp_instant:
    /* Instant must set the TARGET as well as the value: the node's
     * block-rate code is `if frames <= 0: level = target`, so writing
     * the level alone is undone within one block. Same post-modify
     * trap as above -- the old dm(i4, 3) wrote back over [r0+0].
     *
     * Reached for a profile-0 (InstantCtl) write to a parameter that
     * HAS ramp state. Setting the level alone is not enough: the
     * block-rate code runs `if frames <= 0: level = target` every
     * block, so the write would be undone within one block period.
     * Level and target both, and frames cleared so the snap path
     * holds the new value. r5 is still 0 from the mode test. */
    dm(i4, 0) = f1;                                /* level   [r0+0]  */
    r11 = r0;
    r11 = r11 + r12;  i4 = r11;  dm(i4, 0) = f1;   /* target  [r0+s]  */
    r11 = r11 + r12;                               /* step    [r0+2s] */
    r11 = r11 + r12;  i4 = r11;  dm(i4, 0) = r5;   /* frames  [r0+3s] */
    rts;
_ramp_set_target.end:
