/* block_io.asm — DMA↔node scatter/gather for CHIP2 */
/* AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly. */

.section/dm seg_dmda;

/* IC RX scatter entries (32 recv channels) */
.extern _rx_ic_slot_C2_RECV_01;
.extern _rx_ic_slot_C2_RECV_02;
.extern _rx_ic_slot_C2_RECV_03;
.extern _rx_ic_slot_C2_RECV_04;
.extern _rx_ic_slot_C2_RECV_05;
.extern _rx_ic_slot_C2_RECV_06;
.extern _rx_ic_slot_C2_RECV_07;
.extern _rx_ic_slot_C2_RECV_08;
.extern _rx_ic_slot_C2_RECV_09;
.extern _rx_ic_slot_C2_RECV_10;
.extern _rx_ic_slot_C2_RECV_11;
.extern _rx_ic_slot_C2_RECV_12;
.extern _rx_ic_slot_C2_RECV_13;
.extern _rx_ic_slot_C2_RECV_14;
.extern _rx_ic_slot_C2_RECV_15;
.extern _rx_ic_slot_C2_RECV_16;
.extern _rx_ic_slot_C2_RECV_17;
.extern _rx_ic_slot_C2_RECV_18;
.extern _rx_ic_slot_C2_RECV_19;
.extern _rx_ic_slot_C2_RECV_20;
.extern _rx_ic_slot_C2_RECV_21;
.extern _rx_ic_slot_C2_RECV_22;
.extern _rx_ic_slot_C2_RECV_23;
.extern _rx_ic_slot_C2_RECV_24;
.extern _rx_ic_slot_C2_RECV_25;
.extern _rx_ic_slot_C2_RECV_26;
.extern _rx_ic_slot_C2_RECV_27;
.extern _rx_ic_slot_C2_RECV_28;
.extern _rx_ic_slot_C2_RECV_29;
.extern _rx_ic_slot_C2_RECV_30;
.extern _rx_ic_slot_C2_RECV_31;
.extern _rx_ic_slot_C2_RECV_32;
.var _c2_ic_rx_slots[32] =
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31;
.var _c2_ic_rx_ptrs[32] =
    _rx_ic_slot_C2_RECV_01,
    _rx_ic_slot_C2_RECV_02,
    _rx_ic_slot_C2_RECV_03,
    _rx_ic_slot_C2_RECV_04,
    _rx_ic_slot_C2_RECV_05,
    _rx_ic_slot_C2_RECV_06,
    _rx_ic_slot_C2_RECV_07,
    _rx_ic_slot_C2_RECV_08,
    _rx_ic_slot_C2_RECV_09,
    _rx_ic_slot_C2_RECV_10,
    _rx_ic_slot_C2_RECV_11,
    _rx_ic_slot_C2_RECV_12,
    _rx_ic_slot_C2_RECV_13,
    _rx_ic_slot_C2_RECV_14,
    _rx_ic_slot_C2_RECV_15,
    _rx_ic_slot_C2_RECV_16,
    _rx_ic_slot_C2_RECV_17,
    _rx_ic_slot_C2_RECV_18,
    _rx_ic_slot_C2_RECV_19,
    _rx_ic_slot_C2_RECV_20,
    _rx_ic_slot_C2_RECV_21,
    _rx_ic_slot_C2_RECV_22,
    _rx_ic_slot_C2_RECV_23,
    _rx_ic_slot_C2_RECV_24,
    _rx_ic_slot_C2_RECV_25,
    _rx_ic_slot_C2_RECV_26,
    _rx_ic_slot_C2_RECV_27,
    _rx_ic_slot_C2_RECV_28,
    _rx_ic_slot_C2_RECV_29,
    _rx_ic_slot_C2_RECV_30,
    _rx_ic_slot_C2_RECV_31,
    _rx_ic_slot_C2_RECV_32;

/* TX output slot tables (2 output channels, stride=2) */
.extern _tx_out_slot_C2_OUT_L;
.extern _tx_out_slot_C2_OUT_R;
.var _c2_tx_slots[2] =
    0,
    1;
.var _c2_tx_ptrs[2] =
    _tx_out_slot_C2_OUT_L,
    _tx_out_slot_C2_OUT_R;

.extern _ic_rx_active_buf;
.extern _tx_active_buf;
.extern _meter_peaks;

.section/pm seg_pmco;

/* Scatter 32 inter-chip recv channels from IC DMA RX */
.global _scatter_chip2;
_scatter_chip2:
    /* r0 = sample index (0..31) */
    r1 = 32;
    r1 = r0 * r1;
    r6 = dm(_ic_rx_active_buf);
    r6 = r6 + r1;             /* r6 = IC buf base for this sample */
    i1 = _c2_ic_rx_slots;     /* slot offset table */
    i2 = _c2_ic_rx_ptrs;      /* destination var pointers */
    r5 = 32;
    lcntr = r5; do .c2_scat_ic until lce;
        r3 = dm(i1, 1);       /* IC slot offset */
        r4 = dm(i2, 1);       /* pointer to _rx_ic_slot_* var */
        r1 = r6 + r3;         /* DMA buf addr */
        i3 = r1;
        r2 = dm(i3, 0);       /* read from IC DMA */
        i3 = r4;
        dm(i3, 0) = r2;       /* write to recv slot var */
    .c2_scat_ic:
        nop;
    rts;
_scatter_chip2.end:

/* Gather 2 DAC outputs to DMA TX buffer (stride=2) */
.global _gather_chip2;
_gather_chip2:
    /* r0 = sample index (0..31) */
    r1 = 2;
    r1 = r0 * r1;
    r6 = dm(_tx_active_buf);
    r6 = r6 + r1;             /* r6 = TX buf base for this sample */
    i1 = _c2_tx_slots;
    i2 = _c2_tx_ptrs;
    r5 = 2;
    lcntr = r5; do .c2_gath_tx until lce;
        r3 = dm(i1, 1);       /* slot offset */
        r4 = dm(i2, 1);       /* pointer to _tx_out_slot_* var */
        i3 = r4;
        r2 = dm(i3, 0);       /* read slot value */
        r4 = r6 + r3;         /* DMA buf addr */
        i3 = r4;
        dm(i3, 0) = r2;
    .c2_gath_tx:
        nop;
    rts;
_gather_chip2.end:

/* Peak-hold meter scan: run once per block on last-gathered output values */
.global _meter_scan_chip2;
_meter_scan_chip2:
    i0 = _c2_tx_ptrs;
    i1 = _meter_peaks;
    m0 = 0;                   /* no-advance for peak read */
    m1 = 1;                   /* advance for peak write */
    r5 = 2;
    lcntr = r5; do .c2_mscan until lce;
        r2 = dm(i0, 1);       /* pointer to _tx_out_slot_* var */
        i2 = r2;
        f3 = dm(i2, 0);       /* last-gathered output sample */
        f3 = abs f3;          /* abs(sample) */
        f4 = dm(i1, m0);      /* current peak (no advance) */
        comp(f3, f4);         /* compare abs to peak */
        if gt f4 = f3;        /* conditional reg move: valid SHARC op */
        dm(i1, m1) = f4;      /* write updated peak and advance */
    .c2_mscan:
        nop;
    rts;
_meter_scan_chip2.end:
