#!/usr/bin/env python3
"""s55_ingest.py — desk side of S55 (numpy). Reads data/<XLR>_loop.json (+ the 16k 150-ohm captures) for every channel
present, plus MIC 5 (J25) from S54's 64-code sweep, and regenerates:

  law.csv         channel, code, loop gain dB (TEST_MEAS coherent gain, osc on the donor strip -> lane)
  trim-table.md   per code mean/min/max/spread of the HARDWARE gain (re each channel's own code 0) across channels;
                  the universal table: target 0..60 dB -> largest MEAN hw gain <= target, trim = target - hw >= 0,
                  worst-case error a channel at the spread's edge sees; channels deviating > 0.5 dB from the mean flagged
  channels.md     one summary row per channel (T1, T2, T3, T4/T4b EIN both weightings + sub-20 Hz, T5, T8)

EIN (S57-R): noise power P dBFS (FS sine = -3.01) -> dBu at the input = P + 3.01 + 23.13 - G_loop(code), with the
channel's OWN loop gain at that code (DAC FS +23.13 dBu at J45, spec-audio-test-set.md measured references)."""
import csv, glob, json, math, os, sys
import numpy as np
HERE = os.path.dirname(os.path.abspath(__file__))
S55 = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(HERE, '../../s57/tools'))
import s57_analyse as A, s57_bands as B

DAC_FS_DBU = 23.13
FLAG_DB = 0.5
PANEL = {'J25': 'MIC 5', 'J26': 'MIC 17', 'J27': 'MIC 6', 'J28': 'MIC 18', 'J29': 'MIC 7', 'J30': 'MIC 19', 'J31': 'MIC 8',
         'J32': 'MIC 20', 'J35': 'MIC 9', 'J36': 'MIC 21', 'J37': 'MIC 10', 'J38': 'MIC 22', 'J39': 'MIC 11', 'J40': 'MIC 23',
         'J41': 'MIC 12', 'J42': 'MIC 24'}
ORDER = list(PANEL)


def em(v):
    return 10 * math.log10(sum(10 ** (x / 10) for x in v) / len(v))


def load():
    ch = {}
    # MIC 5 from S54 (same loop, same method; T4b from S57 at 150 ohm)
    g = {}
    for l in open(os.path.join(S55, '../s54/data/s54_t1all.jsonl')):
        r = json.loads(l)
        if r.get('ev') == 't1all':
            g[r['code']] = r['gain_coh']
    ch['J25'] = {'xlr': 'J25', 'lane': 20, 'src': 'S54/S57', 'G': g}
    for f in sorted(glob.glob(os.path.join(S55, 'data', 'J*_loop.json'))):
        r = json.load(open(f))
        r['G'] = {t['code']: t['gain_coh'] for t in r['t1']}
        r['src'] = 'S55'
        if len(r['G']) == 64:
            ch[r['xlr']] = r
    return {k: ch[k] for k in ORDER if k in ch}


def noise_figs(r):
    out = {}
    for code in (63, 0):
        fs = sorted(glob.glob(os.path.join(S55, 'data', '%s_c%02d_*.json' % (r['xlr'], code))))
        if not fs:
            continue
        an = [A.anat(f) for f in fs]; bd = [B.bands(f) for f in fs]
        off = 3.0103 + DAC_FS_DBU - r['G'][code]
        o = {'n': len(fs), 'aud': em([a['b20k_dbfs'] for a in an]), 'aw': em([a['a20k_dbfs'] for a in an]),
             'raw': em([b['total'] for b in bd]), 'lf5': em([b['0.1-5'] for b in bd]), 'lf20': em([b['5-20'] for b in bd]),
             'mains_pct': sum(a['mains_share_pct'] for a in an) / len(an),
             'kurt': max(a['imp_raw']['kurtosis'] for a in an), 'ovr': sum(json.load(open(f))['overruns'] for f in fs)}
        o['sub20'] = 10 * math.log10(10 ** (o['lf5'] / 10) + 10 ** (o['lf20'] / 10))
        for k in ('aud', 'aw', 'raw', 'sub20'):
            o[k + '_dbu'] = o[k] + off
        out[code] = o
    return out


def write_law(ch):
    with open(os.path.join(S55, 'law.csv'), 'w', newline='') as f:
        w = csv.writer(f)
        w.writerow(['channel', 'code', 'loop_gain_db'])
        for k, r in ch.items():
            for c in range(64):
                w.writerow(['%s (%s)' % (k, PANEL[k]), c, '%.3f' % r['G'][c]])


def write_table(ch):
    ks_all = list(ch)
    hw = {k: [ch[k]['G'][c] - ch[k]['G'][0] for c in range(64)] for k in ks_all}
    mean_all = [sum(hw[k][c] for k in ks_all) / len(ks_all) for c in range(64)]
    flags, flagged = [], set()
    for k in ks_all:
        worst = max(((hw[k][c] - mean_all[c], c) for c in range(64)), key=lambda d: abs(d[0]))
        if abs(worst[0]) > FLAG_DB:
            flags.append('%s (%s): %+.3f dB at code %d' % (k, PANEL[k], worst[0], worst[1]))
            flagged.add(k)
    # the standard is built from the channels that pass; a flagged channel (a stage off-value) is reported, not averaged in
    ks = [k for k in ks_all if k not in flagged]
    mean = [sum(hw[k][c] for k in ks) / len(ks) for c in range(64)]
    mn = [min(hw[k][c] for k in ks) for c in range(64)]
    mx = [max(hw[k][c] for k in ks) for c in range(64)]
    mn_all = [min(hw[k][c] for k in ks_all) for c in range(64)]
    mx_all = [max(hw[k][c] for k in ks_all) for c in range(64)]
    L = []
    L.append('# S55 — universal mic-gain step/trim table (MW-D24-2, generated by `tools/s55_ingest.py`; do not hand-edit)')
    L.append('')
    L.append('Channels measured (%d): %s. Hardware gain = each channel\'s loop gain at the code minus its own loop gain at '
             'code 0 (1 kHz, TEST_MEAS coherent, lane peak −20…−6 dBFS).' % (len(ks_all), ', '.join('%s (%s)' % (k, PANEL[k]) for k in ks_all)))
    L.append('')
    L.append('**Deviation flags (> %.1f dB from the all-channel mean at any code): %s**' % (FLAG_DB, '; '.join(flags) if flags else 'none'))
    L.append('')
    L.append('**The mean, min, max and the universal table are built from the %d unflagged channels%s.** The last two columns '
             'of the per-code table include every channel.' % (len(ks), (' (excluded: %s)' % ', '.join(sorted(flagged))) if flagged else ''))
    L.append('')
    L.append('Worst per-channel deviation from the (unflagged) mean: ' + ', '.join(
        '%s %+.3f dB (code %d)' % ((k,) + max(((hw[k][c] - mean[c], c) for c in range(64)), key=lambda d: abs(d[0])))
        for k in ks_all))
    L.append('')
    L.append('## Per code (hardware gain re code 0, dB)')
    L.append('')
    L.append('| code | byte | mean | min | max | spread | min (all) | spread (all) |')
    L.append('|---:|---|---:|---:|---:|---:|---:|---:|')
    for c in range(64):
        L.append('| %d | 0x%02X | %.3f | %.3f | %.3f | %.3f | %.3f | %.3f |' % (c, c << 2, mean[c], mn[c], mx[c], mx[c] - mn[c],
                 mn_all[c], mx_all[c] - mn_all[c]))
    g0 = [ch[k]['G'][0] for k in ks_all]
    L.append('')
    L.append('Code-0 loop gain (DAC → AUX 1 → input network → ADC) across all channels: mean %+.3f dB, min %+.3f, max %+.3f, spread %.3f dB (%s).' % (
        sum(g0) / len(g0), min(g0), max(g0), max(g0) - min(g0), ', '.join('%s %+.3f' % (k, ch[k]['G'][0]) for k in ks_all)))
    L.append('')
    L.append('## Universal table (target → code + digital trim, trim never negative)')
    L.append('')
    L.append('Rule (spec-audio-test-set.md, PW 09-16): hw = largest MEAN hardware gain ≤ target; trim = target − hw. '
             '"Edge error" = the gain a channel at the unflagged spread\'s edge is off by at that code (low: mean − min; '
             'high: max − mean, that channel is HOT).')
    L.append('')
    L.append('| target dB | code | byte | mean hw dB | trim dB | edge error dB (low / high) |')
    L.append('|---:|---:|---|---:|---:|---|')
    top = max(mean)
    rows = []
    for t in range(61):
        c = max((c for c in range(64) if mean[c] <= t + 1e-9), key=lambda q: mean[q])
        rows.append((t, c, mean[c], t - mean[c]))
        L.append('| %d | %d | 0x%02X | %.3f | %.3f%s | −%.3f / +%.3f |' % (t, c, c << 2, mean[c], t - mean[c],
                 ' (above hw range)' if t > top else '', mean[c] - mn[c], mx[c] - mean[c]))
    inside = [r[3] for r in rows if r[0] <= top]
    used = sorted(set(r[1] for r in rows))
    L.append('')
    L.append('Largest trim inside the hardware range (target ≤ %.2f dB): %.3f dB (targets 1–12 dB ride on code 0: the first '
             'hardware step is %.2f dB). Codes the table uses: %s. Largest edge error over those codes: %.3f dB.' % (
        top, max(inside), mean[1], ', '.join(map(str, used)), max(max(mean[c] - mn[c], mx[c] - mean[c]) for c in used)))
    open(os.path.join(S55, 'trim-table.md'), 'w').write('\n'.join(L) + '\n')
    with open(os.path.join(S55, 'trim-table.csv'), 'w', newline='') as f:
        w = csv.writer(f)
        w.writerow(['target_db', 'code', 'byte', 'hw_gain_db', 'trim_db'])
        for t, c, h, tr in rows:
            w.writerow([t, c, '0x%02X' % (c << 2), '%.3f' % h, '%.3f' % tr])
    prop = os.path.join(S55, '../../../../proposals/defs/common/tables/mic-gain-law.csv')
    if os.path.isdir(os.path.dirname(prop)):
        with open(prop, 'w', newline='') as f:
            f.write('# mic-gain-law.csv — PROPOSED (dsp S55). Target mic gain -> 595 gain code + DSP digital trim (trim >= 0).\n')
            f.write('# Source: MW-D24-2 analog board 2, %d of %d powered preamps%s, 1 kHz, 2026-09-16.\n' % (
                len(ks), len(ks_all), (' (%s excluded: stage fault)' % ', '.join(sorted(flagged))) if flagged else ''))
            f.write('# Generated by MW/D24/DSP/s55/tools/s55_ingest.py; do not hand-edit.\n')
            w = csv.writer(f)
            w.writerow(['target_db', 'code', 'byte', 'hw_gain_db', 'trim_db'])
            for t, c, h, tr in rows:
                w.writerow([t, c, '0x%02X' % (c << 2), '%.3f' % h, '%.3f' % tr])
    return flags


def f2(x, fmt='%.2f'):
    return fmt % x if x is not None else '—'


def write_channels(ch):
    L = ['# S55 — per-channel summary (MW-D24-2, `s56` pair, TEST_MEAS + chip-1 capture arm; generated by `tools/s55_ingest.py`)',
         '',
         'Loop: TEST_OSC (donor strip 6, strip 1 for J32) → AUX 1 → J45 → loop cable → XLR → preamp → lane (strip) → TEST_MEAS. '
         'T4/T4b source: 150 Ω across pins 2–3, loop cable off. EIN in dBu at the input = P + 3.01 + 23.13 − G_loop(code). '
         'J15–J22 (U15, lanes 1–4/13–16) have no rails today: not tested.',
         '',
         '| XLR | panel | lane | T1 range dB (code 0 loop gain) | T1 largest step dB (sorted / code order) | monotonic | '
         'T2 20 Hz re 1 k, code 0 / 63 | T3 best THD+N code 0 | T3 code 63 @ −3 dBFS | T4 floor code 0 / 63 dBFS (150 Ω) | '
         'T4b EIN code 63 20–20k / A dBu | sub-20 Hz / raw DC–24k dBu (code 63) | T5 | T8 samples |',
         '|---|---|---:|---|---|---|---|---|---|---|---|---|---|---:|']
    for k, r in ch.items():
        G = r['G']
        srt = sorted(range(64), key=lambda c: G[c])
        big = max(G[srt[i + 1]] - G[srt[i]] for i in range(63))
        cstep = max(G[c + 1] - G[c] for c in range(63))
        mono = all(G[c + 1] > G[c] for c in range(63))
        if r['src'] != 'S55':
            L.append('| J25 | MIC 5 | 20 | %.2f (%+.2f) | %.2f / %.2f | %s | −0.41 / −2.06 | −92.80 dB = 0.00229 %% (S54) | −47.05 dB = 0.444 %% | '
                     '−113.79 / −87.97 (S54, node) | −127.2 / −130.5 (S57) | see S57-5 | inverted | 91.40 |'
                     % (G[63] - G[0], G[0], big, cstep, 'yes' if mono else 'NO'))
            continue
        t2 = {c: {q['f']: q['re1k'] for q in r['t2'][str(c)]} for c in (0, 63)}
        t3c0 = [q for q in r['t3'] if q['code'] == 0]
        best = min(t3c0, key=lambda q: q['thd'])
        t3c63 = [q for q in r['t3'] if q['code'] == 63][0]
        nf = noise_figs(r) if 't4' in r else {}
        t4 = r.get('t4', {})
        t4f = lambda c: t4[str(c)]
        fl = ('%.2f / %.2f' % (t4f(0)['rms'], t4f(63)['rms'])) if t4 else 'pending'
        ein = ('%.1f / %.1f' % (nf[63]['aud_dbu'], nf[63]['aw_dbu'])) if 63 in nf else 'pending'
        sub = ('%.1f / %.1f' % (nf[63]['sub20_dbu'], nf[63]['raw_dbu'])) if 63 in nf else 'pending'
        f8 = r['t58']['fits'][0]
        L.append('| %s | %s | %d | %.2f (%+.2f) | %.2f / %.2f | %s | %+.2f / %+.2f | %.2f dB = %.5f %% @ %.0f dBFS | %.2f dB = %.3f %% | %s | %s | %s | %s | %.2f |' % (
            k, PANEL[k], r['lane'], G[63] - G[0], G[0], big, cstep, 'yes' if mono else 'NO', t2[0][20], t2[63][20],
            best['thd'], 100 * 10 ** (best['thd'] / 20), best['target'], t3c63['thd'], 100 * 10 ** (t3c63['thd'] / 20),
            fl, ein, sub, r['t58']['polarity'].replace('INVERTED', 'inverted'), f8['delay_samples']))
    L.append('')
    L.append('## Noise detail (150 Ω, capture arm, energy average)')
    L.append('')
    L.append('| XLR | code | captures | 20–20k dBFS | A dBFS | DC–24k dBFS | 20–20k dBu in | A dBu in | sub-20 Hz dBu in | DC–24k dBu in | mains share % | max kurtosis | overruns |')
    L.append('|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|')
    for k, r in ch.items():
        if r['src'] != 'S55' or 't4' not in r:
            continue
        for code, o in noise_figs(r).items():
            L.append('| %s | %d | %d | %.2f | %.2f | %.2f | %.1f | %.1f | %.1f | %.1f | %.2f | %.2f | %d |' % (
                k, code, o['n'], o['aud'], o['aw'], o['raw'], o['aud_dbu'], o['aw_dbu'], o['sub20_dbu'], o['raw_dbu'],
                o['mains_pct'], o['kurt'], o['ovr']))
    reps = [k for k, r in ch.items() if r['src'] == 'S55' and glob.glob(os.path.join(S55, 'data', '%sr_c63_*.json' % k))]
    if reps:
        L.append('')
        L.append('## Repeats (150 Ω refitted by PW, same conditions; hub addendum after the run)')
        L.append('')
        L.append('| XLR | run | code | 20–20k dBu in | A dBu in | sub-20 Hz dBu in | DC–24k dBu in | 2–20 kHz dBFS | 20–24 kHz dBFS | overruns |')
        L.append('|---|---|---:|---:|---:|---:|---:|---:|---:|---:|')
        for k in reps:
            for tag, lab in ((k, 'first (12:47)' if k == 'J31' else 'first'), (k + 'r', 'repeat (14:31, refit)')):
                nf = noise_figs({'xlr': tag, 'G': ch[k]['G']})
                bs = [B.bands(f) for f in sorted(glob.glob(os.path.join(S55, 'data', '%s_c63_*.json' % tag)))]
                for code, o in nf.items():
                    hf = ('%.1f | %.1f' % (em([b['2000-20000'] for b in bs]), em([b['20000-24000'] for b in bs]))) if code == 63 else '— | —'
                    L.append('| %s | %s | %d | %.1f | %.1f | %.1f | %.1f | %s | %d |' % (k, lab, code, o['aud_dbu'], o['aw_dbu'],
                             o['sub20_dbu'], o['raw_dbu'], hf, o['ovr']))
        L.append('')
        L.append('J31 repeat agrees with the first run to 0.1 dB in-band and in both HF bands: the excess is not the shunt or its fitting. '
                 'A first arming (14:24) false-triggered on the code-switch transient and measured the OPEN input (floor −78.7 dBFS); '
                 'those captures are void (not committed, `void_open_J31/` on the bench), and the detector now arms on a settled baseline.')
    open(os.path.join(S55, 'channels.md'), 'w').write('\n'.join(L) + '\n')


if __name__ == '__main__':
    ch = load()
    write_law(ch)
    flags = write_table(ch)
    write_channels(ch)
    print('channels:', list(ch), '| flags:', flags or 'none')
