<?xml version="1.0" encoding="utf-8"?>
<!-- *********************************************************************** -->
<!-- reporter_style.xsl                                                      -->
<!-- Copyright 2008-2020 Analog Devices, Inc.  All rights reserved.          -->
<!-- *********************************************************************** -->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" encoding="utf-8" doctype-public="-//W3C//DTD HTML 4.01 Transitional//EN" doctype-system="http://www.w3.org/TR/html4/loose.dtd"/>
  <xsl:include href="reporter_style_instrprof.xsl"/>
  <xsl:include href="reporter_style_heap.xsl"/>
  <xsl:include href="reporter_style_pgo.xsl"/>
  <xsl:template match="report_document">
    <html>
      <head>
        <xsl:element name="META">
          <xsl:attribute name="http-equiv">Content-Type</xsl:attribute>
          <xsl:attribute name="content">text/html;charset=utf-8</xsl:attribute>
        </xsl:element>
        <title>Your Report Document</title>
        <style type="text/css">
          .call-stack
          {
            font-family: Courier New;
          }
          .func_def
          {
            font-family: Courier New;
          }          
          .overlay
          {
            position: relative;
            left: 30px;
            top: 21px;
            z-index: 100;
          }
          .font_arial_2
          {
            font-family: Arial;
            font-size: 2;
          }
          body
          {
            font: 0.8em Verdana, Geneva, Arial, Helvetica, sans-serif;
          }
          .func_def_hit {
            /* white-space: pre-wrap;    FireFox 3+, Chrome, and Safari 4 */
            /* word-wrap: break-word;    Internet Explorer 5.5+ */
            font-family: Courier New;
            color: #02a64c;
            font-weight: bold;
          }      
          .func_def_miss {
            /* white-space: pre-wrap;    FireFox 3+, Chrome, and Safari 4 */
            /* word-wrap: break-word;    Internet Explorer 5.5+ */
            font-family: Courier New;
            color: #ff0000;
          }      
          .func_def_no_block {
            /* white-space: pre-wrap;    FireFox 3+, Chrome, and Safari 4 */
            /* word-wrap: break-word;    Internet Explorer 5.5+ */
            font-family: Courier New;
            color: #808080;
            font-style: italic;
          }      
          .pgo_percent_outer {
            border:1px solid;
            background-color: #ff0000;
          }
          .pgo_percent_inner {
            background-color: #00ff00;
            white-space:nowrap;
          }
        </style>
        <script type="text/javascript">
          <![CDATA[
          //
          // Javascript function for expanding and contracting a table or row.
          //
          function showHideElement(ind, is_table)
          {            
            s = document.getElementById("sp_" + ind);
            i = document.getElementById("im_" + ind);
            if (navigator.appName == "Microsoft Internet Explorer") {
              if (s.style.visibility == 'hidden') {
                s.style.visibility = 'visible';
                s.style.display = 'block';
                i.innerHTML='-';
              } else if (   s.style.visibility == '' 
                         || s.style.visibility == 'visible'){
                s.style.visibility = 'hidden';
                s.style.display = 'none';                
                i.innerHTML='+';
              }
            }
            else {
              if (s.style.display == 'none') {
                s.style.display = is_table ? 'table' : 'table-row';                
                i.innerHTML='-';
              } else if (   (is_table && s.style.display == 'table') 
                         || (! is_table && s.style.display == 'table-row')){
                s.style.display = 'none';                
                i.innerHTML='+';
              }
            }
          }
          function setHighlightHeapConnections(id)
          {
            s = document.getElementById("hpl_" + id);
            s.style.background = '#bcbcbc';
            s = document.getElementById("grp_" + id);
            if (s != null) {
              s.style.background = '#bcbcbc';
            }
          }
          function clrHighlightHeapConnections(id)
          {
            s = document.getElementById("hpl_" + id);
            s.style.background = '#ffffff';
            s = document.getElementById("grp_" + id);
            if (s != null) {
              s.style.background = '#ffffff';
            }
          }      
          ]]>
        </script>
      </head>
      <body>
        <xsl:apply-templates/>
        <!-- All web pages generated by the Reporter tool are HTML 4.01 Transitional. -->
        <!-- Verified by visiting http://validator.w3.org/#validate_by_upload -->
      </body>
    </html>
  </xsl:template>

  <xsl:template match="reporter_version">   
    <table border="0">
      <tr>
        <td class="font_arial_2"><xsl:value-of select="../@report_type"/> Report Document was created on <b><xsl:value-of select="../@created"/></b>
            by the Reporter Tool version <b>(<xsl:value-of select="."/>)</b>
        </td>
      </tr>
      <tr>
        <td class="font_arial_2">using <b><xsl:value-of select="../@dxe_filename"/></b> for reference.</td>
      </tr>
    </table>
  </xsl:template>
</xsl:stylesheet>
