/*----------------------------------------------------------------------
 * Aux 3 Out (OUTPUT_TDM)
 * Node ID:    C2_AUX_OUT_03
 * Chip:       2
 * Channels:   1
 * SPI Page:   1
 * SPI Addr:   260
 * RampProfile: (none)
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/
#include "dsp_block.h"

/* OUTPUT_TDM: Write to SPORT0 slot 2 */

.section/dm seg_dmda;
.extern _buf_C2_AUX_DLY_03;
.global _tx_out_slot_C2_AUX_OUT_03;
.var _tx_out_slot_C2_AUX_OUT_03;
.global _buf_C2_AUX_OUT_03;
.var _buf_C2_AUX_OUT_03;

.section/pm seg_pmco;
.global _C2_AUX_OUT_03_process;
_C2_AUX_OUT_03_process:
    r0 = dm(_buf_C2_AUX_DLY_03);
    dm(_tx_out_slot_C2_AUX_OUT_03) = r0;
    dm(_buf_C2_AUX_OUT_03) = r0;
    rts;
_C2_AUX_OUT_03_process.end:
