/*----------------------------------------------------------------------
 * Aux 9 Lim (LIMITER)
 * Node ID:    C2_AUX_LIM_09
 * Chip:       2
 * Channels:   1
 * SPI Page:   1
 * SPI Addr:   776
 * RampProfile: DynSafe
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/

/* RampProfile: DynSafe | Mode: LinearFrames | Up: 6ms (9f) Down: 20ms (30f) | Curve: Exp | Scope: Scalar */

/* LIMITER: Brick-wall peak limiter */
/* SPI page=1 addr=776 */
/* threshold=-0.5dB */

.section/dm seg_dmda;
.extern _buf_C2_AUX_AFB_09;
.global _lim_on_C2_AUX_LIM_09;
.var _lim_on_C2_AUX_LIM_09 = 1;
.global _lim_threshold_C2_AUX_LIM_09;
.var _lim_threshold_C2_AUX_LIM_09;
.global _lim_attack_C2_AUX_LIM_09;
.var _lim_attack_C2_AUX_LIM_09;
.global _lim_release_C2_AUX_LIM_09;
.var _lim_release_C2_AUX_LIM_09;
.global _lim_envelope_C2_AUX_LIM_09;
.var _lim_envelope_C2_AUX_LIM_09 = 0.0;
.global _buf_C2_AUX_LIM_09;
.var _buf_C2_AUX_LIM_09;

.section/pm seg_pmco;
.extern _dyn_envelope_follow;
.extern _dyn_to_dB;
.extern _dyn_from_dB;
.global _C2_AUX_LIM_09_process;
_C2_AUX_LIM_09_process:
    r0 = dm(_buf_C2_AUX_AFB_09);
    /* --- Bypass --- */
    r2 = dm(_lim_on_C2_AUX_LIM_09);
    r3 = 0;
    comp(r2, r3);
    if eq jump (pc, .lim_bypass_C2_AUX_LIM_09);
    f15 = f0;                   /* save dry input */

    /* Peak detect */
    f0 = abs f0;
    f1 = dm(_lim_attack_C2_AUX_LIM_09);
    f2 = dm(_lim_release_C2_AUX_LIM_09);
    f3 = dm(_lim_envelope_C2_AUX_LIM_09);
    call _dyn_envelope_follow;
    dm(_lim_envelope_C2_AUX_LIM_09) = f0;

    /* Convert to dB */
    call _dyn_to_dB;

    /* Brick-wall: if env_dB > threshold, reduce by excess */
    f1 = dm(_lim_threshold_C2_AUX_LIM_09);
    f4 = f0 - f1;             /* excess dB */
    r5 = 0x00000000;  /* 0.0 IEEE 754 */
    comp(f4, f5);
    if le jump (pc, .lim_pass_C2_AUX_LIM_09);

    /* Gain reduction = -excess dB */
    f0 = -f4;
    call _dyn_from_dB;
    f14 = f0;                 /* gain_linear < 1.0 */
    f0 = f15;
    f0 = f0 * f14;
    dm(_buf_C2_AUX_LIM_09) = r0;
    rts;

.lim_bypass_C2_AUX_LIM_09:
    dm(_buf_C2_AUX_LIM_09) = r0;
    rts;
.lim_pass_C2_AUX_LIM_09:
    /* No limiting needed */
    f0 = f15;
    dm(_buf_C2_AUX_LIM_09) = r0;
    rts;
_C2_AUX_LIM_09_process.end:
