/*----------------------------------------------------------------------
 * Aux 9 Delay (DELAY)
 * Node ID:    C2_AUX_DLY_09
 * Chip:       2
 * Channels:   1
 * SPI Page:   1
 * SPI Addr:   780
 * RampProfile: InstantCtl
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/

/* RampProfile: InstantCtl | Mode: Instant | Up: 0ms (0f) Down: 0ms (0f) | Curve: Linear | Scope: Scalar */

/* DELAY: Audio delay line (circular buffer) */
/* SPI page=1 addr=780 */
/* Max: 250.0ms = 12000 samples */

.section/dm seg_delay;
.extern _buf_C2_AUX_LIM_09;
.global _dly_buf_C2_AUX_DLY_09;
.var _dly_buf_C2_AUX_DLY_09[12000];  /* L2 SRAM delay buffer */
.section/dm seg_dmda;
.global _dly_write_ptr_C2_AUX_DLY_09;
.var _dly_write_ptr_C2_AUX_DLY_09 = 0;
.global _dly_read_offset_C2_AUX_DLY_09;
.var _dly_read_offset_C2_AUX_DLY_09 = 0;      /* in samples; 0 = no delay */
.global _dly_pool_slot_C2_AUX_DLY_09;
.var _dly_pool_slot_C2_AUX_DLY_09 = -1; /* reserved for future reassignment */
.global _dly_max_C2_AUX_DLY_09;
.var _dly_max_C2_AUX_DLY_09 = 12000;
.global _tap_pre_fader_C2_AUX_DLY_09;
.var _tap_pre_fader_C2_AUX_DLY_09;   /* pre-fader tap */
.global _buf_C2_AUX_DLY_09;
.var _buf_C2_AUX_DLY_09;

.section/pm seg_pmco;
.global _C2_AUX_DLY_09_process;
_C2_AUX_DLY_09_process:
    r0 = dm(_buf_C2_AUX_LIM_09);

    /* Write to circular buffer at write pointer */
    i0 = _dly_buf_C2_AUX_DLY_09;
    r1 = dm(_dly_write_ptr_C2_AUX_DLY_09);
    m0 = r1;
    modify(i0, m0);
    dm(i0, 0) = r0;

    /* Read from (write_ptr - read_offset) with wrap */
    r2 = dm(_dly_read_offset_C2_AUX_DLY_09);
    r1 = r1 - r2;
    r3 = dm(_dly_max_C2_AUX_DLY_09);
    if lt r1 = r1 + r3;
    i0 = _dly_buf_C2_AUX_DLY_09;
    m0 = r1;
    modify(i0, m0);
    r0 = dm(i0, 0);

    /* Advance write pointer with wrap */
    r1 = dm(_dly_write_ptr_C2_AUX_DLY_09);
    r15 = 1;
    r1 = r1 + r15;
    r3 = dm(_dly_max_C2_AUX_DLY_09);
    comp(r1, r3);
    if ge r1 = r1 - r3;
    dm(_dly_write_ptr_C2_AUX_DLY_09) = r1;

    dm(_tap_pre_fader_C2_AUX_DLY_09) = r0;
    dm(_buf_C2_AUX_DLY_09) = r0;
    rts;
_C2_AUX_DLY_09_process.end:
