/*----------------------------------------------------------------------
 * Aux 4 Out (OUTPUT_TDM)
 * Node ID:    C2_AUX_OUT_04
 * Chip:       2
 * Channels:   1
 * SPI Page:   1
 * SPI Addr:   347
 * RampProfile: (none)
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/
#include "dsp_block.h"

/* OUTPUT_TDM: Write to SPORT0 slot 3 */

.section/dm seg_dmda;
.extern _buf_C2_AUX_DLY_04;
.global _tx_out_slot_C2_AUX_OUT_04;
.var _tx_out_slot_C2_AUX_OUT_04;
.global _buf_C2_AUX_OUT_04;
.var _buf_C2_AUX_OUT_04;
.global _mtr_wide_C2_AUX_OUT_04;
.var _mtr_wide_C2_AUX_OUT_04;

.section/pm seg_pmco;
.global _C2_AUX_OUT_04_process;
_C2_AUX_OUT_04_process:
    r0 = dm(_buf_C2_AUX_DLY_04);
    dm(_tx_out_slot_C2_AUX_OUT_04) = r0;
    dm(_buf_C2_AUX_OUT_04) = r0;
    r1 = ashift r0 by -4;    /* Q4.28 -> Q8.24 */
    dm(_mtr_wide_C2_AUX_OUT_04) = r1;
    rts;
_C2_AUX_OUT_04_process.end:
