/*----------------------------------------------------------------------
 * Aux 3 GEQ (GEQ)
 * Node ID:    C2_AUX_GEQ_03
 * Chip:       2
 * Channels:   1
 * SPI Page:   1
 * SPI Addr:   202
 * RampProfile: EqSafe
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/

/* RampProfile: EqSafe | Mode: LinearFrames | Up: 12ms (18f) Down: 12ms (18f) | Curve: Linear | Scope: CoeffSetAtomic */

/* GEQ: 28-band 1/3-octave graphic EQ — dual-instance crossfade */
/* SPI page=1 addr=202 */
/*
 * Dual-instance crossfade (CoeffSetAtomic scope):
 *   Two parallel 28-stage biquad cascades (A/B) with independent
 *   coefficients and state.  Architecture identical to EQ_BIQUAD.
 *   See gen_eq_biquad docstring for full description.
 */

.section/dm seg_dmda;
.extern _buf_C2_AUX_EQ_03;
.global _geq_gains_C2_AUX_GEQ_03;
.var _geq_gains_C2_AUX_GEQ_03[28];              /* per-band gain (linear, display) */

/* ---- Instance A ---- */
.global _geq_coeffs_A_C2_AUX_GEQ_03;
.var _geq_coeffs_A_C2_AUX_GEQ_03[140] = 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0;
.global _geq_state_A_C2_AUX_GEQ_03;
.var _geq_state_A_C2_AUX_GEQ_03[56];

/* ---- Instance B ---- */
.global _geq_coeffs_B_C2_AUX_GEQ_03;
.var _geq_coeffs_B_C2_AUX_GEQ_03[140] = 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0;
.global _geq_state_B_C2_AUX_GEQ_03;
.var _geq_state_B_C2_AUX_GEQ_03[56];

/* ---- SPI staging buffer ---- */
.global _geq_coeffs_next_C2_AUX_GEQ_03;
.var _geq_coeffs_next_C2_AUX_GEQ_03[140] = 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0;
.global _geq_swap_pending_C2_AUX_GEQ_03;
.var _geq_swap_pending_C2_AUX_GEQ_03 = 0;

/* ---- Crossfade control ---- */
.global _geq_active_C2_AUX_GEQ_03;
.var _geq_active_C2_AUX_GEQ_03 = 0;
.global _geq_xfade_alpha_C2_AUX_GEQ_03;
.var _geq_xfade_alpha_C2_AUX_GEQ_03 = 0.0;
.global _geq_xfade_step_C2_AUX_GEQ_03;
.var _geq_xfade_step_C2_AUX_GEQ_03 = 0.0;

.global _buf_C2_AUX_GEQ_03;
.var _buf_C2_AUX_GEQ_03;

.section/pm seg_pmco;
.extern _biquad_cascade_N;
.global _C2_AUX_GEQ_03_process;
_C2_AUX_GEQ_03_process:

    /* ── Check for new coefficients ── */
    r4 = dm(_geq_swap_pending_C2_AUX_GEQ_03);
    r4 = pass r4;
    if ne call _geq_start_xfade_C2_AUX_GEQ_03;

    /* ── Crossfade or steady-state? ── */
    r4 = dm(_geq_xfade_step_C2_AUX_GEQ_03);
    r4 = pass r4;
    if ne jump .geq_xfade_C2_AUX_GEQ_03;

    /* ═══ STEADY STATE ═══════════════════════════════════════ */
    r0 = dm(_buf_C2_AUX_EQ_03);
    r4 = dm(_geq_active_C2_AUX_GEQ_03);
    r4 = pass r4;
    if ne jump .geq_ss_B_C2_AUX_GEQ_03;
    i0 = _geq_coeffs_A_C2_AUX_GEQ_03;
    i1 = _geq_state_A_C2_AUX_GEQ_03;
    jump .geq_ss_run_C2_AUX_GEQ_03;
.geq_ss_B_C2_AUX_GEQ_03:
    i0 = _geq_coeffs_B_C2_AUX_GEQ_03;
    i1 = _geq_state_B_C2_AUX_GEQ_03;
.geq_ss_run_C2_AUX_GEQ_03:
    r4 = 28;
    call _biquad_cascade_N;
    dm(_buf_C2_AUX_GEQ_03) = r0;
    rts;

    /* ═══ CROSSFADE ═════════════════════════════════════════ */
.geq_xfade_C2_AUX_GEQ_03:
    r0 = dm(_buf_C2_AUX_EQ_03);
    f15 = f0;                            /* save input */

    /* ── Active (old) instance ── */
    r4 = dm(_geq_active_C2_AUX_GEQ_03);
    r4 = pass r4;
    if ne jump .geq_xf_actB_C2_AUX_GEQ_03;
    i0 = _geq_coeffs_A_C2_AUX_GEQ_03;
    i1 = _geq_state_A_C2_AUX_GEQ_03;
    jump .geq_xf_act_run_C2_AUX_GEQ_03;
.geq_xf_actB_C2_AUX_GEQ_03:
    i0 = _geq_coeffs_B_C2_AUX_GEQ_03;
    i1 = _geq_state_B_C2_AUX_GEQ_03;
.geq_xf_act_run_C2_AUX_GEQ_03:
    r4 = 28;
    call _biquad_cascade_N;
    f13 = f0;                            /* old output */

    /* ── Inactive (new) instance ── */
    f0 = f15;
    r4 = dm(_geq_active_C2_AUX_GEQ_03);
    r4 = pass r4;
    if eq jump .geq_xf_inB_C2_AUX_GEQ_03;
    i0 = _geq_coeffs_A_C2_AUX_GEQ_03;
    i1 = _geq_state_A_C2_AUX_GEQ_03;
    jump .geq_xf_in_run_C2_AUX_GEQ_03;
.geq_xf_inB_C2_AUX_GEQ_03:
    i0 = _geq_coeffs_B_C2_AUX_GEQ_03;
    i1 = _geq_state_B_C2_AUX_GEQ_03;
.geq_xf_in_run_C2_AUX_GEQ_03:
    r4 = 28;
    call _biquad_cascade_N;

    /* ── Blend: out = (1 − α) × old + α × new ── */
    f14 = dm(_geq_xfade_alpha_C2_AUX_GEQ_03);
    r15 = 0x3F800000;  /* 1.0 IEEE 754 */
    f15 = f15 - f14;
    f13 = f13 * f15;
    f0 = f0 * f14;
    f0 = f0 + f13;

    /* ── Advance α ── */
    f14 = dm(_geq_xfade_alpha_C2_AUX_GEQ_03);
    f15 = dm(_geq_xfade_step_C2_AUX_GEQ_03);
    f14 = f14 + f15;
    dm(_geq_xfade_alpha_C2_AUX_GEQ_03) = f14;
    r15 = 0x3F800000;  /* 1.0 IEEE 754 */
    comp(f14, f15);
    if ge call _geq_xfade_done_C2_AUX_GEQ_03;

    dm(_buf_C2_AUX_GEQ_03) = f0;
    rts;

/* ── Start crossfade: load dormant instance ── */
_geq_start_xfade_C2_AUX_GEQ_03:
    r4 = 0;
    dm(_geq_swap_pending_C2_AUX_GEQ_03) = r4;

    r4 = dm(_geq_active_C2_AUX_GEQ_03);
    r4 = pass r4;
    if ne jump .geq_sxf_toA_C2_AUX_GEQ_03;

    /* Active=A → dormant=B */
    i0 = _geq_coeffs_next_C2_AUX_GEQ_03;
    i1 = _geq_coeffs_B_C2_AUX_GEQ_03;
    r4 = 140;
    lcntr = r4; do .geq_cp_B_C2_AUX_GEQ_03 until lce;
        r0 = dm(i0, 1);
        dm(i1, 1) = r0;
    .geq_cp_B_C2_AUX_GEQ_03:
    i1 = _geq_state_B_C2_AUX_GEQ_03;
    r0 = 0;
    r4 = 56;
    lcntr = r4; do .geq_zs_B_C2_AUX_GEQ_03 until lce;
        dm(i1, 1) = r0;
    .geq_zs_B_C2_AUX_GEQ_03:
    nop;
    jump .geq_sxf_go_C2_AUX_GEQ_03;

.geq_sxf_toA_C2_AUX_GEQ_03:
    /* Active=B → dormant=A */
    i0 = _geq_coeffs_next_C2_AUX_GEQ_03;
    i1 = _geq_coeffs_A_C2_AUX_GEQ_03;
    r4 = 140;
    lcntr = r4; do .geq_cp_A_C2_AUX_GEQ_03 until lce;
        r0 = dm(i0, 1);
        dm(i1, 1) = r0;
    .geq_cp_A_C2_AUX_GEQ_03:
    i1 = _geq_state_A_C2_AUX_GEQ_03;
    r0 = 0;
    r4 = 56;
    lcntr = r4; do .geq_zs_A_C2_AUX_GEQ_03 until lce;
        dm(i1, 1) = r0;
    .geq_zs_A_C2_AUX_GEQ_03:

.geq_sxf_go_C2_AUX_GEQ_03:
    r0 = 0;
    dm(_geq_xfade_alpha_C2_AUX_GEQ_03) = r0;
    f0 = 0.001736111111111111;
    dm(_geq_xfade_step_C2_AUX_GEQ_03) = f0;
    rts;
_geq_start_xfade_C2_AUX_GEQ_03.end:

/* ── Crossfade complete ── */
_geq_xfade_done_C2_AUX_GEQ_03:
    r4 = dm(_geq_active_C2_AUX_GEQ_03);
    r5 = 1;
    r4 = r4 xor r5;
    dm(_geq_active_C2_AUX_GEQ_03) = r4;
    r4 = 0;
    dm(_geq_xfade_alpha_C2_AUX_GEQ_03) = r4;
    dm(_geq_xfade_step_C2_AUX_GEQ_03) = r4;
    rts;
_geq_xfade_done_C2_AUX_GEQ_03.end:

_C2_AUX_GEQ_03_process.end:
