/*----------------------------------------------------------------------
 * Aux 2 GEQ (GEQ)
 * Node ID:    C2_AUX_GEQ_02
 * Chip:       2
 * Channels:   1
 * SPI Page:   1
 * SPI Addr:   115
 * RampProfile: EqSafe
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/

/* RampProfile: EqSafe | Mode: LinearFrames | Up: 12ms (18f) Down: 12ms (18f) | Curve: Linear | Scope: CoeffSetAtomic */

/* GEQ (FIXED Q4.28, D5): 28-stage cascade, dual-instance crossfade */
/* SPI page=1 addr=115 */
/* Normative model: tools/dsp/fixed_ref.py::biquad (offset form). */

.section/dm seg_dmda;
.extern _buf_C2_AUX_EQ_02;
.global _geq_gains_C2_AUX_GEQ_02;
.var _geq_gains_C2_AUX_GEQ_02[28];              /* per-band gain (display) */

.global _geq_coeffs_A_C2_AUX_GEQ_02;
.var _geq_coeffs_A_C2_AUX_GEQ_02[140] = 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000;
.global _geq_state_A_C2_AUX_GEQ_02;
.var _geq_state_A_C2_AUX_GEQ_02[168];
.global _geq_coeffs_B_C2_AUX_GEQ_02;
.var _geq_coeffs_B_C2_AUX_GEQ_02[140] = 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000, 0x10000000, 0x20000000, 0xF0000000, 0x20000000, 0x10000000;
.global _geq_state_B_C2_AUX_GEQ_02;
.var _geq_state_B_C2_AUX_GEQ_02[168];

/* SPI staging (FLOAT RBJ words — wire format unchanged) */
.global _geq_coeffs_next_C2_AUX_GEQ_02;
.var _geq_coeffs_next_C2_AUX_GEQ_02[140];
.global _geq_swap_pending_C2_AUX_GEQ_02;
.var _geq_swap_pending_C2_AUX_GEQ_02 = 0;

.global _geq_active_C2_AUX_GEQ_02;
.var _geq_active_C2_AUX_GEQ_02 = 0;
.global _geq_xfade_alpha_C2_AUX_GEQ_02;
.var _geq_xfade_alpha_C2_AUX_GEQ_02 = 0.0;
.global _geq_xfade_step_C2_AUX_GEQ_02;
.var _geq_xfade_step_C2_AUX_GEQ_02 = 0.0;


.global _buf_C2_AUX_GEQ_02;
.var _buf_C2_AUX_GEQ_02;

.section/pm seg_pmco;
.extern _bq_fx_cascade_N;
.extern _bq_fx_convert_N;
.global _C2_AUX_GEQ_02_process;
_C2_AUX_GEQ_02_process:

    r4 = dm(_geq_swap_pending_C2_AUX_GEQ_02);
    r4 = pass r4;
    if ne call _geq_start_xfade_C2_AUX_GEQ_02;

    r4 = dm(_geq_xfade_step_C2_AUX_GEQ_02);
    r4 = pass r4;
    if ne jump (pc, .geq_xfade_C2_AUX_GEQ_02);

    /* ===== steady state ===== */
    r0 = dm(_buf_C2_AUX_EQ_02);
    r4 = dm(_geq_active_C2_AUX_GEQ_02);
    r4 = pass r4;
    if ne jump (pc, .geq_ss_b_C2_AUX_GEQ_02);
    i0 = _geq_coeffs_A_C2_AUX_GEQ_02;
    i1 = _geq_state_A_C2_AUX_GEQ_02;
    jump (pc, .geq_ss_go_C2_AUX_GEQ_02);
.geq_ss_b_C2_AUX_GEQ_02:
    i0 = _geq_coeffs_B_C2_AUX_GEQ_02;
    i1 = _geq_state_B_C2_AUX_GEQ_02;
.geq_ss_go_C2_AUX_GEQ_02:
    r4 = 28;
    call _bq_fx_cascade_N;

    dm(_buf_C2_AUX_GEQ_02) = r0;
    rts;

    /* ===== crossfade: run both, blend fixed ===== */
.geq_xfade_C2_AUX_GEQ_02:
    r0 = dm(_buf_C2_AUX_EQ_02);
    r13 = r0;                     /* input (r13-r15 preserved by lib) */
    i0 = _geq_coeffs_A_C2_AUX_GEQ_02;
    i1 = _geq_state_A_C2_AUX_GEQ_02;
    r4 = 28;
    call _bq_fx_cascade_N;
    r14 = r0;                     /* ya */
    r0 = r13;
    i0 = _geq_coeffs_B_C2_AUX_GEQ_02;
    i1 = _geq_state_B_C2_AUX_GEQ_02;
    r4 = 28;
    call _bq_fx_cascade_N;        /* r0 = yb */

    r4 = dm(_geq_active_C2_AUX_GEQ_02);
    r4 = pass r4;
    if eq jump (pc, .geq_bl_C2_AUX_GEQ_02);
    r5 = r14;                     /* active B: new is A */
    r14 = r0;
    r0 = r5;
.geq_bl_C2_AUX_GEQ_02:
    /* alpha_q31 = fix(alpha * 2^31); blend in MRF */
    f4 = dm(_geq_xfade_alpha_C2_AUX_GEQ_02);
    r5 = 0x4F000000;               /* 2^31 as float */
    f5 = r5;
    f4 = f4 * f5;
    r4 = fix f4;
    r5 = r0 - r14;                 /* new - old */
    mrf = r5 * r4 (ssi);
    r5 = 0x40000000;               /* 2^30 rounding half */
    r12 = 1;
    mrf = mrf + r5 * r12 (ssi);
    r5 = mr0f;
    r12 = mr1f;
    r5 = lshift r5 by -31;
    r12 = lshift r12 by 1;
    r5 = r5 or r12;
    r0 = r14 + r5;                 /* blended output */

    dm(_buf_C2_AUX_GEQ_02) = r0;

    /* advance alpha (float control) */
    f4 = dm(_geq_xfade_alpha_C2_AUX_GEQ_02);
    f5 = dm(_geq_xfade_step_C2_AUX_GEQ_02);
    f4 = f4 + f5;
    dm(_geq_xfade_alpha_C2_AUX_GEQ_02) = f4;
    r5 = 0x3F800000;
    f5 = r5;
    comp(f4, f5);
    if lt rts;
    r4 = dm(_geq_active_C2_AUX_GEQ_02);
    r5 = 1;
    r4 = r4 xor r5;
    dm(_geq_active_C2_AUX_GEQ_02) = r4;
    r4 = 0;
    dm(_geq_xfade_step_C2_AUX_GEQ_02) = r4;
    dm(_geq_xfade_alpha_C2_AUX_GEQ_02) = r4;
    rts;

    /* ===== stage new coeffs into dormant ===== */
_geq_start_xfade_C2_AUX_GEQ_02:
    r4 = 0;
    dm(_geq_swap_pending_C2_AUX_GEQ_02) = r4;
    i0 = _geq_coeffs_next_C2_AUX_GEQ_02;
    r4 = dm(_geq_active_C2_AUX_GEQ_02);
    r4 = pass r4;
    if ne jump (pc, .geq_st_a_C2_AUX_GEQ_02);
    i1 = _geq_coeffs_B_C2_AUX_GEQ_02;
    i2 = _geq_state_B_C2_AUX_GEQ_02;
    jump (pc, .geq_st_go_C2_AUX_GEQ_02);
.geq_st_a_C2_AUX_GEQ_02:
    i1 = _geq_coeffs_A_C2_AUX_GEQ_02;
    i2 = _geq_state_A_C2_AUX_GEQ_02;
.geq_st_go_C2_AUX_GEQ_02:
    r4 = 28;
    call _bq_fx_convert_N;
    r4 = 0;
    r5 = 168;
    lcntr = r5, do .geq_zst_C2_AUX_GEQ_02 until lce;
.geq_zst_C2_AUX_GEQ_02:
        dm(i2, 1) = r4;
    f0 = 0.001736111111111111;
    dm(_geq_xfade_step_C2_AUX_GEQ_02) = f0;
    r4 = 0;
    dm(_geq_xfade_alpha_C2_AUX_GEQ_02) = r4;
    rts;
_C2_AUX_GEQ_02_process.end:
