/*----------------------------------------------------------------------
 * Codec Aux Out (OUTPUT_TDM)
 * Node ID:    C2_CODEC_AUX_OUT
 * Chip:       2
 * Channels:   2
 * SPI Page:   1
 * SPI Addr:   1839
 * RampProfile: (none)
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/

/* OUTPUT_TDM: Write to SPORT2 slot 2 */

.section/dm seg_dmda;
.extern _buf_C2_MAIN_DLY;
.global _tx_out_slot_C2_CODEC_AUX_OUT;
.var _tx_out_slot_C2_CODEC_AUX_OUT;
.global _buf_C2_CODEC_AUX_OUT;
.var _buf_C2_CODEC_AUX_OUT;

.section/pm seg_pmco;
.global _C2_CODEC_AUX_OUT_process;
_C2_CODEC_AUX_OUT_process:
    r0 = dm(_buf_C2_MAIN_DLY);
    dm(_tx_out_slot_C2_CODEC_AUX_OUT) = r0;
    dm(_buf_C2_CODEC_AUX_OUT) = r0;
    rts;
_C2_CODEC_AUX_OUT_process.end:
