/*----------------------------------------------------------------------
 * Codec Aux Input (AUX_INPUT)
 * Node ID:    C2_CODEC_AUX_IN
 * Chip:       2
 * Channels:   2
 * SPI Page:   1
 * SPI Addr:   1818
 * RampProfile: GainFast
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/
#include "dsp_block.h"

/* RampProfile: GainFast | Mode: Slew | Up: 3ms (18f) Down: 8ms (48f) | Curve: Exp | Scope: Scalar */

/* AUX_INPUT (FIXED Q4.28, D5) */
/* SPI page=1 addr=1818 */

.section/dm seg_dmda;
.extern _buf_C2_XR_CODEC_AUX_L;
.extern _buf_C2_XR_CODEC_AUX_R;
.global _auxin_on_C2_CODEC_AUX_IN;
.var _auxin_on_C2_CODEC_AUX_IN = 0;
.global _auxin_level_C2_CODEC_AUX_IN;
.var _auxin_level_C2_CODEC_AUX_IN = 1.0;
.global _auxin_level_target_C2_CODEC_AUX_IN;
.var _auxin_level_target_C2_CODEC_AUX_IN = 1.0;
.global _auxin_level_step_C2_CODEC_AUX_IN;
.var _auxin_level_step_C2_CODEC_AUX_IN = 0.0;
.global _auxin_level_frames_C2_CODEC_AUX_IN;
.var _auxin_level_frames_C2_CODEC_AUX_IN = 0;
.global _auxin_q_C2_CODEC_AUX_IN;
.var _auxin_q_C2_CODEC_AUX_IN = 0;                  /* Q4.28 coeff x assign */
.global _buf_C2_CODEC_AUX_IN;
.var _buf_C2_CODEC_AUX_IN;

        #if DSP4_BLOCK_KERNELS
        .extern _blk_C2_XR_CODEC_AUX_L;
        .extern _blk_C2_XR_CODEC_AUX_R;
        #endif
        #if DSP4_BLOCK_KERNELS
        .global _blk_C2_CODEC_AUX_IN;
        .var _blk_C2_CODEC_AUX_IN[DSP4_BLOCK_SIZE];
        .global _bw_i_C2_CODEC_AUX_IN;
        .var _bw_i_C2_CODEC_AUX_IN;        /* sample index, across the call */
        .global _bw_k_C2_CODEC_AUX_IN;
        .var _bw_k_C2_CODEC_AUX_IN;        /* the caller's _sample_idx */
        .global _bw_s0_C2_CODEC_AUX_IN;
        .var _bw_s0_C2_CODEC_AUX_IN;       /* walking source pointer */
        .global _bw_s1_C2_CODEC_AUX_IN;
        .var _bw_s1_C2_CODEC_AUX_IN;       /* walking source pointer */
        .global _bw_d0_C2_CODEC_AUX_IN;
        .var _bw_d0_C2_CODEC_AUX_IN;       /* walking sink pointer */
        #endif

.section/pm seg_pmco;
.extern _sample_idx;
.extern _mrf_rns28;
.global _C2_CODEC_AUX_IN_process;
_C2_CODEC_AUX_IN_process:
        #if DSP4_BLOCK_KERNELS
            /* ---- generic per-block wrapper (review finding D16) ----
             * Runs the per-sample reference body BLOCK times over this
             * node's own block buffer, staging each sample through the
             * scalar _buf_ words the body already reads and writes. Same
             * arithmetic, same order, same result as the per-sample
             * build; what it removes is the chain's call/rts and the
             * _sample_idx guard being re-evaluated from the chain.
             */
            i4 = _blk_C2_XR_CODEC_AUX_L;
            r3 = i4;
            dm(_bw_s0_C2_CODEC_AUX_IN) = r3;
            i4 = _blk_C2_XR_CODEC_AUX_R;
            r3 = i4;
            dm(_bw_s1_C2_CODEC_AUX_IN) = r3;
            i4 = _blk_C2_CODEC_AUX_IN;
            r3 = i4;
            dm(_bw_d0_C2_CODEC_AUX_IN) = r3;
            r5 = dm(_sample_idx);
            dm(_bw_k_C2_CODEC_AUX_IN) = r5;
            r5 = 0;
            dm(_bw_i_C2_CODEC_AUX_IN) = r5;
            lcntr = DSP4_BLOCK_SIZE, do .bwlp_C2_CODEC_AUX_IN until lce;
                r5 = dm(_bw_i_C2_CODEC_AUX_IN);
                dm(_sample_idx) = r5;
                r3 = dm(_bw_s0_C2_CODEC_AUX_IN);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_XR_CODEC_AUX_L) = r0;
                r3 = r3 + 1;
                dm(_bw_s0_C2_CODEC_AUX_IN) = r3;
                r3 = dm(_bw_s1_C2_CODEC_AUX_IN);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_XR_CODEC_AUX_R) = r0;
                r3 = r3 + 1;
                dm(_bw_s1_C2_CODEC_AUX_IN) = r3;
                call _C2_CODEC_AUX_IN_process_sample;
                r0 = dm(_buf_C2_CODEC_AUX_IN);
                r3 = dm(_bw_d0_C2_CODEC_AUX_IN);
                i4 = r3;
                dm(i4, 0) = r0;
                r3 = r3 + 1;
                dm(_bw_d0_C2_CODEC_AUX_IN) = r3;
                r5 = dm(_bw_i_C2_CODEC_AUX_IN);
                r5 = r5 + 1;
            .bwlp_C2_CODEC_AUX_IN: dm(_bw_i_C2_CODEC_AUX_IN) = r5;
            r5 = dm(_bw_k_C2_CODEC_AUX_IN);
            dm(_sample_idx) = r5;
            rts;

        .global _C2_CODEC_AUX_IN_process_sample;
        _C2_CODEC_AUX_IN_process_sample:
        #endif
    /* CONTROL RATE (08-25 crosspoint-coefficient mandate). This
     * node used to advance its ramp, multiply by 2^28 and FIX the
     * result on EVERY SAMPLE -- coefficient prep sitting in the
     * audio path, thirty-two times per block -- and then test the
     * input-assign bit per sample as well. Both are control state:
     * the coefficient is prepared once per block with the assign
     * bit folded in, and the sample path is one MAC.
     *
     * The frame count is consumed 32 at a time to keep the ramp
     * DURATION identical now that it advances once per block; the
     * same correction GAIN and FADER_PAN carry (2026-08-23). */
        /* LIVE IN BOTH BUILDS (review finding D16). The block wrapper
         * below drives _sample_idx 0..BLOCK-1 before each call into this
         * body, so the guard fires exactly ONCE per block and the
         * block-rate work behind it -- the parameter conversion, and the
         * float ramps that consume a BLOCK's worth of frames at a time --
         * runs once and not BLOCK times. Removing it, which is right for
         * a node the chain reaches once per block with the index left at
         * BLOCK-1, would run the whole conversion on every sample. */
    r4 = dm(_sample_idx);
    r1 = 0;
    comp(r4, r1);
    if ne jump (pc, .auxin_apply_C2_CODEC_AUX_IN);
    r4 = dm(_auxin_level_frames_C2_CODEC_AUX_IN);
    r15 = DSP4_BLOCK_SIZE;
    r4 = r4 - r15;
    if le jump (pc, .no_auxramp_C2_CODEC_AUX_IN);
    dm(_auxin_level_frames_C2_CODEC_AUX_IN) = r4;
    f1 = dm(_auxin_level_C2_CODEC_AUX_IN);
    f2 = dm(_auxin_level_step_C2_CODEC_AUX_IN);
    r15 = DSP4_BLOCK_F32;             /* BLOCK_SIZE as float */
    f15 = r15;
    f2 = f2 * f15;
    f1 = f1 + f2;
    dm(_auxin_level_C2_CODEC_AUX_IN) = f1;
    jump (pc, .auxin_go_C2_CODEC_AUX_IN);
.no_auxramp_C2_CODEC_AUX_IN:
    f1 = dm(_auxin_level_target_C2_CODEC_AUX_IN);
    dm(_auxin_level_C2_CODEC_AUX_IN) = f1;
.auxin_go_C2_CODEC_AUX_IN:
    r2 = 0x4D800000;
    f2 = r2;
    f1 = f1 * f2;
    r1 = fix f1;
    /* fold the input-assign bit INTO the coefficient */
    r3 = 0;
    r2 = dm(_auxin_on_C2_CODEC_AUX_IN);
    r2 = pass r2;
    if eq r1 = r3;
    dm(_auxin_q_C2_CODEC_AUX_IN) = r1;

.auxin_apply_C2_CODEC_AUX_IN:
    r0 = dm(_buf_C2_XR_CODEC_AUX_L);
    r1 = dm(_auxin_q_C2_CODEC_AUX_IN);
    mrf = r0 * r1 (ssi);
    call _mrf_rns28;
    dm(_buf_C2_CODEC_AUX_IN) = r0;
    rts;
_C2_CODEC_AUX_IN_process.end:
