/*----------------------------------------------------------------------
 * DCA 6 (DCA)
 * Node ID:    C2_DCA_06
 * Chip:       2
 * Channels:   1
 * SPI Page:   1
 * SPI Addr:   1772
 * RampProfile: GainFast
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/

/* RampProfile: GainFast | Mode: Slew | Up: 3ms (4f) Down: 8ms (12f) | Curve: Exp | Scope: Scalar */

/* DCA: Control-only master (no audio path) */
/* Level/Mute scalar: multiplied into all assigned member faders */
/* SPI page=1 addr=1772 */

.section/dm seg_dmda;
.global _dca_level_C2_DCA_06;
.var _dca_level_C2_DCA_06 = 1.0;
.global _dca_level_target_C2_DCA_06;
.var _dca_level_target_C2_DCA_06 = 1.0;
.global _dca_level_step_C2_DCA_06;
.var _dca_level_step_C2_DCA_06 = 0.0;
.global _dca_level_frames_C2_DCA_06;
.var _dca_level_frames_C2_DCA_06 = 0;
.global _dca_mute_C2_DCA_06;
.var _dca_mute_C2_DCA_06 = 0;

.section/pm seg_pmco;
.global _C2_DCA_06_process;
_C2_DCA_06_process:
    /* Ramp DCA level */
    r4 = dm(_dca_level_frames_C2_DCA_06);
    r15 = 1;
    r4 = r4 - r15;
    if le jump (pc, .no_dcaramp_C2_DCA_06);
    dm(_dca_level_frames_C2_DCA_06) = r4;
    f1 = dm(_dca_level_C2_DCA_06);
    f2 = dm(_dca_level_step_C2_DCA_06);
    f1 = f1 + f2;
    dm(_dca_level_C2_DCA_06) = f1;
    jump (pc, .dca_done_C2_DCA_06);
.no_dcaramp_C2_DCA_06:
    f1 = dm(_dca_level_target_C2_DCA_06);
    dm(_dca_level_C2_DCA_06) = f1;
.dca_done_C2_DCA_06:
    /* DCA does not process audio — level is read by member faders */
    rts;
_C2_DCA_06_process.end:
