/*----------------------------------------------------------------------
 * FX 6 Engine (FX_ENGINE)
 * Node ID:    C2_FX_ENG_06
 * Chip:       2
 * Channels:   2
 * SPI Page:   1
 * SPI Addr:   1721
 * RampProfile: GainSafe
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/
#include "dsp_block.h"

/* RampProfile: GainSafe | Mode: Slew | Up: 10ms (60f) Down: 30ms (180f) | Curve: Exp | Scope: Scalar */

/* FX_ENGINE [reverb]: effects processor */
/* SPI page=1 addr=1721 */
/* Default type: Reverb */
/* fx_class=reverb */

.section/dm seg_dmda;
.extern _buf_C2_RECV_FX_06;
.extern _sample_idx;
.global _fx_on_C2_FX_ENG_06;
.var _fx_on_C2_FX_ENG_06 = 1;
.global _fx_type_C2_FX_ENG_06;
.var _fx_type_C2_FX_ENG_06 = 0;           /* 0=Echo,1=PingPong,2=Doubling,3=Reverb,4=Chorus,5=Flanger,6=Phaser */
.global _fx_decay_C2_FX_ENG_06;
.var _fx_decay_C2_FX_ENG_06;
.global _fx_predelay_C2_FX_ENG_06;
.var _fx_predelay_C2_FX_ENG_06;
.global _fx_delay_ms_C2_FX_ENG_06;
.var _fx_delay_ms_C2_FX_ENG_06;
.global _fx_feedback_C2_FX_ENG_06;
.var _fx_feedback_C2_FX_ENG_06;
.global _fx_balance_C2_FX_ENG_06;
.var _fx_balance_C2_FX_ENG_06;
.global _fx_damp_C2_FX_ENG_06;
.var _fx_damp_C2_FX_ENG_06;
.global _fx_eq_lo_C2_FX_ENG_06;
.var _fx_eq_lo_C2_FX_ENG_06;
.global _fx_eq_mid_C2_FX_ENG_06;
.var _fx_eq_mid_C2_FX_ENG_06;
.global _fx_eq_hi_C2_FX_ENG_06;
.var _fx_eq_hi_C2_FX_ENG_06;
.global _fx_hpf_coeffs_C2_FX_ENG_06;
.var _fx_hpf_coeffs_C2_FX_ENG_06[5];
.global _fx_mod_rate_C2_FX_ENG_06;
.var _fx_mod_rate_C2_FX_ENG_06;
.global _fx_mod_level_C2_FX_ENG_06;
.var _fx_mod_level_C2_FX_ENG_06;
.global _fx_lfo_shape_C2_FX_ENG_06;
.var _fx_lfo_shape_C2_FX_ENG_06 = 0;      /* 0=sine, 1=triangle */
.global _fx_width_C2_FX_ENG_06;
.var _fx_width_C2_FX_ENG_06;
.global _fx_mix_C2_FX_ENG_06;
.var _fx_mix_C2_FX_ENG_06;
.global _fx_mix_target_C2_FX_ENG_06;
.var _fx_mix_target_C2_FX_ENG_06;
.global _fx_mix_step_C2_FX_ENG_06;
.var _fx_mix_step_C2_FX_ENG_06 = 0.0;
.global _fx_mix_frames_C2_FX_ENG_06;
.var _fx_mix_frames_C2_FX_ENG_06 = 0;
.global _fx_duck_on_C2_FX_ENG_06;
.var _fx_duck_on_C2_FX_ENG_06 = 0;
.global _fx_duck_sens_C2_FX_ENG_06;
.var _fx_duck_sens_C2_FX_ENG_06;

/* LFO state */
.global _fx_lfo_phase_C2_FX_ENG_06;
.var _fx_lfo_phase_C2_FX_ENG_06 = 0.0;
.global _fx_scratch_C2_FX_ENG_06;
.var _fx_scratch_C2_FX_ENG_06;

/* Reverb buffers (seg_delay for large arrays) */
.section/dm seg_delay;
.global _fx_comb_buf_L_C2_FX_ENG_06;
.var _fx_comb_buf_L_C2_FX_ENG_06[11024];
.global _fx_comb_buf_R_C2_FX_ENG_06;
.var _fx_comb_buf_R_C2_FX_ENG_06[11024];
.global _fx_allpass_buf_L_C2_FX_ENG_06;
.var _fx_allpass_buf_L_C2_FX_ENG_06[1563];
.global _fx_allpass_buf_R_C2_FX_ENG_06;
.var _fx_allpass_buf_R_C2_FX_ENG_06[1563];
.section/dm seg_dmda;
.global _fx_rv_comb_wptrs_C2_FX_ENG_06;
.var _fx_rv_comb_wptrs_C2_FX_ENG_06[8];
.global _fx_rv_comb_lpfs_C2_FX_ENG_06;
.var _fx_rv_comb_lpfs_C2_FX_ENG_06[8];
.global _fx_rv_comb_lens_C2_FX_ENG_06;
.var _fx_rv_comb_lens_C2_FX_ENG_06[8] = 1557, 1617, 1491, 1422, 1277, 1356, 1188, 1116;
.global _fx_rv_comb_ofs_C2_FX_ENG_06;
.var _fx_rv_comb_ofs_C2_FX_ENG_06[8] = 0, 1557, 3174, 4665, 6087, 7364, 8720, 9908;
.global _fx_rv_ap_wptrs_C2_FX_ENG_06;
.var _fx_rv_ap_wptrs_C2_FX_ENG_06[4];
.global _fx_rv_ap_lens_C2_FX_ENG_06;
.var _fx_rv_ap_lens_C2_FX_ENG_06[4] = 556, 441, 341, 225;
.global _fx_rv_ap_ofs_C2_FX_ENG_06;
.var _fx_rv_ap_ofs_C2_FX_ENG_06[4] = 0, 556, 997, 1338;
/* Tiny state buf for phaser fallback */
.global _fx_echo_buf_C2_FX_ENG_06;
.var _fx_echo_buf_C2_FX_ENG_06[8];
.global _fx_echo_wptr_C2_FX_ENG_06;
.var _fx_echo_wptr_C2_FX_ENG_06 = 0;

.global _buf_L_C2_FX_ENG_06;
.var _buf_L_C2_FX_ENG_06;
.global _buf_R_C2_FX_ENG_06;
.var _buf_R_C2_FX_ENG_06;
.global _buf_C2_FX_ENG_06;
.var _buf_C2_FX_ENG_06;

        #if DSP4_BLOCK_KERNELS
        .extern _blk_C2_RECV_FX_06;
        #endif
        #if DSP4_BLOCK_KERNELS
        .global _blk_C2_FX_ENG_06;
        .var _blk_C2_FX_ENG_06[DSP4_BLOCK_SIZE];
        .global _bw_i_C2_FX_ENG_06;
        .var _bw_i_C2_FX_ENG_06;        /* sample index, across the call */
        .global _bw_k_C2_FX_ENG_06;
        .var _bw_k_C2_FX_ENG_06;        /* the caller's _sample_idx */
        .global _bw_s0_C2_FX_ENG_06;
        .var _bw_s0_C2_FX_ENG_06;       /* walking source pointer */
        .global _bw_d0_C2_FX_ENG_06;
        .var _bw_d0_C2_FX_ENG_06;       /* walking sink pointer */
        #endif

.section/pm seg_pmco;
.global _C2_FX_ENG_06_process;
_C2_FX_ENG_06_process:
        #if DSP4_BLOCK_KERNELS
            /* ---- generic per-block wrapper (review finding D16) ----
             * Runs the per-sample reference body BLOCK times over this
             * node's own block buffer, staging each sample through the
             * scalar _buf_ words the body already reads and writes. Same
             * arithmetic, same order, same result as the per-sample
             * build; what it removes is the chain's call/rts and the
             * _sample_idx guard being re-evaluated from the chain.
             */
            i4 = _blk_C2_RECV_FX_06;
            r3 = i4;
            dm(_bw_s0_C2_FX_ENG_06) = r3;
            i4 = _blk_C2_FX_ENG_06;
            r3 = i4;
            dm(_bw_d0_C2_FX_ENG_06) = r3;
            r5 = dm(_sample_idx);
            dm(_bw_k_C2_FX_ENG_06) = r5;
            r5 = 0;
            dm(_bw_i_C2_FX_ENG_06) = r5;
            lcntr = DSP4_BLOCK_SIZE, do .bwlp_C2_FX_ENG_06 until lce;
                r5 = dm(_bw_i_C2_FX_ENG_06);
                dm(_sample_idx) = r5;
                r3 = dm(_bw_s0_C2_FX_ENG_06);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_RECV_FX_06) = r0;
                r3 = r3 + 1;
                dm(_bw_s0_C2_FX_ENG_06) = r3;
                call _C2_FX_ENG_06_process_sample;
                r0 = dm(_buf_C2_FX_ENG_06);
                r3 = dm(_bw_d0_C2_FX_ENG_06);
                i4 = r3;
                dm(i4, 0) = r0;
                r3 = r3 + 1;
                dm(_bw_d0_C2_FX_ENG_06) = r3;
                r5 = dm(_bw_i_C2_FX_ENG_06);
                r5 = r5 + 1;
            .bwlp_C2_FX_ENG_06: dm(_bw_i_C2_FX_ENG_06) = r5;
            r5 = dm(_bw_k_C2_FX_ENG_06);
            dm(_sample_idx) = r5;
            rts;

        .global _C2_FX_ENG_06_process_sample;
        _C2_FX_ENG_06_process_sample:
        #endif
    /* Ramp mix level */
    r4 = dm(_fx_mix_frames_C2_FX_ENG_06);
    r15 = 1;
    r4 = r4 - r15;
    if le jump (pc, .no_fxramp_C2_FX_ENG_06);
    dm(_fx_mix_frames_C2_FX_ENG_06) = r4;
    f1 = dm(_fx_mix_C2_FX_ENG_06);
    f2 = dm(_fx_mix_step_C2_FX_ENG_06);
    f1 = f1 + f2;
    dm(_fx_mix_C2_FX_ENG_06) = f1;
    jump (pc, .fx_dispatch_C2_FX_ENG_06);
.no_fxramp_C2_FX_ENG_06:
    f1 = dm(_fx_mix_target_C2_FX_ENG_06);
    dm(_fx_mix_C2_FX_ENG_06) = f1;
.fx_dispatch_C2_FX_ENG_06:

    /* Load input */
    r0 = dm(_buf_C2_RECV_FX_06);
    /* float island entry: Q4.28 -> float32 (D5) */
    r1 = -28;
    f0 = float r0 by r1;
    f15 = f0;                   /* dry input saved in f15 */

    /* Dispatch on algorithm type */
    r0 = dm(_fx_type_C2_FX_ENG_06);

r1 = 3; comp(r0, r1); if eq jump (pc, .fx_reverb_C2_FX_ENG_06);
r1 = 2; comp(r0, r1); if eq jump (pc, .fx_doubling_C2_FX_ENG_06);
jump (pc, .fx_passthru_C2_FX_ENG_06);

/* ===================== DOUBLING ===================== */
.fx_doubling_C2_FX_ENG_06:
    /* Short fixed delay for thickening (15ms = 720 samples) */
    r1 = dm(_fx_echo_wptr_C2_FX_ENG_06);
    r5 = 720;
    r3 = r1 - r5;
    r4 = 8;
    if lt r3 = r3 + r4;
    i0 = _fx_echo_buf_C2_FX_ENG_06;
    m0 = r3;
    modify(i0, m0);
    f13 = dm(i0, 0);
    /* Write input to delay buffer */
    i0 = _fx_echo_buf_C2_FX_ENG_06;
    m0 = r1;
    modify(i0, m0);
    dm(i0, 0) = f15;
    r15 = 1;
    r1 = r1 + r15;
    comp(r1, r4);
    if ge r1 = r1 - r4;
    dm(_fx_echo_wptr_C2_FX_ENG_06) = r1;
    f0 = f13;
    jump (pc, .fx_mix_C2_FX_ENG_06);

/* ===================== REVERB ===================== */
.fx_reverb_C2_FX_ENG_06:
    /* Freeverb: 8 parallel comb-LPF + 4 series allpass */
    r14 = 0x00000000;  /* 0.0 IEEE 754 */                   /* comb sum accumulator */
    i3 = _fx_rv_comb_wptrs_C2_FX_ENG_06;
    i4 = _fx_rv_comb_lens_C2_FX_ENG_06;
    i5 = _fx_rv_comb_ofs_C2_FX_ENG_06;
    i6 = _fx_rv_comb_lpfs_C2_FX_ENG_06;
    f10 = dm(_fx_feedback_C2_FX_ENG_06); /* comb feedback */
    f11 = dm(_fx_damp_C2_FX_ENG_06);     /* damp1 */
    r12 = 0x3F800000;  /* 1.0 IEEE 754 */
    f12 = f12 - f11;             /* damp2 = 1 - damp1 */
    r5 = 8;
    lcntr = r5; do .rv_comb_C2_FX_ENG_06 until lce;
        r1 = dm(i3, 0);           /* wptr (peek) */
        r2 = dm(i4, 1);           /* comb length */
        r3 = dm(i5, 1);           /* base offset into comb buffer */
        /* Read delayed sample */
        r4 = r3 + r1;
        i0 = _fx_comb_buf_L_C2_FX_ENG_06;
        m0 = r4;
        modify(i0, m0);
        f1 = dm(i0, 0);           /* delayed sample */
        /* LPF: filt = damp1*delayed + damp2*prev */
        f4 = dm(i6, 0);           /* prev LP state */
        f5 = f11 * f1;
        f6 = f12 * f4;
        f5 = f5 + f6;
        dm(i6, 1) = f5;           /* store LP, advance i6 */
        /* Write: input + feedback * filtered */
        f7 = f10 * f5;
        f8 = f15 + f7;
        dm(i0, 0) = f8;           /* i0 still at same position */
        /* Advance wptr with wrap */
        r15 = 1;
        r1 = r1 + r15;
        comp(r1, r2);
        if ge r1 = r1 - r2;
        dm(i3, 1) = r1;           /* store, advance i3 */
        /* Accumulate */
        f14 = f14 + f1;
    .rv_comb_C2_FX_ENG_06:

    /* Scale comb sum */
    f0 = f14;
    f1 = 0.125;                  /* 1/8 */
    f0 = f0 * f1;

    /* 4 series allpass */
    i3 = _fx_rv_ap_wptrs_C2_FX_ENG_06;
    i4 = _fx_rv_ap_lens_C2_FX_ENG_06;
    i5 = _fx_rv_ap_ofs_C2_FX_ENG_06;
    r10 = 0x3F000000;  /* 0.5 IEEE 754 */                   /* allpass feedback */
    r5 = 4;
    lcntr = r5; do .rv_ap_C2_FX_ENG_06 until lce;
        r1 = dm(i3, 0);
        r2 = dm(i4, 1);
        r3 = dm(i5, 1);
        r4 = r3 + r1;
        i0 = _fx_allpass_buf_L_C2_FX_ENG_06;
        m0 = r4;
        modify(i0, m0);
        f1 = dm(i0, 0);           /* buf_out */
        /* Write: in + fb * buf_out */
        f2 = f10 * f1;
        f3 = f0 + f2;
        dm(i0, 0) = f3;
        /* Advance wptr */
        r15 = 1;
        r1 = r1 + r15;
        comp(r1, r2);
        if ge r1 = r1 - r2;
        dm(i3, 1) = r1;
        /* Output: buf_out - input */
        f0 = f1 - f0;
    .rv_ap_C2_FX_ENG_06:
        nop;

    /* f0 = reverb output */
    jump (pc, .fx_mix_C2_FX_ENG_06);

/* ===================== PASSTHROUGH ===================== */
.fx_passthru_C2_FX_ENG_06:
    f0 = f15;                    /* dry pass-through */

/* ===================== DRY/WET MIX ===================== */
.fx_mix_C2_FX_ENG_06:
    /* f0 = wet, f15 = dry */
    f7 = dm(_fx_mix_C2_FX_ENG_06);
    r8 = 0x3F800000;  /* 1.0 IEEE 754 */
    f8 = f8 - f7;               /* 1 - mix */
    f0 = f0 * f7;               /* wet * mix */
    f1 = f15 * f8;              /* dry * (1-mix) */
    f0 = f0 + f1;
    dm(_buf_L_C2_FX_ENG_06) = r0;
    /* float island exit: float32 -> Q4.28 (D5) */
    r1 = 0x4D800000;
    f1 = r1;
    f0 = f0 * f1;
    r0 = fix f0;
    dm(_buf_C2_FX_ENG_06) = r0;
    rts;
_C2_FX_ENG_06_process.end:
