/*----------------------------------------------------------------------
 * Grp 4 Comp (COMPRESSOR)
 * Node ID:    C2_GRP_COMP_04
 * Chip:       2
 * Channels:   1
 * SPI Page:   1
 * SPI Addr:   1268
 * RampProfile: DynSafe
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/

        /* RampProfile: DynSafe | Mode: LinearFrames | Up: 6ms (9f) Down: 20ms (30f) | Curve: Exp | Scope: Scalar */

        /* COMPRESSOR (FIXED Q4.28, D5) */
        /* SPI page=1 addr=1268 */

#include "blk_pool.h"

.section/dm seg_dmda;
.extern _buf_C2_GRP_GATE_04;
        .global _comp_on_C2_GRP_COMP_04;
        .var _comp_on_C2_GRP_COMP_04 = 1;
        .global _comp_threshold_C2_GRP_COMP_04;
        .var _comp_threshold_C2_GRP_COMP_04 = -20.0;
        .global _comp_ratio_C2_GRP_COMP_04;
        .var _comp_ratio_C2_GRP_COMP_04 = 4.0;
        .global _comp_attack_C2_GRP_COMP_04;
        .var _comp_attack_C2_GRP_COMP_04 = 0.01;
        .global _comp_release_C2_GRP_COMP_04;
        .var _comp_release_C2_GRP_COMP_04 = 0.001;
        .global _comp_makeup_C2_GRP_COMP_04;
        .var _comp_makeup_C2_GRP_COMP_04 = 1.0;
        .global _comp_makeup_target_C2_GRP_COMP_04;
        .var _comp_makeup_target_C2_GRP_COMP_04 = 1.0;
        .global _comp_makeup_step_C2_GRP_COMP_04;
        .var _comp_makeup_step_C2_GRP_COMP_04 = 0.0;
        .global _comp_makeup_frames_C2_GRP_COMP_04;
        .var _comp_makeup_frames_C2_GRP_COMP_04 = 0;
        .global _comp_knee_C2_GRP_COMP_04;
        .var _comp_knee_C2_GRP_COMP_04 = 0.0;   /* hard knee until the host sets it */
        .global _comp_parallel_C2_GRP_COMP_04;
        .var _comp_parallel_C2_GRP_COMP_04 = 0.0;
        .global _comp_type_C2_GRP_COMP_04;
        .var _comp_type_C2_GRP_COMP_04 = 0;
        .global _comp_key_src_C2_GRP_COMP_04;
        .var _comp_key_src_C2_GRP_COMP_04 = 0;
        .global _comp_det_src_C2_GRP_COMP_04;
        .var _comp_det_src_C2_GRP_COMP_04 = 0;
        .global _comp_eq_pos_C2_GRP_COMP_04;
        .var _comp_eq_pos_C2_GRP_COMP_04 = 0;
        .global _comp_lim_mode_C2_GRP_COMP_04;
        .var _comp_lim_mode_C2_GRP_COMP_04 = 0;
        .global _comp_filter_on_C2_GRP_COMP_04;
        .var _comp_filter_on_C2_GRP_COMP_04 = 0;
        .global _comp_filter_coeffs_C2_GRP_COMP_04;
        .var _comp_filter_coeffs_C2_GRP_COMP_04[10];
        .global _comp_filter_state_C2_GRP_COMP_04;
        .var _comp_filter_state_C2_GRP_COMP_04[4];
        .global _comp_envelope_C2_GRP_COMP_04;
        .var _comp_envelope_C2_GRP_COMP_04 = 0;        /* Q4.28 */
        .global _comp_gain_C2_GRP_COMP_04;
        .var _comp_gain_C2_GRP_COMP_04 = 0x10000000;   /* Q4.28 (display) */
        .global _comp_attq_C2_GRP_COMP_04;
        .var _comp_attq_C2_GRP_COMP_04 = 0;
        .global _comp_relq_C2_GRP_COMP_04;
        .var _comp_relq_C2_GRP_COMP_04 = 0;
        .global _comp_mkq_C2_GRP_COMP_04;
        .var _comp_mkq_C2_GRP_COMP_04 = 0x10000000;
        .global _comp_parq_C2_GRP_COMP_04;
        .var _comp_parq_C2_GRP_COMP_04 = 0;            /* Q0.31 */
        .global _comp_cgp_C2_GRP_COMP_04;
        .var _comp_cgp_C2_GRP_COMP_04[4];              /* thr, slope, halfk, k2 */
        .global _buf_C2_GRP_COMP_04;
        .var _buf_C2_GRP_COMP_04;

#if DSP4_BLOCK_KERNELS
.global _comp_saved_idx_C2_GRP_COMP_04;
.var _comp_saved_idx_C2_GRP_COMP_04;
#endif
        .section/pm seg_pmco;
        .extern _sample_idx;
        .extern _envq_fx;
        .extern _compgain_fx;
        .extern _mrf_rns28;
        .global _C2_GRP_COMP_04_process;
        _C2_GRP_COMP_04_process:

            r0 = dm(_buf_C2_GRP_GATE_04);
            r2 = dm(_comp_on_C2_GRP_COMP_04);
            r3 = 0;
            comp(r2, r3);
            if eq jump (pc, .comp_bypass_C2_GRP_COMP_04);
            r13 = r0;                     /* dry (r13-r15 lib-safe) */
        #if DSP4_COMP_NOCVT
            jump (pc, .comp_go_C2_GRP_COMP_04);   /* TEMP bisect: skip block-rate cvt */
        #endif

            /* --- block rate: makeup ramp + param conversion --- */
        /* Per-sample builds only. Under DSP4_BLOCK_KERNELS this node has no
         * block kernel, the chain reaches it once per block with _sample_idx
         * at 31, and a surviving guard would never fire -- the parameters
         * below would never convert and the node would run on its .var
         * initialisers. */
        #if !DSP4_BLOCK_KERNELS
            r4 = dm(_sample_idx);
            r1 = 0;
            comp(r4, r1);
            if ne jump (pc, .comp_go_C2_GRP_COMP_04);
        #endif

            r4 = dm(_comp_makeup_frames_C2_GRP_COMP_04);
            comp(r4, r1);
            if le jump (pc, .no_mramp_C2_GRP_COMP_04);
            /* Consume a BLOCK's worth of frames and apply a BLOCK's
             * worth of step. spi_handler scales every profile frame count
             * by 32 (BLOCK_SIZE), which is right for the ramps that
             * decrement once per SAMPLE. This one decrements once per
             * BLOCK, so taking 1 per block ran it 32x long: measured
             * 2026-08-23, a GainSafe down-ramp took 960 ms against the
             * 30 ms its own cell table specifies, and a GainFast fader
             * move took 85 ms instead of 3 ms. 32.0f is exact in binary,
             * so scaling the step loses nothing. */
            r5 = 32;
            r4 = r4 - r5;
            dm(_comp_makeup_frames_C2_GRP_COMP_04) = r4;
            f1 = dm(_comp_makeup_C2_GRP_COMP_04);
            f2 = dm(_comp_makeup_step_C2_GRP_COMP_04);
            r5 = 0x42000000;                  /* 32.0f */
            f5 = r5;
            f2 = f2 * f5;
            f1 = f1 + f2;
            dm(_comp_makeup_C2_GRP_COMP_04) = f1;
            jump (pc, .comp_cvt_C2_GRP_COMP_04);
        .no_mramp_C2_GRP_COMP_04:
            f1 = dm(_comp_makeup_target_C2_GRP_COMP_04);
            dm(_comp_makeup_C2_GRP_COMP_04) = f1;
        .comp_cvt_C2_GRP_COMP_04:
            r2 = 0x4D800000;
            f2 = r2;
            f1 = f1 * f2;
            r1 = fix f1;
            dm(_comp_mkq_C2_GRP_COMP_04) = r1;
            f1 = dm(_comp_parallel_C2_GRP_COMP_04);
            r2 = 0x4F000000;
            f2 = r2;
            f1 = f1 * f2;
            r1 = fix f1;
            /* CLAMP. parallel = 1.0 scales to 2^31, which int32 cannot
             * hold: `fix` wrapped and stored -1, so in Q0.31 the MAXIMUM
             * parallel setting blended in essentially nothing and the
             * compressor went fully DRY -- the same output as
             * parallel = 0, with a working compressor sitting behind it.
             * Bench 2026-08-23: par 0.999 settled at -16.49 dBFS on a
             * -6.02 dBFS step, par 1.0 returned the input untouched. */
            r3 = 0;
            r2 = 0x7FFFFFFF;
            comp(r1, r3);
            if lt r1 = pass r2;
            dm(_comp_parq_C2_GRP_COMP_04) = r1;
            r2 = 0x4F000000;              /* 2^31 float */
            f2 = r2;
            f1 = dm(_comp_attack_C2_GRP_COMP_04);
            f1 = f1 * f2;
            r1 = fix f1;
            dm(_comp_attq_C2_GRP_COMP_04) = r1;
            f1 = dm(_comp_release_C2_GRP_COMP_04);
            f1 = f1 * f2;
            r1 = fix f1;
            dm(_comp_relq_C2_GRP_COMP_04) = r1;
            r2 = 0x4AAA152D;            /* dB -> Q6.25 log2 */
            f2 = r2;
            f1 = dm(_comp_threshold_C2_GRP_COMP_04);
            f1 = f1 * f2;
            r1 = fix f1;
            dm(_comp_cgp_C2_GRP_COMP_04) = r1;    /* thr */
            /* slope = 1 - 1/ratio */
            f6 = dm(_comp_ratio_C2_GRP_COMP_04);
            f7 = recips f6;
            f8 = f6 * f7;
            r10 = 0x40000000;
            f8 = f10 - f8;
            f7 = f7 * f8;
            f8 = f6 * f7;
            f8 = f10 - f8;
            f6 = f7 * f8;
            r2 = 0x3F800000;
            f5 = r2;
            f5 = f5 - f6;                 /* slope float */
            r2 = 0x4F000000;
            f2 = r2;
            f1 = f5 * f2;
            r1 = fix f1;
            dm(_comp_cgp_C2_GRP_COMP_04 + 1) = r1;
            /* knee: halfk = knee_db/2 in Q6.25 log2; k2 = slope*K/(2*knee) Q6.25 */
            f4 = dm(_comp_knee_C2_GRP_COMP_04);
            r2 = 0x3DCCCCCD;              /* 0.1 dB min for soft path */
            f3 = r2;
            comp(f4, f3);
            if gt jump (pc, .comp_soft_C2_GRP_COMP_04);
            r1 = 0;
            dm(_comp_cgp_C2_GRP_COMP_04 + 2) = r1;
            dm(_comp_cgp_C2_GRP_COMP_04 + 3) = r1;
            jump (pc, .comp_kdone_C2_GRP_COMP_04);
        .comp_soft_C2_GRP_COMP_04:
            r2 = 0x4AAA152D;
            f2 = r2;
            f1 = f4 * f2;
            r2 = 0x3F000000;              /* 0.5 */
            f3 = r2;
            f1 = f1 * f3;
            r1 = fix f1;
            dm(_comp_cgp_C2_GRP_COMP_04 + 2) = r1;  /* halfk */
            f7 = recips f4;
            f8 = f4 * f7;
            r10 = 0x40000000;
            f8 = f10 - f8;
            f7 = f7 * f8;
            f8 = f4 * f7;
            f8 = f10 - f8;
            f6 = f7 * f8;
            r2 = 0x4040A8C1;             /* K/2 */
            f3 = r2;
            f6 = f6 * f3;                 /* K/(2*knee_db) */
            f6 = f6 * f5;                 /* * slope */
            r2 = 0x4C000000;              /* 2^25 float */
            f2 = r2;
            f1 = f6 * f2;
            r1 = fix f1;
            dm(_comp_cgp_C2_GRP_COMP_04 + 3) = r1;  /* k2 */
        .comp_kdone_C2_GRP_COMP_04:
        .comp_go_C2_GRP_COMP_04:

            /* --- envelope (fixed) --- */
            r0 = abs r13;
            r1 = dm(_comp_envelope_C2_GRP_COMP_04);
            r2 = dm(_comp_attq_C2_GRP_COMP_04);
            r3 = dm(_comp_relq_C2_GRP_COMP_04);
            call _envq_fx;
            dm(_comp_envelope_C2_GRP_COMP_04) = r0;

            /* --- gain computer (log2 domain) --- */
            i0 = _comp_cgp_C2_GRP_COMP_04;
            call _compgain_fx;            /* r0 = gain Q4.28 */
            dm(_comp_gain_C2_GRP_COMP_04) = r0;

            /* wet = dry * gain * makeup */
            r1 = r0;
            r0 = r13;
            mrf = r0 * r1 (ssi);
            call _mrf_rns28;
            r1 = dm(_comp_mkq_C2_GRP_COMP_04);
            mrf = r0 * r1 (ssi);
            call _mrf_rns28;

            /* parallel: out = dry + par*(wet - dry) — matches the float
             * node exactly (par==0 -> dry, its default behaviour) */
            r5 = r0 - r13;
            r4 = dm(_comp_parq_C2_GRP_COMP_04);
            mrf = r5 * r4 (ssi);
            r1 = 0x40000000;
            r12 = 1;
            mrf = mrf + r1 * r12 (ssi);
            r1 = mr0f;
            r12 = mr1f;
            r1 = lshift r1 by -31;
            r12 = lshift r12 by 1;
            r1 = r1 or r12;
            r0 = r13 + r1;
            dm(_buf_C2_GRP_COMP_04) = r0;
            rts;
        .comp_bypass_C2_GRP_COMP_04:
            dm(_buf_C2_GRP_COMP_04) = r0;
            rts;
        _C2_GRP_COMP_04_process.end:
