/*----------------------------------------------------------------------
 * Grp 1 Gate (GATE)
 * Node ID:    C2_GRP_GATE_01
 * Chip:       2
 * Channels:   1
 * SPI Page:   1
 * SPI Addr:   1072
 * RampProfile: DynSafe
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/
#include "dsp_block.h"

/* RampProfile: DynSafe | Mode: LinearFrames | Up: 6ms (36f) Down: 20ms (120f) | Curve: Exp | Scope: Scalar */

/* GATE (FIXED Q4.28, D5) */
/* SPI page=1 addr=1072 */

#include "blk_pool.h"

.section/dm seg_dmda;
.extern _buf_C2_GRP_GEQ_01;
.global _gate_on_C2_GRP_GATE_01;
.var _gate_on_C2_GRP_GATE_01 = 1;
.global _gate_threshold_C2_GRP_GATE_01;
.var _gate_threshold_C2_GRP_GATE_01 = -40.0;
.global _gate_attack_C2_GRP_GATE_01;
.var _gate_attack_C2_GRP_GATE_01 = 0.05;
.global _gate_release_C2_GRP_GATE_01;
.var _gate_release_C2_GRP_GATE_01 = 0.005;
.global _gate_hold_C2_GRP_GATE_01;
.var _gate_hold_C2_GRP_GATE_01 = 2400;
.global _gate_hold_count_C2_GRP_GATE_01;
.var _gate_hold_count_C2_GRP_GATE_01 = 0;
.global _gate_range_C2_GRP_GATE_01;
.var _gate_range_C2_GRP_GATE_01 = 0.001;       /* linear floor (float) */
.global _gate_key_src_C2_GRP_GATE_01;
.var _gate_key_src_C2_GRP_GATE_01 = 0;
.global _gate_det_src_C2_GRP_GATE_01;
.var _gate_det_src_C2_GRP_GATE_01 = 0;
.global _gate_filter_on_C2_GRP_GATE_01;
.var _gate_filter_on_C2_GRP_GATE_01 = 0;
.global _gate_filter_hpf_C2_GRP_GATE_01;
.var _gate_filter_hpf_C2_GRP_GATE_01[5] = 1.0, 0.0, 0.0, 0.0, 0.0;
.global _gate_filter_lpf_C2_GRP_GATE_01;
.var _gate_filter_lpf_C2_GRP_GATE_01[5] = 1.0, 0.0, 0.0, 0.0, 0.0;
.global _gate_filter_cq_C2_GRP_GATE_01;
.var _gate_filter_cq_C2_GRP_GATE_01[10];
.global _gate_filter_state_C2_GRP_GATE_01;
.var _gate_filter_state_C2_GRP_GATE_01[12];
.global _gate_envelope_C2_GRP_GATE_01;
.var _gate_envelope_C2_GRP_GATE_01 = 0;
.global _gate_gain_C2_GRP_GATE_01;
.var _gate_gain_C2_GRP_GATE_01 = 0x10000000;
.global _gate_gain_target_q_C2_GRP_GATE_01;
.var _gate_gain_target_q_C2_GRP_GATE_01 = 0x10000000;
.global _gate_attq_C2_GRP_GATE_01;
.var _gate_attq_C2_GRP_GATE_01 = 0;
.global _gate_relq_C2_GRP_GATE_01;
.var _gate_relq_C2_GRP_GATE_01 = 0;
.global _gate_thrq_C2_GRP_GATE_01;
.var _gate_thrq_C2_GRP_GATE_01 = 0;
.global _gate_rngq_C2_GRP_GATE_01;
.var _gate_rngq_C2_GRP_GATE_01 = 0;
.global _buf_C2_GRP_GATE_01;
.var _buf_C2_GRP_GATE_01;

#if DSP4_BLOCK_KERNELS
.global _gate_saved_idx_C2_GRP_GATE_01;
.var _gate_saved_idx_C2_GRP_GATE_01;
#endif

.section/pm seg_pmco;
.extern _sample_idx;
.extern _envq_fx;
.extern _log2q_fx;
.extern _exp2q_fx;
.extern _mrf_rns28;
.extern _bq_fx_cascade_N;
.extern _bq_fx_convert_N;

.global _C2_GRP_GATE_01_process;
_C2_GRP_GATE_01_process:

    r0 = dm(_buf_C2_GRP_GEQ_01);
    r2 = dm(_gate_on_C2_GRP_GATE_01);
    r3 = 0;
    comp(r2, r3);
    if eq jump (pc, .gate_bypass_C2_GRP_GATE_01);
    r13 = r0;

    /* --- block rate: param conversion --- */
/* Per-sample builds only. Under DSP4_BLOCK_KERNELS this node has no
 * block kernel, the chain reaches it once per block with _sample_idx
 * at 31, and a surviving guard would never fire -- the parameters
 * below would never convert and the node would run on its .var
 * initialisers. */
#if !DSP4_BLOCK_KERNELS
    r4 = dm(_sample_idx);
    r1 = 0;
    comp(r4, r1);
    if ne jump (pc, .gate_go_C2_GRP_GATE_01);
#endif

    r2 = 0x4F000000;
    f2 = r2;
    f1 = dm(_gate_attack_C2_GRP_GATE_01);
    f1 = f1 * f2;
    r1 = fix f1;
    dm(_gate_attq_C2_GRP_GATE_01) = r1;
    f1 = dm(_gate_release_C2_GRP_GATE_01);
    f1 = f1 * f2;
    r1 = fix f1;
    dm(_gate_relq_C2_GRP_GATE_01) = r1;
    r2 = 0x4AAA152D;
    f2 = r2;
    f1 = dm(_gate_threshold_C2_GRP_GATE_01);
    f1 = f1 * f2;
    r1 = fix f1;
    dm(_gate_thrq_C2_GRP_GATE_01) = r1;
    r2 = 0x4D800000;
    f2 = r2;
    f1 = dm(_gate_range_C2_GRP_GATE_01);
    f1 = f1 * f2;
    r1 = fix f1;
    dm(_gate_rngq_C2_GRP_GATE_01) = r1;
    r2 = dm(_gate_filter_on_C2_GRP_GATE_01);
    r2 = pass r2;
    if eq jump (pc, .gate_go_C2_GRP_GATE_01);
    i0 = _gate_filter_hpf_C2_GRP_GATE_01;
    i1 = _gate_filter_cq_C2_GRP_GATE_01;
    r4 = 1;
    call _bq_fx_convert_N;
    i0 = _gate_filter_lpf_C2_GRP_GATE_01;
    r4 = 1;
    call _bq_fx_convert_N;      /* i1 continued */
.gate_go_C2_GRP_GATE_01:

    /* --- sidechain: |x| (+ optional HPF/LPF) --- */
    r0 = abs r13;
    r2 = dm(_gate_filter_on_C2_GRP_GATE_01);
    r2 = pass r2;
    if eq jump (pc, .gate_nofilt_C2_GRP_GATE_01);
    i0 = _gate_filter_cq_C2_GRP_GATE_01;
    i1 = _gate_filter_state_C2_GRP_GATE_01;
    r4 = 2;
    call _bq_fx_cascade_N;
    r0 = abs r0;
.gate_nofilt_C2_GRP_GATE_01:

    r1 = dm(_gate_envelope_C2_GRP_GATE_01);
    r2 = dm(_gate_attq_C2_GRP_GATE_01);
    r3 = dm(_gate_relq_C2_GRP_GATE_01);
    call _envq_fx;
    dm(_gate_envelope_C2_GRP_GATE_01) = r0;

    /* threshold compare in log2 domain */
    r1 = pass r0;
    if le jump (pc, .gate_below_C2_GRP_GATE_01);   /* env==0: below */
    call _log2q_fx;
    r1 = dm(_gate_thrq_C2_GRP_GATE_01);
    comp(r0, r1);
    if ge jump (pc, .gate_open_C2_GRP_GATE_01);
.gate_below_C2_GRP_GATE_01:
    r4 = dm(_gate_hold_count_C2_GRP_GATE_01);
    r15 = 1;
    r4 = r4 - r15;
    dm(_gate_hold_count_C2_GRP_GATE_01) = r4;
    if gt jump (pc, .gate_ramp_C2_GRP_GATE_01);
    r5 = dm(_gate_rngq_C2_GRP_GATE_01);
    dm(_gate_gain_target_q_C2_GRP_GATE_01) = r5;
    jump (pc, .gate_ramp_C2_GRP_GATE_01);
.gate_open_C2_GRP_GATE_01:
    r5 = 0x10000000;
    dm(_gate_gain_target_q_C2_GRP_GATE_01) = r5;
    r4 = dm(_gate_hold_C2_GRP_GATE_01);
    dm(_gate_hold_count_C2_GRP_GATE_01) = r4;
.gate_ramp_C2_GRP_GATE_01:
    /* one-pole gain smoother (fixed): gain += a*(target-gain) */
    r0 = dm(_gate_gain_target_q_C2_GRP_GATE_01);
    r1 = dm(_gate_gain_C2_GRP_GATE_01);
    r2 = dm(_gate_attq_C2_GRP_GATE_01);
    r3 = dm(_gate_relq_C2_GRP_GATE_01);
    call _envq_fx;                 /* same one-pole form */
    dm(_gate_gain_C2_GRP_GATE_01) = r0;

    r1 = r0;
    r0 = r13;
    mrf = r0 * r1 (ssi);
    call _mrf_rns28;
    dm(_buf_C2_GRP_GATE_01) = r0;
    rts;
.gate_bypass_C2_GRP_GATE_01:
    dm(_buf_C2_GRP_GATE_01) = r0;
    rts;
_C2_GRP_GATE_01_process.end:
