/*----------------------------------------------------------------------
 * Main Out 1 Comp (COMPRESSOR)
 * Node ID:    C2_MAIN_OCOMP_01
 * Chip:       2
 * Channels:   1
 * SPI Page:   1
 * SPI Addr:   1464
 * RampProfile: DynSafe
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/
#include "dsp_block.h"
#include "lib/dyn_lut.h"

        /* RampProfile: DynSafe | Mode: LinearFrames | Up: 6ms (18f) Down: 20ms (60f) | Curve: Exp | Scope: Scalar */

        /* COMPRESSOR (FIXED Q4.28, D5) */
        /* SPI page=1 addr=1464 */

#include "blk_pool.h"

.section/dm seg_dmda;
.extern _buf_C2_MAIN_OEQ_01;
        .global _comp_on_C2_MAIN_OCOMP_01;
        .var _comp_on_C2_MAIN_OCOMP_01 = 1;
        .global _comp_threshold_C2_MAIN_OCOMP_01;
        .var _comp_threshold_C2_MAIN_OCOMP_01 = -20.0;
        .global _comp_ratio_C2_MAIN_OCOMP_01;
        .var _comp_ratio_C2_MAIN_OCOMP_01 = 4.0;
        .global _comp_attack_C2_MAIN_OCOMP_01;
        .var _comp_attack_C2_MAIN_OCOMP_01 = 0.01;
        .global _comp_release_C2_MAIN_OCOMP_01;
        .var _comp_release_C2_MAIN_OCOMP_01 = 0.001;
        .global _comp_makeup_C2_MAIN_OCOMP_01;
        .var _comp_makeup_C2_MAIN_OCOMP_01 = 1.0;
        .global _comp_makeup_target_C2_MAIN_OCOMP_01;
        .var _comp_makeup_target_C2_MAIN_OCOMP_01 = 1.0;
        .global _comp_makeup_step_C2_MAIN_OCOMP_01;
        .var _comp_makeup_step_C2_MAIN_OCOMP_01 = 0.0;
        .global _comp_makeup_frames_C2_MAIN_OCOMP_01;
        .var _comp_makeup_frames_C2_MAIN_OCOMP_01 = 0;
        .global _comp_knee_C2_MAIN_OCOMP_01;
        .var _comp_knee_C2_MAIN_OCOMP_01 = 0.0;   /* hard knee until the host sets it */
        .global _comp_parallel_C2_MAIN_OCOMP_01;
        .var _comp_parallel_C2_MAIN_OCOMP_01 = 100.0;   /* PERCENT (D40); fully wet by default (D59) */
        .global _comp_type_C2_MAIN_OCOMP_01;
        .var _comp_type_C2_MAIN_OCOMP_01 = 0;
        .global _comp_key_src_C2_MAIN_OCOMP_01;
        .var _comp_key_src_C2_MAIN_OCOMP_01 = 0;
        .global _comp_det_src_C2_MAIN_OCOMP_01;
        .var _comp_det_src_C2_MAIN_OCOMP_01 = 0;
        .global _comp_eq_pos_C2_MAIN_OCOMP_01;
        .var _comp_eq_pos_C2_MAIN_OCOMP_01 = 0;
        .global _comp_lim_mode_C2_MAIN_OCOMP_01;
        .var _comp_lim_mode_C2_MAIN_OCOMP_01 = 0;
        .global _comp_filter_on_C2_MAIN_OCOMP_01;
        .var _comp_filter_on_C2_MAIN_OCOMP_01 = 0;
        .global _comp_filter_coeffs_C2_MAIN_OCOMP_01;
        .var _comp_filter_coeffs_C2_MAIN_OCOMP_01[10];
        .global _comp_filter_state_C2_MAIN_OCOMP_01;
        .var _comp_filter_state_C2_MAIN_OCOMP_01[4];
        .global _comp_envelope_C2_MAIN_OCOMP_01;
        .var _comp_envelope_C2_MAIN_OCOMP_01 = 0;        /* Q4.28 */
        .global _comp_gain_C2_MAIN_OCOMP_01;
        .var _comp_gain_C2_MAIN_OCOMP_01 = 0x10000000;   /* Q4.28 (display) */
        .global _comp_attq_C2_MAIN_OCOMP_01;
        .var _comp_attq_C2_MAIN_OCOMP_01 = 0;
        .global _comp_relq_C2_MAIN_OCOMP_01;
        .var _comp_relq_C2_MAIN_OCOMP_01 = 0;
        .global _comp_mkq_C2_MAIN_OCOMP_01;
        .var _comp_mkq_C2_MAIN_OCOMP_01 = 0x10000000;
        .global _comp_parq_C2_MAIN_OCOMP_01;
        .var _comp_parq_C2_MAIN_OCOMP_01 = 0x7FFFFFFF;   /* Q0.31, = _comp_parallel_ converted */
        .global _comp_cgp_C2_MAIN_OCOMP_01;
        .var _comp_cgp_C2_MAIN_OCOMP_01[4];              /* thr, slope, halfk, k2 */
#if DSP4_DYN_LUT
        /* THE LEVEL -> GAIN TABLE FOR THIS NODE (S15), its design
         * cursor, and the parameter set the table was designed for.
         *
         * Per node because the parameters are per node: the whole static
         * curve is baked in, so two compressors with different
         * thresholds cannot share one. DYN_LUT_N is 337 words at the
         * shipped K = 4, which is 43 kB across chip 1's 32 compressors
         * against the 123,852 free bytes the linker map reports at the
         * shipping configuration -- it fits in DM, which is what S15
         * gate 1 settled by measurement rather than assuming L2.
         *
         * The cursor is the design step's progress: DYN_LUT_N means the
         * table is finished and matches _comp_lutk_, anything less means
         * it is being rebuilt and this node runs the EXACT polynomial
         * meanwhile. */
        .global _comp_lut_C2_MAIN_OCOMP_01;
        .var _comp_lut_C2_MAIN_OCOMP_01[DYN_LUT_N];
        .global _comp_lutc_C2_MAIN_OCOMP_01;
        .var _comp_lutc_C2_MAIN_OCOMP_01 = 0;
        .global _comp_lutk_C2_MAIN_OCOMP_01;
        .var _comp_lutk_C2_MAIN_OCOMP_01[4] = 1, 1, 1, 1;
#endif
        .global _buf_C2_MAIN_OCOMP_01;
        .var _buf_C2_MAIN_OCOMP_01;

#if DSP4_BLOCK_KERNELS
.global _comp_saved_idx_C2_MAIN_OCOMP_01;
.var _comp_saved_idx_C2_MAIN_OCOMP_01;
#endif
        #if DSP4_BLOCK_KERNELS
        .extern _blk_C2_MAIN_OEQ_01;
        #endif
        #if DSP4_BLOCK_KERNELS
        .global _blk_C2_MAIN_OCOMP_01;
        .var _blk_C2_MAIN_OCOMP_01[DSP4_BLOCK_SIZE];
        .global _bw_k_C2_MAIN_OCOMP_01;
        .var _bw_k_C2_MAIN_OCOMP_01;        /* the caller's _sample_idx */
        .global _bw_s0_C2_MAIN_OCOMP_01;
        .var _bw_s0_C2_MAIN_OCOMP_01;       /* walking source pointer */
        .global _bw_d0_C2_MAIN_OCOMP_01;
        .var _bw_d0_C2_MAIN_OCOMP_01;       /* walking sink pointer */
        #endif

        .section/pm seg_pmco;
        .extern _sample_idx;
        .extern _envq_fx;
        .extern _compgain_fx;
        .extern _mrf_rns28;
#if DSP4_DYN_LUT
        .extern _dyn_lut_step;
        .extern _dyn_lut_gain;
#endif
        .global _C2_MAIN_OCOMP_01_process;
        _C2_MAIN_OCOMP_01_process:
        #if DSP4_BLOCK_KERNELS
            /* ---- generic per-block wrapper (review finding D16) ----
             * Runs the per-sample reference body BLOCK times over this
             * node's own block buffer, staging each sample through the
             * scalar _buf_ words the body already reads and writes. Same
             * arithmetic, same order, same result as the per-sample
             * build; what it removes is the chain's call/rts and the
             * _sample_idx guard being re-evaluated from the chain.
             *
             * SAMPLE 0 IS PEELED AND _sample_idx IS NOT COUNTED
             * (2026-09-02). The loop used to carry a DM sample index,
             * loading it, storing it to _sample_idx, reloading it,
             * incrementing it and storing it back -- five instructions
             * a sample to drive a guard that only ever asks whether the
             * index is ZERO. Every one of the 119 wrapped bodies was
             * checked: all of them compare it against 0 and none reads
             * it for anything else. So sample 0 runs once outside the
             * loop with _sample_idx = 0, the word is then set to 1, and
             * the remaining BLOCK-1 samples run with the guard shut.
             * The block-rate conversions still fire exactly once per
             * block, which is the property the guard exists for.
             *
             * NOT a free win to generalise: the C2_RECV_* stimulus
             * nodes read _sample_idx & 1 to alternate the profile
             * square, and they would break under this. They are not
             * wrapped nodes -- they carry their own block form -- and
             * that is why the audit is per-node and recorded here.
             * 38 cycles a block per wrapped node.
             */
            i4 = _blk_C2_MAIN_OEQ_01;
            r3 = i4;
            dm(_bw_s0_C2_MAIN_OCOMP_01) = r3;
            i4 = _blk_C2_MAIN_OCOMP_01;
            r3 = i4;
            dm(_bw_d0_C2_MAIN_OCOMP_01) = r3;
            r5 = dm(_sample_idx);
            dm(_bw_k_C2_MAIN_OCOMP_01) = r5;
            r5 = 0;
            dm(_sample_idx) = r5;
            /* sample 0, peeled: the block-rate guard fires here */
                r3 = dm(_bw_s0_C2_MAIN_OCOMP_01);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_MAIN_OEQ_01) = r0;
                r3 = r3 + 1;
                dm(_bw_s0_C2_MAIN_OCOMP_01) = r3;
                call _C2_MAIN_OCOMP_01_process_sample;
                r0 = dm(_buf_C2_MAIN_OCOMP_01);
                r3 = dm(_bw_d0_C2_MAIN_OCOMP_01);
                i4 = r3;
                dm(i4, 0) = r0;
                r3 = r3 + 1;
                dm(_bw_d0_C2_MAIN_OCOMP_01) = r3;
            r5 = 1;
            dm(_sample_idx) = r5;   /* guard shut for 1..BLOCK-1 */
            lcntr = DSP4_BLOCK_SIZE-1, do .bwlp_C2_MAIN_OCOMP_01 until lce;
                r3 = dm(_bw_s0_C2_MAIN_OCOMP_01);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_MAIN_OEQ_01) = r0;
                r3 = r3 + 1;
                dm(_bw_s0_C2_MAIN_OCOMP_01) = r3;
                call _C2_MAIN_OCOMP_01_process_sample;
                r0 = dm(_buf_C2_MAIN_OCOMP_01);
                r3 = dm(_bw_d0_C2_MAIN_OCOMP_01);
                i4 = r3;
                dm(i4, 0) = r0;
                r3 = r3 + 1;
            .bwlp_C2_MAIN_OCOMP_01: dm(_bw_d0_C2_MAIN_OCOMP_01) = r3;
            r5 = dm(_bw_k_C2_MAIN_OCOMP_01);
            dm(_sample_idx) = r5;
            rts;

        .global _C2_MAIN_OCOMP_01_process_sample;
        _C2_MAIN_OCOMP_01_process_sample:
        #endif

            r0 = dm(_buf_C2_MAIN_OEQ_01);
            r2 = dm(_comp_on_C2_MAIN_OCOMP_01);
            r3 = 0;
            comp(r2, r3);
            if eq jump (pc, .comp_bypass_C2_MAIN_OCOMP_01);
            r13 = r0;                     /* dry (r13-r15 lib-safe) */
        #if DSP4_COMP_NOCVT
            jump (pc, .comp_go_C2_MAIN_OCOMP_01);   /* TEMP bisect: skip block-rate cvt */
        #endif

            /* --- block rate: makeup ramp + param conversion --- */
        /* LIVE IN BOTH BUILDS (review finding D16). The block wrapper
         * below drives _sample_idx 0..BLOCK-1 before each call into this
         * body, so the guard fires exactly ONCE per block and the
         * block-rate work behind it -- the parameter conversion, and the
         * float ramps that consume a BLOCK's worth of frames at a time --
         * runs once and not BLOCK times. Removing it, which is right for
         * a node the chain reaches once per block with the index left at
         * BLOCK-1, would run the whole conversion on every sample. */
            r4 = dm(_sample_idx);
            r1 = 0;
            comp(r4, r1);
            if ne jump (pc, .comp_go_C2_MAIN_OCOMP_01);

            r4 = dm(_comp_makeup_frames_C2_MAIN_OCOMP_01);
            comp(r4, r1);
            if le jump (pc, .no_mramp_C2_MAIN_OCOMP_01);
            /* Consume a BLOCK's worth of frames and apply a BLOCK's
             * worth of step. spi_handler scales every profile frame count
             * by DSP4_BLOCK_SIZE, which is right for the ramps that
             * decrement once per SAMPLE. This one decrements once per
             * BLOCK, so taking 1 per block ran it BLOCK times long:
             * measured 2026-08-23 at BLOCK=32, a GainSafe down-ramp took
             * 960 ms against the 30 ms its own cell table specifies, and a
             * GainFast fader move took 85 ms instead of 3 ms. A power of
             * two is exact in binary, so scaling the step loses nothing. */
            r5 = DSP4_BLOCK_SIZE;
            r4 = r4 - r5;
            dm(_comp_makeup_frames_C2_MAIN_OCOMP_01) = r4;
            f1 = dm(_comp_makeup_C2_MAIN_OCOMP_01);
            f2 = dm(_comp_makeup_step_C2_MAIN_OCOMP_01);
            r5 = DSP4_BLOCK_F32;              /* BLOCK_SIZE as float */
            f5 = r5;
            f2 = f2 * f5;
            f1 = f1 + f2;
            dm(_comp_makeup_C2_MAIN_OCOMP_01) = f1;
            jump (pc, .comp_cvt_C2_MAIN_OCOMP_01);
        .no_mramp_C2_MAIN_OCOMP_01:
            f1 = dm(_comp_makeup_target_C2_MAIN_OCOMP_01);
            dm(_comp_makeup_C2_MAIN_OCOMP_01) = f1;
        .comp_cvt_C2_MAIN_OCOMP_01:
            r2 = 0x4D800000;
            f2 = r2;
            f1 = f1 * f2;
            r1 = fix f1;
            dm(_comp_mkq_C2_MAIN_OCOMP_01) = r1;
            /* PARALLEL BLEND IS PERCENT ON THE WIRE (review finding
             * D40). The master documents Chan[1-32]CompPar as 0-100 %
             * (d32-mx-master.csv, table 0=0/127=100); this used to
             * multiply the raw wire value by 2^31 with no /100, so any
             * documented value of 1 % or more pinned the blend fully wet
             * and the control could not take an intermediate setting at
             * all. The masters win: clamp to the documented 0..100 and
             * scale by 2^31/100. */
            f1 = dm(_comp_parallel_C2_MAIN_OCOMP_01);
            r2 = 0x00000000;              /* 0 %, documented minimum */
            f2 = r2;
            comp(f1, f2);
            if lt f1 = f2;
            r2 = 0x42C80000;              /* 100 %, documented maximum */
            f2 = r2;
            comp(f1, f2);
            if gt f1 = f2;
            r2 = 0x4BA3D70A;              /* 2^31 / 100 */
            f2 = r2;
            f1 = f1 * f2;
            r1 = fix f1;
            /* CLAMP. parallel = 100 % scales to exactly 2^31, which int32 cannot
             * hold: `fix` wraps and stores -1, so in Q0.31 the MAXIMUM
             * parallel setting blended in essentially nothing and the
             * compressor went fully DRY -- the same output as
             * parallel = 0, with a working compressor sitting behind it.
             * Bench 2026-08-23: par 0.999 settled at -16.49 dBFS on a
             * -6.02 dBFS step, par 1.0 returned the input untouched. */
            r3 = 0;
            r2 = 0x7FFFFFFF;
            comp(r1, r3);
            if lt r1 = pass r2;
            dm(_comp_parq_C2_MAIN_OCOMP_01) = r1;
            r2 = 0x4F000000;              /* 2^31 float */
            f2 = r2;
            f1 = dm(_comp_attack_C2_MAIN_OCOMP_01);
            f1 = f1 * f2;
            r1 = fix f1;
            dm(_comp_attq_C2_MAIN_OCOMP_01) = r1;
            f1 = dm(_comp_release_C2_MAIN_OCOMP_01);
            f1 = f1 * f2;
            r1 = fix f1;
            dm(_comp_relq_C2_MAIN_OCOMP_01) = r1;
            r2 = 0x4AAA152D;            /* dB -> Q6.25 log2 */
            f2 = r2;
            f1 = dm(_comp_threshold_C2_MAIN_OCOMP_01);
            f1 = f1 * f2;
            r1 = fix f1;
            dm(_comp_cgp_C2_MAIN_OCOMP_01) = r1;    /* thr */
            /* slope = 1 - 1/ratio */
            f6 = dm(_comp_ratio_C2_MAIN_OCOMP_01);
            f7 = recips f6;
            f8 = f6 * f7;
            r10 = 0x40000000;
            f8 = f10 - f8;
            f7 = f7 * f8;
            f8 = f6 * f7;
            f8 = f10 - f8;
            f6 = f7 * f8;
            r2 = 0x3F800000;
            f5 = r2;
            f5 = f5 - f6;                 /* slope float */
            r2 = 0x4F000000;
            f2 = r2;
            f1 = f5 * f2;
            r1 = fix f1;
            dm(_comp_cgp_C2_MAIN_OCOMP_01 + 1) = r1;
            /* knee: halfk = knee_db/2 in Q6.25 log2; k2 = slope*K/(2*knee) Q6.25 */
            f4 = dm(_comp_knee_C2_MAIN_OCOMP_01);
            r2 = 0x3DCCCCCD;              /* 0.1 dB min for soft path */
            f3 = r2;
            comp(f4, f3);
            if gt jump (pc, .comp_soft_C2_MAIN_OCOMP_01);
            r1 = 0;
            dm(_comp_cgp_C2_MAIN_OCOMP_01 + 2) = r1;
            dm(_comp_cgp_C2_MAIN_OCOMP_01 + 3) = r1;
            jump (pc, .comp_kdone_C2_MAIN_OCOMP_01);
        .comp_soft_C2_MAIN_OCOMP_01:
            r2 = 0x4AAA152D;
            f2 = r2;
            f1 = f4 * f2;
            r2 = 0x3F000000;              /* 0.5 */
            f3 = r2;
            f1 = f1 * f3;
            r1 = fix f1;
            dm(_comp_cgp_C2_MAIN_OCOMP_01 + 2) = r1;  /* halfk */
            f7 = recips f4;
            f8 = f4 * f7;
            r10 = 0x40000000;
            f8 = f10 - f8;
            f7 = f7 * f8;
            f8 = f4 * f7;
            f8 = f10 - f8;
            f6 = f7 * f8;
            r2 = 0x4040A8C1;             /* K/2 */
            f3 = r2;
            f6 = f6 * f3;                 /* K/(2*knee_db) */
            f6 = f6 * f5;                 /* * slope */
            r2 = 0x4C000000;              /* 2^25 float */
            f2 = r2;
            f1 = f6 * f2;
            r1 = fix f1;
            dm(_comp_cgp_C2_MAIN_OCOMP_01 + 3) = r1;  /* k2 */
        .comp_kdone_C2_MAIN_OCOMP_01:
#if DSP4_DYN_LUT
            /* --- block rate: THE DESIGN STEP (S15) ---
             *
             * The four converted words in _comp_cgp_ ARE the curve. If
             * they have moved since the table was designed, the design
             * restarts; either way DYN_LUT_CHUNK points are filled per
             * block until the cursor reaches the end, and until it does
             * the per-sample body below runs the exact polynomial.
             *
             * WHY NOT ALL AT ONCE: one point is a whole _compgain_fx,
             * about 211 instructions, so a 337-point table is ~71,000
             * cycles against a block's 327,680 -- 22 % of a block for
             * ONE node, and chip 1 has 32 of them.
             *
             * WHY NOT A TWO-TABLE BLEND, which is what S14 proposed for
             * a ramping parameter: tools/dsp/dyn_lut_design.py --blend
             * measures it at 1.13 dB for a 10 dB threshold ramp and
             * 20.2 dB for a 57 dB one, against a 0.1 dB bar, because two
             * curves whose KNEES sit at different levels do not
             * interpolate into the curve whose knee is between them.
             * Running the polynomial while the table is stale is exact,
             * costs only what ships today, and needs no second table.
             *
             * r13 holds the live sample and both _dyn_lut_fill and
             * _compgain_fx under it clobber r0-r12 only. */
            r0 = _comp_cgp_C2_MAIN_OCOMP_01;
            r1 = _comp_lutk_C2_MAIN_OCOMP_01;
            r2 = _comp_lut_C2_MAIN_OCOMP_01;
            r3 = _comp_lutc_C2_MAIN_OCOMP_01;
            call _dyn_lut_step;
#endif
        .comp_go_C2_MAIN_OCOMP_01:

            /* --- envelope (fixed) --- */
            r0 = abs r13;
            r1 = dm(_comp_envelope_C2_MAIN_OCOMP_01);
            r2 = dm(_comp_attq_C2_MAIN_OCOMP_01);
            r3 = dm(_comp_relq_C2_MAIN_OCOMP_01);
            call _envq_fx;
            dm(_comp_envelope_C2_MAIN_OCOMP_01) = r0;

            /* --- gain computer --- */
#if DSP4_DYN_LUT
            /* ONE TABLE, level -> gain: no log2, no knee, no exp2. The
             * envelope is already in r0. A table that is still being
             * designed falls through to the polynomial, which is the
             * arithmetic the table is designed against, so the changeover
             * is a step of at most the table's own error (0.0950 dB worst
             * case over the documented parameter sweep, 0.004 dB at the
             * shipped defaults) at one block boundary. */
            r4 = dm(_comp_lutc_C2_MAIN_OCOMP_01);
            r5 = DYN_LUT_N;
            comp(r4, r5);
            if lt jump (pc, .clutpoly_C2_MAIN_OCOMP_01);
            i0 = _comp_lut_C2_MAIN_OCOMP_01;
            call _dyn_lut_gain;           /* r0 = gain Q4.28 */
            jump (pc, .clutgain_C2_MAIN_OCOMP_01);
        .clutpoly_C2_MAIN_OCOMP_01:
#endif
            i0 = _comp_cgp_C2_MAIN_OCOMP_01;
            call _compgain_fx;            /* r0 = gain Q4.28 */
#if DSP4_DYN_LUT
        .clutgain_C2_MAIN_OCOMP_01:
#endif
            dm(_comp_gain_C2_MAIN_OCOMP_01) = r0;

            /* wet = dry * gain * makeup */
            r1 = r0;
            r0 = r13;
            mrf = r0 * r1 (ssi);
            call _mrf_rns28;
            r1 = dm(_comp_mkq_C2_MAIN_OCOMP_01);
            mrf = r0 * r1 (ssi);
            call _mrf_rns28;

            /* parallel: out = dry + par*(wet - dry) — matches the float
             * node exactly (par==0 -> dry, its default behaviour) */
            r5 = r0 - r13;
            r4 = dm(_comp_parq_C2_MAIN_OCOMP_01);
            mrf = r5 * r4 (ssi);
            r1 = 0x40000000;
            r12 = 1;
            mrf = mrf + r1 * r12 (ssi);
            r1 = mr0f;
            r12 = mr1f;
            r1 = lshift r1 by -31;
            r12 = lshift r12 by 1;
            r1 = r1 or r12;
            r0 = r13 + r1;
            dm(_buf_C2_MAIN_OCOMP_01) = r0;
            rts;
        .comp_bypass_C2_MAIN_OCOMP_01:
            dm(_buf_C2_MAIN_OCOMP_01) = r0;
            rts;
        _C2_MAIN_OCOMP_01_process.end:
