/*----------------------------------------------------------------------
 * Main Out 2 (OUTPUT_TDM)
 * Node ID:    C2_MAIN_OUT_02
 * Chip:       2
 * Channels:   1
 * SPI Page:   1
 * SPI Addr:   1490
 * RampProfile: (none)
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/
#include "dsp_block.h"

/* OUTPUT_TDM: Write to SPORT1 slot 5 */

.section/dm seg_dmda;
.extern _buf_C2_MAIN_OLIM_02;
.global _tx_out_slot_C2_MAIN_OUT_02;
.var _tx_out_slot_C2_MAIN_OUT_02;
.global _buf_C2_MAIN_OUT_02;
.var _buf_C2_MAIN_OUT_02;
.global _mtr_wide_C2_MAIN_OUT_02;
.var _mtr_wide_C2_MAIN_OUT_02;

.section/pm seg_pmco;
.global _C2_MAIN_OUT_02_process;
_C2_MAIN_OUT_02_process:
    r0 = dm(_buf_C2_MAIN_OLIM_02);
    dm(_tx_out_slot_C2_MAIN_OUT_02) = r0;
    dm(_buf_C2_MAIN_OUT_02) = r0;
    r1 = ashift r0 by -4;    /* Q4.28 -> Q8.24 */
    dm(_mtr_wide_C2_MAIN_OUT_02) = r1;
    rts;
_C2_MAIN_OUT_02_process.end:
