/*----------------------------------------------------------------------
 * Main Out 4 (OUTPUT_TDM)
 * Node ID:    C2_MAIN_OUT_04
 * Chip:       2
 * Channels:   1
 * SPI Page:   1
 * SPI Addr:   1580
 * RampProfile: (none)
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/

/* OUTPUT_TDM: Write to SPORT4 slot 4 */

.section/dm seg_dmda;
.extern _buf_C2_MAIN_OLIM_04;
.global _tx_out_slot_C2_MAIN_OUT_04;
.var _tx_out_slot_C2_MAIN_OUT_04;
.global _buf_C2_MAIN_OUT_04;
.var _buf_C2_MAIN_OUT_04;

.section/pm seg_pmco;
.global _C2_MAIN_OUT_04_process;
_C2_MAIN_OUT_04_process:
    r0 = dm(_buf_C2_MAIN_OLIM_04);
    dm(_tx_out_slot_C2_MAIN_OUT_04) = r0;
    dm(_buf_C2_MAIN_OUT_04) = r0;
    rts;
_C2_MAIN_OUT_04_process.end:
