/*----------------------------------------------------------------------
 * Phones R (MONITOR)
 * Node ID:    C2_PHN_R
 * Chip:       2
 * Channels:   1
 * SPI Page:   -1
 * SPI Addr:   -1
 * RampProfile: GainFast
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/
#include "dsp_block.h"
#include "lib/dyn_lut.h"

/* RampProfile: GainFast | Mode: Slew | Up: 3ms (9f) Down: 8ms (24f) | Curve: Exp | Scope: Scalar */

/* MONITOR FOLLOWER (S143) — the L leg of C2_PHN. */
/* Coefficient: _mon_q_l_C2_PHN (Mon Level[1], converted by C2_PHN). */
/* No cell, no SPI address: nothing here is host-writable. */

.section/dm seg_dmda;
.extern _buf_C2_MON_PICK_R;
.extern _mon_q_l_C2_PHN;
.extern _mon_source_C2_MON;
.global _buf_C2_PHN_R;
.var _buf_C2_PHN_R;

        #if DSP4_BLOCK_KERNELS
        .extern _blk_C2_MON_PICK_R;
        #endif
        #if DSP4_BLOCK_KERNELS
        .global _blk_C2_PHN_R;
        .var _blk_C2_PHN_R[DSP4_BLOCK_SIZE];
        .global _bw_k_C2_PHN_R;
        .var _bw_k_C2_PHN_R;        /* the caller's _sample_idx */
        .global _bw_s0_C2_PHN_R;
        .var _bw_s0_C2_PHN_R;       /* walking source pointer */
        .global _bw_d0_C2_PHN_R;
        .var _bw_d0_C2_PHN_R;       /* walking sink pointer */
        #endif

.section/pm seg_pmco;
.extern _sample_idx;
.extern _mrf_rns28;
.global _C2_PHN_R_process;
_C2_PHN_R_process:
        #if DSP4_BLOCK_KERNELS
            /* ---- generic per-block wrapper (review finding D16) ----
             * Runs the per-sample reference body BLOCK times over this
             * node's own block buffer, staging each sample through the
             * scalar _buf_ words the body already reads and writes. Same
             * arithmetic, same order, same result as the per-sample
             * build; what it removes is the chain's call/rts and the
             * _sample_idx guard being re-evaluated from the chain.
             *
             * SAMPLE 0 IS PEELED AND _sample_idx IS NOT COUNTED
             * (2026-09-02). The loop used to carry a DM sample index,
             * loading it, storing it to _sample_idx, reloading it,
             * incrementing it and storing it back -- five instructions
             * a sample to drive a guard that only ever asks whether the
             * index is ZERO. Every one of the 119 wrapped bodies was
             * checked: all of them compare it against 0 and none reads
             * it for anything else. So sample 0 runs once outside the
             * loop with _sample_idx = 0, the word is then set to 1, and
             * the remaining BLOCK-1 samples run with the guard shut.
             * The block-rate conversions still fire exactly once per
             * block, which is the property the guard exists for.
             *
             * NOT a free win to generalise: the C2_RECV_* stimulus
             * nodes read _sample_idx & 1 to alternate the profile
             * square, and they would break under this. They are not
             * wrapped nodes -- they carry their own block form -- and
             * that is why the audit is per-node and recorded here.
             * 38 cycles a block per wrapped node.
             */
        #if DSP4_CUE
        .extern _rx_ic_slot_C2_RECV_CUE_L;
            r3 = _blk_C2_MON_PICK_R;
            r5 = _rx_ic_slot_C2_RECV_CUE_L;
            r4 = dm(_mon_source_C2_MON);
            r6 = 13;
            comp(r4, r6);
            if eq r3 = r5;
        #else
            i4 = _blk_C2_MON_PICK_R;
            r3 = i4;
        #endif
            dm(_bw_s0_C2_PHN_R) = r3;
            i4 = _blk_C2_PHN_R;
            r3 = i4;
            dm(_bw_d0_C2_PHN_R) = r3;
            r5 = dm(_sample_idx);
            dm(_bw_k_C2_PHN_R) = r5;
            r5 = 0;
            dm(_sample_idx) = r5;
            /* sample 0, peeled: the block-rate guard fires here */
                r3 = dm(_bw_s0_C2_PHN_R);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_MON_PICK_R) = r0;
                r3 = r3 + 1;
                dm(_bw_s0_C2_PHN_R) = r3;
                call _C2_PHN_R_process_sample;
                r0 = dm(_buf_C2_PHN_R);
                r3 = dm(_bw_d0_C2_PHN_R);
                i4 = r3;
                dm(i4, 0) = r0;
                r3 = r3 + 1;
                dm(_bw_d0_C2_PHN_R) = r3;
            r5 = 1;
            dm(_sample_idx) = r5;   /* guard shut for 1..BLOCK-1 */
            lcntr = DSP4_BLOCK_SIZE-1, do .bwlp_C2_PHN_R until lce;
                r3 = dm(_bw_s0_C2_PHN_R);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_MON_PICK_R) = r0;
                r3 = r3 + 1;
                dm(_bw_s0_C2_PHN_R) = r3;
                call _C2_PHN_R_process_sample;
                r0 = dm(_buf_C2_PHN_R);
                r3 = dm(_bw_d0_C2_PHN_R);
                i4 = r3;
                dm(i4, 0) = r0;
                r3 = r3 + 1;
            .bwlp_C2_PHN_R: dm(_bw_d0_C2_PHN_R) = r3;
            r5 = dm(_bw_k_C2_PHN_R);
            dm(_sample_idx) = r5;
            rts;

        .global _C2_PHN_R_process_sample;
        _C2_PHN_R_process_sample:
        #endif
    r0 = dm(_buf_C2_MON_PICK_R);
    r1 = dm(_mon_q_l_C2_PHN);
    mrf = r0 * r1 (ssi);
    call _mrf_rns28;
    dm(_buf_C2_PHN_R) = r0;
    rts;
_C2_PHN_R_process.end:
