/*----------------------------------------------------------------------
 * Aux 1 Recv (INTERCHIP_RECV)
 * Node ID:    C2_RECV_AUX_01
 * Chip:       2
 * Channels:   1
 * SPI Page:   -1
 * SPI Addr:   -1
 * RampProfile: (none)
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/

/* INTERCHIP_RECV: mix-fabric line 0 slot 7 (global slot 7, signal BUS_AUX_01) */

.section/dm seg_dmda;
.global _rx_ic_slot_C2_RECV_AUX_01;
.var _rx_ic_slot_C2_RECV_AUX_01;
.global _buf_C2_RECV_AUX_01;
.var _buf_C2_RECV_AUX_01;

.section/pm seg_pmco;
.global _C2_RECV_AUX_01_process;
_C2_RECV_AUX_01_process:
    r0 = dm(_rx_ic_slot_C2_RECV_AUX_01);
    dm(_buf_C2_RECV_AUX_01) = r0;
    rts;
_C2_RECV_AUX_01_process.end:
