/*----------------------------------------------------------------------
 * Grp 2 Recv (INTERCHIP_RECV)
 * Node ID:    C2_RECV_GRP_02
 * Chip:       2
 * Channels:   1
 * SPI Page:   -1
 * SPI Addr:   -1
 * RampProfile: (none)
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/

/* INTERCHIP_RECV: mix-fabric line 0 slot 4 (global slot 4, signal BUS_GRP_02) */

.section/dm seg_dmda;
#if DSP4_BLOCK_KERNELS
/* Scatter writes slot[sample] under block kernels, so this MUST
 * be a 32-word array even before the node itself is converted --
 * otherwise scatter writes past a scalar. */
.global _rx_ic_slot_C2_RECV_GRP_02;
.var _rx_ic_slot_C2_RECV_GRP_02[32];
.global _buf_C2_RECV_GRP_02;
.var _buf_C2_RECV_GRP_02[32];
#else
.global _rx_ic_slot_C2_RECV_GRP_02;
.var _rx_ic_slot_C2_RECV_GRP_02;
.global _buf_C2_RECV_GRP_02;
.var _buf_C2_RECV_GRP_02;
#endif

.section/pm seg_pmco;
.global _C2_RECV_GRP_02_process;
_C2_RECV_GRP_02_process:
#if DSP4_BLOCK_KERNELS
    l0 = 0;
    l1 = 0;
    i0 = _rx_ic_slot_C2_RECV_GRP_02;
    i1 = _buf_C2_RECV_GRP_02;
    r5 = 32;
    lcntr = r5; do .icr_lp_C2_RECV_GRP_02 until lce;
        r0 = dm(i0, 1);
        dm(i1, 1) = r0;
.icr_lp_C2_RECV_GRP_02:
        nop;
    rts;
#else
    r0 = dm(_rx_ic_slot_C2_RECV_GRP_02);
    dm(_buf_C2_RECV_GRP_02) = r0;
    rts;
#endif
_C2_RECV_GRP_02_process.end:
