/*----------------------------------------------------------------------
 * Main L Recv (INTERCHIP_RECV)
 * Node ID:    C2_RECV_MAIN_L
 * Chip:       2
 * Channels:   1
 * SPI Page:   -1
 * SPI Addr:   -1
 * RampProfile: (none)
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/

/* INTERCHIP_RECV: mix-fabric line 0 slot 0 (global slot 0, signal BUS_MAIN_L) */

.section/dm seg_dmda;
.global _rx_ic_slot_C2_RECV_MAIN_L;
.var _rx_ic_slot_C2_RECV_MAIN_L;
.global _buf_C2_RECV_MAIN_L;
.var _buf_C2_RECV_MAIN_L;

.section/pm seg_pmco;
.global _C2_RECV_MAIN_L_process;
_C2_RECV_MAIN_L_process:
    r0 = dm(_rx_ic_slot_C2_RECV_MAIN_L);
    dm(_buf_C2_RECV_MAIN_L) = r0;
    rts;
_C2_RECV_MAIN_L_process.end:
