/*----------------------------------------------------------------------
 * FX 2 Recv (INTERCHIP_RECV)
 * Node ID:    C2_RECV_FX_02
 * Chip:       2
 * Channels:   1
 * SPI Page:   -1
 * SPI Addr:   -1
 * RampProfile: (none)
 *
 * AUTO-GENERATED by dsp_codegen.py (D32) — do not edit directly.
 *----------------------------------------------------------------------*/

/* INTERCHIP_RECV: Read from inter-chip SPORT7 slot 20 */

.section/dm seg_dmda;
.global _rx_ic_slot_C2_RECV_FX_02;
.var _rx_ic_slot_C2_RECV_FX_02;
.global _buf_C2_RECV_FX_02;
.var _buf_C2_RECV_FX_02;

.section/pm seg_pmco;
.global _C2_RECV_FX_02_process;
_C2_RECV_FX_02_process:
    r0 = dm(_rx_ic_slot_C2_RECV_FX_02);
    dm(_buf_C2_RECV_FX_02) = r0;
    rts;
_C2_RECV_FX_02_process.end:
