/*----------------------------------------------------------------------
 * Snake Return 4 Input (AUX_INPUT)
 * Node ID:    C2_SNK_IN_04
 * Chip:       2
 * Channels:   1
 * SPI Page:   1
 * SPI Addr:   1828
 * RampProfile: GainFast
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/

/* RampProfile: GainFast | Mode: Slew | Up: 3ms (4f) Down: 8ms (12f) | Curve: Exp | Scope: Scalar */

/* AUX_INPUT: USB/BT/DAW auxiliary stereo input */
/* SPI page=1 addr=1828 */

.section/dm seg_dmda;
.extern _buf_C2_XR_SNAKE_04;
.global _auxin_on_C2_SNK_IN_04;
.var _auxin_on_C2_SNK_IN_04 = 0;
.global _auxin_level_C2_SNK_IN_04;
.var _auxin_level_C2_SNK_IN_04 = 1.0;
.global _auxin_level_target_C2_SNK_IN_04;
.var _auxin_level_target_C2_SNK_IN_04 = 1.0;
.global _auxin_level_step_C2_SNK_IN_04;
.var _auxin_level_step_C2_SNK_IN_04 = 0.0;
.global _auxin_level_frames_C2_SNK_IN_04;
.var _auxin_level_frames_C2_SNK_IN_04 = 0;
.global _buf_C2_SNK_IN_04;
.var _buf_C2_SNK_IN_04;

.section/pm seg_pmco;
.global _C2_SNK_IN_04_process;
_C2_SNK_IN_04_process:
    /* Ramp level */
    r4 = dm(_auxin_level_frames_C2_SNK_IN_04);
    r15 = 1;
    r4 = r4 - r15;
    if le jump (pc, .no_auxramp_C2_SNK_IN_04);
    dm(_auxin_level_frames_C2_SNK_IN_04) = r4;
    f1 = dm(_auxin_level_C2_SNK_IN_04);
    f2 = dm(_auxin_level_step_C2_SNK_IN_04);
    f1 = f1 + f2;
    dm(_auxin_level_C2_SNK_IN_04) = f1;
    jump (pc, .auxin_go_C2_SNK_IN_04);
.no_auxramp_C2_SNK_IN_04:
    f1 = dm(_auxin_level_target_C2_SNK_IN_04);
    dm(_auxin_level_C2_SNK_IN_04) = f1;
.auxin_go_C2_SNK_IN_04:

    /* Read USB/BT input, apply level */
    r0 = dm(_buf_C2_XR_SNAKE_04);
    f1 = dm(_auxin_level_C2_SNK_IN_04);
    f0 = f0 * f1;
    /* Check on/off */
    r2 = dm(_auxin_on_C2_SNK_IN_04);
    r3 = 0;
    comp(r2, r3);
    if eq r0 = r3;      /* if off, mute (0 = 0.0f IEEE 754) */
    dm(_buf_C2_SNK_IN_04) = r0;
    rts;
_C2_SNK_IN_04_process.end:
