/*----------------------------------------------------------------------
 * Sub Fader (FADER_PAN)
 * Node ID:    C2_SUB_FDR
 * Chip:       2
 * Channels:   1
 * SPI Page:   1
 * SPI Addr:   1284
 * RampProfile: GainFast
 *
 * AUTO-GENERATED by dsp_codegen.py (D32) — do not edit directly.
 *----------------------------------------------------------------------*/

/* RampProfile: GainFast | Mode: Slew | Up: 3ms (4f) Down: 8ms (12f) | Curve: Exp | Scope: Scalar */

/* FADER_PAN: Level fader + constant-power pan + mute */
/* SPI page=1 addr=1284 */

.section/dm seg_dmda;
.extern _buf_C2_RECV_SUB;
.global _fdr_level_C2_SUB_FDR;
.var _fdr_level_C2_SUB_FDR = 1.0;
.global _fdr_level_target_C2_SUB_FDR;
.var _fdr_level_target_C2_SUB_FDR = 1.0;
.global _fdr_level_step_C2_SUB_FDR;
.var _fdr_level_step_C2_SUB_FDR = 0.0;
.global _fdr_level_frames_C2_SUB_FDR;
.var _fdr_level_frames_C2_SUB_FDR = 0;
.global _fdr_pan_C2_SUB_FDR;
.var _fdr_pan_C2_SUB_FDR = 0.5;       /* 0=L, 0.5=C, 1=R */
.global _fdr_pan_target_C2_SUB_FDR;
.var _fdr_pan_target_C2_SUB_FDR = 0.5;
.global _fdr_pan_step_C2_SUB_FDR;
.var _fdr_pan_step_C2_SUB_FDR = 0.0;
.global _fdr_pan_frames_C2_SUB_FDR;
.var _fdr_pan_frames_C2_SUB_FDR = 0;
.global _fdr_mute_C2_SUB_FDR;
.var _fdr_mute_C2_SUB_FDR = 0;
.global _fdr_dca_gain_C2_SUB_FDR;
.var _fdr_dca_gain_C2_SUB_FDR = 1.0;  /* DCA master multiplier */
.global _tap_post_fader_C2_SUB_FDR;
.var _tap_post_fader_C2_SUB_FDR;      /* post-fader tap */
.global _buf_C2_SUB_FDR;
.var _buf_C2_SUB_FDR;


.section/pm seg_pmco;
.global _C2_SUB_FDR_process;
_C2_SUB_FDR_process:
    /* --- Level ramp (GainFast: 3ms up / 8ms down, Exp) --- */
    r4 = dm(_fdr_level_frames_C2_SUB_FDR);
    r15 = 1;
    r4 = r4 - r15;
    if le jump (pc, .no_lramp_C2_SUB_FDR);
    dm(_fdr_level_frames_C2_SUB_FDR) = r4;
    f1 = dm(_fdr_level_C2_SUB_FDR);
    f2 = dm(_fdr_level_step_C2_SUB_FDR);
    f1 = f1 + f2;
    dm(_fdr_level_C2_SUB_FDR) = f1;
    jump (pc, .do_pan_C2_SUB_FDR);
.no_lramp_C2_SUB_FDR:
    f1 = dm(_fdr_level_target_C2_SUB_FDR);
    dm(_fdr_level_C2_SUB_FDR) = f1;
.do_pan_C2_SUB_FDR:

    /* --- Pan ramp --- */
    r4 = dm(_fdr_pan_frames_C2_SUB_FDR);
    r15 = 1;
    r4 = r4 - r15;
    if le jump (pc, .no_pramp_C2_SUB_FDR);
    dm(_fdr_pan_frames_C2_SUB_FDR) = r4;
    f5 = dm(_fdr_pan_C2_SUB_FDR);
    f6 = dm(_fdr_pan_step_C2_SUB_FDR);
    f5 = f5 + f6;
    dm(_fdr_pan_C2_SUB_FDR) = f5;
    jump (pc, .apply_fdr_C2_SUB_FDR);
.no_pramp_C2_SUB_FDR:
    f5 = dm(_fdr_pan_target_C2_SUB_FDR);
    dm(_fdr_pan_C2_SUB_FDR) = f5;
.apply_fdr_C2_SUB_FDR:

    r0 = dm(_buf_C2_RECV_SUB);

    /* Apply level (incl. DCA multiplier) */
    f3 = dm(_fdr_dca_gain_C2_SUB_FDR);
    f1 = f1 * f3;       /* effective_gain = fader × DCA */
    f0 = f0 * f1;

    /* Mute */
    r2 = dm(_fdr_mute_C2_SUB_FDR);
    r3 = 0;
    comp(r2, r3);
    if ne r0 = r3;      /* if muted, clear f0 (0 = 0.0f IEEE 754) */

    /* Bus fader: mono passthrough (no pan split) */
    dm(_tap_post_fader_C2_SUB_FDR) = f0;
    dm(_buf_C2_SUB_FDR) = f0;
    rts;
_C2_SUB_FDR_process.end:
