/*----------------------------------------------------------------------
 * Woof Source (SOURCE_SEL)
 * Node ID:    C2_WOOF_SRC
 * Chip:       2
 * Channels:   1
 * SPI Page:   1
 * SPI Addr:   2312
 * RampProfile: GainFast
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/
#include "dsp_block.h"
#include "lib/dyn_lut.h"

/* RampProfile: GainFast | Mode: Slew | Up: 3ms (9f) Down: 8ms (24f) | Curve: Exp | Scope: Scalar */

/* SOURCE_SEL (FIXED Q4.28, 13 sources): ramped click-free select */
/* SPI page=1 addr=2312 */
/* +0 select index (0..12), +1 link, +2/+3 spare.            */
/* Crossfade 12 ms = 36 block(s), step 0.027777778. */

.section/dm seg_dmda;
.extern _buf_C2_AUX_DLY_01;
.extern _buf_C2_AUX_DLY_02;
.extern _buf_C2_AUX_DLY_03;
.extern _buf_C2_AUX_DLY_04;
.extern _buf_C2_AUX_DLY_05;
.extern _buf_C2_AUX_DLY_06;
.extern _buf_C2_AUX_DLY_07;
.extern _buf_C2_AUX_DLY_08;
.extern _buf_C2_AUX_DLY_09;
.extern _buf_C2_AUX_DLY_10;
.extern _buf_C2_AUX_DLY_11;
.extern _buf_C2_AUX_DLY_12;
.extern _buf_C2_WOOF_MIX;
.global _ssel_sel_C2_WOOF_SRC;
.var _ssel_sel_C2_WOOF_SRC = 0;             /* SPI +0 */
.global _ssel_link_C2_WOOF_SRC;
.var _ssel_link_C2_WOOF_SRC = 0;                /* SPI +1 */
.global _ssel_cur_C2_WOOF_SRC;
.var _ssel_cur_C2_WOOF_SRC = 0;             /* the source at gain 1   */
.global _ssel_from_C2_WOOF_SRC;
.var _ssel_from_C2_WOOF_SRC = 0;            /* the one fading out     */
.global _ssel_alpha_C2_WOOF_SRC;
.var _ssel_alpha_C2_WOOF_SRC = 1.0;             /* 1.0 = settled on `cur` */
.global _ssel_step_C2_WOOF_SRC;
.var _ssel_step_C2_WOOF_SRC = 0.0;              /* non-zero = fading      */
.global _ssel_gq_C2_WOOF_SRC;
.var _ssel_gq_C2_WOOF_SRC[13] = 0x10000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000;          /* Q4.28, one per source  */
.global _buf_C2_WOOF_SRC;
.var _buf_C2_WOOF_SRC;

        #if DSP4_BLOCK_KERNELS
        .extern _blk_C2_WOOF_MIX;
        .extern _blk_C2_AUX_DLY_01;
        .extern _blk_C2_AUX_DLY_02;
        .extern _blk_C2_AUX_DLY_03;
        .extern _blk_C2_AUX_DLY_04;
        .extern _blk_C2_AUX_DLY_05;
        .extern _blk_C2_AUX_DLY_06;
        .extern _blk_C2_AUX_DLY_07;
        .extern _blk_C2_AUX_DLY_08;
        .extern _blk_C2_AUX_DLY_09;
        .extern _blk_C2_AUX_DLY_10;
        .extern _blk_C2_AUX_DLY_11;
        .extern _blk_C2_AUX_DLY_12;
        #endif
        #if DSP4_BLOCK_KERNELS
        .global _blk_C2_WOOF_SRC;
        .var _blk_C2_WOOF_SRC[DSP4_BLOCK_SIZE];
        .global _bw_k_C2_WOOF_SRC;
        .var _bw_k_C2_WOOF_SRC;        /* the caller's _sample_idx */
        .global _bw_s0_C2_WOOF_SRC;
        .var _bw_s0_C2_WOOF_SRC;       /* walking source pointer */
        .global _bw_s1_C2_WOOF_SRC;
        .var _bw_s1_C2_WOOF_SRC;       /* walking source pointer */
        .global _bw_s2_C2_WOOF_SRC;
        .var _bw_s2_C2_WOOF_SRC;       /* walking source pointer */
        .global _bw_s3_C2_WOOF_SRC;
        .var _bw_s3_C2_WOOF_SRC;       /* walking source pointer */
        .global _bw_s4_C2_WOOF_SRC;
        .var _bw_s4_C2_WOOF_SRC;       /* walking source pointer */
        .global _bw_s5_C2_WOOF_SRC;
        .var _bw_s5_C2_WOOF_SRC;       /* walking source pointer */
        .global _bw_s6_C2_WOOF_SRC;
        .var _bw_s6_C2_WOOF_SRC;       /* walking source pointer */
        .global _bw_s7_C2_WOOF_SRC;
        .var _bw_s7_C2_WOOF_SRC;       /* walking source pointer */
        .global _bw_s8_C2_WOOF_SRC;
        .var _bw_s8_C2_WOOF_SRC;       /* walking source pointer */
        .global _bw_s9_C2_WOOF_SRC;
        .var _bw_s9_C2_WOOF_SRC;       /* walking source pointer */
        .global _bw_s10_C2_WOOF_SRC;
        .var _bw_s10_C2_WOOF_SRC;       /* walking source pointer */
        .global _bw_s11_C2_WOOF_SRC;
        .var _bw_s11_C2_WOOF_SRC;       /* walking source pointer */
        .global _bw_s12_C2_WOOF_SRC;
        .var _bw_s12_C2_WOOF_SRC;       /* walking source pointer */
        .global _bw_d0_C2_WOOF_SRC;
        .var _bw_d0_C2_WOOF_SRC;       /* walking sink pointer */
        #endif

.section/pm seg_pmco;
.extern _sample_idx;
.extern _mrf_rns28;
.global _C2_WOOF_SRC_process;
_C2_WOOF_SRC_process:
        #if DSP4_BLOCK_KERNELS
            /* ---- generic per-block wrapper (review finding D16) ----
             * Runs the per-sample reference body BLOCK times over this
             * node's own block buffer, staging each sample through the
             * scalar _buf_ words the body already reads and writes. Same
             * arithmetic, same order, same result as the per-sample
             * build; what it removes is the chain's call/rts and the
             * _sample_idx guard being re-evaluated from the chain.
             *
             * SAMPLE 0 IS PEELED AND _sample_idx IS NOT COUNTED
             * (2026-09-02). The loop used to carry a DM sample index,
             * loading it, storing it to _sample_idx, reloading it,
             * incrementing it and storing it back -- five instructions
             * a sample to drive a guard that only ever asks whether the
             * index is ZERO. Every one of the 119 wrapped bodies was
             * checked: all of them compare it against 0 and none reads
             * it for anything else. So sample 0 runs once outside the
             * loop with _sample_idx = 0, the word is then set to 1, and
             * the remaining BLOCK-1 samples run with the guard shut.
             * The block-rate conversions still fire exactly once per
             * block, which is the property the guard exists for.
             *
             * NOT a free win to generalise: the C2_RECV_* stimulus
             * nodes read _sample_idx & 1 to alternate the profile
             * square, and they would break under this. They are not
             * wrapped nodes -- they carry their own block form -- and
             * that is why the audit is per-node and recorded here.
             * 38 cycles a block per wrapped node.
             */
            i4 = _blk_C2_WOOF_MIX;
            r3 = i4;
            dm(_bw_s0_C2_WOOF_SRC) = r3;
            i4 = _blk_C2_AUX_DLY_01;
            r3 = i4;
            dm(_bw_s1_C2_WOOF_SRC) = r3;
            i4 = _blk_C2_AUX_DLY_02;
            r3 = i4;
            dm(_bw_s2_C2_WOOF_SRC) = r3;
            i4 = _blk_C2_AUX_DLY_03;
            r3 = i4;
            dm(_bw_s3_C2_WOOF_SRC) = r3;
            i4 = _blk_C2_AUX_DLY_04;
            r3 = i4;
            dm(_bw_s4_C2_WOOF_SRC) = r3;
            i4 = _blk_C2_AUX_DLY_05;
            r3 = i4;
            dm(_bw_s5_C2_WOOF_SRC) = r3;
            i4 = _blk_C2_AUX_DLY_06;
            r3 = i4;
            dm(_bw_s6_C2_WOOF_SRC) = r3;
            i4 = _blk_C2_AUX_DLY_07;
            r3 = i4;
            dm(_bw_s7_C2_WOOF_SRC) = r3;
            i4 = _blk_C2_AUX_DLY_08;
            r3 = i4;
            dm(_bw_s8_C2_WOOF_SRC) = r3;
            i4 = _blk_C2_AUX_DLY_09;
            r3 = i4;
            dm(_bw_s9_C2_WOOF_SRC) = r3;
            i4 = _blk_C2_AUX_DLY_10;
            r3 = i4;
            dm(_bw_s10_C2_WOOF_SRC) = r3;
            i4 = _blk_C2_AUX_DLY_11;
            r3 = i4;
            dm(_bw_s11_C2_WOOF_SRC) = r3;
            i4 = _blk_C2_AUX_DLY_12;
            r3 = i4;
            dm(_bw_s12_C2_WOOF_SRC) = r3;
            i4 = _blk_C2_WOOF_SRC;
            r3 = i4;
            dm(_bw_d0_C2_WOOF_SRC) = r3;
            r5 = dm(_sample_idx);
            dm(_bw_k_C2_WOOF_SRC) = r5;
            r5 = 0;
            dm(_sample_idx) = r5;
            /* sample 0, peeled: the block-rate guard fires here */
                r3 = dm(_bw_s0_C2_WOOF_SRC);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_WOOF_MIX) = r0;
                r3 = r3 + 1;
                dm(_bw_s0_C2_WOOF_SRC) = r3;
                r3 = dm(_bw_s1_C2_WOOF_SRC);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_AUX_DLY_01) = r0;
                r3 = r3 + 1;
                dm(_bw_s1_C2_WOOF_SRC) = r3;
                r3 = dm(_bw_s2_C2_WOOF_SRC);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_AUX_DLY_02) = r0;
                r3 = r3 + 1;
                dm(_bw_s2_C2_WOOF_SRC) = r3;
                r3 = dm(_bw_s3_C2_WOOF_SRC);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_AUX_DLY_03) = r0;
                r3 = r3 + 1;
                dm(_bw_s3_C2_WOOF_SRC) = r3;
                r3 = dm(_bw_s4_C2_WOOF_SRC);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_AUX_DLY_04) = r0;
                r3 = r3 + 1;
                dm(_bw_s4_C2_WOOF_SRC) = r3;
                r3 = dm(_bw_s5_C2_WOOF_SRC);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_AUX_DLY_05) = r0;
                r3 = r3 + 1;
                dm(_bw_s5_C2_WOOF_SRC) = r3;
                r3 = dm(_bw_s6_C2_WOOF_SRC);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_AUX_DLY_06) = r0;
                r3 = r3 + 1;
                dm(_bw_s6_C2_WOOF_SRC) = r3;
                r3 = dm(_bw_s7_C2_WOOF_SRC);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_AUX_DLY_07) = r0;
                r3 = r3 + 1;
                dm(_bw_s7_C2_WOOF_SRC) = r3;
                r3 = dm(_bw_s8_C2_WOOF_SRC);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_AUX_DLY_08) = r0;
                r3 = r3 + 1;
                dm(_bw_s8_C2_WOOF_SRC) = r3;
                r3 = dm(_bw_s9_C2_WOOF_SRC);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_AUX_DLY_09) = r0;
                r3 = r3 + 1;
                dm(_bw_s9_C2_WOOF_SRC) = r3;
                r3 = dm(_bw_s10_C2_WOOF_SRC);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_AUX_DLY_10) = r0;
                r3 = r3 + 1;
                dm(_bw_s10_C2_WOOF_SRC) = r3;
                r3 = dm(_bw_s11_C2_WOOF_SRC);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_AUX_DLY_11) = r0;
                r3 = r3 + 1;
                dm(_bw_s11_C2_WOOF_SRC) = r3;
                r3 = dm(_bw_s12_C2_WOOF_SRC);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_AUX_DLY_12) = r0;
                r3 = r3 + 1;
                dm(_bw_s12_C2_WOOF_SRC) = r3;
                call _C2_WOOF_SRC_process_sample;
                r0 = dm(_buf_C2_WOOF_SRC);
                r3 = dm(_bw_d0_C2_WOOF_SRC);
                i4 = r3;
                dm(i4, 0) = r0;
                r3 = r3 + 1;
                dm(_bw_d0_C2_WOOF_SRC) = r3;
            r5 = 1;
            dm(_sample_idx) = r5;   /* guard shut for 1..BLOCK-1 */
            lcntr = DSP4_BLOCK_SIZE-1, do .bwlp_C2_WOOF_SRC until lce;
                r3 = dm(_bw_s0_C2_WOOF_SRC);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_WOOF_MIX) = r0;
                r3 = r3 + 1;
                dm(_bw_s0_C2_WOOF_SRC) = r3;
                r3 = dm(_bw_s1_C2_WOOF_SRC);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_AUX_DLY_01) = r0;
                r3 = r3 + 1;
                dm(_bw_s1_C2_WOOF_SRC) = r3;
                r3 = dm(_bw_s2_C2_WOOF_SRC);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_AUX_DLY_02) = r0;
                r3 = r3 + 1;
                dm(_bw_s2_C2_WOOF_SRC) = r3;
                r3 = dm(_bw_s3_C2_WOOF_SRC);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_AUX_DLY_03) = r0;
                r3 = r3 + 1;
                dm(_bw_s3_C2_WOOF_SRC) = r3;
                r3 = dm(_bw_s4_C2_WOOF_SRC);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_AUX_DLY_04) = r0;
                r3 = r3 + 1;
                dm(_bw_s4_C2_WOOF_SRC) = r3;
                r3 = dm(_bw_s5_C2_WOOF_SRC);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_AUX_DLY_05) = r0;
                r3 = r3 + 1;
                dm(_bw_s5_C2_WOOF_SRC) = r3;
                r3 = dm(_bw_s6_C2_WOOF_SRC);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_AUX_DLY_06) = r0;
                r3 = r3 + 1;
                dm(_bw_s6_C2_WOOF_SRC) = r3;
                r3 = dm(_bw_s7_C2_WOOF_SRC);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_AUX_DLY_07) = r0;
                r3 = r3 + 1;
                dm(_bw_s7_C2_WOOF_SRC) = r3;
                r3 = dm(_bw_s8_C2_WOOF_SRC);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_AUX_DLY_08) = r0;
                r3 = r3 + 1;
                dm(_bw_s8_C2_WOOF_SRC) = r3;
                r3 = dm(_bw_s9_C2_WOOF_SRC);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_AUX_DLY_09) = r0;
                r3 = r3 + 1;
                dm(_bw_s9_C2_WOOF_SRC) = r3;
                r3 = dm(_bw_s10_C2_WOOF_SRC);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_AUX_DLY_10) = r0;
                r3 = r3 + 1;
                dm(_bw_s10_C2_WOOF_SRC) = r3;
                r3 = dm(_bw_s11_C2_WOOF_SRC);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_AUX_DLY_11) = r0;
                r3 = r3 + 1;
                dm(_bw_s11_C2_WOOF_SRC) = r3;
                r3 = dm(_bw_s12_C2_WOOF_SRC);
                i4 = r3;
                r0 = dm(i4, 0);
                dm(_buf_C2_AUX_DLY_12) = r0;
                r3 = r3 + 1;
                dm(_bw_s12_C2_WOOF_SRC) = r3;
                call _C2_WOOF_SRC_process_sample;
                r0 = dm(_buf_C2_WOOF_SRC);
                r3 = dm(_bw_d0_C2_WOOF_SRC);
                i4 = r3;
                dm(i4, 0) = r0;
                r3 = r3 + 1;
            .bwlp_C2_WOOF_SRC: dm(_bw_d0_C2_WOOF_SRC) = r3;
            r5 = dm(_bw_k_C2_WOOF_SRC);
            dm(_sample_idx) = r5;
            rts;

        .global _C2_WOOF_SRC_process_sample;
        _C2_WOOF_SRC_process_sample:
        #endif
        /* LIVE IN BOTH BUILDS (review finding D16). The block wrapper
         * below drives _sample_idx 0..BLOCK-1 before each call into this
         * body, so the guard fires exactly ONCE per block and the
         * block-rate work behind it -- the parameter conversion, and the
         * float ramps that consume a BLOCK's worth of frames at a time --
         * runs once and not BLOCK times. Removing it, which is right for
         * a node the chain reaches once per block with the index left at
         * BLOCK-1, would run the whole conversion on every sample. */
    r4 = dm(_sample_idx);
    r1 = 0;
    comp(r4, r1);
    if ne jump (pc, .ssel_go_C2_WOOF_SRC);
    /* ── block rate ──────────────────────────────────────────── */
    /* A fade runs to its end before a new target is taken; the
     * select word is re-read every block, so the host's LATEST
     * value is the one that lands.
     *
     * Tested as an INTEGER: the only two things ever stored in the
     * step are integer 0 and a positive float constant, so the
     * zero test is the same test in either domain and this one
     * cannot be confused by a float flag. */
    r4 = dm(_ssel_step_C2_WOOF_SRC);
    r4 = pass r4;
    if ne jump (pc, .ssel_fade_C2_WOOF_SRC);

    r4 = dm(_ssel_sel_C2_WOOF_SRC);
    r5 = 0;
    r4 = max(r4, r5);
    r5 = 12;
    r4 = min(r4, r5);
    r5 = dm(_ssel_cur_C2_WOOF_SRC);
    comp(r4, r5);
    if eq jump (pc, .ssel_lay_C2_WOOF_SRC);
    /* the select moved: start a fade from where we are */
    dm(_ssel_from_C2_WOOF_SRC) = r5;
    dm(_ssel_cur_C2_WOOF_SRC) = r4;
    r6 = 0;
    dm(_ssel_alpha_C2_WOOF_SRC) = r6;
    r6 = 0x3CE38E39;
    dm(_ssel_step_C2_WOOF_SRC) = r6;
    jump (pc, .ssel_lay_C2_WOOF_SRC);

.ssel_fade_C2_WOOF_SRC:
    f4 = dm(_ssel_alpha_C2_WOOF_SRC);
    f5 = dm(_ssel_step_C2_WOOF_SRC);
    f4 = f4 + f5;
    r5 = 0x3F800000;          /* 1.0f */
    f5 = r5;
    comp(f4, f5);
    if lt jump (pc, .ssel_astore_C2_WOOF_SRC);
    f4 = f5;
    r6 = 0;
    dm(_ssel_step_C2_WOOF_SRC) = r6;   /* settled */
.ssel_astore_C2_WOOF_SRC:
    dm(_ssel_alpha_C2_WOOF_SRC) = f4;

.ssel_lay_C2_WOOF_SRC:
    /* THE WHOLE COEFFICIENT SET, IN ONE WALK, BRANCH-FREE. Source
     * `from` gets 1 - alpha, source `cur` gets alpha and every
     * other gets exactly zero; the Q4.28 conversion rides the same
     * loop, so there is no float gain array to keep in step with
     * the shadow. `cur` is tested SECOND, so from == cur (the
     * settled case, alpha = 1) leaves that source at 1.0 and
     * everything else at 0 — which makes the sample sum bit-exact
     * the selected source, since (x*2^28 + 2^27) >> 28 = x.
     *
     * Each comp and its conditional move are ADJACENT: the move
     * reads ASTAT from the last flag-setting instruction, so the
     * index increment cannot sit between them. */
    l0 = 0;
    i0 = _ssel_gq_C2_WOOF_SRC;
    f4 = dm(_ssel_alpha_C2_WOOF_SRC);
    r5 = 0x3F800000;          /* 1.0f */
    f5 = r5;
    f6 = f5 - f4;             /* 1 - alpha */
    r8 = dm(_ssel_from_C2_WOOF_SRC);
    r9 = dm(_ssel_cur_C2_WOOF_SRC);
    r10 = 0;                  /* source index */
    r11 = 0;                  /* 0.0f */
    r2 = 0x4D800000;          /* 2^28 */
    f2 = r2;
    lcntr = 13, do .ssel_lay_lp_C2_WOOF_SRC until lce;
        r12 = r11;
        comp(r10, r8);
        if eq r12 = r6;
        comp(r10, r9);
        if eq r12 = r4;
        r10 = r10 + 1;
        f12 = f12 * f2;
        r12 = fix f12;
    .ssel_lay_lp_C2_WOOF_SRC: dm(i0, 1) = r12;

.ssel_go_C2_WOOF_SRC:
    r1 = 0;
    mr0f = r1;
    mr1f = r1;
    mr2f = r1;
    r0 = dm(_buf_C2_WOOF_MIX);
    r1 = dm(_ssel_gq_C2_WOOF_SRC + 0);
    mrf = mrf + r0 * r1 (ssi);
    r0 = dm(_buf_C2_AUX_DLY_01);
    r1 = dm(_ssel_gq_C2_WOOF_SRC + 1);
    mrf = mrf + r0 * r1 (ssi);
    r0 = dm(_buf_C2_AUX_DLY_02);
    r1 = dm(_ssel_gq_C2_WOOF_SRC + 2);
    mrf = mrf + r0 * r1 (ssi);
    r0 = dm(_buf_C2_AUX_DLY_03);
    r1 = dm(_ssel_gq_C2_WOOF_SRC + 3);
    mrf = mrf + r0 * r1 (ssi);
    r0 = dm(_buf_C2_AUX_DLY_04);
    r1 = dm(_ssel_gq_C2_WOOF_SRC + 4);
    mrf = mrf + r0 * r1 (ssi);
    r0 = dm(_buf_C2_AUX_DLY_05);
    r1 = dm(_ssel_gq_C2_WOOF_SRC + 5);
    mrf = mrf + r0 * r1 (ssi);
    r0 = dm(_buf_C2_AUX_DLY_06);
    r1 = dm(_ssel_gq_C2_WOOF_SRC + 6);
    mrf = mrf + r0 * r1 (ssi);
    r0 = dm(_buf_C2_AUX_DLY_07);
    r1 = dm(_ssel_gq_C2_WOOF_SRC + 7);
    mrf = mrf + r0 * r1 (ssi);
    r0 = dm(_buf_C2_AUX_DLY_08);
    r1 = dm(_ssel_gq_C2_WOOF_SRC + 8);
    mrf = mrf + r0 * r1 (ssi);
    r0 = dm(_buf_C2_AUX_DLY_09);
    r1 = dm(_ssel_gq_C2_WOOF_SRC + 9);
    mrf = mrf + r0 * r1 (ssi);
    r0 = dm(_buf_C2_AUX_DLY_10);
    r1 = dm(_ssel_gq_C2_WOOF_SRC + 10);
    mrf = mrf + r0 * r1 (ssi);
    r0 = dm(_buf_C2_AUX_DLY_11);
    r1 = dm(_ssel_gq_C2_WOOF_SRC + 11);
    mrf = mrf + r0 * r1 (ssi);
    r0 = dm(_buf_C2_AUX_DLY_12);
    r1 = dm(_ssel_gq_C2_WOOF_SRC + 12);
    mrf = mrf + r0 * r1 (ssi);
    call _mrf_rns28;
    dm(_buf_C2_WOOF_SRC) = r0;
    rts;
_C2_WOOF_SRC_process.end:
