/*----------------------------------------------------------------------
 * XFER_SNAKE_05 Recv (INTERCHIP_RECV)
 * Node ID:    C2_XR_SNAKE_05
 * Chip:       2
 * Channels:   1
 * SPI Page:   -1
 * SPI Addr:   -1
 * RampProfile: (none)
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/
#include "dsp_block.h"

/* INTERCHIP_RECV: mix-fabric line 2 slot 1 (global slot 33, signal XFER_SNAKE_05) */

.section/dm seg_dmda;
#if DSP4_BLOCK_KERNELS
/* Scatter writes slot[sample] under block kernels, so this MUST
 * be a 32-word array even before the node itself is converted --
 * otherwise scatter writes past a scalar. */
.global _rx_ic_slot_C2_XR_SNAKE_05;
.var _rx_ic_slot_C2_XR_SNAKE_05[DSP4_BLOCK_SIZE];
.global _buf_C2_XR_SNAKE_05;
.var _buf_C2_XR_SNAKE_05[DSP4_BLOCK_SIZE];
#else
.global _rx_ic_slot_C2_XR_SNAKE_05;
.var _rx_ic_slot_C2_XR_SNAKE_05;
.global _buf_C2_XR_SNAKE_05;
.var _buf_C2_XR_SNAKE_05;
#endif

.section/pm seg_pmco;
.global _C2_XR_SNAKE_05_process;
_C2_XR_SNAKE_05_process:
#if DSP4_BLOCK_KERNELS
    l0 = 0;
    l1 = 0;
    i0 = _rx_ic_slot_C2_XR_SNAKE_05;
    i1 = _buf_C2_XR_SNAKE_05;
    r5 = DSP4_BLOCK_SIZE;
    lcntr = r5; do .icr_lp_C2_XR_SNAKE_05 until lce;
        r0 = dm(i0, 1);
        dm(i1, 1) = r0;
.icr_lp_C2_XR_SNAKE_05:
        nop;
    rts;
#else
    r0 = dm(_rx_ic_slot_C2_XR_SNAKE_05);
    dm(_buf_C2_XR_SNAKE_05) = r0;
    rts;
#endif
_C2_XR_SNAKE_05_process.end:
