/*----------------------------------------------------------------------
 * XFER_SNAKE_02 Recv (INTERCHIP_RECV)
 * Node ID:    C2_XR_SNAKE_02
 * Chip:       2
 * Channels:   1
 * SPI Page:   -1
 * SPI Addr:   -1
 * RampProfile: (none)
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/

/* INTERCHIP_RECV: mix-fabric line 1 slot 14 (global slot 30, signal XFER_SNAKE_02) */

.section/dm seg_dmda;
.global _rx_ic_slot_C2_XR_SNAKE_02;
.var _rx_ic_slot_C2_XR_SNAKE_02;
.global _buf_C2_XR_SNAKE_02;
.var _buf_C2_XR_SNAKE_02;

.section/pm seg_pmco;
.global _C2_XR_SNAKE_02_process;
_C2_XR_SNAKE_02_process:
    r0 = dm(_rx_ic_slot_C2_XR_SNAKE_02);
    dm(_buf_C2_XR_SNAKE_02) = r0;
    rts;
_C2_XR_SNAKE_02_process.end:
