/*----------------------------------------------------------------------
 * Master EQ L (EQ_BIQUAD)
 * Node ID:    C2_EQ_MAIN_L
 * Chip:       2
 * Channels:   1
 * SPI Page:   6
 * SPI Addr:   100
 * RampProfile: (none)
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/

/* RampProfile: Instant (default — no ramp) */

/* EQ_BIQUAD: 4-band parametric EQ — dual-instance crossfade */
/* SPI page=6 addr=100 */
/*
 * Dual-instance crossfade (CoeffSetAtomic scope):
 *   Two parallel 4-stage biquad cascades (A/B) with independent
 *   coefficients and state.  Only the active instance runs in steady
 *   state.  When SPI delivers new coefficients, the dormant instance
 *   is loaded, its state zeroed, and a 576-sample linear
 *   crossfade (12.0 ms) blends old → new.
 *
 *   This eliminates coefficient-interpolation instability for large
 *   EQ frequency sweeps — each instance always holds a self-consistent
 *   coefficient set; no intermediate poles are generated.
 *
 * Register contract (biquad.asm): f13–f15 are preserved across
 * _biquad_cascade_N calls (lib clobbers f1–f12 only).
 */

.section/dm seg_dmda;
.extern _buf_C2_REVERB;

/* ---- Instance A: coefficients + biquad state ---- */
.global _eq_coeffs_A_C2_EQ_MAIN_L;
.var _eq_coeffs_A_C2_EQ_MAIN_L[20] = 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0;
.global _eq_state_A_C2_EQ_MAIN_L;
.var _eq_state_A_C2_EQ_MAIN_L[8];

/* ---- Instance B: coefficients + biquad state ---- */
.global _eq_coeffs_B_C2_EQ_MAIN_L;
.var _eq_coeffs_B_C2_EQ_MAIN_L[20] = 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0;
.global _eq_state_B_C2_EQ_MAIN_L;
.var _eq_state_B_C2_EQ_MAIN_L[8];

/* ---- SPI staging buffer (ISR writes here word-by-word) ---- */
.global _eq_coeffs_next_C2_EQ_MAIN_L;
.var _eq_coeffs_next_C2_EQ_MAIN_L[20];
.global _eq_swap_pending_C2_EQ_MAIN_L;
.var _eq_swap_pending_C2_EQ_MAIN_L = 0;

/* ---- Crossfade control ---- */
.global _eq_active_C2_EQ_MAIN_L;
.var _eq_active_C2_EQ_MAIN_L = 0;            /* 0 = A active, 1 = B active */
.global _eq_xfade_alpha_C2_EQ_MAIN_L;
.var _eq_xfade_alpha_C2_EQ_MAIN_L = 0.0;     /* blend: 0.0 = all old, 1.0 = all new */
.global _eq_xfade_step_C2_EQ_MAIN_L;
.var _eq_xfade_step_C2_EQ_MAIN_L = 0.0;      /* per-sample α increment (0 = idle) */

.global _tap_post_eq_C2_EQ_MAIN_L;
.var _tap_post_eq_C2_EQ_MAIN_L;              /* post-EQ tap */
.global _buf_C2_EQ_MAIN_L;
.var _buf_C2_EQ_MAIN_L;

.section/pm seg_pmco;
.extern _biquad_cascade_N;
.global _C2_EQ_MAIN_L_process;
_C2_EQ_MAIN_L_process:

    /* ── 1. Check for new coefficients from SPI ──────────────── */
    r4 = dm(_eq_swap_pending_C2_EQ_MAIN_L);
    r4 = pass r4;
    if ne call _eq_start_xfade_C2_EQ_MAIN_L;

    /* ── 2. Crossfade or steady-state? ───────────────────────── */
    /*    IEEE-754 +0.0 is all-zero bits, so integer pass/zero   */
    /*    test correctly detects the idle (no-crossfade) state.   */
    r4 = dm(_eq_xfade_step_C2_EQ_MAIN_L);
    r4 = pass r4;
    if ne jump .eq_xfade_C2_EQ_MAIN_L;

    /* ═══ STEADY STATE: active instance only ═════════════════ */
    r0 = dm(_buf_C2_REVERB);
    r4 = dm(_eq_active_C2_EQ_MAIN_L);
    r4 = pass r4;
    if ne jump .eq_ss_B_C2_EQ_MAIN_L;
    i0 = _eq_coeffs_A_C2_EQ_MAIN_L;
    i1 = _eq_state_A_C2_EQ_MAIN_L;
    jump .eq_ss_run_C2_EQ_MAIN_L;
.eq_ss_B_C2_EQ_MAIN_L:
    i0 = _eq_coeffs_B_C2_EQ_MAIN_L;
    i1 = _eq_state_B_C2_EQ_MAIN_L;
.eq_ss_run_C2_EQ_MAIN_L:
    r4 = 4;
    call _biquad_cascade_N;
    dm(_tap_post_eq_C2_EQ_MAIN_L) = r0;
    dm(_buf_C2_EQ_MAIN_L) = r0;
    rts;

    /* ═══ CROSSFADE: both instances + linear blend ═══════════ */
.eq_xfade_C2_EQ_MAIN_L:
    r0 = dm(_buf_C2_REVERB);
    f15 = f0;                            /* save input (preserved) */

    /* ── Run active (old) instance ── */
    r4 = dm(_eq_active_C2_EQ_MAIN_L);
    r4 = pass r4;
    if ne jump .eq_xf_actB_C2_EQ_MAIN_L;
    i0 = _eq_coeffs_A_C2_EQ_MAIN_L;
    i1 = _eq_state_A_C2_EQ_MAIN_L;
    jump .eq_xf_act_run_C2_EQ_MAIN_L;
.eq_xf_actB_C2_EQ_MAIN_L:
    i0 = _eq_coeffs_B_C2_EQ_MAIN_L;
    i1 = _eq_state_B_C2_EQ_MAIN_L;
.eq_xf_act_run_C2_EQ_MAIN_L:
    r4 = 4;
    call _biquad_cascade_N;
    f13 = f0;                            /* f13 = old output (preserved) */

    /* ── Run inactive (new) instance ── */
    f0 = f15;                            /* reload input */
    r4 = dm(_eq_active_C2_EQ_MAIN_L);
    r4 = pass r4;
    if eq jump .eq_xf_inB_C2_EQ_MAIN_L;        /* active=A → inactive=B */
    i0 = _eq_coeffs_A_C2_EQ_MAIN_L;
    i1 = _eq_state_A_C2_EQ_MAIN_L;
    jump .eq_xf_in_run_C2_EQ_MAIN_L;
.eq_xf_inB_C2_EQ_MAIN_L:
    i0 = _eq_coeffs_B_C2_EQ_MAIN_L;
    i1 = _eq_state_B_C2_EQ_MAIN_L;
.eq_xf_in_run_C2_EQ_MAIN_L:
    r4 = 4;
    call _biquad_cascade_N;
    /* f0 = new output */

    /* ── Blend: out = (1 − α) × old + α × new ── */
    f14 = dm(_eq_xfade_alpha_C2_EQ_MAIN_L);     /* α */
    r15 = 0x3F800000;  /* 1.0 IEEE 754 */
    f15 = f15 - f14;                     /* 1 − α */
    f13 = f13 * f15;                     /* old × (1 − α) */
    f0 = f0 * f14;                       /* new × α */
    f0 = f0 + f13;                       /* blended output */

    /* ── Advance α ── */
    f14 = dm(_eq_xfade_alpha_C2_EQ_MAIN_L);
    f15 = dm(_eq_xfade_step_C2_EQ_MAIN_L);
    f14 = f14 + f15;                     /* α += step */
    dm(_eq_xfade_alpha_C2_EQ_MAIN_L) = f14;

    /* ── Check completion ── */
    r15 = 0x3F800000;  /* 1.0 IEEE 754 */
    comp(f14, f15);
    if ge call _eq_xfade_done_C2_EQ_MAIN_L;

    dm(_tap_post_eq_C2_EQ_MAIN_L) = f0;
    dm(_buf_C2_EQ_MAIN_L) = f0;
    rts;

/* ── Start crossfade: load dormant instance with new coefficients ── */
_eq_start_xfade_C2_EQ_MAIN_L:
    /* Clear pending flag */
    r4 = 0;
    dm(_eq_swap_pending_C2_EQ_MAIN_L) = r4;

    /* Determine dormant instance and copy coeffs_next into it */
    r4 = dm(_eq_active_C2_EQ_MAIN_L);
    r4 = pass r4;
    if ne jump .eq_sxf_toA_C2_EQ_MAIN_L;

    /* Active=A → dormant=B: copy coeffs, zero state */
    i0 = _eq_coeffs_next_C2_EQ_MAIN_L;
    i1 = _eq_coeffs_B_C2_EQ_MAIN_L;
    r4 = 20;
    lcntr = r4; do .eq_cp_B_C2_EQ_MAIN_L until lce;
        r0 = dm(i0, 1);
        dm(i1, 1) = r0;
    .eq_cp_B_C2_EQ_MAIN_L:
    i1 = _eq_state_B_C2_EQ_MAIN_L;
    r0 = 0;                              /* 0x00000000 = float 0.0 */
    r4 = 8;
    lcntr = r4; do .eq_zs_B_C2_EQ_MAIN_L until lce;
        dm(i1, 1) = r0;
    .eq_zs_B_C2_EQ_MAIN_L:
    nop;                                 /* pipeline gap: no branch within 2 insns of loop end */
    jump .eq_sxf_go_C2_EQ_MAIN_L;

.eq_sxf_toA_C2_EQ_MAIN_L:
    /* Active=B → dormant=A: copy coeffs, zero state */
    i0 = _eq_coeffs_next_C2_EQ_MAIN_L;
    i1 = _eq_coeffs_A_C2_EQ_MAIN_L;
    r4 = 20;
    lcntr = r4; do .eq_cp_A_C2_EQ_MAIN_L until lce;
        r0 = dm(i0, 1);
        dm(i1, 1) = r0;
    .eq_cp_A_C2_EQ_MAIN_L:
    i1 = _eq_state_A_C2_EQ_MAIN_L;
    r0 = 0;
    r4 = 8;
    lcntr = r4; do .eq_zs_A_C2_EQ_MAIN_L until lce;
        dm(i1, 1) = r0;
    .eq_zs_A_C2_EQ_MAIN_L:

.eq_sxf_go_C2_EQ_MAIN_L:
    /* Initiate crossfade ramp: α = 0, step = 1/576 */
    r0 = 0;
    dm(_eq_xfade_alpha_C2_EQ_MAIN_L) = r0;
    f0 = 0.001736111111111111;
    dm(_eq_xfade_step_C2_EQ_MAIN_L) = f0;
    rts;
_eq_start_xfade_C2_EQ_MAIN_L.end:

/* ── Crossfade complete: flip active instance, go idle ── */
_eq_xfade_done_C2_EQ_MAIN_L:
    /* Toggle active: 0→1 or 1→0 (uses r4/r5 only — f0 preserved) */
    r4 = dm(_eq_active_C2_EQ_MAIN_L);
    r5 = 1;
    r4 = r4 xor r5;
    dm(_eq_active_C2_EQ_MAIN_L) = r4;
    /* Reset crossfade to idle */
    r4 = 0;                              /* 0x00000000 = float 0.0 */
    dm(_eq_xfade_alpha_C2_EQ_MAIN_L) = r4;
    dm(_eq_xfade_step_C2_EQ_MAIN_L) = r4;       /* step=0 → idle */
    rts;
_eq_xfade_done_C2_EQ_MAIN_L.end:

_C2_EQ_MAIN_L_process.end:
