/*----------------------------------------------------------------------
 * Ch 29 Recv (INTERCHIP_RECV)
 * Node ID:    C2_RECV_29
 * Chip:       2
 * Channels:   1
 * SPI Page:   -1
 * SPI Addr:   -1
 * RampProfile: (none)
 *
 * AUTO-GENERATED by tools/dsp/dsp_codegen.py — do not edit directly.
 *----------------------------------------------------------------------*/

/* INTERCHIP_RECV: Read from inter-chip SPORT7 slot 28 */

.section/dm seg_dmda;
.global _rx_ic_slot_C2_RECV_29;
.var _rx_ic_slot_C2_RECV_29;
.global _buf_C2_RECV_29;
.var _buf_C2_RECV_29;

.section/pm seg_pmco;
.global _C2_RECV_29_process;
_C2_RECV_29_process:
    r0 = dm(_rx_ic_slot_C2_RECV_29);
    dm(_buf_C2_RECV_29) = r0;
    rts;
_C2_RECV_29_process.end:
