/*----------------------------------------------------------------------
 * Monitor Out (OUTPUT_TDM)
 * Node ID:    C2_MON_OUT
 * Chip:       2
 * Channels:   2
 * SPI Page:   1
 * SPI Addr:   1757
 * RampProfile: (none)
 *
 * AUTO-GENERATED by dsp_codegen.py (D32) — do not edit directly.
 *----------------------------------------------------------------------*/

/* OUTPUT_TDM: Write to SPORT5 slot 0 */

.section/dm seg_dmda;
.extern _buf_C2_MON_DLY;
.global _tx_out_slot_C2_MON_OUT;
.var _tx_out_slot_C2_MON_OUT;
.global _buf_C2_MON_OUT;
.var _buf_C2_MON_OUT;

.section/pm seg_pmco;
.global _C2_MON_OUT_process;
_C2_MON_OUT_process:
    r0 = dm(_buf_C2_MON_DLY);
    dm(_tx_out_slot_C2_MON_OUT) = r0;
    dm(_buf_C2_MON_OUT) = r0;
    rts;
_C2_MON_OUT_process.end:
