<!ELEMENT DOCUMENT (LINKPROJECT+, LINKPROJECT_UNNEEDED_OBJECTS*)>
<!ELEMENT LINKPROJECT (SECTION | OBJECT | IMPORTED_FILE)*>
  <!ATTLIST LINKPROJECT id            CDATA #REQUIRED
                        name          CDATA #REQUIRED
                        importer_id   CDATA #REQUIRED>
<!ELEMENT LINKPROJECT_UNNEEDED_OBJECTS (OBJECT)*>
  <!ATTLIST LINKPROJECT_UNNEEDED_OBJECTS project_id  CDATA #REQUIRED
                                         importer_id CDATA #REQUIRED>
<!ELEMENT SECTION (SYMBOL*, REFERENCE*)>
  <!ATTLIST SECTION id   CDATA #REQUIRED
                    name CDATA #REQUIRED>
<!ELEMENT OBJECT (SYMBOL*, REFERENCE*)>
  <!ATTLIST OBJECT id      CDATA #REQUIRED
                   name    CDATA #REQUIRED
                   section CDATA #REQUIRED>
<!ELEMENT IMPORTED_FILE EMPTY>
  <!ATTLIST IMPORTED_FILE id       CDATA #REQUIRED
                          name     CDATA #REQUIRED
                          importer CDATA #REQUIRED>
<!ELEMENT REFERENCE EMPTY>
  <!ATTLIST REFERENCE symbol_id CDATA #REQUIRED
                      symbol    CDATA #REQUIRED>
<!ELEMENT SYMBOL EMPTY>
  <!ATTLIST SYMBOL id   CDATA #REQUIRED
                   name CDATA #REQUIRED>
