/*----------------------------------------------------------------------
 * Ch 20 Gain (GAIN)
 * Node ID:    C1_GAIN_20
 * Chip:       1
 * Channels:   1
 * SPI Page:   1
 * SPI Addr:   290
 *
 * AUTO-GENERATED by dsp_codegen.py — do not edit directly.
 * Implement DSP logic in the marked section below.
 *----------------------------------------------------------------------*/

/* GAIN: Per-channel gain control */
/* SPI-controllable: page=1 addr=290 */

.section/dm seg_dmda;
.var _gain_coeff_C1_GAIN_20 = 1.0;    /* linear gain coefficient (updated via SPI) */
.var _mute_C1_GAIN_20 = 0;
.var _buf_C1_GAIN_20;

.section/pm seg_pmco;
.global _C1_GAIN_20_process;
_C1_GAIN_20_process:
    /* Read input sample */
    r0 = dm(_buf_C1_IN_20);

    /* Apply gain (SIMD-capable for stereo pairs) */
    r1 = dm(_gain_coeff_C1_GAIN_20);
    f0 = f0 * f1;

    /* Apply mute */
    r2 = dm(_mute_C1_GAIN_20);
    comp(r2, r2);    /* test mute flag */
    if eq f0 = 0.0;  /* if mute=0, pass; if mute=1(nonzero), zero output */
    /* TODO: implement clickless mute with ramp */

    dm(_buf_C1_GAIN_20) = r0;
    rts;
_C1_GAIN_20_process.end:
