/*----------------------------------------------------------------------
 * Ch 30 Input (INPUT_TDM)
 * Node ID:    C1_IN_30
 * Chip:       1
 * Channels:   1
 * SPI Page:   -1
 * SPI Addr:   -1
 *
 * AUTO-GENERATED by dsp_codegen.py — do not edit directly.
 * Implement DSP logic in the marked section below.
 *----------------------------------------------------------------------*/

/* INPUT_TDM: Read from SPORT3 TDM slot 5 */
/* DMA fills rx_buf[] automatically — just reference the slot offset */

.section/dm seg_dmda;
.var _rx_slot_C1_IN_30;     /* pointer to DMA rx buffer slot */

.section/pm seg_pmco;
.global _C1_IN_30_process;
_C1_IN_30_process:
    /* Audio sample available in _rx_slot_C1_IN_30 after DMA complete */
    /* Copy to channel processing buffer */
    r0 = dm(_rx_slot_C1_IN_30);
    dm(_buf_C1_IN_30) = r0;
    rts;
_C1_IN_30_process.end:
